sched-ext/scx

scheds/rust-user/scx_rusty/src/bpf/main.bpf.c
As in scx_layered, bpf_map_delete_elem() can fail due to recursion protection triggering spuriously which can then lead to task_ctx creation failure after PIDs wrap. Work around by dropping BPF_NOEXIST.
=> scx_rusty: Work around spurious task_ctx update failures

scheds/kernel-examples/scx_simple.bpf.c
SCX_DSQ_GLOBAL now does not support vtime dispatching. scx_simple uses it to do vtime scheduling, so let's update it to create and use a separate DSQ that it can both FIFO and PRIQ dispatch to.
=> scx_simple: Don't vtime dispatch to SCX_DSQ_GLOBAL

rust/scx_utils/src/bpf_builder.rs
Newer rustc is unhappy about lack of explicit lifetime parameter.
=> scx_utils::BpfBuilder: Add 'static to BPF_H_TAR definition

meson-scripts/get_clang_ver
Some distro may add their own prefix to the version string of clang, for example in Ubuntu:
$ clang --version
Ubuntu clang version 17.0.5 (1ubuntu1)
...
That triggers the following meson error during the setup phase:
meson.build:25:44: ERROR: String '' cannot be converted to int
Change the regexp used to evaluate the clang version to avoid this build failure.
=> build: properly detect clang version in Ubuntu

scheds/rust-user/scx_rusty/src/main.rs
We were assigning curr to prev stats, and vice versa, in calc_util(). This was causing the following crash on debug builds:
[void@maniforge scheds]$ sudo RUST_BACKTRACE=1 scx_rusty 00:00:56 [INFO] CPUs: online/possible = 32/32
00:00:56 [INFO] DOM[00] cpumask 0000000000FF00FF (16 cpus) 00:00:56 [INFO] DOM[01] cpumask 00000000FF00FF00 (16 cpus) 00:00:56 [INFO] Rusty Scheduler Attached
thread 'main' panicked at /rustc/475c71da0710fd1d40c046f9cee04b733b5b2b51/library/core/src/ops/arith.rs:217:1: attempt to subtract with overflow
stack backtrace:
0: rust_begin_unwind
at /rustc/475c71da0710fd1d40c046f9cee04b733b5b2b51/library/std/src/panicking.rs:597:5
1: core::panicking::panic_fmt
at /rustc/475c71da0710fd1d40c046f9cee04b733b5b2b51/library/core/src/panicking.rs:72:14
2: core::panicking::panic …
=> rusty: Fix calc_util() in rusty

scheds/c-user/scx_nest.c, scheds/kernel-examples/scx_central.c, scheds/kernel-examples/scx_flatcg.bpf.c, scheds/kernel-examples/scx_flatcg.c, scheds/kernel-examples/scx_pair.c, scheds/kernel-examples/scx_qmap.bpf.c, scheds/kernel-examples/scx_qmap.c, scheds/kernel-examples/scx_userland.bpf.c
Set of fixes that allow to build the scx on 32-bit architectures (e.g., armhf).
=>  build scx on 32-bit architectures

scheds/rust-user/scx_rusty/src/main.rs
It seems that under certain conditions, the difference between the current and the previous procfs::CpuStat values may become negative, triggering the following crash/trace:
thread 'main' panicked at /build/rustc-VvCkKl/rustc-1.73.0+dfsg0ubuntu1/library/core/src/ops/arith.rs:217:1: attempt to subtract with overflow
stack backtrace:
...
19:     0x590d8481909e - scx_rusty::calc_util::h46f2af9c512c2ecd
at /home/arighi/src/scx/scheds/rust-user/scx_rusty/src/main.rs:217:31
20:     0x590d8481c794 - scx_rusty::Tuner::step::h2e51076f043a8593
at /home/arighi/src/scx/scheds/rust-user/scx_rusty/src/main.rs:444:38
21:     0x590d84828270 - scx_rusty::Scheduler::run::hb5483f1e585f52fe
at /home/arighi/src/scx/scheds/rust-user/scx_rusty/src/main.rs:1198:17
22:     0x590d848289e9 - …
=> scx_rusty: fix "subtract with overflow" error

README.md, meson.build, meson.options, scheds/meson.build
Introduce an option to enable/disable the build of all the Rust sub-projects (default is enabled).
This can be useful to build scx on those systems where Rust is not fully supported (e.g., armhf).
=> build: introduce enable_rust build option

meson.build
Add the proper mapping from Debian architecture "s390x" to the kernel architecture name "s390".
=> build: add Debian arch name mapping for s390

scheds/kernel-examples/scx_central.bpf.c
For the case where many tasks being popped from the central queue cannot be dispatched to the local DSQ of the target CPU, we will keep bouncing them to the fallback DSQ and continue the dispatch_to_cpu loop until we find one which can be dispatch to the local DSQ of the target CPU.
In a contrived case, it might be so that all tasks pin themselves to CPUs != target CPU, and due to their affinity cannot be dispatched to that CPU's local DSQ. If all of them are filling up the central queue, then we will keep looping in the dispatch_to_cpu loop and eventually run out of slots for the dispatch buffer. The nr_mismatched counter will quickly rise and the sched_ext core will notice the error and unload the BPF scheduler.
To remedy this, ensure that we break the dispatch_to_cpu loop when we can …
=> scx_central: Break dispatch_to_cpu loop when running out of buffer slots

scheds/kernel-examples/scx_userland.bpf.c, scheds/kernel-examples/scx_userland.c, scheds/kernel-examples/scx_userland.h
Currently the array of enqueued tasks is statically allocated to a fixed size of USERLAND_MAX_TASKS to avoid potential deadlocks that could be introduced by performing dynamic allocations in the enqueue path.
However, this also adds a limit on the maximum pid that the scheduler can handle, since the pid is used as the index to access the array.
In fact, it is quite easy to trigger the following failure on an average desktop system (making this scheduler pretty much unusable in such scenario):
$ sudo scx_userland
...
Failed to enqueue task 33258: No such file or directory
EXIT: BPF scheduler unregistered
Prevent this by using sysctl's kernel.pid_max as the size of the tasks array (and still allocate it all at once during initialization).
The downside of this change is that scx_userland may …
=> scx_userland: allocate tasks array based on kernel.pid_max

scheds/kernel-examples/scx_userland.bpf.c, scheds/kernel-examples/scx_userland.c
Allow to handle dispatch failure events without crashing, reduce MAX_ENQUEUED_TASKS to improve memory footprint and make enqueue/dispatch events more consistent.
=> make scx_userland more robust

rust/scx_utils/Cargo.toml, scheds/rust-user/scx_layered/Cargo.toml, scheds/rust-user/scx_layered/src/main.rs, scheds/rust-user/scx_rusty/Cargo.toml, scheds/rust-user/scx_rusty/src/main.rs
This is a follow on to #32, which got reverted. I wrongly assumed that scx_rusty resides in the sched_ext tree and consumes published version of scx_utils.
With this change we update the other in-tree dependencies. I built scx_layered & scx_rusty. I bumped scx-utils to 0.4, because the libbpf-cargo seems to be part of the public API surface and libbpf-cargo 0.21 and 0.22 are not compatible with each other.
=> rust: Update libbpf-rs & libbpf-cargo to 0.22

scheds/c/scx_nest.bpf.c
Julia noticed a few things that can be improved in scx_nest. Address them here
=> Fix some things in Nest

.github/workflows/build-scheds.yml, scheds/c/meson.build
When Ubuntu ships with sched_ext, we can also maybe test loading the schedulers (not sure if the runners can run as root though). For now, we should at least have a CI job that lets us verify that the schedulers can _build_. To that end, this patch adds a basic CI action that builds the schedulers.
As is, this is a bit brittle in that we're having to manually download and install a few dependencies. I don't see a better way for now without hosting our own runners with our own containers, but that's a bigger investment. For now, hopefully this will get us _some_ coverage.
=> scx: Add CI action that builds schedulers for PRs

.github/workflows/build-scheds.yml
Andrea pointed out that we can and should be using Ubuntu 22.04. Unfortunately it still doesn't ship some of the deps we need like clang-17, but it does at least ship virtme-ng, so it's good for us to use this so that we can actually test running the schedulers in a virtme-ng VM when it supports being run in docker.
Also, update the job to run on pushes, and not just when a PR is opened
Suggested-by: Andrea Righi <andrea.righi@canonical.com>
=> ci: Run CI job on Ubuntu 22.04

scheds/rust/scx_rustland/src/bpf/intf.h, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Set of changes for scx_rustland that allow to massively improve the user-space scheduler effectiveness, especially for low latency tasks:
- provide CPU usage awareness to the user-space scheduler
- dispatch tasks from the user-space scheduler to the BPF dispatcher in batch, instead of draining the entire task pool all at once
- distinguish between graceful exit vs non-graceful exit
=> scx_rustland improvements

scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
A set of interlocking improvements for scx_rustland:
- clarify interlocking between the BPF dispatcher and the user-space scheduler
- introduce get/set_cpu_owner() primitives as a baseline to implement a better idle tracking in the future
- move user-space scheduler activation from `.enqueue()` to `.stopping()` (and activate only when needed) to reduce unnecessary user-space activations
- always bypass user-space scheduling for kthreads
I have also explored the possibility to move the user-space scheduler activation from `.stopping()` to `.update_idle()`, but the scheduler performs quite poorly with this change: it seems that CPUs are not fully used even in presence of CPU intensive workloads, as if the user-space scheduler isn't feeding the dispatcher fast enough. My guess is that …
=> scx_rustland: clarify and improve BPF / userspace interlocking

scheds/rust/scx_rustland/src/bpf/main.bpf.c
- move the logic to activate the user-space scheduler to an `update_idle()` callback
- restore the logic to prioritize only per-cpu kthreads (not all kthreads)
=> scx_rustland: introduce update_idle callback

rust/scx_utils/Cargo.toml, rust/scx_utils/src/bpf_builder.rs
This is so we can package scx_utils into fedora without having to upgrade rust-bindgen
(https://bodhi.fedoraproject.org/updates/FEDORA-2023-18e7f124e1).
To make this happen we need to stop using the `CargoCallbacks::new` constructor which was added in 0.69. Old way seems legit according to the docs:
https://rust-lang.github.io/rust-bindgen/non-system-libraries.html
=> Downgrade bindgen to 0.68

scheds/rust/README.md
Add documentation for scx_rustland to the README.md files of the Rust schedulers.
=> scx_rustland: add documentation to scheds/rust/README.md

scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
- always consider the CPU where the scheduler is running as idle
- fix a bug that was causing the user-space scheduler to spin and improve the logic to activate the user-space scheduler, preventing unnecessary activations
These changes make scx_rustland more reliable and they strongly reduce the scheduler overhead.
=> scx_rustland: reduce scheduler overhead

scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Implement a more reasonable idle CPU selection logic in the user-space scheduler.
=> scx_rustland: improve scheduler cpu selection

scheds/rust/scx_rustland/src/main.rs
When a task is dispatched we always try to pick the previously used CPU (if idle) to minimize the migration overhead. Alternatively, if such CPU is not available, we pick any other idle CPU in the system.
However, we don't update the list of idle CPUs as we dispatch tasks, therefore we may end up sending multiple tasks to the same idle CPU (if their previously used CPU is the same) and we may even skip some idle CPUs completely.
Change this logic to make sure that we never dispatch multiple tasks to the same idle CPU, by updating the list of idle CPUs as we send tasks to the BPF dispatcher.
This also avoids dispatching tasks with a closely matched vruntime to the same CPU, thereby negating the advantages of the vruntime ordering. With this change in place, we ensure that tasks with a …
=> scx_rustland: prevent dispatching multiple tasks on the same idle cpu

scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Low-latency improvements:
- scx_rustland: always use dispatch_on_cpu() when possible
- scx_rustland: bypass user-space scheduler for short-lived kthreads 
Reduce user-space overhead:
- scx_rustland: enable SCX_OPS_ENQ_LAST
UI improvement:
- scx_rustland: show the CPU where the scheduler is running
=> scx_rustland: lowlatency improvements

scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Improvements and fixes to scx_rustland to prevent some cases of starvation and enhance responsiveness:
- scx_rustland: evaluate the proper vruntime delta
- scx_rustland: prevent starvation handling short-lived tasks properly
- bpf_rustland: do not dispatch the scheduler to the global DSQ
- scx_rustland: remove SCX_ENQ_LAST check in is_task_cpu_available()
- scx_rustland: never account more than slice_ns to vruntime
- scx_rustland: clean up old entries in the task map
Small code readability improvement:
- scx_rustland: small code refactoring
- scx_rustland: rename variable id -> pos for better clarity
With all these changes in place the scheduler can properly handle, on my 8-cores laptop, a parallel kernel build (`make -j32`), a stress test (`stress-ng --cpu 32 --iomix 4 --vm 2 --vm-bytes …
=> scx_rustland: prevent starvation and improve responsiveness

scheds/rust/scx_rustland/src/bpf/intf.h, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Instead of implementing a garbage collector to periodically free up exiting tasks' resources, implement a proper synchronous mechanism to notify the user-space scheduler about the exiting tasks from the BPF component, using the .disable() callback.
When the user-space scheduler receives a queued task with a negative CPU number, it can then release all the resources associated with that task (which currently includes only the entry in the TaskInfoMap for now).
This allows to get rid of the TaskInfoMap periodic garbage collector routine, save a lot of syscalls in procfs (used to check if the pids were still alive), and improve the overall scheduler performance.
=> scx_rustland: notify user-space scheduler about exiting tasks

.github/workflows/build-scheds.yml, meson-scripts/test_sched, meson.build, meson.options, scheds/c/scx_flatcg.c, scheds/c/scx_userland.c
Use virtme-ng to test the schedulers in the github workflow.
Keep in mind that I've only tested this locally (using `gh act`), so in the actual github workflow it may behave differently and it probably requires more testing / planning.
I've opened the PR to start some discussions / suggestions / ideas for now.
Overall, I think it can be really useful, I've already triggered a few bugs with this (see https://github.com/sched-ext/scx/issues/49, https://github.com/sched-ext/sched_ext/pull/101 and https://github.com/sched-ext/sched_ext/issues/74#issuecomment-1870958545).
=> test the schedulers in the github workflow using virtme-ng

.github/workflows/build-scheds.yml, scheds/include/scx/common.bpf.h
Improve build portability by including asm-generic/errno.h, instead of linux/errno.h.
The difference between these two headers can be summarized as following:
- asm-generic/errno.h contains generic error code definitions that are intended to be common across different architectures,
- linux/errno.h includes architecture-specific error codes and provides additional (or overrides) error code definitions based on the specific architecture where the code is compiled.
Considering the architecture-independent nature of scx, the advantages of being able to use architecture-specific error codes are marginal or negligible (and we should probably discourage using them).
Moving towards asm-generic/errno.h, however, allows the removal of cross-compilation dependencies (such as the gcc-multilib …
=> scheds: c: improve build portability

scheds/c/scx_userland.bpf.c, scheds/c/scx_userland.c
This patch fixes a couple issues in the ~`scx_rustland` and~ `scx_userland` scheduler:
- ~In `scx_rustland`, we keep using builtin idle tracking with `SCX_OPS_KEEP_BUILTIN_IDLE` to avoid racy checks in `ops.select_cpu()`~
- In `scx_userland`, we avoid hangs by using more robust checks to see if there's more work to be done in user space, and sending resched IPIs whenever there is.
=> Userland scheduler updates

scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Big logical change:
- scx_rustland: prioritize interactive workloads
Small "cleanup" changes:
- scx_rustland: do not update exiting tasks statistics
- scx_rustland: schedule non-cpu intensive kthreads normally
The big change can actually make scx_rustland relevant under certain conditions. As I mentioned in the commit message:
```
For example, with a parallel kernel build (make -j32) running in the
background, I can play Terraria with a constant rate of ~30-40 fps,
while the default Linux scheduler can handle only ~20-30 fps under the
same conditions.
```
While the scheduler isn't quite production-ready, I think we're approaching a state where it can be considered "usable" (under certain conditions) and someone might even find it beneficial in a few real-world scenarios (also considering …
=> scx_rustland: improve interactive workloads

scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
A small set of changes to improve scx_rustland reliability and make it more robust under heavy CPU load conditions.
Example (on a 8-cores system)
```
$ stress-ng -c 128
```
Before, this stress test could easily trigger short lockups or even trigger the sched-ext watchdog that would automatically disable the scheduler.
With this set of changes applied the system remains reasonably responsive and the scheduler is never disabled.
=> Improve scx_rustland reliability

scheds/rust/README.md, scheds/rust/scx_layered/README.md, scheds/rust/scx_rustland/README.md, scheds/rust/scx_rusty/README.md
This because each scheduler has it's own Rust Crate and it's better if they had a README associated with each one.
https://crates.io/crates/scx_layered
=> Add README files for each rust scheduler

scheds/rust/scx_rustland/src/bpf.rs, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Minor improvement:
- scx_rustland: make dispatcher more robust
- scx_rustland: remove unnecessary scx_bpf_dispatch_nr_slots() check
- scx_rustland: introduce nr_failed_dispatches
Code refactoring:
- scx_rustland: provide an abstraction layer for the BPF component
- scx_rustland: update comments and documentation in the BPF part
There is basically no functional change in this pull request, just some code refactoring. The important part is the new abstraction to the BPF component that makes the scheduler code much more readable and understandable.
Maybe in the future we could also consider to move this BPF abstraction to a more generic place, with a proper API documentation, to give the possibility to implement scx user-space schedulers in a more high-level abstracted way.
=> scx_rustland: refactoring

scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_rusty/Cargo.toml
These were supposed to be bumped in this commit:
https://github.com/sched-ext/scx/commit/fed1dae9da71926772248996e9007370f348a2f0
=> bump scx_rusty and scx_layered

scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Some fixes and enhancements to make scx_rustland more usable on a desktop / interactive system.
=> scx_rustland: enhancements

scheds/rust/scx_rustland/src/bpf.rs, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Provide a new abstraction for the user-space scheduler to dynamically adjust the time slice used to dispatch tasks. Moreover, implement a mechanism in the user-space scheduler to dynamically scale the time slice as a function of the waiting tasks and the available CPUs in the system.
Apart for the benefits of having an additional scheduling abstraction (that can be beneficial for potential developers interested in expanding RustLand), this change also significantly improves the interactive performance of the scheduler, especially when the system is overloaded by a massive amount of CPU hogs (e.g., `stress-ng -c 256`).
Before this change the stress-ng command above could make my system pretty much unresponsive (triggering the sched-ext watchdog / stall detector). With this change applied …
=> scx_rustland: dynamic time slice

scheds/rust/scx_rustland/src/bpf.rs, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
A small fix to detect the right amount of CPUs on multi-core / multi-threading systems and a small fix to return the proper cpu id from bpf_cpumask_any_distribute().
Edit: forgot to include another little change (now pushed) to simplify update_enqueued(), not really multicore related, but it helps to make the scheduler more resilient in presence of massive cpu stress test.
=> scx_rustland: multicore fixes

meson.build, rust/scx_utils/Cargo.toml, scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml, scheds/rust/scx_rusty/Cargo.toml
After updates to reflect the updated init and direct dispatch API, the schedulers aren't compatible with older kernels. Bump versions and publish releases.
=> Bump versions

scheds/rust/scx_rustland/README.md, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Small updates to rustland after the API change:
-  get rid of force_local and dispatch in `select_cpu()` when possible
- improved the dynamic time slice logic (especially in large multi-core system)
- added a link to my live demo YouTube video in README.md
=> scx_rustland: small updates

.github/workflows/build-scheds.yml
Temporarily switch to the unstable sched-ext ppa, so that we can resume testing with the new kernel API.
=> ci: temporarily switch to ppa:arighi/sched-ext-unstable

scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
This PR includes the "time slice boost"  option (that should be called "time slice penalty", but boost sounds more cool :wink:), that is the extra patch that I've used for live demo video (https://www.youtube.com/watch?v=oCfVbz9jvVQ), cleaned up a little bit.
I was a bit skeptical to send this one, because it can make the scheduler more unpredictable / unstable if used improperly, but at the end the worst case scenario would be a 5s stall, before the sched-ext watchdog kicks out the scheduler and the benefit can be that people may actually want to test and play around with this. 
Moreover, without using `-b NUM`, no boosting is applied, so the default behavior remains unchanged.
In addition to that there's also a small patch to dispatch the user-space scheduler without SCX_ENQ_PREEMPT, …
=> scx_rustland: time slice boost

scheds/c/scx_flatcg.bpf.c
We may end up stalling for too long in fcg_dispatch() if try_pick_next_cgroup() doesn't find another valid cgroup to pick. This can be quite risky, considering that we are holding the rq lock in dispatch().
This condition can be reproduced easily in our CI, where we can trigger stalling softirq works:
[    4.972926] NOHZ tick-stop error: local softirq work is pending, handler #200!!!
Or rcu stalls:
[   47.731900] rcu: INFO: rcu_preempt detected stalls on CPUs/tasks:
[   47.731900] rcu:     1-...!: (0 ticks this GP) idle=b29c/1/0x4000000000000000 softirq=2204/2204 fqs=0
[   47.731900] rcu:     3-...!: (0 ticks this GP) idle=db74/1/0x4000000000000000 softirq=2286/2286 fqs=0
[   47.731900] rcu:     (detected by 0, t=26002 jiffies, g=6029, q=54 ncpus=4)
[   47.731900] Sending NMI from CPU 0 …
=> scx_flatcg: introduce CGROUP_MAX_RETRIES

scheds/rust/scx_rustland/src/bpf.rs, scheds/rust/scx_rustland/src/bpf/intf.h, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
A significant improvement in scheduler responsiveness for low-latency application: in short, the idea is to take into account the amount of voluntary context switches to identify interactive tasks vs CPU-intensive background tasks, and use this criteria to reduce the accounted time slice of interactive tasks (implicitly boosting their priority).
This simple heuristic is much better than the previous approach that was de-prioritizing newly created tasks, as it allows to classify CPU-intensive workloads that are not spawning too many tasks vs the actual interactive low-latency applications. And it also allows avoids to de-prioritize interactive applications that need to fork short-lived tasks, e.g., interactive shell sessions, that receive a big responsiveness improvement with this change. …
=> scx_rustland: voluntary context switch boost

scheds/rust/scx_rustland/src/main.rs
Entries from TaskInfoMap associated to exiting tasks are already removed via the BPF .exit_task() callback, so drop the obsolete TODO note and replace it with a proper comment.
=> scx_rustland: remove obsolete TODO note

scheds/rust/scx_rustland/src/bpf.rs, scheds/rust/scx_rustland/src/bpf/alloc.rs, scheds/rust/scx_rustland/src/main.rs
To prevent potential deadlock conditions under heavy loads, any scheduler that delegates scheduling decisions to user-space should avoid triggering page faults.
To address this issue, replace the default Rust allocator with a custom one (RustLandAllocator), designed to operate on a pre-allocated buffer.
This, coupled with the memory locking (via mlockall), prevents page faults from happening during the execution of the user-space scheduler, avoiding the deadlock condition.
This memory allocator is completely transparent to the user-space scheduler code and it is applied automatically when the bpf module is imported.
In the future we may decide to move this allocator to a more generic place (scx_utils crate), so that also other user-space Rust schedulers can use it.
This initial …
=> scx_userland: use a custom memory allocator to prevent page faults

scheds/rust/scx_rustland/src/main.rs
Update the slice boost dynamically, as a function of the amount of CPUs in the system and the amount of tasks currently waiting to be dispatched: as the amount of waiting tasks in the task_pool increases, reduce the slice boost.
This adjustment ensures that the scheduler adheres more closely to a pure vruntime-based policy as the amount of tasks contending the available CPUs increases and it allows to sustain stress tests that are spawning a massive amount of tasks.
=> scx_rustland: introduce dynamic slice boost

scheds/c/scx_nest.bpf.c, scheds/c/scx_nest.c
scx_nest: Set timer callback after cancelling
In scx_nest, we use a per-cpu BPF timer to schedule compaction for a
primary core before it goes idle. If a task comes along that could use
that core, we cancel the callback with bpf_timer_cancel().
bpf_timer_cancel() drops a refcnt on the prog and nullifies the
callback, so if we want to schedule the callback again, we must use
bpf_timer_set_callback() to reset the prog. This patch does that.
Reported-by: Julia Lawall <julia.lawall@inria.fr>
Signed-off-by: David Vernet <void@manifault.com>
=> scx_nest: Set timer callback after cancelling

scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
This PR contains an improvement in the SMT logic, it's actually a simplification and, performance-wise, it seem to deliver better results, so it's a win-win IMHO.
As mentioned in the git commit:
```
Some preliminary results on an AMD Ryzen 7 5800X 8-Cores (SMT enabled):
running my usual benchmark of measuring the fps of a videogame
(Counter-Strike 2) during a parallel kernel build-induced system
overload, shows an improvement of approximately 2x (from 8-10fps to
15-25fps vs 1-2fps with EEVDF).
```
The other commit is more like a clean-up, apparently now we can drop the `scx_bpf_kick_cpu()` from `update_idle()` without any noticeable performance drop, so let's just get rid of it.
=> scx-rustland: SMT improvements

services/journald@sched-ext.conf, services/meson.build, services/scx_central.service, services/scx_flatcg.service, services/scx_nest.service, services/scx_pair.service, services/scx_qmap.service, services/scx_rustland.service, services/scx_rusty.service, services/scx_simple.service, services/scx_userland.service
@arighi @htejun @Decave
As mentioned in the previous PR #88  that could help solve the log problem.
=> Set log size to 10M

.github/workflows/build-scheds.yml
Instead of downloading a precompiled sched-ext enabled kernel from the Ubuntu ppa, fetch the latest kernel directly from the sched-ext git repository and recompile it on-the-fly using virtme-ng.
This allows to get rid of the Ubuntu ppa dependency, take out from the equation potential Ubuntu-specific patches, and ensures testing all the schedulers with the most up-to-date sched-ext kernel (that should also help to detect potential kernel-related issues in advance).
The downside is that the CI runs will take a bit longer now, because we are recompiling the kernel from scratch. However, the kernel built with virtme-ng is relatively quick to compile and includes all the sched-ext features required for testing.
It's worth noting that this method aligns with the current sched-ext kernel CI, …
=> ci: test the shedulers with the latest sched-ext kernel

README.md, services/README.md
Brief information on how to use systemd services with a bunch of useful journald commands.
=> Add README.md for systemd services

scheds/include/scx/user_exit_info.h
When a scx scheduler aborts, it can be difficult to find out what happened because all the scheduling states are lost as the system is reverted back to the default scheduler. Kernel now captures debug dump. Print it out if available. It looks like the following:
```
root@test ~# os/work/tools/sched_ext/build/bin/scx_qmap -t 500
enq=5, dsp=0, delta=5, reenq=0, deq=0, core=0
enq=451, dsp=445, delta=6, reenq=0, deq=0, core=0
enq=871, dsp=868, delta=3, reenq=0, deq=0, core=0
enq=1263, dsp=1259, delta=4, reenq=8, deq=0, core=0
enq=1595, dsp=1593, delta=2, reenq=8, deq=0, core=0
enq=1870, dsp=1869, delta=1, reenq=8, deq=0, core=0
enq=1940, dsp=1939, delta=1, reenq=8, deq=0, core=0
enq=1974, dsp=1974, delta=0, reenq=15, deq=0, core=0
DEBUG DUMP …
```
=> user_exit_info: Print out debug dump if available

scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_layered/src/main.rs
Currently scx_layered outputs statistics periodically as info! logs. The format of this is largely unstructured and mostly suitable for running scx_layered interactively (e.g. observing its behavior on the command line or via logs after the fact).
In order to run scx_layered at larger scale, it's desireable to have statistics output in some format that is amenable to being ingested into monitoring databases (e.g. Prometheseus). This allows collection of stats across many machines.
This commit adds a command line flag (-o) that outputs statistics to stderr in OpenMetrics format instead of the normal log mechanism. OpenMetrics has a public format
specification (https://github.com/OpenObservability/OpenMetrics) and is in use by many projects.
The library for producing OpenMetrics metrics is …
=> scx_layered: Add support for OpenMetrics format

scheds/rust/scx_layered/src/bpf/main.bpf.c
Prior to this patch, we only bump LSTAT_AFFN_BIOL when the target cpu was idle, but in both cases it should be counted as AFFN_VIOL.
=> scx_layered: Fix AFFN_VIOL stat bump

services/scx_central.service, services/scx_flatcg.service, services/scx_nest.service, services/scx_pair.service, services/scx_qmap.service, services/scx_rustland.service, services/scx_rusty.service, services/scx_simple.service, services/scx_userland.service
Together with @arighi , we have figured out that there is a specific bug in Ubuntu - when installing the apt/systemd tries to activate all schedulers simultaneously. The consequences of this error are as follows: 
```
[22053.942960] BUG: kernel NULL pointer dereference, address: 0000000000000000
[22053.942966] #PF: supervisor write access in kernel mode
[22053.942968] #PF: error_code(0x0002) - not-present page
[22053.942969] PGD 0 P4D 0 
[22053.942972] Oops: 0002 [#1] PREEMPT SMP NOPTI
[22053.942976] CPU: 6 PID: 3550 Comm: sched_ext_ops_h Tainted: G           O       6.7.0-4-generic #4+scx3-Ubuntu
[22053.942978] Hardware name: GPD G1621-02/G1621-02, BIOS 2.04 09/01/2022
[22053.942980] Sched_ext: central (enabled+all)
[22053.942981] RIP: 0010:scx_ops_disable_workfn+0x85/0x610 …
```
=> systemd-services: setting conflict between schedulers

services/meson.build
I’ve removed the unnecessary array declarations for single files and also I’ve added comments to each line to explain what it does. This can be helpful for others (or even yourself in the future) to understand what each line of code is doing.
=> Make meson.build more readable

scheds/rust/scx_layered/src/bpf/main.bpf.c
These are two mostly unrelated changes that just cleanup some unnecessary idle cpumask logic in scx_layered
=> scx_layered: small idle_cpumask cleanups

scheds/rust/scx_layered/Cargo.toml
This library at version 22 is not available in fedora: https://src.fedoraproject.org/rpms/rust-prometheus-client
Rather than bothering the maintainer, let's just downgrade here.
I tested locally. The output still looks sane:
```
[root@fedora debug]# sudo ./scx_layered file:example.json -o
12:33:51 [INFO] CPUs: online/possible=1/1 nr_cores=1
12:33:51 [INFO] Layered Scheduler Attached
total 250
local 0.0
open_idle 0.0
affn_viol 0.0
tctx_err 0
proc_ms 5
busy 0.0
util 0.5660943994986982
load 0.3895238176528804
l_util{layer_name="batch"} 0.187327642437604
l_util{layer_name="immediate"} 0.0
l_util{layer_name="normal"} 0.37876675706109427
l_util_frac{layer_name="immediate"} 0.0
l_util_frac{layer_name="normal"} 66.90876246020258
l_util_frac{layer_name="batch"} 33.09123753979742 …
```
=> [scx_layered] downgrade prometheus-client

scheds/rust/scx_layered/src/bpf/main.bpf.c
This is a minor optimization to avoid enqueue() in the event that select_cpu chooses to dispatch to the core it's running on.
=> scx_layered: dispatch from select_cpu if possible

rust/scx_utils/Cargo.toml, rust/scx_utils/bindings.h, rust/scx_utils/build.rs, rust/scx_utils/src/bindings.rs, rust/scx_utils/src/lib.rs, rust/scx_utils/src/user_exit_info.rs, scheds/include/scx/user_exit_info.h, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_rustland/src/bpf.rs, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs, scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/main.rs
This unifies exit handling across rust scheds and also adds debug dump printing to them.
=> Add user_exit_info support to scx_utils and convert the rust scheds accordingly

scheds/rust/scx_rustland/src/bpf.rs, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Opening this PR mostly as an open discussion.
**Main topic**
Designing a universal BPF layer that allows to implement totally generic schedulers in user-space.
**Specific goal addressed by this PR**
The BPF part should provide an interface that allows the user-space scheduler to select a specific CPU to dispatch a task and it should also allow to not specify any CPU at all (in this case the task can be dispatched in any CPU, like the first one that becomes available).
**Implementation**
The idea is to adapt @Decave's suggestion of introducing per-CPU DSQs, the user-space scheduler sends to the BPF dispatcher a PID with an optional target CPU; the BPF part dispatches the task to the DSQ associated to the target CPU, if specified, otherwise the task is dispatched to a global shared DSQ. …
=> scx_rustland: per-CPU DSQs + global shared DSQ

scheds/sync-to-kernel.sh
Only scx_simple/qmap are in the kernel tree now. Drop the rest from the sync script. Also update the sync script so that it can handle empty rust_scheds variable.
=> scheds/sync-to-kernel.sh: Drop most schedulers from sync

meson.build
If a user wants to use an external libbpf source (via libbpf_h opt) we need to also pass this to c sched compilation.
=> Include libbpf_h path in c sched compilation

scheds/rust/scx_rustland/src/main.rs
Items in the task BTreeSet are stored by pid and vruntime. Make sure that we never store multiple items with the same PID, so that re-enqueued tasks are not dispatched multiple times.
=> scx_rustland: prevent duplicate PIDs in the task BTreeSet

scheds/c/scx_userland.bpf.c, scheds/c/scx_userland.c
Let's make it clear that this scheduler isn't expected to perform well, and instead point people to scx_rustland.
Should clarify the situation for issues such as https://github.com/sched-ext/scx/issues/123
Also increases the timeout for `scx_userland` back to the system default.
=> scx_userland: Print warning about poor performance

.github/workflows/build-scheds.yml
We're basically always runnin two CI jobs: one for a remote push, and another for when a PR is opened. These are essentially measuring the same thing, so let's save CI bandwidth and just do a PR run. This will hopefully make things a bit less noisy as well.
=> ci: Only do CI runs for pull requests

README.md
Along with the name change, https://github.com/sched-ext/scx-packaging-arch/commit/2c48384a8e87981a97bb95253b2af3191cb4e285 kernel went into the CachyOS repo. Pull Request includes a change to the installation instructions. Now it is no longer necessary to put the kernel in the repo on Github, it will be available in CachyOS and updated with each release. 
```
❯ pacman -Ss linux-sched-ext
cachyos/linux-sched-ext 6.7.1.scx1-2
The Linux kernel and modules
cachyos/linux-sched-ext-docs 6.7.1.scx1-2
Documentation for the Linux kernel
cachyos/linux-sched-ext-git 6.7.0.r1236012.g6eb6c92567b1-5
The Linux Kernel based on the sched_ext branch kernel and modules
cachyos/linux-sched-ext-git-headers 6.7.0.r1236012.g6eb6c92567b1-5
Headers and scripts for building modules for the Linux Kernel based on …
```
=> Add linux-sched-ext to CachyOS repo

meson-scripts/test_sched
Search for potential errors only in the kernel logs and the scheduler stderr.
In this way we can use "error keywords" in the scheduler's output without triggering false positives in the CI (see for example #127).
NOTE: this works, because virtme-ng, when executed in verbose mode, sends the kernel messages to stderr (together with the command's stderr) and it channels the command's stdout to the stdout of the host.
=> ci: detect errors only from stderr

scheds/rust/scx_rustland/src/bpf.rs, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
A set of improvements/fixes for rustland.
In particular:
`scx_rustland: use scx_bpf_dispatch_cancel()`
This uses the new `scx_bpf_dispatch_cancel()` API that prevents the cpumask-related stall conditions. I still can't completely ignore the task when the cpumask is not valid anymore, because there are cases where a task is never dispatched to any DSQ. But I can use the cancel operation to redirect the task to the CPU assigned during select_cpu or to the shared DSQ (if the prev cpu is also not available) in a reliable way. With this logic applied I haven't been able to stall the scheduler using `stress-ng --race-sched`, so in any case it is definitely an improved and a reasonable fix IMHO.
And this also allows to enable the following:
`scx_rustland: keep default CPU selection when idle` …
=> scx_rustland: fix cpumask stall and prevent stuttery behavior

scheds/include/scx/ravg.bpf.h, scheds/rust/scx_rusty/Cargo.toml, scheds/rust/scx_rusty/src/bpf/intf.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/main.rs
As described in [this paper], there is an open problem in load balancing
called the "infeasible weights" problem. Essentially, the problem boils
down to the fact that a task with disproportionately high load can be
granted more CPU time than they can actually consume per their duty
cycle.
This patch implements a solution to that problem, wherein we apply the
algorithm described in this paper to adjust all infeasible weights in
the system down to a feasible wight that gives them their full duty
cycle, while allowing the remaining feasible tasks on the system to
share the remaining compute capacity on the machine.
[this paper]: https://drive.google.com/file/d/1fAoWUlmW-HTp6akuATVpMxpUpvWcGSAv/view?usp=drive_link
=> Implement solution to infeasible weights problem

scheds/rust/scx_rustland/src/bpf.rs, scheds/rust/scx_rustland/src/bpf/intf.h, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Introduce a per-task generation counter to check the validity of the cpumask at dispatch time.
The logic is the following:
- the cpumask generation number is incremented every time a task calls .set_cpumask()
- when a task is enqueued the current generation number is stored in the queued_task_ctx and relayed to the user-space scheduler
- the user-space scheduler can decide to dispatch the task on the CPU determined by the BPF layer in .select_cpu(), redirect the task to any other specific CPU, or redirect to the first CPU available (using NO_CPU)
- task is then dispatched back to the BPF code along with its cpumask generation counter
- at dispatch time the BPF code checks if the generation number is the same and it discards the dispatch attempt if the cpumask is not valid anymore (the …
=> scx_rustland: per-task cpumask generation counter

scheds/rust/scx_rustland/Cargo.toml, scheds/rust/scx_rustland/src/bpf.rs, scheds/rust/scx_rustland/src/bpf/alloc.rs, scheds/rust/scx_rustland/src/main.rs
Reduce custom memory allocator overhead by switching to buddy-alloc and use a HashMap to speed up search by PID in tasks BTreeSet.
=> scx_rustland: performance improvements

rust/scx_utils/src/user_exit_info.rs
Use c_char to convert C strings, that is more portable across different architectures.
This prevents a build failure on arm64 and ppc64el.
Fixes: d57a23f ("rust/scx_utils: Add user_exit_info support")
=> scx_utils: use c_char to prevent build failures

meson.build
There is an old version in the meson.build file: https://github.com/sched-ext/scx/blob/main/meson.build#L2
=> Bump to 0.1.7

README.md
We have moved generic sched-ext status files outside of debugfs, so that kernels without SCHED_DEBUG enabled can also access this information.
However, the README.md file is still showing the old ABI in an example.
Replace it with the new sysfs interface to avoid confusion.
=> README: drop reference to old ABI /sys/kernel/debug/sched/ext

scheds/rust/scx_rustland/src/bpf.rs, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Reduce the overhead of kernel/user-space communication by using a BPF_MAP_TYPE_RINGBUF for the enqueued tasks and change cpu_map (map of pids running on the available CPUs) from a BPF_MAP_TYPE_ARRAY to a global static array.
These changes allow to significantly reduce the amount of syscalls and memcpy operations performed by scx_rustland. Looking at perf top:
Before:
``` 
5.52%  [kernel]  [k] __sys_bpf
4.10%  [kernel]  [k] _copy_from_user
```
After:
```
0.14%  [kernel]  [k] __sys_bpf
0.07%  [kernel]  [k] _copy_from_user
```
=> scx_rustland: improve kernel/user-space communication

scheds/rust/scx_rustland/src/bpf.rs
The buffer used to store struct queued_task_ctx items fetched from the BPF ring buffer needs to be aligned to the architecture register size, otherwise we may hit misaligned pointer dereference issues, such as:
thread 'main' panicked at src/bpf.rs:162:43:
misaligned pointer dereference: address must be a multiple of 0x8 but is 0x56516a51e004
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Prevent this by making sure the buffer is always aligned to 64-bits.
Fixes: 93dc615 ("scx_rustland: use a ring buffer for queued tasks")
=> scx_rustland: prevent misaligned pointer dereference

rust/scx_utils/Cargo.toml, rust/scx_utils/src/lib.rs, rust/scx_utils/src/topology.rs, scheds/rust/scx_rusty/Cargo.toml, scheds/rust/scx_rusty/src/main.rs
scx_rusty has logic in the scheduler to inspect the host to automatically build scheduling domains across every L3 cache. This would be generically useful for many different types of schedulers, so let's add it to the scx_utils crate so it can be used by others.
=> rust: Add topology module to utils crate

scheds/rust/scx_rustland/src/bpf.rs, scheds/rust/scx_rustland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Add two command line options to adjust rustland behavior without recompiling the code. These are the usual changes that I apply manually in the code to test the "generic layer" of the scheduler.
Having them available as command line options can help for testing and debugging, in particular for users that may need to evaluate how the scheduler works under specific scenarios.
New options:
- `--full-user`: disable all the in-kernel optimizations and sends all the scheduling events and actions to the user-space scheduler
- `--builtin-idle`: apply the built-in idle selection logic in the user-space scheduler (scheduler will dispatch tasks in the CPU selected in the `.select_cpu()` callback, using the built-in idle selection logic); also change the default behavior to dispatch tasks on the …
=> scx_rustland: additional comand line options 

rust/scx_utils/src/topology.rs
We currently panic! if we're building a Topology that detects more than two siblings on a physical core. This can and will likely happen on multi-socket machines. Given that we're planning to add support for detecting NUMA nodes soon, let's just demote the panic! to a warn!.
=> scx: Demote panic! to warn! in topology crate

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
- For static configurations of confined or grouped layers, we weren't properly propagating them to the kernel.
- We weren't trying to consume from the proper layer for grouped layers in layered_dispatch
=> layered: Fix static configuration, and dispatch for Grouped layers

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
For some reason we're sometimes (non-deterministically) not seeing the
updated cpumask / layer values in BPF if we initialize the cpumasks here
before attaching. Let's undo this for now so to avoid observing buggy
behavior, until we figure it out.
=> Refresh after attach

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
I have a usecase where specific nice values are used to bucket tasks into groups that are handled separately by different `scx_layered` policies, with no implications of relative priority between niceness X, X + 1, X - 1, etc. In other words, nicevals are used as simple tags in this scenario.
If we wanted to treat a specific niceness this way e.g. `11`, we could do so with AND'd MATCH_NICE_{ABOVE,BELOW} like so:
```json
"matches" : [
[
{
"NiceAbove": 10
},
{
"NiceBelow": 12
},
],
],
```
But this is unnecessarily verbose and doesn't communicate the intent of the match very well. Adding a `NiceEquals` matcher simplifies the config and makes intent obvious:
```json
"matches" : [
[
{
"NiceEquals": 11
},
],
],
```
This PR adds support for such a matcher.
Also, rename …
=> scx_layered: Add MATCH_NICE_EQUALS match kind

rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/lib.rs, rust/scx_utils/src/topology.rs
Manipulating cpumasks is a very common occurrence in sched_ext schedulers. The Rust `BitVec` object is available, but it's pretty confusing to use, and we also have to deal with sched_ext-specific things like being able to represent the bitmask in a way that can be consumed by BPF programs, etc.
Let's pull that logic into a new cpumask.rs crate that wraps `BitVec`, and provides a number of quality-of-life improvements. Along the way, we pull some logic out of topology.rs and move it to cpumask.rs. In a future (soon) change, we'll further update topology.rs to be more generic.
=> Add cpumask.rs crate

scheds/sync-to-kernel.sh
We aren't gonna sync all headers to the kernel tree.
=> scheds/sync-to-kernel.sh: Warn and skip if destination file is missing instead of failing

scheds/sync-to-kernel.sh
They got added back as example schedulers in the kernel tree.
=> sync-to-kernel.sh: Sync scx_central and scx_flatcg

meson-scripts/test_sched
These two schedulers are provided mostly as examples / PoC, so we should exclude them from our periodic testing, to prevent triggering false positives in our CI.
=> ci: eclude scx_qmap and scx_userland from testing

meson.build
This is to not have to require cargo when building the c schedulers (https://bugzilla.redhat.com/show_bug.cgi?id=2264277)
=> Gate cargo build options behind 'enable_rust'

rust/scx_utils/src/infeasible.rs, rust/scx_utils/src/lib.rs, scheds/rust/scx_rusty/src/main.rs
We want to avoid every scheduler implementation from having to implement
load balancing, but we also want to enable sufficient flexibility where
not every program has to have the same partition of scheduling domains,
etc. To enable this, a new load_balance crate is added which
encapsulates all of the logic for being given duty cycle and weight, and
performing the necessary math to adjust for infeasibility.
In addition, update `scx_rusty` to use the new crate.
=> Add new infeasible.rs crate

.gitmodules, README.md, meson.build, meson.options
This is to potentinally reduce issues with folks using different versions of libbpf at runtime.
=> Add libbpf as a submodule

meson.build
This reverts commit a7b39f24e2fa17297cdbef9a95f60bc54c6ddada, reversing changes made to cf7404fb03afc9a4c839825fb6692f31fac08cde.
The PR doesn't do what the description says. It instead limits the number of rustc instances to 1 for each cargo build making rust builds extremely slow. Let's revert and try again.
=> Revert "Merge pull request #165 from sched-ext/reduce-rust-build-load"

.gitmodules, README.md, meson-scripts/build_libbpf, meson-scripts/cc_cflags_probe.c, meson.build, meson.options, rust/scx_rustland_core/meson.build, rust/scx_utils/meson.build, scheds/rust/scx_layered/meson.build, scheds/rust/scx_rlfifo/meson.build, scheds/rust/scx_rustland/meson.build, scheds/rust/scx_rusty/meson.build
This is to potentinally reduce issues with folks
using different versions of libbpf at runtime.
This also:
- makes static linking of libbpf the default
- adds steps in `meson setup` to fetch libbpf and make it
=> Add libbpf as a submodule (take 2)

rust/scx_rustland_core/README.md, rust/scx_rustland_core/src/bpf.rs, rust/scx_rustland_core/src/bpf/intf.h, rust/scx_rustland_core/src/bpf/main.bpf.c, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/src/main.rs
Improve `scx_rustland_core` API:
- add a method to assign a specific CPU to a task: `DispatchedTask.set_cpu()`
- add a method to assing a specific time slice to a task (overriding the default global time slice): `DispatchedTask.set_slice_ns()`
- provide a constructor that allows to create a `DispatchedTask` from a `QueuedTask`
- drop unused `payload` attribute (in the future we will provide a better API to attach a custom payload to a dispatched task, if needed)
This is all purely code refactoring, no functional change to `scx_rustland` or `scx_rlfifo`.
=> scx_rustland_core: API improvements

meson-scripts/build_libbpf
Otherwise, we end up passing CC=ccache to libbpf's Makefile which triggers an error as ccache invoked on its own can't act as a stand-in for the compiler.
=> meson-scripts/build_libbpf: Accommodate meson setting CC to "ccache $COMPILER"

scheds/rust/scx_rlfifo/src/main.rs
Small improvement to make the scheduler a little more responsive without introducing extra complexity.
Moreover, print a warning banner when the scheduler starts to clarify its role as a basic example.
=> scx_rlfifo: warn user about performance

meson.build
This is to fix an error sometimes seen when compiling with gcc,
whereby the position independent sched ext rust libraries
don't play nicely with the libbpf library if it's not also built
as position independent.
This also explicitly sets the rustc relocation-mode to "pic",
which is the default (just so this doesn't accidentally change
out from under us).
=> Always build libbpf as a PIE

meson-scripts/build_libbpf
As @Decave pointed out, we really only need the static library file.
=> Libbpf - add BUILD_STATIC_ONLY flag

OVERVIEW.md
I changed by GitHub username to Byte-Lab, so let's update the docs.
=> [trivial] docs: Update rhone link

rust/scx_rustland_core/Cargo.toml, rust/scx_rustland_core/src/bpf.rs, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml
Use the new consume_raw() API provided by libbpf-rs with https://github.com/libbpf/libbpf-rs/pull/680.
This allows to be more precise and efficient at processing tasks consumed from the BPF ring buffer.
NOTE: the new consume_raw() API is not available yet in any official release of the libbpf-rs crate, but cargo allows to pick versions directly from git. This slightly increases the build time of scx_rustland_core and the schedulers based on this crate (since we need to recompile libbpf-rs from source), but we can re-add a proper versioned dependency once the libbpf-rs is out.
TODO: this new API also offers the possibility to consume multiple items from the BPF ring buffer with a single call to consume_raw(). This could be investigated and implemented as a potential future enhancement.
=> scx_rustland_core: use new consume_raw() libbpf-rs API

scheds/rust/scx_rustland/src/main.rs
A couple of adjustments that have been empirically proven to be highly effective in improving system responsiveness, particularly in the context of gaming and live conferencing / live streaming workloads.
Reducing the base time slice from 20ms to 5ms helps prevent potential audio cracking issues and sporadic lags under average load conditions. Additionally, setting a cap on the maximum task weight helps prevent similar issues when tasks with very high priority are running within the same SCHED_EXT scheduling class.
=> scx_rustland: interactive tuning

rust/scx_rustland_core/Cargo.toml, rust/scx_rustland_core/src/bpf.rs, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml
In order to use the new consume_raw() API we need to depend on a version of libbpf-rs that is not released yet.
Apparently adding such dependency may introduce a potential dependency conflict with libbpf-sys.
Therefore, revert this change and go back to the previous consume() API. One a new version of libbpf-rs will be out we can update all our dependencies to use the new libbpf-rs and re-apply this patch to scx_rustland_core.
Fixes: 7c8c5fd ("scx_rustland_core: use new consume_raw() libbpf-rs API")
=> Revert "scx_rustland_core: use new consume_raw() libbpf-rs API"

.github/workflows/build-scheds.yml, README.md, meson-scripts/bpftool_dummy.c, meson-scripts/build_bpftool, meson-scripts/fetch_bpftool, meson.build, meson.options, rust/scx_rustland_core/meson.build, rust/scx_utils/meson.build, scheds/rust/scx_layered/meson.build, scheds/rust/scx_rlfifo/meson.build, scheds/rust/scx_rustland/meson.build, scheds/rust/scx_rusty/meson.build
This pairs with the new default behavior to fetch and build libbpf and is mostly being used so we can use the latest bpftool and libbpf.
=> Fetch and build bpftool by default

scheds/c/scx_flatcg.bpf.c, scheds/include/scx/common.bpf.h
The flatcg scheduler uses a rb_node type - struct cgv_node - to keep track of vtime. On cgroup init, a cgv_node is created and stashed in a hashmap - cgv_node_stash - for later use. In cgroup_enqueued and try_pick_next_cgroup, the node is inserted into the rbtree, which required removing it from the stash before this patch's changes.
This patch makes cgv_node refcounted, which allows keeping it in the stash for the entirety of the cgroup's lifetime. Unnecessary bpf_kptr_xchg's and other boilerplate can be removed as a result.
Note that in addition to bpf_refcount patches, which have been upstream for quite some time, this change depends on a more recent series [0].
[0]: https://lore.kernel.org/bpf/20231107085639.3016113-1-davemarchevsky@fb.com/
=> scx_flatcg: Keep cgroup rb nodes stashed

scheds/rust/scx_layered/src/main.rs
This makes writing configs and allows introducing new fields without breaking existing configs.
=> scx_layered: Make config json assume default vaules for unspecified fields

meson-scripts/get_clang_ver, meson.build
My development environment uses clang from git, and meson fails with the following error:
```
meson setup build --prefix ~
The Meson build system
Version: 1.4.0
<snip>
meson.build:44:44: ERROR: String '' cannot be converted to int
```
Fix this problem by expanding how `get_clang_ver`  parses of clang version
=> Better parsing for clang version

rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/topology.rs, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/src/main.rs, scheds/rust/scx_rusty/src/bpf/intf.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/domain.rs, scheds/rust/scx_rusty/src/load_balance.rs, scheds/rust/scx_rusty/src/main.rs, scheds/rust/scx_rusty/src/tuner.rs
As described in https://bugzilla.kernel.org/show_bug.cgi?id=218109,
https://github.com/sched-ext/scx/issues/147 and https://github.com/sched-ext/sched_ext/issues/69, AMD chips can
sometimes report fully disabled CPUs as offline, which causes us to
count them when looking at /sys/devices/system/cpu/possible.
Additionally, systems can have holes in their active CPU maps. For
example, a system with CPUs 0, 1, 2, 3 possible, may have only 0 and 2
active. To address this, we need to do a few things:   
1. Update topology.rs to be clear that it's returning the number of
_possible_ CPUs in the system. Also update Topology to only record
online CPUs when creating its span and iterating over sysfs when
creating domains. It was previously trying to record when a CPU was
online, but this was …
=> rusty: Account for disabled but offline CPUs

rust/scx_utils/src/topology.rs
We are failing to parse /sys/devices/system/cpu/online in systems with just one CPU, for example:
$ vng -r --cpus 1 -- scx_rusty
Error: Failed to parse online cpus 0
Correctly handle strings containing only a single CPU during parsing.
Fixes: c5a3b83b ("topology: Add new topology crate")
=> topology: support single CPU systems

scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
This PR contains all the fixes for the suggested changes in PR #192. It includes the following changes:
- scx_lavd: fix formatting issues in main.rs and main.bpf.c
- scx_lavd: replace num_cpus to scx_utils::Topology
- scx_lavd: remove unnecessary arg from put_local_rq()
- scx_lavd: print one scheduling decision by default
- scs_lavd: improve the description of fairness
- scx_lavd: remove unnecessary condition check in is_wakeup_wf()
- scx_lavd: add a utility func, {try_}get_task_ctx()
- scx_lavd: move scx_bpf_error() calls to get_cpu_ctx{_id}()
- scx_lavd: improve the clarity of the task state transition
- scx_lavd: use is_wakeup_ef() in checking wait flag
- scx_lavd: remove unnecessary condition check at update_stat_for_stop()
- scx_lavd: remove unnecessary condition check at …
=> scx_lavd: addressed comments from PR #192

rust/scx_utils/src/topology.rs
As described in https://github.com/sched-ext/scx/issues/195, apparently some chips don't export information about their cache topology. There's not much we can do if we don't have that information, so let's just assume a unified cache per node if that happens.
Andrea suggested this patch -- I'm applying exactly what he proposed, with a slightly modified comment.
Suggested-by: Andrea Righi <andrea.righi@canonical.com>
=> topology: Fall back to cache 0

scheds/rust/scx_layered/src/bpf/main.bpf.c
lookup_task_ctx(), lookup_task_ctx_may_fail(), and lookup_layer() currently don't have the static keyword, so BPF may treat them as a global function. We don't actually want these to be global, so let's make them static to avoid confusing the verifier.
=> layered: Make helper functions static

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
In scx_layered, we're using a BPF_MAP_TYPE_HASH map (indexed by pid) rather than a BPF_MAP_TYPE_TASK_STORAGE, to track local storage for a task. As far as I can tell, there's no reason we need to be doing this. We never access the map from user space, and we're even passing a struct task_struct * to a helper subprog to look up the task context rather than only doing it by pid.
Using a hashmap is error prone for this because we end up having to manually track lifecycles for entries in the map rather than relying on BPF to do it for us. For example, BPF will automatically free a task's entry from the map when it exits. Let's just use TLS here rather than a hashmap to avoid issues from this (e.g. we've observed the scheduler getting evicted because we're accessing a stale map entry after a …
=> layered: Use TLS map instead of hash map

scheds/rust/scx_rusty/src/bpf/main.bpf.c
In rusty_select_cpu(), if a task is WAKE_SYNC, we'll currently migrate the task to that CPU if there are any idle cores on the system. As in [0], this condition is insufficient, as there could be idle cores elsewhere on the system, but still tasks piled up on a single local DSQ. Let's add a condition that the local DSQ has to be empty in order to apply the WAKE_SYNC migration.
Before patch:
[void@maniforge src]$ hackbench
Running in process mode with 10 groups using 40 file descriptors each (== 400 tasks) Each sender will pass 100 messages of 100 bytes
Time: 0.433
With patch:
[void@maniforge src]$ hackbench
Running in process mode with 10 groups using 40 file descriptors each (== 400 tasks) Each sender will pass 100 messages of 100 bytes
Time: 0.035
=> rusty: Check LOCAL_DSQ length for WAKE_SYNC

scheds/rust/scx_lavd/.gitignore
This is needed for `cargo publish`.
=> scx_lavd: Add .gitignore

rust/scx_rustland_core/Cargo.toml, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml
Bump up the version of the crate and update dependencies.
=> scx_rustland_core: bump up version to 0.2

rust/scx_utils/src/user_exit_info.rs, scheds/include/scx/common.bpf.h, scheds/rust/scx_rusty/src/bpf/intf.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/main.rs
The scx_rusty scheduler does not support hotplug, and expects a static
host topology throughout its runtime. Though the kernel does have
support for detecting hotplug events, we currently don't detect this in
the kernel, nor surface it to user space when it happens. Now that we
have scx_bpf_exit(), we can gracefully exit the kernel in the event of a
hotplug, and communicate to user space that it should restart the
scheduler.
This patch adds that support to scx_rusty. Note that this assumes that
we're running on a recent enough kernel that has scx_bpf_exit(). If it
doesn't, then we instead just error out of the kernel scheduler and exit
the application.
=> Gracefully handle hotplug in scx_rusty

meson.build
The build system included linux/btf.h from system even there is one in libbpf.  Adding libbpf/include/uapi to libbpf_local_h, the build system will include linux/btf.h provided by libbpf.
=> meson: Add missing path to libbpf_local_h.

meson-scripts/get_bpftool_ver, meson.build
The recent compat additions require new libbpf and bpftool. Update the requirements.
- libbpf >= 1.4
- bpftool >= 7.4
=> meson.build: Update libbpf and bpftool version requirements

meson.build
Make sure these include the same header directories.
=> Sync libbpf_h and libbpf_local_h

scheds/rust/scx_layered/src/bpf/main.bpf.c
ENONET means "Machine is not on the network" - this was supposed to be ENOENT "No such file or directory"
=> Fix error typo

scheds/rust/scx_rusty/src/bpf/main.bpf.c
In scx_rusty, now that we have a complete view of the host's topology thanks to the Topology crate, we can update our calls to scx_bpf_create_dsq() to create the DSQ on the NUMA node of the domain. It's unclear how much this will end up mattering for performance in the typical case, but we might as well do the right thing given that host topolgoy is static, and we have the information.
=> rusty: Allocate DSQ on appropriate NUMA node

scheds/rust/scx_rusty/src/bpf/main.bpf.c
Noticed a few things that could be cleaned up and/or fixed. Mostly just gets rid of
ugly boilerplate, but also fixes some issues that for some reason the compiler
wasn't noticing; like unused variables, and improper print formatting.
=> Small rusty cleanup

scheds/rust/scx_rusty/src/bpf/main.bpf.c
As of libbpf-rs 0.23.0 (which contains commit
https://github.com/libbpf/libbpf-rs/commit/9d9e979fcfb99dfee80bb81e534b5e17df941a85), libbpf-rs now generates rust structs that honor padding. We can therefore remove the custom padding in scx_rusty's struct pcpu_ctx.
For example, here is the generated pub struct pcpu_ctx:
```
pub struct pcpu_ctx {
pub dom_rr_cur: u32,
pub dom_id: u32,
pub nr_node_doms: u32,
pub node_doms: [u32; 64],
pub __pad_268: [u8; 52],
}
```
And here is the matching struct in the BPF object file:
```
struct pcpu_ctx {
u32                        dom_rr_cur;           /*     0     4 */
u32                        dom_id;               /*     4     4 */
u32                        nr_node_doms;         /*     8     4 */
u32                        node_doms[64];        /* …
```
=> rusty: Remove explicit padding

scheds/rust/scx_layered/src/bpf/main.bpf.c
When I transitioned layered to using task local storage, I messed up initializing the task_ctx, not realizing we had a separate object that was previously being used to initialize the hashmap entry. We need to initialize the task's layer to -1, and also set refresh_layer to 1.
=> layered: Fix init_task

scheds/rust/meson.build, scheds/rust/scx_lavd/meson.build, scheds/rust/scx_layered/meson.build, scheds/rust/scx_rlfifo/meson.build, scheds/rust/scx_rustland/meson.build, scheds/rust/scx_rusty/meson.build
Potentially fixes #202.
This is honestly a temporary fix until a proper fix comes by.
=> scheds-rust: build rust schedulers in sequence

rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/intf.h, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
Provide preemption capability in `scx_rustland_core` and use this feature in `scx_rustland` to improve the the responsiveness of interactive tasks.
For now the design is pretty simple:
- `scx_rustland_core` provides a new dispatch flag `RL_PREEMPT_CPU` that is mapped to `SCX_ENQ_PREEMPT`
- `scx_rustland` uses this flag when dispatching tasks that are classified as "interactive", so that they can preempt other tasks before their assigned time slice expires
This implies that interactive tasks can also preempt each other, potentially causing an excessive amount of preemption events if a consistent amount of tasks is classified as "interactive". This can be improved in the future by limiting the the amount of preemption events per sec., similar to what `scx_lavd` is doing.
Measuring the …
=> rustland: enable preemption

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
If a library creates threads, those threads will often have the same
name. If two different processes of different priority both use a
library, it may be that we want the library's threads in each process to
be put into different layers.
To support this, let's add the ability to filter not only by task name,
but also by process name via the task thread group leader's comm.
Tested by creating two executables named "foo" and "bar", which both
spawn a bunch of tasks named "exp_worker" that spin until being
interrupted. With this config: https://pastebin.com/QSGwnkDF, the tasks
were correctly matched to the expected layers.
=> layered: Add ability to match by process name

rust/scx_utils/src/topology.rs, scheds/rust/scx_rustland/src/main.rs, scheds/rust/scx_rusty/src/domain.rs
We're currently cloning cpumasks returned by calls to {Core, Cache, Node, Topology}::span(). If a caller needs to clone it, they can. Let's not penalize the callers that just want to query the underlying cpumask.
We might be able to further optimize -- the trait implementations for bitwise operations on Cpumasks don't take references on the rhs, so we're doing extra clones where we shouldn't need to. I also wasn't able to figure out how to iterate over the bits set in the underlying cpumask without using `.into_iter()`, which requires cloning as well.
=> topology: Don't allocate on calls to span()

scheds/include/scx/common.bpf.h, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
This change adds `scx_bpf_cpuperf_cap`, `scx_bpf_cpuperf_cur` and `scx_bpf_cpuperf_set` definitions that were recently introduced into [`sched_ext`](https://github.com/sched-ext/sched_ext/pull/180). It adds a `perf` field to `scx_layered` to allow for controlling performance per layer.
=> Add CPU frequency related helpers and extend scx_layered

rust/scx_utils/src/compat.rs, scheds/include/scx/common.bpf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Only the very newest kernels support scx_bpf_cpuperf_set(). Let's update
scx_layered to accommodate older kernels as well.
=> layered: Make layered backwards compat with cpufreq

scheds/rust/scx_lavd/src/main.rs
In Rust c_char can be aliased to i8 or u8, depending on the particular target architecture.
For example, trying to build scx_lavd on ppc64 triggers the following error:
error[E0308]: mismatched types
--> src/main.rs:200:38
|
200 |         let c_tx_cm: *const c_char = (&tx.comm as *const [i8; 17]) as *const i8;
|                      -------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
|                      |
|                      expected due to this
|
= note: expected raw pointer `*const u8`
found raw pointer `*const i8`
To fix this, consistently use c_char instead of assuming it corresponds to i8.
=> scx_lavd: use c_char consistently

rust/scx_rustland_core/Cargo.toml, rust/scx_rustland_core/src/lib.rs, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml, scheds/rust/scx_rustland/src/main.rs
Given that rustland now supports task preemption and it has been tested successfully, it's worhtwhile to cut a new version of the `scx_rustland_core` and `scx_rustland` crates.
Edit: also provide a `--version` command to print the version of `scx_rustland` and the version of the `scx_rustland_core` crate.
=> rustland: bump up version

rust/scx_rustland_core/Cargo.toml, rust/scx_utils/Cargo.toml, scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml, scheds/rust/scx_rusty/Cargo.toml
Bump up scx-utils version to provide the new `scx_utils::TopologyMap` (and allow to publish a new `scx_rustland` crate).
=> scx-utils: bump up version to 0.8.0

scheds/rust/scx_lavd/src/bpf/main.bpf.c
In _some_ kernel versions, loading scx_lavd fails with an error of "bpf_rcu_read_unlock is missing". The usage of
bpf_rcu_read_lock/unlock() in proc_dump_all_tasks() is correct but the bpf verifier still think bpf_rcu_read_unlock() is missing. The most plausible reason so far is that the problematic kernel does not have a commit 6fceea0fa59f ("bpf: Transfer RCU lock state between subprog calls"), failing inter-procedural analysis between proc_dump_all_tasks() and 
submit_task_ctx(). Thus, we force inline submit_task_ctx() (no inter-procedural analysis by the verifier is necessary) for the time being.
Suggested-by: Tejun Heo <tj@kernel.org>
=> scx_lavd: always inline submit_task_ctx to make the verifier happy

rust/scx_rustland_core/Cargo.toml, rust/scx_rustland_core/src/alloc.rs, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml
In order to prevent deadlock conditions user-space schedulers need to perform memory allocations from a pool of pre-allocated memory that will never be unmapped/reclaimed by the kernel (unevictable memory).
However, there is a special kernel sysctl setting
(vm.compact_unevictable_allowed) that allows kcompactd to reclaim unevictable memory. This behavior should be prevented by setting vm.compact_unevictable_allowed = 0, that is what scx_rustland_core does transparently when a scheduler is started, restoring the previous value when the scheduler is stopped.
Unfortunately, this is not always doable, especially when running a scheduler inside a containerized environment or under certain security/privilege restrictions (e.g., AppArmor confinement).
Therefore, just report a WARNING if we are …
=> scx_rustland_core: relax compact unevictable memory constraint

scheds/rust/scx_rustland/Cargo.toml
Bump up scx_rustland version to use the new scx_rustland_core crate.
=> scx_rustland: bump up version to 0.0.6

meson-scripts/fetch_libbpf
When CDPATH is set the fetch_libbpf build script will cd into the preferred CDPATH directory. This change removes the CDPATH environment variable so any preferred CDPATH paths are ignored. The issue can be reproduced with the following steps:
```
$ mkdir -p /tmp/libbpf
$ CDPATH=/tmp/ meson setup build --prefix /tmp
```
The build should fail at the fetch_libbpf step.
=> Fix issue when CDPATH contains libbpf directory

README.md
Add extra info to the README for linking against local `libbpf.a`. It may not be the preferred way of building, but still could be useful in certain situations such as testing changes against a local libbpf version.
=> Update README with instructions for building against local libbpf

scheds/rust/scx_rusty/src/load_balance.rs
Fix 1:
scx_rusty: make per-task loads sensitive to lb_apply_weight
Rusty's load balancer calculates load differently based on average system CPU utilization in create_domain_hierarchy().  At >= 99.999% utilization, load is the product of a task's weight and duty cycle; below that, load is the same as the task's duty cycle.
populate_tasks_by_load(), however, always uses the product when calculating per-task load so that in the sub-99.999% util case, load is inflated, typically by a factor of 100 with a normal priority task.  Tasks look too heavy to migrate as a result because a single task would transfer more load than the domain imbalance allows, leading to significant imbalance in some cases.
Make populate_tasks_by_load() calculate task load the same way as domain load, checking …
=> scx_rusty: load balancing fixes

README.md
The current Slack URL gives a link to the Slack workspace, but doesn't include the invite. Update the URL to include the invite URL to make it easier for people to join the Slack workspace.
=> Update README with Slack invite link

scheds/rust/scx_rusty/src/bpf/intf.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/main.rs, scheds/rust/scx_rusty/src/tuner.rs
This is the first iteration that attempts to make `scx_rusty` more accommodating to interactive workloads. The patch set does the following:
- Makes `scx_rusty` a deadline scheduler, rather than a simple vtime scheduler. The deadline is calculated according to a number of factors:
- First and foremost, the deadline is determined by a task's average runtime. Unlike with EEVDF, which sets a task's deadline based on its slice length, `scx_rusty` tracks a task's average runtime, and scales its deadline inversely according to its weight.
- `scx_rusty` also tracks the frequency with which a task is blocked, and the frequency with which a task wakes other tasks. In the former case, the task is likely to be a consumer, and in the latter case, a producer (or both if the frequency is high for …
=> Make scx_rusty interactive

.github/workflows/build-scheds.yml, meson-scripts/test_sched
Enable kvm acceleration and qemu microvm to speed up CI tests inside virtme-ng.
Also adjust the regex to catch potential errors excluding a false positive triggered by the new configuration.
Link: https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
Link: https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
=> ci: enable kvm support in the github workflow

scheds/include/scx/common.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/bpf/main.bpf.c
scx_lavd implemented 32 and 64 bit versions of a base-2 logarithm function. This is now also used in rusty. To avoid code duplication, let's pull it into a shared header.
Note that there is technically a functional change here as we remove the always inline compiler directive. We instead assume that the compiler will know best whether or not to inline the function.
=> common: Pull bpf_log2l() into helper function header

INSTALL.md
Add install instruction for Nix, which is maintained as Flake by [Chaotic-CX](https://github.com/chaotic-cx/nyx)
=> INSTALL: Add instructions for Nix

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
This PR supports CPU frequency scaling in scx_lavd in a minimal form. 
We keep track of 1) utilization of each CPU and 2) _performance criticality_ of each task to know the required CPU performance (e.g., frequency) demand. The performance criticality of a task denotes how critical it is to CPU performance (frequency). Like the notion of latency criticality, we use three factors: the task's average runtime, wake-up frequency, and waken-up frequency. A task's runtime is longer, and its two frequencies are higher; the task is more performance-critical because it would be a bottleneck in the middle of the task chain.
=> scx_lavd: support CPU frequency scaling

scheds/include/scx/common.bpf.h, scheds/rust/scx_rusty/src/bpf/intf.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/main.rs
There's currently a slight issue on existing kernels on the hotplug
path wherein we can start to receive scheduling callbacks on a CPU
before that CPU has received hotplug events. For CPUs going online, this
can possibly confuse a scheduler because it may not be expecting
anything to ever happen on that CPU, and therefore may do things that
could cause the scheduler to crash. For example, without this PR,
scx_rusty will try to consume from a bogus DSQ that doesn't exist on the
hotplug online path, which causes ext.c to boot out the scheduler.
Though this issue will soon be fixed in ext.c, let's explicitly add the
necessary logic to scx_rusty so that it supports hotplug onlining.
=> rusty: Support CPU hotplug onlining

rust/scx_rustland_core/Cargo.toml, rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml
Replace the BPF_MAP_TYPE_QUEUE with a BPF_MAP_TYPE_USER_RINGBUF to store the tasks dispatched from the user-space scheduler to the BPF component.
This eliminates the need of the bpf() syscalls, significantly reducing the overhead of the user-space->kernel communication and delivering a notable performance boost in the overall system throughput.
Based on experimental results, this change allows to reduces the scheduling overhead by approximately 30-35% when the system is overcommitted.
This improvement has the potential to make user-space schedulers based on scx_rustland_core viable options for real production systems.
Link: https://github.com/libbpf/libbpf-rs/pull/776
=> scx_rustland_core: use a BPF_MAP_TYPE_USER_RINGBUF to dispatch tasks

services/systemd/scx.service
Currently if the scx.service is failing to launch due issues, systemd will try to start the scheduler all the time. This results into a massive flood to the kernel and does not bring the service up again.
explanation of the changes:
The StartLimitBurst=2 and StartLimitIntervalSec=30 settings tell systemd that if the service unsuccessfully tries to restart itself twice within 30 seconds, it should enter a failed state and no longer try to restart. This ensures that if the service is truly broken, systemd won't continuously try to restart it.
=> systemd-service: Don't restart always

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
If there is a higher priority task when running ops.tick(), ops.select_cpu(), and ops.enqueue() callbacks, the current running tasks yields its CPU by shrinking time slice to zero and a higher priority task can run on the current CPU.
As low-cost, fine-grained preemption becomes available, default parameters are adjusted as follows:
- Raise the bar for remote CPU preemption to avoid IPIs.
- Increase the maximum time slice.
- Gradually enforce the fair use of CPU time (i.e., ineligible duration)
Lastly, using CAS, we ensure that a remote CPU is preempted by only one CPU. This removes unnecessary remote preemptions (and IPIs).
=> scx_lavd: support yield-based preemption

rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/main.bpf.c, rust/scx_utils/src/topology.rs, scheds/rust/scx_rustland/src/main.rs
This PR contains a set of changes that I've been experimenting with for some time.
Given the optimized communication between user-space -> kernel (#270), it seems like a good time now to apply also these changes and potentially elevate scx_rustland to a more production-ready scheduler.
With these changes in place we can reduce the CPU time used by the scheduler and improve the level of responsiveness whether the system is under or over commissioned.
In terms of numbers the improvement can be quantified around a +4-5% boost in fps in games, such as Baldur's Gate 3, Counter-Strike 2 and Cyberpunk 2077, when the system is over commissioned. <s>The same results can be obtained both in the under-commissioned and over-commissioned scenarios.</s>
Here is a short summary of the changes:
- …
=> rustland: reduce scheduling overhead

scheds/rust/scx_rustland/src/main.rs
Always dispatch at least one task, even if all the CPUs are busy.
This small overcommitment allows to maximize the CPU utilization without introducing bubbles in the scheduling and also without introducing regressions in terms of resposiveness.
Before this change the average CPU utilization of a `stress-ng -c 8` on an 8-cores system is around 95%. With this change applied the CPU utilization goes up to a consistent 100%.
=> scx_rustland: maximize CPU utilization

scheds/rust/scx_rustland/src/main.rs
During the initialization phase the scheduler needs to be aware of all the available CPUs in the system (also those that are offline), in order to create a proper per-CPU DSQ for all of them.
Otherwise, if some cores are offline, we may get errors like the following:
swapper/7[0] triggered exit kind 1024:
runtime error (invalid DSQ ID 0x0000000000000007)
Backtrace:
scx_bpf_consume+0xaa/0xd0
bpf_prog_42ff1b9d1ac5b184_rustland_dispatch+0x12b/0x187
Change the code to configure the BpfScheduler object with the total amount of CPUs available in the system and prevent such failure.
This fixes #280.
=> scx_rustland: properly support offline CPUs

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
This PR contains two non-functional changes:
1) Added the comments describing the preemption design in scx_lavd.
2) Added the log message saying the scx_lavd is not optimized for multi-CCX/NUMA architectures. The message will be printed out when the scx_lavd is initialized.
=> scx_lavd: add non-functional misc updates

scripts/process_runqlat.bt
Add a `scripts` folder to hold scripts that are useful for the project, and add a bpftrace program to measure the runqueue latency for a process.
bpftrace's built-in runqlat.bt program instruments runqueue latency for all processes and does not provide a way to filter by PID. For sched_ext performance work, we are interested in the runqueue latency of a specific process we are trying to optimize, such as a video game. Therefore, we need to create a custom bpftrace program to achieve this.
`process_runqlat.bt` instruments runqueue latency for a PID and its threads. This script measures the runqueue latency for a specified PID and includes all threads spawned by that process.
USAGE: `sudo ./scripts/process_runqlat.bt <PID>`
The program output will include:
- Stats by thread (count, avg …
=> scripts: Add script to measure runqlat for a process

scripts/process_runqlat.bt
Use tabs instead of spaces for indentation in process_runqlat.bt. I also updated comments and fixed a typo.
=> scripts: whitespace cleanup for process_runqlat.bt

services/systemd/journald@sched-ext.conf
It seems that the original journald settings were a bit too restrictive. 
- Let's increase the journal limit to 50MB (the default value for regular journald in CachyOS)
- let's abolish unnecessary cleaning limits
The changes made will make it easier to catch potential anomalies in the system.
=> journal.conf: increase the size of the logs and drop unneeded options

scheds/rust/scx_lavd/src/bpf/main.bpf.c
Originally the implementation of function rsigmoid_u64 will perform substraction even when the value of "v" equals to the value of "max" , in which the result is certainly zero.
We can avoid this redundant substration by changing the condition from ">" to ">=" since we know when the value of "v" and "max" are equal we can return 0 without any substract operation.
=> Avoid redundant substraction in rsigmoid_u64

rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/src/main.rs
Introduce a "low power" mode in `scx_rustland` (provided by `scx_rustland_core`) that can be used to reduce power consumption with a minimal impact on the performance of latency-critical tasks.
The idea is to prevent CPUs from immediately waking up when they enter the idle state, if there are other CPUs active. Having other CPUs active still allows to dispatch latency-critical tasks, so system is still responsiveness, while the background CPU-intensive tasks receive an additional throttling.
This has the consequence of reducing the overall system throughput by intentionally creating bubbles in the scheduling and exploiting the additional time spent by the CPUs in idle state to save power.
The following test case summarizes the benefit of the "low power" mode:
- play a video game …
=> scx_rustland: introduce low power mode

rust/scx_utils/src/compat.rs, rust/scx_utils/src/lib.rs, rust/scx_utils/src/user_exit_info.rs, scheds/rust/scx_rusty/src/bpf/intf.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/main.rs
The kernel now has the notion of `hotplug_seq`, wherein a scheduler can specify the current hotplug sequence number in its struct sched_ext_ops, and if that value has changed by the time the scheduler is attached, the scheduler is exited from the kernel with exit code `SCX_ECODE_ACT_RESTART | SCX_ECODE_RSN_HOTPLUG`.
This set does a couple of things:
1. Updates scx_utils to support these semantics
2. Update `scx_rusty` to use this built-in hotplug logic rather than spinning its own
`scx_lavd` and `scx_layered` are not updated to use `scx_ops_open!()`, as they don't have the requisite logic to detect and restart in the event of a hotplug.
=> Add remaining hotplug pieces

meson.build, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/include/scx/common.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/bpf/main.bpf.c
When compiling with warnings enabled, I noticed some bugs in scx_rusty, and stray warnings in scx_layered. To make it easier to catch such issues in the future, we:
1. Extend the build system to apply -Werror if the built-in meson --werror `meson setup` flag is specified (option is `true` by default)
2. Fix the issues in `scx_layered`, `scx_rusty`, `scx_rustland`, `scx_rlfifo`, and `scx_lavd`
The issues in `scx_rusty` are correctness issues, not just benign build issues. They seem to marginally improve interactivity, but it seems somewhat clear that rusty is really in need of preemption support to cut down on rq delays. The other fixes are all benign, but we make them anyways as otherwise the build will break for anyone using the default options.
=> Fix warnings

meson.build
Add '-Wno-maybe-uninitialized' option since gcc spits a warning (as an error) at release build. Following is the error message without the option. The problem is reported at [here](https://github.com/sched-ext/scx/issues/296#issuecomment-2119141992).
❯ meson setup build -Dbuildtype=release  --prefix ~
❯ meson compile -C build  --jobs=$(nproc)
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/changwoo/ws-multics69/dev/scx-github/build -j 16 ninja: Entering directory `/home/changwoo/ws-multics69/dev/scx-github/build' [3/40] Generating libbpf with a custom command
FAILED: cc_cflags_probe.c.__PHONY__
/home/changwoo/ws-multics69/dev/scx-github/meson-scripts/build_libbpf /usr/bin/jq /usr/bin/make …
=> meson: fix a build error for libbpf at release build

scheds/c/scx_simple.bpf.c
scx_simple is a basic scheduler that does either basic vtime, or global FIFO, scheduling. At first glance, it may be confusing why we create a separate DSQ rather than just using SCX_DSQ_GLOBAL. Let's add a comment explaining the reason for this, so that users that are going over scx_simple as an example scheduler don't get confused.
=> simple: Add comment explaining use of SHARED_DSQ

scheds/rust/scx_rustland/src/main.rs
No functional changes, just some code cleanup, remove dead code and also report `nr_running` to stdout.
=> scx_rustland: cleanups

scheds/c/scx_flatcg.bpf.c
A's share in the hierarchy should be 100/(200+100), plus 200/(200+100) doesn't equal to 1/3. Correct the mistake by changing "200" to "100".
=> scx_flatcg: Correct content error in comment

rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/src/main.rs
This is a v2 of the FIFO mode feature, more tested and tuned, based on additional experimental results (specifically to determine the optimal USERSCHED_TIMER_NS and the conditions to automatically enter and exit to/from FIFO mode).
The idea is to give an option to automatically transition to a FIFO scheduler when the system is underutilized and switch to the user-space scheduler only when the system is over commissioned.
This allows to maximize performance during regular system use, for example gaming without additional stress tests running, while also ensuring responsiveness if a CPU-intensive workload is suddenly started.
FIFO mode can lead to less predictable performance (due to the potential transitions between the scheduling policies), therefore it is provided as an optional feature …
=> scx_rustland: introduce fifo mode

rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
A set of changes that seems to mitigate the audio cracking issues that I was experiencing when the system is massively over-commissioned.
Here's a summary of these changes:
- dispatch interactive tasks on the first CPU available and non-interactive tasks on the CPU selected by the idle selection logic
- assign the same time slice both to interactive and non-interactive tasks
- implement a second-chance migration in `select_cpu()`: after a task has been directly dispatched prevent to immediately migrate it on a different CPU, but force it to stay on `prev_cpu` for another round
Tested both on an Intel Core i7 and AMD Ryzen 7 5800X 8-Core with multiple games / audio workloads. On both systems these changes seem to improve the responsiveness both in terms of fps and audio quality.
=> scx_rustland: improve audio workload and performance predictability

rust/scx_rustland_core/assets/bpf/main.bpf.c
The setting of `ops->dispatch_max_batch` leads to a too large allocated size for percpu allocator, and it will be unhappy if we want a size larger than `PCPU_MIN_UNIT_SIZE`. Reduce `MAX_ENQUEUED_TASKS` for fix.
The details for the issue can be found at #308.
=> Reduce MAX_ENQUEUED_TASKS to fit percpu allocator

scheds/c/scx_central.bpf.c
Newer sched_ext kernel versions sets the scheduler to schedule all tasks within the system by default. However, some users are using the old versions of kernel.
Therefore we call "__COMPAT_scx_bpf_switch_all()" to move all tasks to "SCHED_EXT" class so scx_central would schedule all tasks by default in older kernels.
fix #313
=> scx_central: Provide backward compability

scheds/rust/scx_lavd/src/bpf/main.bpf.c
Use the GNU built-in __sync_fetch_and_xor() to perform the XOR operation on global variable "__sys_cpu_util_idx" to ensure the operations visibility.
The built-in function "__sync_fetch_and_xor()" can provide both atomic operation and full memory barrier which is needed by every operation (especially store operation) on global variables.
=> scx_lavd: Enforce memory barrier in flip_sys_cpu_util

scheds/rust/scx_lavd/src/bpf/main.bpf.c
Reverts sched-ext/scx#318
Since the write is done in the interrupt context, we don't need atomic write here. So I revert it.
=> Revert "scx_lavd: Enforce memory barrier in flip_sys_cpu_util"

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c
- Any tasks with custom affinity which are enqueued outside of wakeup path were considered to be `affn_viol` and queued on the global DSQ. This is unnecessary. The per-layer DSQs and preemption path can handle tasks with custom affinities just fine for tasks in open or grouped layers. Update enqueue to better handle tasks with custom affinities.
- `affn_viol` tasks were queued onto `SCX_DSQ_GLOBAL` which has precedence over all user and thus per-layer DSQs. It doesn't make sense to boost tasks which are in violation. Let's create user fallback DSQs and use them to handle affinity violations.
- Add dump method to aid debugging.
=> scx_layered: Improve affn_viol handling and implement dump method

rust/scx_rustland_core/assets/bpf.rs
As reported in #319, we may get a build failure in presence of musl, that requires additional parameters in sched_param.
Fix by adding a proper conditional to support both gnu libc and musl libc.
This fixes #319.
=> scx_rustland_core: fix build error with musl

README.md
Linked to #317 where the schedulers failed to load due to CONFIG_BPF_LSM being disabled.
=> Document the needed BPF kernel config

scheds/include/scx/common.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c
In order to prevent compiler from merging or refetching load/store operations or unwanted reordering, we take the implemetation of READ_ONCE()/WRITE_ONCE() from kernel sources and add them into `scheds/include/scx/common.bpf.h`.
Use WRITE_ONCE() in function flip_sys_cpu_util() to ensure the compiler doesn't perform unnecessary optimization so the modification of bit flipping can be visible to readers as fast as possible.
=> scx_lavd: Adding READ_ONCE()/WRITE_ONCE() macros

README.md
One user on Slack reported a bug with building. This was due to a lack of installed dependencies. It may be worth pointing out to users what needs to be installed as dependencies.
=> README: Adding dependencies to allow compilation

scheds/rust/scx_rustland/src/main.rs
Commit 23b0bb5f ("scx_rustland: dispatch interactive tasks on any CPU") allows only interactive tasks to be dispatched on any CPU, enabling them to quickly use the first idle CPU available. Non-interactive tasks, on the other hand, are kept on the same CPU as much as possible.
This change deprioritizes CPU-intensive tasks further, but it also helps to exploit cache locality, while latency-sensitive tasks are dispatched sooner, improving overall responsiveness, despite the potential migration cost.
Given this new logic, the built-idle option, which forces all tasks to be dispatched on the CPU assigned during select_cpu(), no longer offers significant benefits. It would merely reduce the responsiveness of interactive tasks.
Therefore, simply remove this option, allowing the scheduler to …
=> scx_rustland: get rid of --builtin-idle option

scheds/rust/scx_rusty/src/bpf/main.bpf.c
In cpumask_intersects_domain(), we check whether a given cpumask has any CPUs in common with the specified domain by looking at the const, static dom_cpumasks map. This map is only really necessary when creating the domain struct bpf_cpumask objects at scheduler load time. After that, we can just use the actual struct bpf_cpumask object embedded in the domain context. Let's use that and cpumask kfuncs instead.
This allows rusty to load with
https://github.com/sched-ext/sched_ext/pull/216.
=> rusty: Use cpumask kfuncs in cpumask_intersects_domain()

rust/scx_rustland_core/assets/bpf.rs, rust/scx_utils/src/user_exit_info.rs, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/src/main.rs, scheds/rust/scx_rusty/src/main.rs
Make restart handling with user_exit_info simpler and consistently use the load and report macros consistently across the rust schedulers. This makes all schedulers automatically handle auto restarts from CPU hotplug events. Note that this is necessary even for scx_lavd which has CPU hotplug operations as CPU hotplug operations which took place between skel open and scheduler init can still trigger restart.
=> scx: Unify loading and running boilerplate across rust schedulers

rust/scx_rustland_core/assets/bpf/main.bpf.c
Report time slice and enqueue flags in the debugging trace of dispatch events. This can be useful to generate more detailed traces about the user-space scheduler, which can provide valuable insights for refining time slice logic and task preemption.
=> scx_rustland_core: add extra debugging info to dispatch_task()

services/systemd/scx.service
In conversation with @Byte-Lab , we determined that it is preferable to launch the service at a later stage of the system's startup.
=> scx.service: start service after graphical target

services/scx
Commit https://github.com/sched-ext/scx/commit/2403f606312123ada197d174aa1aa4158791d8b7 made changes to the naming of flags and thus one of the example flags no longer exists. Therefore, let's use the existing one so as not to cause unnecessary confusion.
=> scx: update /etc/default/scx sample flags

scheds/rust/scx_rustland/src/main.rs
Make sure to never assign a time slice longer than the default time slice, that can be used as an upper limit.
This seems to prevent potential stall conditions (reported by the CachyOS community) when running CPU-intensive workloads, such as:
[   68.062813] sched_ext: BPF scheduler "rustland" errored, disabling
[   68.062831] sched_ext: runnable task stall (ollama_llama_se[3312] failed to run for 5.180s)
[   68.062832]    scx_watchdog_workfn+0x154/0x1e0
[   68.062837]    process_one_work+0x18e/0x350
[   68.062839]    worker_thread+0x2fa/0x490
[   68.062841]    kthread+0xd2/0x100
[   68.062842]    ret_from_fork+0x34/0x50
[   68.062844]    ret_from_fork_asm+0x1a/0x30
Fixes: 6f4cd853 ("scx_rustland: introduce virtual time slice")
Tested-by: SoulHarsh007 <harsh.peshwani@outlook.com> …
=> scx_rustland: never use a time slice that exceeds the default value

scheds/include/vmlinux/vmlinux.h, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
When system-wide CPU utilization is low, it is very likely all the CPUs are running with very low utilization. That means all CPUs run with low clock frequency thanks to dynamic frequency scaling and very frequently go in and out from/to C-state. That results in low performance (i.e., low clock frequency) and high power consumption (i.e., frequent P-/C-state transition).
The idea of *core compaction* is using less number of CPUs when   system-wide CPU utilization is low. The chosen cores (called "active   cores") will run in higher utilization and higher clock frequency, and the rest of the cores (called "idle cores") will be in a C-state for a much longer duration. Thus, the core compaction can achieve higher  performance with lower power consumption.
One potential problem of core …
=> scx_lavd: core compaction for low power consumption

scheds/c/scx_central.c, scheds/c/scx_pair.c, scheds/include/scx/common.h, scheds/include/scx/user_exit_info.h
The RESIZE_ARRAY() macro assumes the presence of an in-scope "skel" variable. This is bad practice and can cause issues in other macros that use it. Let's update it to explicitly take a skel argument.
=> uei: Pass skel to RESIZE_ARRAY()

rust/scx_utils/src/topology.rs
This change adds the CPU frequency transition latency from the `cpuinfo_transition_latency` from sysfs. The value of this field is described [cpufreq
docs](https://www.kernel.org/doc/Documentation/cpu-freq/user-guide.txt). On supported systems it returns the CPU frequency transition latency in nanoseconds. The goal of this change is so that in the future schedulers can use this data to make better frequency scaling decisions.
=> scx_utils: Add CPU freq transition latency

scheds/rust/scx_mitosis/meson.build
The target wasn't dependent on the previous sched so building all schedulers ended up not building scx_mitosis which broke the install script.
=> mitosis: Fix build

meson-scripts/get_clang_ver
If LLVM is compiled with the LLVM_VERSION_SUFFIX cmake option, then the version may have an additional suffix, for example "18.1.7+libcxx". Gentoo for example uses this to fend off ABI issues between libstdc++ and libc++.
=> Support LLVM_VERSION_SUFFIX in clang version parsing regex

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c
When a device is suspended and resumed, the suspended duration is added up to a task's runtime if the task was running on the CPU. After the resume, the task's runtime is incorrectly long and the scheduler starts to recognize the system is under heavy load. To avoid such problem, the suspended duration is measured and substracted from the task's runtime.
=> scx_lavd: properly calculate task's runtime after suspend/resume

scheds/include/scx/common.bpf.h, scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c
These are used in mitosis, but they belong in common code so other schedulers can do css iteration.
=> common: Add css iter forward declares

services/scx
Synchronize the scheduler list with the actual state. Even if scx_mitosis is in the early stages of development, let's show in the config that it exists.
=> scheds: Add scx_mitosis scheduler to /etc/default/scx

services/systemd/scx.service
Switching the scheduler requires changing SCX_SCHEDULER (and potentially also SCX_FLAGS) in /etc/default/scx.
This patch allows overriding these settings using systemd environment variables SCX_SCHEDULER_OVERRIDE and SCX_FLAGS_OVERRIDE, without changing the default configuration.
Example:
> grep SCX_SCHEDULER /etc/default/scx
SCX_SCHEDULER=scx_rusty
> sudo systemctl status scx
...
Main PID: 8021 (scx_rusty)
...
> sudo systemctl set-environment SCX_SCHEDULER_OVERRIDE=scx_rustland
> sudo systemctl restart scx
> sudo systemctl status scx
...
Main PID: 4021 (scx_rustland)
...
This feature can be useful for quickly testing different schedulers and settings, without altering the global system configuration.
=> scx.service: allow overriding scx variables

services/README.md
Add a small section to document how to use SCX_SCHEDULER_OVERRIDE and SCX_FLAGS_OVERRIDE with the scx systemd service.
Also fix a small typo (namspace -> namespace).
=> scx.service: document scx override variables

rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
A set of changes that helps prevent potential starvation conditions.
This also seems to improve system responsiveness (~4-5% fps during the typical "gaming while building the kernel" benchmark) and it also helps to prevent potential audio cracking issues.
This patch has been produced thanks to the extensive iteration tests performed by SoulHarsh007 <harsh.peshwani@outlook.com> from the CachyOS community. Big kudos to him for all his valuable feedback.
=> scx_rustland: prevent starvation

rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/main.bpf.c, rust/scx_utils/src/compat.rs, scheds/c/scx_central.bpf.c, scheds/c/scx_nest.bpf.c, scheds/c/scx_qmap.bpf.c, scheds/c/scx_qmap.c, scheds/c/scx_simple.bpf.c, scheds/include/scx/common.h, scheds/include/scx/compat.bpf.h, scheds/include/scx/compat.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c, scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/main.rs
In preparation of upstreaming, set the currently released v6.9 kernels as the minimum requirement and strip the compat features. The only remaining one is for dsq iters. This needs updates from BPF side and will be handled later.
=> Strip compat support

scheds/rust/scx_rusty/src/bpf/main.bpf.c
It seems that task_set_domain() is nearly at the point where it can cause the verifier to get confused and think that it's exceeding the number of available instructions per program. I've seen this a number of times when making small changes to task_set_domain(), and it's once again happened @vax-r (I-Hsin Cheng) made a small cleanup change to rusty in https://github.com/sched-ext/scx/pull/362.
To avoid this, let's just make dom_xfer_task() a separate global program so that the verifier doens't have to worry about branch pruning, etc depending on what the caller does. This should hopefully make task_set_domain() (and its callers) much less brittle.
=> rusty: Make dom_xfer_task() a global prog

scheds/c/scx_qmap.bpf.c, scheds/c/scx_qmap.c, scheds/include/scx/compat.bpf.h
__COMPAT_scx_bpf_consume_task() wasn't calling scx_bpf_consume_task() at all and was always returning false. Fix it.
Also, update scx_qmap usage example so that it matches cgroup ID rather than comm prefix. This should make testing with multiple processes a bit easier.
=> scx/compat.bpf.h: Fix __COMPAT_scx_bpf_consume_task() and improve scx_qmap example

rust/scx_utils/src/infeasible.rs, rust/scx_utils/src/topology.rs
Take advantages of BTreeMap's Entry API working with or_insert() to do the conditional insertion. Insert only when the entry doesn't exist. Doing so can reduce the amount of code and provide better readability and perform in-place manipulation.
* [BTreeMap example](https://doc.rust-lang.org/nightly/std/collections/struct.BTreeMap.html#examples)
* [BTreeMap Entry API](https://doc.rust-lang.org/nightly/std/collections/struct.BTreeMap.html#method.entry)
=> scx_utils: Utilize Entry API for BTreeMap insertion

scheds/rust/scx_lavd/src/bpf/main.bpf.c
Use the function `can_task1_kick_task2()` to replace places which also checking the `comp_preemption_info` between two cpus for better consistency.
=> scx_lavd: Reuse can_task1_kick_task2

.github/workflows/build-scheds.yml, meson-scripts/run_stress_tests, meson-scripts/stress_tests.ini, meson.build, meson.options
This change adds `stress-ng` as a load test for schedulers when running in CI. It will run `stress-ng` while schedulers are being tested with a reasonable amount of work. At the end of the run the `stress-ng` metrics are collected for later analysis. However, since these results may be running in a VM they may not be super robust.
Potential issues:
- The `stress-ng` args use `nproc` and could OOM (in CI this should be set to a stable value that works).
- This could probably be put into a separate test/benchmark.
Tested with a similar steps the CI uses and then:
```
meson compile -C build test_sched 
```
[output](https://gist.github.com/hodgesds/cd4a6a09d262a9cd04407c46d61f04a9) shows some issues, but they don't seem to be related to this change.
=> Add stress-ng to scheduler tests

libalpm/openrc/90-scx-scheds-upgrade.hook, libalpm/systemd/90-scx-scheds-upgrade.hook
This change will also allow users to create their own packages with a different name than "scx-scheds" and "scx-scheds-git" and the pacman hook will continue to be able to work properly.
=> Simplifying pacman-hooks

scheds/c/scx_flatcg.bpf.c
This reverts commit 3b7f33ea1b4b8182d6fdaead446c1bf1ebb2becd.
I haven't root caused it yet but it's easy to reproduce stall and trigger the watchdog after the commit - just running stress in multiple cgroups easily triggers stalls after a couple tens of seconds. Let's revert it for now.
=> Revert "scx_flatcg: Keep cgroup rb nodes stashed"

scheds/rust/scx_rusty/Cargo.toml, scheds/rust/scx_rusty/src/main.rs
We need a layer of indirection between the stats collection and their output destinations. Currently, stats are only printed to stdout. Our goal is to integrate with various telemetry systems such as Prometheus, StatsD, and custom metric backends like those used by Meta and Netflix. Importantly, adding a new backend should not require changes to the existing stats code.
This patch introduces the `metrics` [1] crate, which provides a framework for defining metrics and publishing them to different backends.
The initial implementation includes the `dispatched_tasks_count` metric, tagged with `type`. This metric increments every time a task is dispatched, emitting the raw count instead of a percentage. A monotonic counter is the most suitable metric type for this use case, as percentages can …
=> rusty: Integrate stats with the metrics framework

scheds/rust/scx_rusty/src/load_balance.rs
Origin assignment of the variable `ridx` is equivalent to comparing between "ridx" and "wids - MAX_PIDS". It's confusing using `if` statement and compare "wids - ridx" with "MAX_PIDS".
Using u64 max library helper function to perform the comparison and provide better readability.
=> scx_rusty: Refactor ridx assignment in populate_tasks_by_load

scheds/rust/scx_rusty/src/load_balance.rs
Check whether the BalanceState of `pull_dom.load` inside function `try_find_move_task` is actually the variant `NeedsPull`. It'll perform task migration in a bit more conservative manner when the system is under high loading situation.
Experiments are performed when the system is compiling linux kernel and undergoing a large amount of I/O operation at the same time using fio.
The experiments are done when compiling linux kernel and using `fio` tool to generate large amount of I/O operation to create large load imbalance by the following commands
```
// In terminal 1
$ make -j $(nproc)
// In terminal 2
$ fio io_test.fio
```
Using `perf` to observe the number of times of task migration.
```
// In terminal 3
$ sudo perf stat -e sched:sched_migrate_task -a sleep 60
```
The result shows that …
=> scx_rusty: Pull domain status check

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c
This is a second attempt to optimize tunables for a wider range of games.
1) LAVD_BOOST_RANGE increased from 14 (35%) to 40 (100% of nice range).
Now the latency priority (biased by nice value) will decide which
task should run first . The nice value will decide the time slice.
2) The first change will give higher priority to latency-critical task
compared to before. For compensation, the slice boost also increased
(2x -> 3x).
=> scx_lavd: revising tunables to reduce micro-stutters

rust/scx_rustland_core/assets/bpf/main.bpf.c
Slight reduction of dispatch overhead and small refactoring of the direct dispatch in `select_cpu`, that is now performed only when the scheduler is operating in FIFO mode (under-commissioned system).
This helps to smooth performance in the over-commissioned scenario: in this case bouncing all the tasks to the user-space scheduler can provide better performance stability (smoothing both high and low performance peaks).
Big thanks to SoulHarsh007 <harsh.peshwani@outlook.com> for the multiple extensive testing sessions.
=> scx_rustland_core: smooth performance

services/systemd/scx.service
In systemd, the After=graphical.target directive specifies that a unit should start after the graphical environment (such as the desktop) has been fully loaded. Users complain that the service's launch is too early and this sometimes causes various unwanted side effects. This should solve the problem. You might still consider adding something like this: 
```
[Unit]
Description=Run scx schedulers
[Timer]
OnBootSec=30sec
Unit=scx.service
[Install]
WantedBy=graphical.target
```
however, the PR solution should be sufficient
=> Add After=graphical.target into service

rust/scx_utils/.gitignore, rust/scx_utils/Cargo.toml, rust/scx_utils/src/lib.rs, rust/scx_utils/src/log_recorder.rs, scheds/rust/scx_rusty/src/main.rs
This change adds a new module to the scx_utils crate that provides a log recorder for metrics-rs. The log recorder will log all metrics to the console at a configurable interval in an easy to read format. Each metric type will be displayed in a separate section. Indentation will be used to show the hierarchy of the metrics. This results in a more verbose output, but it is easier to read and understand.
scx_rusty was updated to use the log recorder and all explicit metric logging was removed.
Counters will show the total count and the rate of change per second. Counters with an additional label, like `type` in
`dispatched_tasks_total` in rusty, will show the count, rate, and percentage of the total count.
```
Counters:
dispatched_tasks_total: 65559 [1344.8/s]
prev_idle: 44963 (68.6%) …
```
=> scx_utils: Add log_recorder module for metrics-rs

rust/scx_utils/Cargo.toml, rust/scx_utils/build.rs, rust/scx_utils/src/build_id.rs, rust/scx_utils/src/lib.rs, scheds/rust/scx_rusty/src/main.rs
We want schedulers to be able to print, log, etc the build ID of the
repository.
These patches update scx_utils accordingly to use vergen to generate the output of
`git describe`, and then updates scx_rusty to print that build ID when it's loaded.
In the future, we could further update scx_utils to include all of the various features
available in [0]. A subsequent patch will update scx_rusty to print this build ID value.
[0]: https://docs.rs/vergen/8.3.1/vergen/index.html
=> Add build-id to build process

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
This PR addresses the fork starvation observed when they compete against CPU-intensive workloads. CPU-intensive workloads are likely to be slice-boosted, but a newly forked task will be penalized anyway until their traits are known to the scheduler. The old initial values were too conservative, causing the fork starvation problem. Now a newly forked task will inherit its parent's tarits.
=> scx_lavd: tweaks to avoid fork starvation

scheds/rust/scx_rusty/src/load_balance.rs
Reverts sched-ext/scx#382
Causes the following issue:
```
21:32:36 [INFO] Running scx_rusty (build ID: 0.8.1-g41d60aef04d2a7fc0da738bf50391ea5f232ddd3 x86_64-unknown-linux-gnu/debug)                                
21:32:36 [INFO] ---                                                           
21:32:36 [INFO] NUMA[00] mask= 0b11111111111111111111111111111111             
21:32:36 [INFO]   DOM[00] mask= 0b00000000111111110000000011111111            
21:32:36 [INFO]   DOM[01] mask= 0b11111111000000001111111100000000            
21:32:36 [INFO] Rusty scheduler started!                                                                                                                    
thread 'main' panicked at src/load_balance.rs:689:25:
attempt to subtract with overflow
note: run with …
```
=> Revert "scx_rusty: Refactor ridx assignment in populate_tasks_by_load"

rust/scx_utils/src/compat.rs
If CONFIG_DEBUG_INFO_BTF is not enabled in the kernel, the C schedulers report the following error via libbpf, clearly indicating the missing kernel config:
libbpf: kernel BTF is missing at '/sys/kernel/btf/vmlinux', was CONFIG_DEBUG_INFO_BTF enabled?
In contrast, the Rust schedulers report a less clear error:
thread 'main' panicked at /home/arighi/src/scx/rust/scx_utils/src/compat.rs:23:9:
btf__load_vmlinux_btf() returned NULL
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Make sure to report a similar error, so that users have a better clue about the missing kernel config. After this change the error looks like the following:
thread 'main' panicked at /home/arighi/src/scx/rust/scx_utils/src/compat.rs:23:9:
btf__load_vmlinux_btf() returned NULL, was …
=> scx_utils: clarify error about missing CONFIG_DEBUG_INFO_BTF

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c
This PR contains three tunings for 
1. When a system is heavily overloaded
2. When a workload is very communication-intensive.
It changes three things:
1. Stretch the time-space more aggressively (lat_prio^2) if the task's latency priority is low (i.e., high value). This prioritizes latency-critical tasks more and gives bounded delay to throughput-oriented tasks.
2. Avoid the active/overflow CPU mask check when all CPUs are using.
3. Tighten the competition window to avoid unnecessary tasks that are competing with each other in the timeline.
In result, it improves:
1. The communication-intensive benchmark (e.g., `perf bench sched messaging`)
2. Interactive tasks when heavy compilation + `stress-ng -c`
=> scx_lavd: optimization for communicaiton-intensive workloads and heavily-overloaded cases

meson.build
libbpf has added a member `link` in the struct `bpf_map_skeleton`, which causes a build failure in SCX. This commit updates the libbpf commit hash to the latest version to avoid this error.
Please refer to commit be998aa in libbpf repo.
Error message:
ninja: Entering directory `/home/otteryc/linux2024/scx/build'
[3/25] Compiling C object scheds/c/scx_simple.p/scx_simple.c.o
FAILED: scheds/c/scx_simple.p/scx_simple.c.o
cc -Ischeds/c/scx_simple.p -Ischeds/c -I../scheds/c -I../scheds/include -I../build/libbpf/src/usr/include -I../build/libbpf/include/uapi -fdiagnostics-color=alway
s -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -pthread -MD -MQ scheds/c/scx_simple.p/scx_simple.c.o -MF scheds/c/scx_simple.p/scx_simple.c.o.d -o scheds/c/s
cx_simple.p/scx_simple.c.o -c …
=> Update libbpf commit hash

meson.build
The upstrem bpftool git repo (https://github.com/libbpf/bpftool.git) is periodically force pushed and the specific commit that we needed is not available anymore.
Instead of failing we are actually fetching the latest bpftool (HEAD) that introduced some breakage initially fixed by commit e59c48a6 ("Update libbpf commit hash").
However, updating libbpf seems to introduce a run-time problem and all the schedulers are failing to start:
libbpf: failed to find skeleton map ''
libbpf: failed to populate skeleton maps for 'bpf_bpf': -3
So, revert libbpf to the previous version and update the commit for bpftool to use a version that still allows to generate a compatible BPF skel.
Fixes: e59c48a6 ("Update libbpf commit hash")
=> meson: restore previous libbpf version and update bpftool

meson.build
On archlinux its suggested to use plain buildtype in order to not ignore system provided flags, for example for packaging
=> meson: run cargo build in release mode when using plain buildtype

meson-scripts/fetch_bpftool, meson-scripts/fetch_libbpf
When fetching external git repositories (libbpf and bpftool) we don't check if the target commit exists.
This can leads to issues such as #400, because we may silently use HEAD, instead of the specified commit.
Prevent this by returning an error when the target SHA1 cannot be found.
=> meson: check if commit exists in remote git repos

README.md, meson.build, meson.options, scheds/rust/scx_lavd/meson.build, scheds/rust/scx_layered/meson.build, scheds/rust/scx_mitosis/meson.build, scheds/rust/scx_rlfifo/meson.build, scheds/rust/scx_rustland/meson.build, scheds/rust/scx_rusty/meson.build
With commit 5d20f89a ("scheds-rust: build rust schedulers in sequence"), schedulers are now built serially one after the other to prevent meson and cargo from forking NxN parallel tasks.
However, this change has made building a single scheduler much more cumbersome, due to the chain of dependencies.
For example, building scx_rusty using the specific meson target would still result in all schedulers being built, because they all depend on each other.
To address this issue, introduce the new meson build option `serialize=true|false` (default is false).
This option allows to disable the schedulers' build chain, restoring the old behavior.
With this option enabled, it is now possible to build just a single scheduler, parallelizing the cargo build properly, without triggering the build of the …
=> meson: introduce serialize build option

scheds/rust/scx_bpfland/meson.build
Properly honor the meson build `serialize` option.
=> scx_bpfland: properly integrate with meson build

services/scx
Just add scx_bpfland to /etc/default/scx
=> scheds: Add scx_bpfland scheduler to /etc/default/scx

scheds/rust/scx_rusty/src/main.rs
The stats map in scx_rusty is a BPF_MAP_TYPE_PERCPU_ARRAY, with its size determined by num_possible_cpus(). Initializing it with nr_cpu_ids() can result in errors such as:
Error: Failed to zero stat
Caused by:
number of values 6 != number of cpus 8
Fix by using num_possible_cpus() to initialize it.
Fixes: 263e02f6 ("rusty: Use nr_cpu_ids instead of nr_cpus_possible")
=> scx_rusty: fix stats map initialization

scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c, scheds/rust/scx_mitosis/src/main.rs
The synchronization for mitosis is a bit ad-hoc, working around lack of atomics in BPF. This commit updates the logic to use READ/WRITE_ONCE and compiler barriers to get the behaviors we want.
=> mitosis: Update synchronization

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
We are incorrectly using the SMT idle cpumask to find any idle CPU, fix by using the generic idle cpumask.
=> scx_bpfland: use the right cpumask to find any idle CPU

rust/scx_rustland_core/assets/bpf/main.bpf.c
Remove unused variable `tctx` in `rustland_select_cpu`.
=> scx_rustland_core: Remove unused variable

scheds/rust/scx_bpfland/src/bpf/intf.h, scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
A set of changes to make performance more consistent and prevent spikes:
- scx_bpfland: adjust default time slice to 5ms (default tuning for latency)
- scx_bpfland: ensure task time slice never exceeds the slice_ns limit (latency improvement)
- scx_bpfland: prevent starvation of regular tasks (prevent interactive tasks from monopolizing the CPUs)
- scx_bpfland: unify dispatching kthreads with direct CPU dispatches (dispatch kthreads using per-CPU DSQs instead of `SCX_DSQ_LOCAL`)
- scx_bpfland: drop built-in idle CPU selection logic (drop unused option / cleanup)
Thanks to the CachyOS community that provided an extensive amount of test results and feedback about these changes.
=> scx_bpfland: enhance performance consistency and predictability

scheds/c/scx_flatcg.bpf.c
Fetch the value of `delta` directly from the returned value from `__sync_fetch_and_sub`, as it returns the origin value of `cgc->cvtime_delta`.
Additional fetching instruction of `cgc->cvtime_delta` would be redundant here.
=> scx_flatcg: Make good use of __sync_fetch_and_sub()

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
No functional changes, only cosmetics: report additional statistics (split kthread / direct dipatches), report the build id version (using `scx_utils::build_id`) and print statistics in a more human-readable format.
=> scx_bpfland: additional stats and output improvements

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
Small improvements / cleanups in bpfland to slightly improve fairness and responsiveness:
- scx_bpfland: refill task time slice (re-evaluate task time slice based on the unused quota and min time slice, to improve fairness and avoid excessive amount of context switches)
- scx_bpfland: always classify interactive tasks (classify interactive tasks also when they're directly dispatched in select_cpu)
- scx_bpfland: pass enqueue flags when dispatching kthread (just for consistency)
=> bpfland: small improvements

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Set of changes extensively tested by the CachyOS community with positive results:
- all kthreads are now following the same scheduling path of regular tasks by default: this allows to prevent interactivity issues or unfairness in presence of too many softirqs (i.e., high RX network traffic)
- mitigate spam of "fake" interactive tasks: workloads that create large amount of tasks doing sync wake events (e.g.., `hackbench -l N`) can make the system almost unresponsive, because all these tasks ae classified as "interactive"; the mitigation puts a limit (= 4x the online cpus) on the amount of tasks that can be queued to the priority DSQ, preventing the flood of too many interactive tasks, all scheduled before regular tasks.
Moreover, report additional statistics to stdout:
- interactive tasks …
=> scx_bpfland: mitigations and additional statistics

meson.build
the value to env variable RUSTFLAGS is getting appended with ':'(like in the PATH variable to list binary folders to search in) instead of ' ' in the flags env variables
resulting in
```
':-C' relocation-model=pic -C link-args=-lelf -C link-args=-lz -C link-args=-lzstd -L /home/smol/.cache/paru/clone/scx-scheds-git/src/scx/build/libbpf/src --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
```
=> meson: fix RUSTFLAGS being appended incorrectly

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c
This PR contains two improvements of scx+lavd:
1) Change the time slice calculation based on the task's ratio in total weights to the total runnable count.  The weight-based calculation deprioritizes nicer tasks too much, but the runnable count-based scheme does not.
2) Improve the accuracy of waker frequency. In the prior approach, any `current` task making another task runnable was considered a waker. However, that is not always true. So we consider the `current` task is a waker only when two tasks are related (e.g., parent-child, etc.)
With these two changes, the scheduler becomes more resilient under heavy load.
=> scx_lavd: improve time slice and waker freq calculation

meson-scripts/install_rust_user_scheds
Since scx_mitosis got disabled, but still gets read out by the install_user_scheds script, lets skip it to avoid packaging issues.
Can be enabled, as soon scx_mitosis got enabled again.
=> install_user_scheds: Skip packaging of scx_mitosis

.github/workflows/build-scheds.yml, .github/workflows/sched-ext.config, meson-scripts/test_sched
Use kernel from kernel.org (for-next branch), include the .config chunk directly in the scx repository and temporarily exclude scx_flatcg and scx_pair due to the missing cgroup ABIs.
=> ci: Use latest upstream kernel and exclude scx_flatcg and scx_pair from testing

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
Small improvements for the CPU hotplug support, time slice evaluation and in the logic to classify interactive/regular tasks. No major improvement in this PR, mostly small fixes/adjustments to enhance the quality of the code.
=> scx_bpfland: small improvements

rust/scx_utils/src/log_recorder.rs
The log_recorder was incorrectly displaying the tag name instead of the value for nested counters.
After the fix:
```
21:19:35 [INFO] Counters:
21:19:35 [INFO]   dispatched_tasks_total: 2672 [890.5/s]
21:19:35 [INFO]     prev_idle: 1814 (67.9%) [604.6/s]
21:19:35 [INFO]     wsync_prev_idle: 676 (25.3%) [225.3/s]
21:19:35 [INFO]     direct_dispatch: 97 (3.6%) [32.3/s]
21:19:35 [INFO]     dsq: 78 (2.9%) [26.0/s]
21:19:35 [INFO]     wsync: 7 (0.3%) [2.3/s]
21:19:35 [INFO]     pinned: 0 (0.0%) [0.0/s]
21:19:35 [INFO]     greedy_idle: 0 (0.0%) [0.0/s]
21:19:35 [INFO]     greedy_xnuma: 0 (0.0%) [0.0/s]
21:19:35 [INFO]     direct_greedy: 0 (0.0%) [0.0/s]
21:19:35 [INFO]     direct_greedy_far: 0 (0.0%) [0.0/s]
21:19:35 [INFO]     greedy_local: 0 (0.0%) [0.0/s]
21:19:35 [INFO]   dl_clamped_total: …
```
=> scx_utils: Display the tag value for nested counters in log_recorder

rust/scx_utils/src/topology.rs
Add the LLC id to the Cpu struct, which will make it easier for referencing the LLC when doing operations on a Cpu.
=> scx_utils: Add LLC id to CPU

scheds/rust/scx_rusty/src/bpf/intf.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/load_balance.rs, scheds/rust/scx_rusty/src/main.rs
This change makes scx_rusty mempolicy aware. When a process uses [`set_mempolicy`](https://man7.org/linux/man-pages/man2/set_mempolicy.2.html) it can change NUMA memory preferences and cause performance issues when tasks are scheduled on remote NUMA nodes. This change modifies task_pick_domain to use the new helper method that returns the preferred node id.
With the ` --mempolicy-affinity` flag set:
```
$ stress-ng  -M --mbind 1 --malloc 5 -t 10 --bigheap 10 --numa 5
stress-ng: info:  [873775] setting to a 10 secs run per stressor
stress-ng: info:  [873775] dispatching hogs: 5 malloc, 10 bigheap, 5 numa
stress-ng: info:  [873796] numa: system has 2 of a maximum 8 memory NUMA nodes
stress-ng: metrc: [873775] stressor       bogo ops real time  usr time  sys time   bogo ops/s     bogo ops/s …
```
=> scx_rusty: Add mempolicy checks to rusty

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Instead of using a static value to classify tasks based on their average amount of voluntary context switches, try to periodically evaluate an optimal threshold, based on a global average of voluntary context switches among of all the running tasks.
Tasks with an average amount of voluntary context switches greater than the global average will be classified as interactive.
The global average is evaluated as an exponentially weighted moving average (EWMA), as:
avg(t) = avg(t - 1) * 0.75 - task_avg(t) * 0.25
This approach is more efficient than iterating through all tasks and it helps to prevent rapid fluctuations that may be caused by bursts of voluntary context switch events.
The dynamic nvcsw threshold enables a more precise adjustment of the classification criteria to swiftly respond to …
=> scx_bpfland: introduce dynamic nvcsw threshold

scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/load_balance.rs
Followed [commit 1c3b563](https://github.com/sched-ext/scx/commit/1c3b563cafd760cddef7d96689e10c94f5171f70), move the checking of task.migrated.get() into the vector filter. In this way, we can remove the skip_while() call in find_first_candidate().
=> scx_rusty: Remove skip_while in find_first_candidate

scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/metrics.rs
Refactor the main module for scx_layered to move metrics into a separate module. This change does no functional differences, only code structure. This will make it a little easier to navigate the logic in the main scheduler code.
=> scx_layered: Add separate module for metrics

scheds/rust/scx_layered/src/bpf/main.bpf.c
Non-kthreads with custom affinities in non-open layers are dispatched into a LO_FALLBACK_DSQ, with the idea being that they're penalized for their custom affinities. When a host is fully utilized, these tasks can end up being starved due to LO_FALLBACK_DSQ being consumed only when there are no other layers to consume from. In internal workloads at Meta, we've observed that this can happen in practice.
Longer term, we can probably address this by implementing layer weights and applying that to fallback DSQs to avoid starvation. For now, let's just dispatch them to the same fallback DSQ to avoid this starvation issue.
=> layered: Don't dispatch to LO_FALLBACK_DSQ

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Scale the variable task time slice inversely proportional to the amount of tasks waiting on the shared and priority DSQs:
- if the system is not fully saturated tasks will be directly dispatched to the available CPUs and they can use the max time slice;
- as soon as the system becomes over-commissioned tasks will be queued either to the priority DSQ (interactive) or the shared DSQ (regular) and the time slice will be adjusted inversely proportional to the total amount of waiting tasks (evaluated a simple moving average).
This change has been tested with positive result by the CachyOS community running micro-benchmarks as well as practical user workloads (gaming with background activity, testing system responsiveness, audio, etc.).
Moreover, the metrics reported by the scheduler have been …
=> scx_bpfland: adjust task time slice as a function of waiting tasks

rust/scx_utils/src/topology.rs, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Add support for NUMA node and LLC layer configuration for `scx_layered`. If the `nodes` or `llcs` fields are unset then all CPUs are used. If both fields have values the cpuset is or'ed. This is useful for running `scx_layered` on NUMA machines where setting a soft affinity to a NUMA node or LLC may be beneficial.
Testing for NUMA nodes using this config:
```
[{
"name":"numa_1",
"comment":"numa1",
"matches":[
[
{"CommPrefix":"stress-ng"}
],[
{"PcommPrefix":"stress-ng"}
]],
"kind": {
"Confined":{
"util_range": [0.04, 0.50],
"min_exec_us":50,
"nodes":[1]
}
}
},{
"name":"numa_XXXX",
"comment":"numa 1, noop layer",
"matches":[
[{"CommPrefix":"not-a-comm"}]
],
"kind": {
"Confined":{
"util_range": [0.01, 0.20],
"min_exec_us": 0,
"nodes":[1]
}
}
},
{
"name":"numa_0",
"comment":"the rest", …
```
=> scx_layered: Add topology awareness for NUMA nodes and LLCs

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Add a layer match based on either the effective user id or the effective group id. This allows for creating layers for individual users or groups.
Test:
```
$ id
uid=224791(hodgesd) gid=100(users) groups=100(users)
```
config:
```
$ cat user.json 
[{
"name":"hodgesd",
"comment":"hodgesd user",
"matches":[
[{"UIDEquals":224791}]
],
"kind": {
"Open":{
"min_exec_us":0,
"preempt": true,
"exclusive": true
}
}
},
{
"name":"normal",
"comment":"the rest",
"matches":[[]],
"kind":{
"Open": {
"min_exec_us":0,
"preempt":false,
"exclusive":false
}
}
}]
```
`scx_layered` has layers for my user:
```
18:56:35 [INFO] excl_coll= 0.00 excl_preempt= 0.00 excl_idle= 0.00 excl_wakeup= 0.02
18:56:35 [INFO]   hodgesd: util/frac=    9.8/  5.5 load/frac=      9.6:  3.2 tasks=   355
18:56:35 [INFO]            tot= …
```
=> scx_layered: Add user and group layers

scheds/rust/scx_rusty/src/bpf/intf.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c
Currently, a task's deadline is computed as its vtime + a scaled function of its average runtime (with its deadline being scaled down if it's more interactive). This makes sense intuitively, as we do want an interactive task to have an earlier deadline, but it also has some flaws.
For one thing, we're currently ignoring duty cycle when determining a task's deadline. This has a few implications. Firstly, because we reward tasks with higher waker and blocked frequencies due to considering them to be part of a work chain, we implicitly penalize tasks that rarely ever use the CPU because those frequencies are low. While those tasks are likely not part of a work chain, they also should get an interactivity boost just by pure virtue of not using the CPU very often. This should in theory be …
=> rusty: Rework deadline as a signed sum

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Using negative values with --slice-us-lag can be useful to make performance more consistent and prioritize newly created tasks over the running tasks.
Therefore, allow to specify negative values from the command line and also update the documentation of this option.
=> scx_bpfland: allow to specify negative values with --slice-us-lag

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
This is the initial support for AMP architecture, such as Intel Alder Lake (P/E). Initially, we tackle the problem from the core compaction point of view.
- Now, the core compaction is AMP-aware, so the more performant core will be chosen first.
- The time slice calculation is also AMP-aware, so the time slice on a CPU will be proportional to the CPU's capacity. Since a task on a more performant core will have a longer slice, but a task on a less performant core will get a shorter slice. This way, the performant core is more likely to be clock-boosted, and a task on a less performant core will have a higher chance of being scheduled on the more performant core.
- Besides these two, there are some clean-ups and tuning related to the core compaction feature.
With these changes, the kernel …
=> lavd_lavd: initial support for AMP (asynmmetric multi-processor) architecture

scheds/rust/scx_lavd/src/main.rs
The max frequency information from topology (from sysfs) seems not always true. In some installations, it returns zero for all CPUs. In this case, let's just consider all CPUs have the same capacity (1024), hoping the kernel can give more preceise information.
=> scx_lavd: fix div by zero error in some installations

scheds/rust/scx_lavd/src/bpf/main.bpf.c
The max_entries parameter in BPF_MAP_TYPE_PERCPU_ARRAY defines the number of values per CPU and for cpu_ctx_stor we only need one item: the CPU context.
Set max_entries to 1 to avoid allocating unnecessary memory and slightly reduce the memory footprint.
=> scx_lavd: set correct size for cpu_ctx_stor

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c
Add a per cpu iterator offset to round robin when iterating on layers. This is to make selection from different layers more fair so that the first layer is not always selected first.
=> scx_layered: Add per cpu layer iterator offset

scheds/rust/scx_layered/src/bpf/main.bpf.c
When the previous CPU for a task is not known do not fall back to enqueueing to CPU 0, use the current CPU.
=> scx_layered: Fix enqueue fallback CPU selection

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
Immediately re-align p->scx.dsq_vtime to the global vruntime (+/- slice lag) as soon as we are evaluating the task's vruntime.
This allows rapidly chase the minimum global vruntime, ensuring to not over prioritize tasks tasks with a predominantly sleeping behavior pattern.
=> scx_bpfland: always re-align task's vruntime to the global vruntime

scripts/dsq_lat.bt
This change adds a bpftrace script to monitor runq latency as well as dsq latency.
```
scheduler: layered
@avg_lat: 396
@usec_hist: 
[0]                16807 |@@@@@@@@                                            |
[1]                69339 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                   |
[2, 4)            106525 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
[4, 8)             82849 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@            |
[8, 16)            76488 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@               |
[16, 32)           63287 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                      |
[32, 64)           49775 |@@@@@@@@@@@@@@@@@@@@@@@@                            |
[64, 128)          14701 |@@@@@@@                                             |
[128, 256)          2163 …
```
=> scripts: Add dsq latency script

rust/scx_rustland_core/assets/bpf.rs
Explicitly import timespec to fix the following potential build error:
error[E0422]: cannot find struct, variant or union type `timespec` in this scope
--> src/bpf.rs:365:35
|
365 | sched_ss_repl_period: timespec {
|                       ^^^^^^^^ not found in this scope
|
help: consider importing this struct
|
6 + use libc::timespec;
|
This fixes issue #469.
=> scx_rustland_core: fix missing import (timespec)

rust/scx_rustland_core/src/alloc.rs
Mutex is preferred for some parallel tasks and libs with parallelization
See / Partially fixes #469
=> scx_rustland_core alloc: Replaced RefCell with Mutex 

scheds/rust/scx_layered/src/bpf/main.bpf.c
The use of the cred struct should be const. Fixes some compile time warnings.
=> scx_layered: Fix cred declaration

rust/scx_utils/src/bpf_builder.rs
Fix args to bpf_builder, existing warnings display for "-Wno-compare-distinct-pointer-types'".
Example warning from failed build (for separate reason):
```
~/scx/scheds/rust/scx_layered (layered-glob)]$ cargo build 
Compiling scx_layered v1.0.1 (/home/hodgesd/scx/scheds/rust/scx_layered)
error: failed to run custom build command for `scx_layered v1.0.1 (/home/hodgesd/scx/scheds/rust/scx_layered)`
Caused by:
process didn't exit successfully: `/home/hodgesd/scx/scheds/rust/scx_layered/target/debug/build/scx_layered-a0d2b0a273b2f960/build-script-build` (exit status: 101)
--- stdout
scx_utils:clang=("clang", "18.1.8", "x86_64") ["-g", "-O2", "-Wall", "-Wno-compare-distinct-pointer-types'", "-D__TARGET_ARCH_x86", "-mcpu=v3", "-mlittle-endian", "-idirafter", …
```
=> scx_utils: Fix build args

rust/scx_rustland_core/Cargo.toml, rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/intf.h, rust/scx_rustland_core/assets/bpf/main.bpf.c, rust/scx_rustland_core/src/alloc.rs, rust/scx_rustland_core/src/rustland_builder.rs, scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/Cargo.toml, scheds/rust/scx_rustland/src/main.rs
First set of changes to re-align `scx_rustland` with the recent changes done in `scx_bpfland`, mostly re-using the same idle selection logic and the CPU hotplugging support.
The other major change involves removing the interactive task classification from the BPF component (in `scx_rustland_core`) and re-implementing it fully in user space in `scx_rustland`. This allows to eliminate the overhead of sending the `nvcsw` counter for each task to the user-space part, so all the potential schedulers based on `scx_rustland_core` that don't require this logic can benefit from this.
These changes are potentially introducing performance regressions in `scx_rustland`, but they can be fixed/improved later, these changes are also in preparation to define a better and more generic user-space API, so …
=> scx_rustland refactoring

version-tool.py
When updating in-tree crate versions, do_rust_ver() was returning the new version string which is then put into rust_deps triggering version mismatch warning in do_rust_deps().
There's no reason for do_meson_ver() and do_rust_ver() to return the new version. Always return the old version.
=> version-tool: Suppress spurious dependency version mismatch warning

meson-scripts/veristat, meson.build, meson.options
Add a meson script to run veristat. This can later be used to generate reports for BPF program complexity at PR time.
```
$ meson setup build -Dscheduler=scx_lavd --reconfigure
$ meson compile -C build veristat 
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/hodgesd/scx/build veristat
ninja: Entering directory `/home/hodgesd/scx/build'
[0/1] Running external command veristat (wrapped by meson to set env)
Running veristat on /home/hodgesd/scx/build/scheds/rust/scx_lavd/debug/build/scx_lavd-75563794c6a33502/out/bpf.bpf.o
Processing 'bpf.bpf.o'...
File       Program           Verdict  Duration (us)  Insns  States  Peak states
---------  ----------------  -------  -------------  -----  ------  -----------
bpf.bpf.o  lavd_cpu_offline …
```
=> meson: Add veristat script

scheds/rust/scx_rusty/src/load_balance.rs
The logic of tasks filtering were moved from `find_first_candidate()` into a vector filter operation in commit 1c3b563. However, it was forgotten to transfer the logic with "NOT" since now `.filter()` will populate the tasks we want, rather than `.skip_while()` which was throwing unwanted tasks out.
That's why the logic here should be reverse so we won't take kworker or migrated tasks into considerations.
=> scx_rusty: Fix logical error when filtering tasks

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
This PR makes LAVD core-type aware, supporting AMP (asymmetric multi-processor), multi-CCX, and multi-NUMA architecture. The PR consists of several parts:
- We define a "compute domain" (cpdom for short) as a collection of CPUs having the same core type (P or E) under the same LLC domain.
- The rust code builds the map of compute domain (cpdom_map) from `Topology` and decides 1) how many DSQs are necessary, 2) which CPU should use what DSQ, and 3) when the designated DSQ are empty, which DSQs are needed to be checked for task stealing.
- The BPF code -- ops.dispatch(), ops.select_cpu(), and ops.enqueue() -- pereforms based on the built cpdom_map.
- Besides the above major changes, the PR includes incremental improvement of virtual deadline calculation, tuning for core compaction, and code …
=> lavd: make LAVD core-type (AMP) aware

scheds/rust/scx_lavd/Cargo.toml
For some reason, the `nix` package version 0.28.0 starts producing compilation errors.
After upgrading it to the latest version (0.29.0), everything works fine.
=> scx_lavd: upgrade nix package from 0.28.0 to 0.29.0

scheds/rust/scx_bpfland/Cargo.toml, scheds/rust/scx_bpfland/build.rs, scheds/rust/scx_bpfland/src/bpf/intf.h, scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/bpf_intf.rs, scheds/rust/scx_bpfland/src/bpf_skel.rs, scheds/rust/scx_bpfland/src/main.rs
This adds the concept of "primary scheduling domain" to bpfland, that can be used to prioritize scheduling on a subset of cores. This is mostly focused at supporting hybrid architectures (systems with P-cores / E-cores).
The user can define the primary scheduling domain via the new option `--primary-domain CPUMASK`; if a primary domain is define the scheduler will try to dispatch tasks on the cores specified by `CPUMASK`, unless they become saturated, at which points tasks will be allowed to overflow on the other available cores.
This allows to define multiple performance profiles in hybrid systems, i.e., use a primary domain of e-cores only for better power consumption or a primary domain of p-cores only for better performance.
Some test results on an Dell Precision 5480 with 13th Gen …
=> scx_bpfland: primary domain

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_rustland/src/main.rs
There're several unused variables and functions scattered in scx schedulers now, causing compiling errors or warnings.
The PR is mainly for removal of those unused variables listed below
* scx_rustland: The member `topo_map` in Scheduler is never used and thus should be removed, the related imports are removed as well.
* scx_bpfland: The variable `vtime` in function `task_vtime` is never used.
=> scx: Remove unused variables, imports and functions

scheds/rust/scx_lavd/Cargo.toml
Add "signal" feature to nix dependency; otherwise, build fails.
=> scx_lavd: Build fix

scheds/rust/scx_layered/src/main.rs
After updating scx_layered to be topology aware the nr_cpus field on the layer was not being updated properly. Update layer growing/shrinking logic to correctly update the nr_cpus count.
```
tot=  17690 local=82.01 open_idle=26.95 affn_viol= 0.00 proc=23ms
busy= 25.5 util= 1961.1 load=   5400.1 fallback_cpu=  2
excl_coll=0 excl_preempt=0 excl_idle=0 excl_wakeup=0
hodgesd  : util/frac= 1918.0/ 97.8 load/frac=   4184.2: 77.5 tasks=  1344
tot=   5268 local=46.34 wake/exp/last/reenq=18.24/ 0.82/34.21/ 0.40
keep/max/busy=33.20/ 1.58/ 0.25 kick= 1.04 yield/ign= 0.00/    0 
open_idle= 0.00 mig=19.72 affn_viol= 0.00
preempt/first/idle/fail= 0.00/ 0.00/ 0.00/ 0.00 min_exec= 0.00/   0.00ms
cpus= 28 [ 26, 30] fff00000 f0000003 000003ff
normal   : util/frac=   43.1/  2.2 load/frac=   1215.9: 22.5 …
```
=> scx_layered: Update nr_cpus when resizing layers

rust/scx_stats/README.md, rust/scx_stats/examples/client.rs, rust/scx_stats/examples/server.rs, rust/scx_stats/src/client.rs, rust/scx_stats/src/lib.rs, rust/scx_stats/src/server.rs, rust/scx_stats/src/stats.rs, scheds/rust/scx_layered/src/stats.rs
- Multiple attributes in a single stat block fixed.
- `om_prefix` added and will be used by openmetrics bridge tool.
- s/stat/stats stragglers renamed.
=> scx_stats, scx_layered: Add `om_prefix` attribute and fix s/stat/stats/ stragglers

rust/scx_stats/README.md, rust/scx_stats/examples/client.rs, rust/scx_stats/examples/server.rs, rust/scx_stats/examples/stats_defs.rs.h, rust/scx_stats/scripts/scxstats_to_openmetrics.py, rust/scx_stats/scx_stats_derive/src/lib.rs, rust/scx_stats/src/server.rs, rust/scx_stats/src/stats.rs, scheds/rust/scx_layered/src/stats.rs
- Implement scxstats_to_openmetrics.py which is a generic translator from scx_stats to openmetrics.
- This uncovered many areas that scx_stats could be improved. Fixed and improved accordingly.
=> scx_stats: Refine scx_stats and implement scxstats_to_openmetrics.py

scheds/rust/scx_rusty/src/bpf/main.bpf.c
=> scx_rusty: Fix typo

INSTALL.md
The guide that is currently available for Fedora sched-ext is outdated. To remedy this, I have opted to update the guide to use CachyOS's kernel that is also available on Fedora. The scx schedulers that are available on Fedora's repositories are also outdated and doesn't work with the current patchset. I have also updated the scheduler installation to use our package in the CachyOS Addons COPR.
The current spec files for the kernel and scx-scheds package can be found below:
- [kernel-cachyos.spec](https://github.com/CachyOS/copr-linux-cachyos/blob/master/sources/kernel-cachyos-bore/kernel-cachyos.spec)
- [scx-scheds](https://github.com/CachyOS/copr-linux-cachyos/blob/master/sources/scx-scheds/scx-scheds.spec)
- [scx-scheds-git](https://github.com/CachyOS/copr-linux-cachyos/blob/master/sour …
=> INSTALL: Update Fedora installation docs

.github/workflows/merge.yml, .github/workflows/pr_veristat.yml, meson-scripts/veristat, meson-scripts/veristat_diff, meson.build, meson.options
Add a github action to run [`veristat`](https://github.com/libbpf/veristat) during PRs and merges. This uses an [action cache](https://github.com/actions/cache) to store the veristat values when a PR is merged. An additional action is added during a PR to use the comparison mode of veristat with the diff value from the cache.
=> meson: Add github action to run veristat

.github/workflows/merge.yml, .github/workflows/pr_veristat.yml, meson-scripts/veristat
See the [failure](https://github.com/sched-ext/scx/actions/runs/10389671253) which needs to have an action defined.
=> ci: Fix veristat pull request workflow

scheds/rust/scx_layered/src/bpf/main.bpf.c
Fix the uninitialized variable "layer" in the function match_layer which caused the compiling process to fail. "layer" is supposed to be the same as "&layers[layer_id]".
=> scx_layered: Fix uninitialized variable

rust/scx_stats/Cargo.toml, rust/scx_stats/README.md, rust/scx_stats/examples/client.rs, rust/scx_stats/examples/server.rs, rust/scx_stats/src/lib.rs, rust/scx_stats/src/server.rs, scheds/rust/scx_layered/Cargo.lock, scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
Currently, scx_layered generates stats at a fixed interval and every stats client reads out the content of the latest update. This means that a client whose poll interval is longer than the scheduler's would see sampled stats (e.g. the average and nr_cpus ranges wouldn't represent the whole period) and a client with shorter poll interval may see the same outputs repeated.
This PR implements `ScxStatsServer::add_stats_ops()` which enables the user to specify `open()` and `close()` closures. The `open()` closure creates a `read()` closure per client session which can carry mutable states. In addition, it provides multiplexed communication channels between the clients and the server user which can be useful when implementing stateful stats generation.
`scx_layered` is updated to make use of …
=> scx_stats, scx_layered: Implement independent stats client sessions

scheds/rust/scx_layered/src/bpf/main.bpf.c
4fccc06905c3 ("scx_layered: Fix uninitialized variable") causes the following verification failure. Fix it by moving deref after range checking.
```
Validating match_layer() func#1...
283: R1=scalar() R2=scalar() R3=mem_or_null(id=49,sz=1) R10=fp0
; int match_layer(u32 layer_id, pid_t pid, const char *cgrp_path) @ main.bpf.c:1029
283: (7b) *(u64 *)(r10 -24) = r3      ; R3=mem_or_null(id=49,sz=1) R10=fp0 fp-24_w=mem_or_null(id=49,sz=1)
284: (bc) w7 = w1                     ; R1=scalar() R7_w=scalar(smin=0,smax=umax=0xffffffff,var_off=(0x0; 0xffffffff))
; struct layer *layer = &layers[layer_id]; @ main.bpf.c:1033
285: (bc) w1 = w7                     ; R1_w=scalar(id=50,smin=0,smax=umax=0xffffffff,var_off=(0x0; 0xffffffff)) R7_w=scalar(id=50,smin=0,smax=umax=0xffffffff,var_off=(0x0; …
```
=> scx_layered: Fix verification failure

scheds/rust/scx_layered/src/main.rs
Currently the core selection logic in scx_layered uses the first available core in the bitmask. This is suboptimal when the scheduler is configured with specific NUMA/LLC restrictions and with multiple layers. This refactors the core selection to use a preferred order of cores based on the layer index.
=> scx_layered: Use topology for core selection

scheds/rust/scx_lavd/src/main.rs
The changes include 1) chopping down a big function into smaller ones for readability and maintainability and 2) using the interior mutability pattern (Cell and RefCell) to avoid unnecessary clone() calls.  There are no functional changes.
=> scx_lavd: revise FlatTopology prettier

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
Before this fix, the scheduler enqueues a task to one of enqueuing CPU's DSQ. That could cause a watchdog timeout error. For example, suppose that a task pinned to NUMA domain 1 is enqueued to a DSQ on NUMA domain 0. The task on the DSQ in a wrong NUMA domain will never be exeuted until a CPU on the correct NUMA domain (NUMA domain 1 in this example) steals the task by any chance.
The fix always enqueues a task to a correct DSQ by referring task's thread information (`task->threadinfo.cpu`).
Besides the major change, it also includes minor code cleanup around ops.enqueue().
=> scx_lavd: fix a potential watchdog timeout error at multi-NUMA/CCX platforms

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
This PR introduces power profile options (--performance, --balanced, --powersave) so a user can choose a proper one according to her usage scenarios. To this end, another option, "--perfer-little-core", was added.
Essentially, the power profile options define a set of low-level options affecting the scheduler's core selection and frequency scaling algorithm.
* Performance mode (--performance)
- Disable core compaction
- Choose physical CPUs over logical CPUs
- Choose big (performance) cores whenever possible
* Balanced mode (--balanced) <= default
- Enable core compaction
- Choose physical CPUs over logical CPUs
- Choose big (performance) cores whenever possible
* Power-save mode (--powersave)
- Enable core compaction
- Choose logical CPUs over physical CPUs
- Choose little (effiency) …
=> scx_lavd: add power profile options: --performance, --balanced, --powersave

rust/scx_utils/src/topology.rs, scheds/rust/scx_bpfland/src/bpf/intf.h, scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Introduce some concepts of topology awareness to scx_bpfland:
- L2 / L3 cache awareness
- cpu frequency awreness (via primary scheduling domain)
These changes enable better utilization of hybrid architectures (P-cores / E-cores) and generally improve performance by keeping tasks running on the same cores and caches, thereby enhancing the reuse of their working set.
=> scx_bpfland: topology awareness

rust/scx_utils/src/cpumask.rs, scheds/rust/scx_bpfland/src/main.rs
Rely on `scx_utils::Cpumask` instead of re-implementing a custom `CpuMask` struct.
This is just some code refactoring, no functional change.
=> scx_bpfland: use scx_utils::Cpumask

rust/scx_utils/build.rs, rust/scx_utils/src/bpf_builder.rs, rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/infeasible.rs, rust/scx_utils/src/lib.rs, rust/scx_utils/src/libbpf_logger.rs, rust/scx_utils/src/topology.rs, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_rusty/Cargo.lock, scheds/rust/scx_rusty/src/domain.rs, scheds/rust/scx_rusty/src/load_balance.rs, scheds/rust/scx_rusty/src/main.rs, scheds/rust/scx_rusty/src/tuner.rs
- Formatting.
- Use nr_cpu_ids where necessary.
- Always use lazy constants `NR_CPU_IDS` and `NR_CPUS_POSSIBLE` 
- Make cpumask default to printing in hex.
=> scx_utils::cpumask,topology: Misc updates

scheds/rust/scx_layered/src/main.rs
Fix a bug introduced in #510 where it assumed core ids are incremental. This refactors the core ordering for layers to be far more simple and provide some space for layer core isolation in low utilization.
Tested by adding some logs on the core selection values:
```
$ sudo ./bin_local/bin/scx_layered --monitor 5 f:user.json -vvv 2>&1 | grep xxx
02:25:45 [TRACE] xxx layer random cores 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 
02:25:45 [TRACE] xxx layer hodgesd cores 36, 37, 38, 39, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 
02:25:45 [TRACE] xxx layer stress-ng cores 8, 9, 10, 11, 12, 13, 14, …
```
=> scx_layered: Fix core selection

rust/scx_utils/src/topology.rs, scheds/rust/scx_bpfland/src/main.rs
With Intel Turbo Boost enabled, some CPUs might show a higher maximum frequency than others, even if they are not actually faster cores.
Instead of relying on the maximum frequency to classify fast and slow cores, use the base frequency, that ensures a more accurate distinction between Intel Turbo Boost CPUs and genuinely faster CPUs.
With this change, bpfland can correctly use all CPUs as the primary scheduling domain in non-hybrid architectures when using `--primary-domain performance`, instead of only selecting the subset of turbo boost-ed CPUs.
=> scx_bpfland: properly classify Intel Turbo Boost CPUs

rust/scx_utils/src/lib.rs, rust/scx_utils/src/topology.rs
LazyLock is stable but has become so only very recently and can trigger build errors on not-too-old stable rustc's which are still in wide use. Let's use lazy_static instead for now.
=> scx_utils::topology: Use lazy_static instead of LazyLock

scheds/rust/scx_bpfland/src/main.rs
With the global scx_utils::NR_CPU_IDS we don't need Topology anymore in init_primary_domain(), so drop the variable to fix the following build warning:
warning: unused variable: `topo`
--> src/main.rs:385:9
|
385 |         topo: &Topology,
|         ^^^^ help: if this is intentional, prefix it with an underscore: `_topo`
|
= note: `#[warn(unused_variables)]` on by default
Fixes: 1da249f ("scx_utils::topology: Always use NR_CPU_IDS and NR_CPUS_POSSIBLE")
=> scx_bpfland: drop unused variable

services/scx
After discussion with @arighi and @htejun  we came to the conclusion that the default scheduler should be one that is actively developed. For various reasons, rusty has ceased to be actively developed, while currently the most developed scheduler that guarantees both extremely good performance seems to be bpfland. 
In addition, @arighi suggested that after enabling more PRs, it would be good to set the following flags as suggested
```
--lowlatency --primary-domain auto
```
=> scx-scheds: set scx_bpfland as default scheduler

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Introduce the new `--lowlatency` option, which enables switching between the default pure vruntime-based scheduling (more optimized for server workloads) and a deadline-based scheduling (better suited for low-latency workloads).
When the low-latency mode is activated, a task's deadline is calculated as its vruntime, adjusted by a bonus proportional to the task's average number of voluntary context switches (the more voluntary context switches, the shorter the deadline).
This feature enhances the prioritization of interactive tasks even more, proportionally to their average voluntary context switches, also within the two main global queues (priority / shared) and it helps to maintain interactive workloads always responsive, even in presence of heavy non-interactive background work. …
=> scx_bpfland: introduce --lowlatency option

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Add matches for pid/ppid.
tested with config:
```
[{
"name":"pid 1",
"comment":"pid 1",
"matches":[
[
{"PIDEquals":1}
]
],
"kind": {
"Confined":{
"util_range": [0.04, 0.50]
}
}
},{
"name":"ppid 1",
"comment":"ppid 1",
"matches":[
[{"PPIDEquals":1}]
],
"kind": {
"Confined":{
"util_range": [0.01, 0.20]
}
}
},
{
"name":"the rest",
"comment":"the rest",
"matches":[[]],
"kind":{
"Grouped": {
"util_range": [0.05, 0.60]
}
}
}]
```
`scx_layered` output:
```
tot=  54903 local=84.96 open_idle= 3.78 affn_viol= 0.00 proc=122ms
busy=  0.8 util=  131.6 load=    363.4 fallback_cpu= 12
excl_coll=0 excl_preempt=0 excl_idle=0 excl_wakeup=0
pid 1   : util/frac=    0.1/  0.0 load/frac=      0.0:  0.0 tasks=     1
tot=      4 local=100.0 wake/exp/last/reenq= 0.00/ 0.00/ 0.00/ 0.00
keep/max/busy= 0.00/ 0.00/ …
```
=> scx_layered: Add pid/ppid matches

README.md, rust/scx_utils/src/cpumask.rs, scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
A set of changes to make bpfland aware of the different CPU frequencies in the system (including P-cores, E-cores, Turbo Boost), as well as the energy profiles, and to adjust the primary scheduling domain based on this information.
The benefits of this change are explained in this video demo:
https://youtu.be/R-FEZOveG-I
=> scx_bpfland: cpu frequency and energy awareness

services/scx
In PR #537, it was mentioned that the suggested flags can be updated when more PRs are enabled. #536 and #540 have been enabled, so let's take advantage of the benefits that @arighi has prepared for us
=> scx-scheds: Update scx_bpfland suggested flags

scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_lavd/src/main.rs
I wanted to do some work improving the end-user documentation, as I noticed some random typos and other things that were worded a little unclearly or just not explained at all.
I made some minor grammatical changes to scx_bpfland, and I added explanations to scx_lavd that were poorly explained or missing entirely; for example, that the power mode options control the defaults for the four scheduling controls wasn't explained anywhere, and I only learned that by paging through the Rust code, or using the correct terminology "SMT sibling" rather than "logical core."
In a perfect world, the documentation for every scheduler should be formatted exactly the same, and the information useful to end users shouldn't just be embedded in the source code. While an experienced sysadmin might not mind, …
=> scx_bpfland, scx_lavd: Improve help info a bit

scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_rusty/README.md, scheds/rust/scx_rusty/src/main.rs
Apparently you cannot just add a second header in the middle of the help info. It won't format properly. I probably should have checked that before making a PR. I also did a bit of work on scx_rusty.
=> scx_lavd: Fix my own formatting error in #543 scx_rusty: help info and README cleanup

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Add layer match for tgid.
Tested with a simple config:
```
[{
"name":"tgid",
"comment":"tgid",
"matches":[
[
{"TGIDEquals":10733}
]
],
"kind": {
"Confined":{
"util_range": [0.04, 0.50]
}
}
},{
"name":"ppid 1",
"comment":"ppid 1",
"matches":[
[{"PPIDEquals":1}]
],
"kind": {
"Confined":{
"util_range": [0.01, 0.20]
}
}
},
{
"name":"the rest",
"comment":"the rest",
"matches":[[]],
"kind":{
"Grouped": {
"util_range": [0.05, 0.60]
}
}
}]
```
layer matching:
```
tot=  17231 local=96.52 open_idle=57.98 affn_viol= 0.00 proc=20ms
busy=  4.1 util=   61.9 load=    316.8 fallback_cpu=  6
excl_coll=0 excl_preempt=0 excl_idle=0 excl_wakeup=0
ppid 1  : util/frac=    4.1/  6.6 load/frac=      6.5:  2.1 tasks=    13
tot=   1638 local=97.50 wake/exp/reenq= 2.50/ 0.00/ 0.00
keep/max/busy= 0.00/ 0.00/ 0.00 …
```
=> scx_layered: Add layer match for tgid

meson-scripts/get_clang_ver
Currently, when using a llvm rc version, the get_clang_ver output is empty, there fore we get following:
```
meson.build:64:2: ERROR: Problem encountered: Unable to find clang version
```
Fix this issue, with adding the "rc" to the regex.
Tested with LLVM 18.1.8 and 19.1.0-rc3
=> get_clang_ver: Fix regex for LLVM RC Versions

rust/scx_stats/examples/server.rs, rust/scx_stats/src/lib.rs, rust/scx_stats/src/server.rs, rust/scx_stats/src/stats.rs, scheds/rust/scx_bpfland/Cargo.lock, scheds/rust/scx_lavd/Cargo.lock, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs, scheds/rust/scx_rlfifo/Cargo.lock, scheds/rust/scx_rustland/Cargo.lock, scheds/rust/scx_rusty/src/main.rs, scheds/rust/scx_rusty/src/stats.rs
Teach scx_stats to generate summary of stats metadata and use that to implement `--help-stats` for scx_rusty and scx_layered. The output looks like the following:
```
$ scheds/rust/scx_layered/target/debug/scx_layered --help-stats
[SysStats  ]
affn_viol          float               % violated config due to CPU affinity
at                 float               timestamp
busy               float               CPU busy % (100% means all CPU)
excl_collision     float               # times an excl task skipped a CPU as the sibling was also excl
excl_idle          float               # times a CPU skipped dispatching due to an excl task on the sibling
excl_preempt       float               # times a sibling CPU was preempted for an excl task
excl_wakeup        float               # times an idle …
```
=> scx_stats, scx_rusty, scx_layered: Implement `--help-stats`

scheds/rust/scx_lavd/src/main.rs
LAVD got topology aware, therefore drop this message to avoid confusion at the user.
=> scx_lavd: Drop message about unsupported multi-CXX support

scheds/rust/scx_lavd/Cargo.lock, scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
This allows introspection to be done on-demand while the scheduler is running so that we can reduce log noise while maintaining debuggability. It should be straightforward to add other introspection criteria and different types of stats too.
=> scx_lavd: Switch introspection to use scx_stats

rust/scx_stats/src/server.rs, scheds/rust/scx_lavd/src/main.rs
scx_lavd unnecessarily prints out sched same field explanation and a warning message about missing "top" stats. Neither is useful. Remove both.
=> scx_lavd, scx_stats: Remove unnecessary messages

rust/scx_stats/examples/client.rs, rust/scx_stats/examples/server.rs, rust/scx_stats/scx_stats_derive/src/lib.rs, rust/scx_stats/src/client.rs, rust/scx_stats/src/lib.rs, rust/scx_stats/src/server.rs, rust/scx_stats/src/stats.rs, rust/scx_utils/src/misc.rs, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs, scheds/rust/scx_rusty/src/main.rs, scheds/rust/scx_rusty/src/stats.rs
Let's make it a bit easier to use:
- Shorten exported names by changing the prefix from ScxStats to Stats. This should be distinctive enough and more inline with how most libraries name their exports.
- Importing the right set of traits can be tricky. Introduce prelude module so that importing is a bit less painful.
=> scx_stats: Shorten exported names and add prelude module

scheds/rust/scx_bpfland/Cargo.lock, scheds/rust/scx_bpfland/Cargo.toml, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_bpfland/src/stats.rs
Make scx_bpfland use scx_stats and make the reported values interval deltas.
=> scx_bpfland: Use scx_stats

rust/scx_stats/src/server.rs
Add deliminators to make the output easier on the eyes.
Before:
```
$ scx_bpfland --help-stats
[Metrics]                                                                                                  
nr_cpus              u64 Number of online CPUs                                                         
nr_direct_dispatches u64 Number of task direct dispatches                      
nr_interactive       u64 Number of running interactive tasks       
nr_prio_dispatches   u64 Number of interactive task dispatches                                         
nr_running           u64 Number of running tasks                                                       
nr_shared_dispatches u64 Number of regular task dispatches                                             
nr_waiting           u64 Average …
```
=> scx_stats: Make StatsServerData::describe_meta() output more readable

rust/scx_rustland_core/README.md, rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/intf.h, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/scx_rlfifo/Cargo.lock, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/Cargo.lock, scheds/rust/scx_rustland/src/main.rs
Second round of big refactoring in `scx_rustland_core`.
This set of changes is aimed to redesign the user-space framework in a better way, giving more importance to the design of the framework itself rather than the schedulers' performance (however, in case of scx_rustland it also seems to improve performance from the previous version).
Summary of the changes:
- Idle CPU selection can be done fully in user-space (the user-space scheduler can pick an idle CPU via `self.bpf.select_cpu(pid, prev_cpu, flags)` mimicking the BPF's `select_cpu()` interface)
- All tasks are always sent to user-space, there's no BPF shortcut anymore (surprisingly this doesn't seem to introduce any noticeable latency)
- Dropped some ugly APIs (notifying exiting tasks, low_power, full_user): low_power will be …
=> scx_rustland_core: user-space framework refactoring

rust/scx_utils/src/misc.rs
Automatically (try to) create the socket dir if it doesn't exist. Sometimes the server will fail with:
```
$ sudo ./target/release/scx_layered --run-example --stats 5
thread '<unnamed>' panicked at src/main.rs:1960:74:
called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
21:52:54 [INFO] CPUs: online/possible=16/16 nr_cores=8
21:52:54 [INFO] configuring node 0, LLCs 2
21:52:54 [INFO] configuring llc 0 for node 0
21:52:54 [INFO] configuring llc 1 for node 0
21:52:55 [INFO] Layered Scheduler Attached. Run `scx_layered --monitor` for metrics.
^CEXIT: unregistered from user space
````
=> scx_utils: Add retryable errors

scheds/rust/Cargo.lock, scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_lavd/README.md, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
The PR contains the following changes:
- add a fast path in pick_idle_cpu() when SMT is not activated
- move time slice calculation to ops.enqueue() and ops.select_cpu()
- prefer big cores in the performance mode
- make the old BPF verifier happy
- misc. refactoring and code clean up
=> scx_lavd: move time slice calculation to ops.enqueue() and ops.select_cpu() and more

rust/scx_rustland_core/README.md, rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/intf.h, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/scx_rlfifo/src/main.rs
Small design improvements, mostly focused at enhancing `scx_rustland_core` usability.
API changes:
- temporarily dropped `RL_PREEMPT_CPU` (preemption will be re-added later with a better design)
- allow to specify a vtime in `DispatchedTask` (the vtime will be passed to `scx_bpf_dispatched_vtime()`)
Misc Improvements:
- `scx_rlfifo`: refactoring to make the code more suitable to be used as a generic template
- include the FIFO code in the `README.md` of `scx_rustland_core` (in this way the README can be used standalone as a guide on how to implement schedulers using `scx_rustland_core`)
=> scx_rustland_core: small core design improvements

scheds/rust/Cargo.lock, scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
This PR contains three commits:
- Prioritize the turbo boostable cores in `performance` and `balanced` profiles by default. When seeking an idle CPU at ops.select_cpu(), the turbo bootable cores are chosen before checking the other active cores. To manually control the behavior, `--no-prefer-turbo-core` option is added.
- Replace nix signal handler to ctrlc
- Add `--version` option
=> scx_lavd: prioritize the turbo boost-able cores

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
When creating the turbo boost scheduling domain, we might use a full CPU mask (selecting all possible CPUs) to indicate "do not prioritize turbo boost CPUs" or when all CPUs have the same maximum frequency.
This approach works when the primary domain also contains all the CPUs, as the complete overlap allows the CPU selection logic to ignore the turbo boost domain and start picking CPUs directly from the primary domain.
However, if the primary domain doesn't include all CPUs, the two domains won't fully overlap, which can lead to the turbo boost domain incorrectly including all CPUs, thereby negating the restrictions set by the primary scheduling domain.
To resolve this, an empty CPU mask should be used for the turbo boost domain when turbo boost CPUs aren't prioritized. If the turbo …
=> scx_bpfland: fix turbo boost domain nullifying primary domain limits

scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_mitosis/src/main.rs, scheds/rust/scx_rusty/src/main.rs
Minor work on scx_layered. There wasn't really that much to do.
I also added the same comma to scx_lavd, scx_rusty, and scx_mitosis as I added to scx_bpfland previously and scx_layered in this PR for consistency.
=> scx_layered: Clean up in-code documentation; add commas for consistency

rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/lib.rs, rust/scx_utils/src/topology.rs, scheds/rust/scx_bpfland/src/main.rs
Integrate in Topology the concept of "Turbo" CPUs (to represent the turbo-boosted cores), refactor scx_bpfland to use simply rely on Topology to classify the CPUs in Turbo, Big and Little.
@hodgesds let me know if you see any problem with the new core type "Turbo" or if you have a better idea to represent it in struct Cpu (this is more of a RFC).
=> scx_bpfland: rely on Topology to classify CPU types

scheds/rust/scx_lavd/src/main.rs
`--no-prefer-turbo-core` was added after I added the clarification that scx_lavd's tunables are set by the specified power mode. Add the same clarification to it.
=> scx_lavd: Add power mode clarification to --no-prefer-turbo-core

rust/scx_utils/Cargo.toml, rust/scx_utils/src/topology.rs, scheds/rust/Cargo.lock
Add GPU awareness to the topology crate.
tested on non gpu machine:
```
$ sudo ./bin_local/bin/scx_layered  f:user.json 
21:43:37 [INFO] CPUs: online/possible=80/80 nr_cores=40
GPUS: []
21:43:37 [INFO] configuring node 0, LLCs 1
21:43:37 [INFO] configuring llc 0 for node 0
21:43:37 [INFO] configuring node 1, LLCs 1
21:43:37 [INFO] configuring llc 1 for node 1
```
gpu machine:
```
$ ./scx_layered f:layered.json 
21:44:25 [INFO] CPUs: online/possible=224/224 nr_cores=112
GPUS: [GPU { id: 0, node_id: 0, max_graphics_clock: 1980, max_sm_clock: 1980, memory: 102625181696 }, GPU { id: 1, node_id: 0, max_graphics_clock: 1980, max_sm_clock: 1980, memory: 102625181696 }, GPU { id: 2, node_id: 0, max_graphics_clock: 1980, max_sm_clock: 1980, memory: 102625181696 }, GPU { id: 3, node_id: 0, …
```
=> scx_utils: Add GPU topology

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/bpf/util.bpf.c
Refactor some BPF code to make verification easier on older kernels. This is to make it easier to maintain backports.
=> scx_layered: Make verification easier on older kernels

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Allow setting a different timeslice per layer.
tested by adding some debug logs:
```
diff --git a/scheds/rust/scx_layered/src/bpf/main.bpf.c b/scheds/rust/scx_layered/src/bpf/main.bpf.c
index 14e6fc9..ebf3362 100644
--- a/scheds/rust/scx_layered/src/bpf/main.bpf.c
+++ b/scheds/rust/scx_layered/src/bpf/main.bpf.c
@@ -1230,20 +1230,21 @@ void BPF_STRUCT_OPS(layered_running, struct task_struct *p)
if (tctx->last_cpu >= 0 && tctx->last_cpu != task_cpu)
lstat_inc(LSTAT_MIGRATION, layer, cctx);
tctx->last_cpu = task_cpu;
if (vtime_before(layer->vtime_now, p->scx.dsq_vtime))
layer->vtime_now = p->scx.dsq_vtime;
cctx->current_preempt = layer->preempt;
cctx->current_exclusive = layer->exclusive;
tctx->running_at = bpf_ktime_get_ns();
+       dbg("CFG: layer: %d slice: %llu", layer->idx, …
```
=> scx_layered: Add per layer timeslice

rust/scx_utils/src/topology.rs
Add a helper for getting the cores per node.
=> scx_utils: Add cores helper to node topology

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
The main purpose of this PR is to provide the "--auto" option, which automatically determines power mode selection (performance, balanced, powersave) based on a user's energy profile selection. It periodically checks the EPP and changes LAVD's core selection preference, etc., according to the EPP value.
Besides this main change, it includes the following minor bug fixes and optimizations:
- minor optimization for consume_task()
- bug fix for improper handling of ctrl-c in the monitoring mode
- removed unused functions in the rust code
=> scx_lavd: automatically determine power mode and more

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
The PR contains the following changes:
- Introduce "autopilot" mode, which dynamically switch the scheduler's power mode between powrsave, balanced, and performance according to system-wide CPU utilization. Under low load (<5%), the scheduler runs  with powersave mode. Under moderate load (5% < x < 30%), it runs with balanced mode. Under high load (>30%), it runs with performance mode.
- Rename the "--auto" option to "--autopower" to avoid the confusion with the "autopilot" mode.
- Print the power mode change in the autopower mode
- Add a fastpath in ops.select_cpu() for a sharply pinned task
- Improve the accuracy of cpu utilization calculation
=> scx_lavd: introduce "autopilot" mode and misc. optimization & bug fix

scheds/rust/scx_layered/src/bpf/main.bpf.c
Fix a small bug where the layer timeslice is not applied.
=> scx_layered: Fix layer timeslice not being applied

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
We want to directly dispatch only kthreads when local_kthreads is enabled, not all tasks that can run on a single CPU.
Fixes: 7cc1846 ("scx_bpfland: always rely on prev_cpu with single-CPU tasks")
=> scx_bpfland: directly dispatch only per-cpu kthreads with local_kthreads

rust/scx_rustland_core/Cargo.toml, scheds/rust/Cargo.lock, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml
The scx_rustland_core API has been redesigned recently, breaking the compatibility with the past.
Considering that Rust crates should update their major version when the previous API becomes incompatible [1], bump up the version to 2.0.0.
[1] https://semver.org/
=> scx_rustland_core: bump up major version to 2.0.0

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c
* dynamically decide autopilot's low watermark
*  A single threshold for a low watermark does not work well across systems with various numbers of cores and core types. Instead of using a single low watermark value, we dynamically decide the low watermark: 1) until one little core is fully utilized or 2) until two big cores are fully utilized. This works better across systems.
* when no_freq_scaling, always set to the max freq
* When the no_freq_scaling changes during runtime in the autopilot mode, the last target freq set would not be 1024. So the performance mode enabled by the autopilot mode would not run in the best profile. Hence, we set the target freq to 1024 always when no_freq_scaling is set.
=> scx_lavd: improve  the autopilot mode

scheds/rust/scx_lavd/README.md, scheds/rust/scx_lavd/src/bpf/main.bpf.c
This PR contains the following misc updates:
- check a core type of the previous cpu at pick_idle_cpu()
- rename "--monitor_sched_samples" to "--monitor" for consistency
- update README
- make the old verifier happy (bpf_cpumask_set_cpu)
=> scx_lavd: misc updates (verifier, README, monitor option name, and micro-optimization)

README.md, services/README.md, services/systemd/journald@sched-ext.conf, services/systemd/meson.build, services/systemd/scx.service
Since scx_stats has been implemented, namespace is already redundant.
=> scx_stats: Drop sched-ext namespace

scheds/include/scx/namespace.bpf.h, scheds/include/scx/namespace_impl.bpf.h
Add pid namespace helpers for translating namespace pids. When taking a look at #587 I realized that it would probably need to support pid namespaces. Add some helpers to make it easier to translate from a namespace pid to a root pid.
=> scx_helpers: Add pid namespace helpers

meson-scripts/test_sched, meson-scripts/veristat, meson-scripts/veristat_diff
Recently, we have triggered some OOM conditions during stress tests, particularly with the user-space schedulers. To avoid this issue and prevent false positives, increase the memory size of the virtme-ng instance from the default 1GB to 2GB.
=> ci: bump up virtme-ng memory size from 1GB to 2GB

rust/scx_rustland_core/Cargo.toml, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/Cargo.lock, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml
Fix the `scx_rustland` stall that is triggering a bunch of failures in our CI.
This issue can be easily reproduced inside a virtme-ng instance (e.g., running our CI stress tests). With this change applied the stall doesn't seem to happen anymore.
Also bump up `scx_rustland_core` PATCH version to include this bug fix.
=> scx_rustland_core: fix pcpu kthread stall

.github/workflows/build-scheds.yml, .github/workflows/merge.yml
Now that we have a sane build environment with meson we don't need to force sequential builds anymore (--jobs=1) and we can just run regular builds without having to worry about excessive parallelization.
See commit 43950c6 ("build: Use workspace to group rust sub-projects").
=> ci: allow parallel builds with meson

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Provide a basic cpufreq control, based on the selected EPP and scheduler's performance profile.
Improve turbo boost CPU selection logic.
=> scx_bpfland: improve cpufreq awareness

rust/scx_rustland_core/assets/bpf/main.bpf.c
Prevent triggering a critical error when a local context for a task can't be found. Instead, handle the error gracefully to enhance the robustness of the schedulers based on scx_rustland_core.
=> scx_rustland_core: avoid critical failures due by missing task context

services/openrc/meson.build, services/openrc/scx.initrd, services/openrc/scx.logrotate
Analogous to #573 - we already have scx_stats so separate log management is no longer needed.
=> openrc: drop separate logs

scheds/rust/scx_layered/src/stats.rs
Fix formatting precision of stats to have lower precision for readability. The existing formatting is hard to read:
tot=   1538 local=31.27 open_idle= 2.73 affn_viol=23.80 proc=4ms
busy=  1.1 util=   16.6 load=     32.7 fallback_cpu=  6
excl_coll=0.06501950585175553 excl_preempt=0.26007802340702213 excl_idle=0.16384915474642392 excl_wakeup=0.25097529258777634
With this fix stats are far more readable formatting:
tot=    441 local=33.56 open_idle= 0.00 affn_viol=20.63 proc=3ms
busy=  0.4 util=    6.3 load=     33.6 fallback_cpu=  6
excl_coll=0.454 excl_preempt=0.000 excl_idle=0.132 excl_wakeup=0.200
=> scx_layered: Fix stats formatting

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Rename "turbo domain" to "preferred domain", that conceptually is more generic and introduce the new option `--preferred-domain CPUMASK`, which allows users to define the preferred domain, specifying a cpumask as a hex number. By default ("auto") the scheduler will always try to detect and use the fastest CPUs in the system.
Moreover, adjust the cpufreq logic to use "auto" both with the "balance_power" and "balance_performance" EPP profiles.
Then, enable "auto" mode by default: the scheduler will try to automatically determine the optimal primary domain, preferred domain and cpufreq level, based on the selected scheduler and energy profiles.
=> scx_bpfland: enable "auto" mode by default

scheds/rust/Cargo.lock, scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
This PR contains the following changes:
- Implemented --monitor and its friend options (--help-stats and --stats)
- Improve pick_idle_cpu() for pinned tasks, further preferring the previous CPU
- Drop time slice boost for big core to avoid little cores more changes to steal peformance-critical tasks
=> scx_lavd: add --monitor flag and two micro-optimizations

.github/actions/install-deps-action/action.yml, .github/workflows/caching-build.yml, meson.options, rust/scx_rustland_core/Cargo.toml, rust/scx_utils/src/bpf_builder.rs, rust/scx_utils/src/build_id.rs, rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/infeasible.rs, rust/scx_utils/src/log_recorder.rs, rust/scx_utils/src/topology.rs
This PR fixes rust tests and configures CI to run them on commit. 
It does this by configuring 3 CI jobs.
One CI job will, hourly, build and cache a new sched_ext kernel if there is a new commit on for-next. This periodic job only runs on main. 
The other two CI jobs run meson tests and cargo tests. These use that cached kernel.
All branches can that cached kernel from main. not-main branches will create their own caches if one for main does not exist for for-next's current head, but these are less useful because they are not shared like main's is.
When the kernel is cached, job turnaround time (test time) looks to be ~12 minutes: https://github.com/likewhatevs/scx/actions/runs/10736459682
Not-cached job time looks like 20-25 minutes.
I'm not sure if I should replace the current configs …
=> fix/enable rust tests, make build faster

rust/scx_rustland_core/Cargo.toml, rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/intf.h, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/Cargo.lock, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/Cargo.toml, scheds/rust/scx_rustland/src/main.rs
Introduce some concepts of topology awareness in `scx_rustland_core` (for now only used in the backend) and expose the task's enqueue flags to user-space.
This doesn't break the current API, it only modifies `BpfScheduler::select_cpu()` internally and it adds the extra attribute `flags` to struct `QueuedTask`, that can be potentially used by the user-space scheduler to make better scheduling decisions.
Moreover, simplify `scx_rlfifo` (that also has the effect to improve its performance FWIW) and include a detailed documentation of the `scx_rustland_core` API.
=> scx_rustland_core: introduce topology awareness

.github/workflows/caching-build.yml
The right options to set the amount of CPUs in vng is `-p`, not `-c`. Change the command to use the long format `--cpu` and `--memory` for better clarity.
This fixes issue #625.
=> ci: fix vng command to set the right amount of CPUs

rust/scx_rustland_core/Cargo.toml
Move included artifacts in the lib section (without this change we can't publish the crate on crates.io).
Fixes: 082bccb ("fix/enable rust tests, make build faster")
=> scx_rustland_core: move includes back to the lib section

.github/actions/install-deps-action/action.yml, .github/workflows/caching-build.yml, meson-scripts/run_stress_tests, meson-scripts/test_sched, meson-scripts/veristat, meson-scripts/veristat_diff, meson.build, scheds/rust/meson.build
split build and test jobs to reduce ci turnaround time
and make it clear what is failing when something fails.
also add virtiofsd to deps to make test compilation faster
(most test time is compliation) and remove all force 9ps.
also have rust tests on schedulers be ran.
time w/ no caches is 23 minutes, time with caches is 7 minutes:
https://github.com/likewhatevs/scx/actions/runs/10756353007
i think this should address GH-462, it goes as far as the trade off's involved make sense imo
=> split integration test execution

.github/workflows/caching-build.yml, .gitignore, rust/.gitignore, rust/scx_rustland_core/src/alloc.rs, rust/scx_utils/src/infeasible.rs
this pr configures documentation generation and publishing to https://sched_ext.github.io/scx once it is merged and enabled.
this would look like this page: https://likewhatevs.github.io/scx/
commits to master would trigger the generation of new docs.
the config needed to enable this beyond that in this PR is the following:
the following page details how to have comments be such that pretty docs are rendered: https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html
=> enable docs generation and upload

Cargo.lock, rust/scx_utils/Cargo.toml, rust/scx_utils/src/lib.rs, rust/scx_utils/src/misc.rs, scheds/rust/scx_bpfland/Cargo.toml, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_lavd/src/main.rs
The rlimit crate is the only dependency crate with a build.rs, kind of.
build.rs files complicate portability.
I say "kind of" wrt/ rlimit.rs being the only dependency crate with a build.rs because the bpf skel generation done by libbpf-rs doesn't really count because of https://facebookmicrosites.github.io/bpf/blog/2020/02/19/bpf-portability-and-co-re.html (i.e., IIUC, compiled code isn't tied to vmlinux.h version beyond "the symbols you want need to be present").
This PR removes the dependency on rlimit.rs, enabling cargo build (and the utilization of https://docs.rs/libbpf-rs/latest/libbpf_rs/#alternate-workflow downstream) to enable consumers of scx to build this crate most simply.
=> remove dependency on rlimit.rs

.github/actions/install-deps-action/action.yml, .github/workflows/caching-build.yml
migrate ci vm to ubuntu 24.04
things checked:
* ci works with all caches deleted: https://github.com/likewhatevs/scx/actions/runs/10788376061
* ci works with caches present: https://github.com/likewhatevs/scx/actions/runs/10788172911 
* generated documentation still works: https://likewhatevs.github.io/scx/
Closes: #639
=> migrate ci vm to 24.04

scheds/rust/scx_layered/src/stats.rs
Small typo in the stats messages and formatting
=> scx_layered: Fix typo in stats

scheds/rust/scx_layered/src/main.rs
Pass in the layer spec when determining the layer core growth algo. This should make it easier to implement layer growth algos that are spec specific.
=> scx_layered: Pass layer spec for core growth algo

rust/scx_utils/src/infeasible.rs, scheds/rust/scx_rusty/src/load_balance.rs
The domains are added to the aggregator when load is added (and duty_cycle is not 0.0f64).
This commit makes sure that all domains are added to the aggregator even when the calculated duty_cycle is 0.
Fixes #608
=> scx_rusty: init domains when calculating averages

.github/workflows/build-scheds.yml, rust/scx_loader/src/main.rs, rust/scx_rustland_core/src/alloc.rs, rust/scx_rustland_core/src/rustland_builder.rs, rust/scx_utils/src/bpf_builder.rs, rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/infeasible.rs, rust/scx_utils/src/lib.rs, rust/scx_utils/src/misc.rs, rust/scx_utils/src/topology.rs, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_bpfland/src/stats.rs, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/src/main.rs, scheds/rust/scx_rustland/src/stats.rs, scheds/rust/scx_rusty/src/domain.rs, scheds/rust/scx_rusty/src/load_balance.rs, scheds/rust/scx_rusty/src/main.rs, scheds/rust/scx_rusty/src/stats.rs, scheds/rust/scx_rusty/src/tuner.rs
Use `cargo fmt` with a specific nightly branch in the CI to enforce formatting. Globally format these files while the diff is still small so we can stay on top of it.
Test plan:
- CI check passes.
=> lint: enable cargo fmt

Cargo.lock, scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_layered/src/main.rs
Add a random layer growth algo.
output of using a config with all random growth algos:
```
12:35:34 [DEBUG] layer: random algo: Random core order: [29, 4, 23, 20, 35, 7, 22, 10, 2, 24, 39, 1, 32, 3, 16, 15, 11, 5, 14, 19, 8, 28, 25, 6, 37, 0, 13, 31, 33, 17, 38, 26, 36, 12, 34, 30, 9, 27, 18, 21]
12:35:34 [DEBUG] layer: hodgesd algo: Random core order: [13, 35, 29, 28, 0, 33, 16, 8, 3, 38, 18, 26, 14, 25, 20, 36, 9, 22, 39, 5, 23, 30, 2, 24, 1, 21, 19, 12, 4, 32, 11, 10, 27, 6, 17, 15, 31, 7, 37, 34]
12:35:34 [DEBUG] layer: stress-ng algo: Random core order: [25, 21, 34, 2, 38, 20, 10, 32, 30, 15, 3, 36, 29, 8, 9, 27, 18, 4, 5, 13, 35, 33, 7, 28, 12, 14, 6, 37, 11, 22, 31, 19, 23, 17, 24, 0, 26, 39, 16, 1]
12:35:34 [DEBUG] layer: normal algo: Random core order: [22, 3, 8, 11, 9, 13, 25, …
```
=> scx_layered: Add random layer growth algo

INSTALL.md, README.md
Kernel package name was change to kernel-default.
Also add link to documentation to README.md
=> update Tumbleweed installation notes

rust/scx_utils/src/topology.rs, scheds/rust/scx_layered/src/main.rs
Add topology aware core growth selection, which uses the order of the `llcs`/`nodes` layer config to determine which cores should be selected first when growing a layer.
`scx_layered` output:
```
15:57:39 [DEBUG] layer: random algo: Sticky core order: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
15:57:39 [DEBUG] layer: hodgesd algo: Topo core order: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
15:57:39 [DEBUG] layer: stress-ng algo: Topo core order: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, …
```
=> scx_layered: Add topology aware core growth selection

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
Add stats for XNUMA/XLLC migrations. An example of the output is shown:
```
tot=  21282 local=97.47 open_idle=48.81 affn_viol= 0.00 proc=4ms
busy=  2.2 util=  166.0 load=   2039.1 fallback_cpu=  0
excl_coll=0.07 excl_preempt=0.00 excl_idle=0.05 excl_wakeup=0.04
hodgesd  : util/frac=    5.8/  3.5 load/frac=      6.2/  0.3 tasks=   747
tot=   4100 local=93.17 wake/exp/reenq= 6.83/ 0.00/ 0.00
keep/max/busy= 0.02/ 0.00/ 0.00 kick= 0.00 yield/ign= 0.22/    0 
open_idle= 0.00 mig= 7.07 xnuma_mig= 4.63 xllc_mig= 4.63 affn_viol= 0.00
preempt/first/idle/fail= 0.00/ 0.00/ 0.00/ 0.00 min_exec= 0.00/   0.00ms
cpus=  2 [  2,  2] 00000000 00000010 00001000
normal   : util/frac=  160.2/ 96.5 load/frac=   2032.8/ 99.7 tasks=  4164
tot=  17182 local=98.50 wake/exp/reenq= 1.12/ 0.38/ 0.00
keep/max/busy= …
```
=> scx_layered: Add stats for XNUMA/XLLC migrations

scheds/rust/scx_lavd/src/bpf/main.bpf.c
When a system does not have a turbo core, skip an effort to choose turbo cores on the pick_idle_cpu() path.
=> scx_lavd: add a short circuit for the case of no turbo core

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c
Many kernel threads performs latency critical tasks (e.g., net, gpu). In particular, AMD GPU driver runs the most part in the kernel space using kworker. Hence, treat kernel threads as if a woken up task.
=> scx_lavd: boost the latency critility of kernel threads

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Now that scx_bpfland has a concept of LLC domain, re-use the same logic from scx_rusty to handle WAKE_SYNC tasks.
Moreover, get rid of the preferred domain (prioritizing turbo boosted CPUs), that seems to introduce more overhead than benefits.
=> scx_bpfland: refine idle CPU selection logic

rust/scx_stats/scripts/scxstats_to_openmetrics.py
On Python versions that perform validation of this line it fails because of a square bracket mismatch. This is due to the single quotes being parsed first. Fix by changing the outer string to double quotes.
=> scxstats_to_openmetrics: fix format string

rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/intf.h, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/src/main.rs
Pass enqueue flags to user-space: flags will be passed via QueuedTask.flags and can be forwarded back to BPF via DispatchedTask.flags.
These flags can be also passed to BpfScheduler.select_cpu() to apply a more refined CPU selection policy.
Moreover, avoid to prioritize the user-space scheduler too much and dispatch it only if there are no other tasks that needs to be dispatched in ops.dispatch().
This improves CPU utilization and enhances the fairness, robustness, and resilience of schedulers based on scx_rustland_core, particularly under stress test conditions.
=> scx_rustland_core: improve idle CPU selection API and logic

rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/main.bpf.c
A couple of changes that should finally prevent all the CI failures.
With this applied, the schedulers based on scx_rustland_core will always dispatch kthreads directly from the BPF component. This should be a safer option for now, allowing to prevent potential stalls also under heavy stress test conditions.
In the future, we will provide a better API to enforce stricter selection criteria for tasks permitted to bypass user-space scheduling.
=> scx_rustland_core: prevent CI failures

rust/scx_rustland_core/assets/bpf.rs
Use an `_` variable to access the returned valued of `saturating_sub()` to mute the compilation warnings.
=> scx_rustland_core: Access the returned value of saturating_sub()

scheds/rust/scx_layered/src/bpf/main.bpf.c
There're two main changes in this PR, describing in sequence in the following content.
First, refactor `match_layer()` to prevent the compilation error caused by the uninitialization of the variable `nr_match_ors`.
Secondly, implement a helper function to access cpumask within `struct bpf_cpumask`.
Because the fact that `struct bpf_cpumask` isn't the same as `struct cpumask` aka `cpumask_t`, conversions between the two types can't be done directly in a safe way.
The actual cpumask within a `struct bpf_cpumask` is embedded within it as a structure member. To access the actual cpumask, a helper function `bpf_cpumask_access()` is implemented and used to wrap `nodec->cpumask` and `cachec->cpumask` before they're passed into `bpf_cpumask_test_cpu()`.
=> scx_layered: Refactor match_layer() and implement helper function to access cpumask within bpf_cpumask

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
The usage of `cast_mask()` within `bpfland_enqueue` aims to cast the type of "p->cpus_ptr" from "struct bpf_cpumask *" to "const struct cpumask *". However, the type of "p->cpus_ptr" is already "const cpumask_t *" aka "const struct cpumask *", so no conversion is needed.
Moreover, passing a value of type "struct cpumask *" into "struct bpf_cpumask *" leads to compiling error.
=> scx_bpfland: Remove the usage of cast_mask in bpfland_enqueue

rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/topology.rs, scheds/rust/scx_layered/src/main.rs
Add layer growth algos for big/little core topologies that prefer one core type. Discussed this with @JakeHillion at LPC as another way to grow layers.
=> scx_layered: Add Big/Little core growth algos

scheds/include/scx/common.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c
Previously, we found a victim from the entire CPUs, which include remote or non-compatible CPUs. Now we limit our search for victim finding within a task's compute domain.
=> scx_lavd: find a victim cpu for preemption within task's compute domain

scheds/rust/scx_layered/src/bpf/main.bpf.c
Trying to track down some stall issues and the output format when using topology awareness is messy. Add in some line breaks per layer DSQ.
new output:
```
swapper/7[0] triggered exit kind 1026:
runnable task stall (watchdog failed to check in for 30.001s)
Backtrace:
scx_tick+0x69/0x70
scheduler_tick+0xf4/0x2a0
update_process_times+0x89/0xa0
tick_nohz_handler+0xc0/0x100
__hrtimer_run_queues+0xea/0x250
hrtimer_interrupt+0xf0/0x390
__sysvec_apic_timer_interrupt+0x47/0x110
sysvec_apic_timer_interrupt+0x68/0x80
asm_sysvec_apic_timer_interrupt+0x16/0x20
cpuidle_enter_state+0x119/0x240
cpuidle_enter+0x28/0x40
do_idle+0x160/0x1f0
cpu_startup_entry+0x26/0x30
start_secondary+0x7e/0x80
common_startup_64+0x13e/0x140
LAYER[0]DSQ[1] nr_cpus=0 nr_queued=0 -0ms cpus= …
```
=> scx_layered: Cleanup dump format

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c
If a waker is more latency critical than a wakee, inherit a waker's latency criticality for the wakee. This allows the wakee to consider the context of who wakes me up. For now, we limit such inheritance to one hop and one schedule.
=> scx_lavd: propagate waker's latency criticality to its wakee

rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/c/scx_nest.bpf.c, scheds/include/scx/common.bpf.h, scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/bpf/main.bpf.c
Remove cast_mask() function distributed throughout different schedulers and add it in common.bpf.h so every scheduler can reference it once they need to.
=> scx_common_bpf: Append cast_mask()

.github/workflows/caching-build.yml
I think I see PRs being harder to write because all parts of a CI job are cancelled when one fails.
I think I am also starting to see that we have enough largely disjoint moving pieces that there will often be one that is failing stress tests at any time.
Make CI run all stress tests always to address this.
=> add 'continue on error' to stress tests in ci jobs

scheds/rust/scx_layered/src/bpf/main.bpf.c
When preempting restrict preemption to the current layer cpumask. This may reduce the amount of preemption, but cause better cache locality of preempted tasks.
=> scx_layered: Restrict preemption to layer cpumask

scheds/rust/scx_layered/src/bpf/main.bpf.c
Make scx_layered idle CPU selection topology aware. It first tries to select an idle CPU from the local LLC before attempting to select an idle CPU from the local node.
=> scx_layered: Make layered idle CPU selection topology aware

.clangd, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/include/scx/common.bpf.h, scheds/include/scx/user_exit_info.h, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_mitosis/src/bpf/intf.h, scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c, scheds/rust/scx_rusty/src/bpf/intf.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c
this makes it so that clangd and ide tools which use clangd can work on the bpf.c code.
nothing should actually be changed outside of that ide/editor environment, all the changes are ifdef'ed on LSP which is set in the added .clangd file.
=> enable ide's etc. to work on the bpf.c files

meson.build, meson.options
enable build and test outside src dir
add a option `build_outside_src`, defaulted
to false, to undo a tweak to enable meson to work
well with builds within src dir.
this makes some tools work better + enables
moving builds etc. to /tmp (faster for iteration if ramdisk)
this enables scripts like the following, which make iteration time nice and fast:
```
#!/bin/bash
set -euxo pipefail
REPOS=/home/patso/repos
SCX=scx
KERNEL=sched-ext-linux
SCHED="$1"
cd $REPOS/$KERNEL
vng -v --build --pwd $REPOS/$KERNEL --config "$REPOS/$SCX/.github/workflows/sched-ext.config"
cd $REPOS/$SCX
BUILDDIR=../../../../tmp/scxbuild/
mkdir -p $BUILDDIR
meson setup -Dkernel=$REPOS/$KERNEL -Dkernel_headers=$REPOS/$KERNEL/usr/include -Denable_stress=true -Dbpftool=/usr/bin/bpftool $BUILDDIR $REPOS/$SCX …
```
=> enable build and test outside src dir

rust/scx_utils/Cargo.toml, rust/scx_utils/src/gpu.rs, rust/scx_utils/src/lib.rs, rust/scx_utils/src/misc.rs, rust/scx_utils/src/topology.rs
The gpu-topology feature can be enabled to include GPUs when generating a topology-map. Disabling the feature will remove the nvml-wrapper dependency as well as GPU-specific code in topology.rs.
Most of the code was moved to a new module in rust/scx_utils/src/gpu.rs but some of it was kept in topology.rs and hidden behind #[cfg(feature = "gpu-topology")].
Fixes #589
=> scx_utils: Add gpu-topology crate feature

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/main.rs
Add an enum for the layer growth algo to the bpf layer config. This will be useful for implementing topology aware layer growth algorithms. When selecting an idle CPU the current logic tries to keep tasks local to LLC/NUMA node. However, for certain growth algorithms (ex: RoundRobin) this is suboptimal. Adding the layer growth algorithm will allow for different paths for CPU selection in the idle/preemption paths.
=> scx_layered: Add layer growth algo to layer bpf config

meson-scripts/run_stress_tests, meson-scripts/stress_tests.ini, meson.build, scripts/bpftrace_stress_wrapper.sh
update meson/stress test runner to enable running bpftrace scripts while running stress tests.
this might blow up CI logs a bit but like, it will blow them up with debug info.
I think later I'll see if I can get vng to mount rw such that individual log files can be saved as CI run artifacts.
=> enable bpftrace when using stress tests

.github/workflows/caching-build.yml
do not cache fast jobs dependencies
doing this will make slow jobs caches get evicted (and the fast jobs are not the long tail anyway).
=> do not cache fast jobs dependencies

scheds/rust/scx_layered/src/bpf/main.bpf.c
Fix idle core selection to correctly use `pick_idle_cpu_from`. Previously it was passing in the mask of the topology (LLC/node) rather than the idle mask of the topology. This will be refactored in the future when `struct layer_cpumask_wrapper` gets support for additional `bpf_cpumasks` for topologies.
=> scx_layered: Fix idle core selection

.github/workflows/caching-build.yml
Enabling the `caching-build` workflow on `merge_group` actions. This is required to enable merge queues which should make merging lots of PRs while getting full CI testing possible. Currently `lint` is the only required check but we will add more in future.
=> ci: enable on merge_group action

DEVELOPER_GUIDE.md
Added documentation of how to match the CI in formatting. It involves two steps: mutating your rustup toolchains to have the right nightly version, and running the formatting. Because of this I've avoided making it a script as I don't want to mess with anyone's local state, but this does mean we'll have to keep it in sync with the CI (CI is always the source of truth here).
=> dev_guide: document cargo fmt

rust/scx_loader/README.md, services/systemd/meson.build, services/systemd/org.scx.Loader.service, services/systemd/scx_loader.service
Provide additional systemd service for `scx_loader` to be able to autostart it by DBUS, even if the service was enabled/started by user, DBUS will search by name and start it with propagation of called dbus method/property
ref: "Example 7. DBus services" https://www.freedesktop.org/software/systemd/man/256/systemd.service.html
=> scx_loader: Add systemd service and on-DBUS launch

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
We used the average performance criticality of tasks as a threshold to
determine the proper core type (big or little). However, if the big
core's compute capacity is not half of the total compute capacity, such
an average-based determination becomes suboptimal. If fewer tasks are
classified as performance-critical tasks and requested to run on big
cores, the big cores would be wasted by stealing arbitrary
non-performance-critical tasks. That could result in performance
instability.
Hence, determine the threshold more accurately by considering (active)
big cores' compute capacity and the (approximated) distribution of
performance criticality of tasks.
=> scx_lavd: more accurately determine the performance criticality threshold

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
This PR contains two potential bugs, one of which causes a stress test failure in CI.
- scx_lavd: do not perform the victim selection for an invalid cpu
- scx_lavd: fix incorrect neighbor_bit initialization
=> scx_lavd: fix two potential bugs

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
Small fix:
- scx_bpfland: fix task_avg_nvcsw() return type (used in `--lowlatency` mode)
Minor improvements:
- scx_bpfland: keep tasks running on full-idle SMT cores (from `ops.dispatch()` keep the current task running it it's the last one and if the used CPU is a full-idle SMT core)
- scx_bpfland: always give tasks a chance to run on an idle CPU (similar logic that will be provided by the new upcoming `SCX_ENQUEUE_RQ_SELECTED` flag)
=> scx_bpfland small fixes and improvements

.gitignore, Cargo.lock, rust/scx_stats/Cargo.toml, rust/scx_stats/scx_stats_derive/src/lib.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
The doc of scx_layered `Opt` is out of sync.
Implement attribute macro #stat_doc to generate doc from the `desc` property, and apply #stat_doc to `LayerStats` and `SysStats` in scx_layered.
Also fix typo and replace `#` with "count of" to avoid messing with markdown syntax in the generated rust doc.
Signed-off-by : Ming Yang <minos.future@gmail.com>
=> scx_stats: Implement macro #stat_doc to autogen doc from stat desc

rust/scx_loader/README.md, rust/scx_loader/org.scx.Loader.xml
XML can be used for code generation like `gdbus-codegen`,`zbus-xmlgen`
refs:
- https://dbus2.github.io/zbus/client.html
- https://docs.gtk.org/gio/migrating-gdbus.html#generating-code-and-docs
- https://dbus.freedesktop.org/doc/dbus-api-design.html
- https://dbus.freedesktop.org/doc/dbus-specification.html
=> scx_loader: Add D-Bus Introspection XML

scheds/rust/scx_bpfland/src/stats.rs, scheds/rust/scx_lavd/src/stats.rs, scheds/rust/scx_rustland/src/stats.rs, scheds/rust/scx_rusty/src/stats.rs
`#stat_doc` extends the document from stat desc property.
Add this attribute macro to the remaining Stats structs.
This follows up #703.
=> Add #stat_doc attribute macro to Stats structs

scheds/rust/scx_rusty/src/bpf/main.bpf.c
"struct task_struct *p" isn't used within the function "task_load_adj()". Delete the function parameter for cleaner code.
=> scx_rusty: Delete unused function variable

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
This PR implements CPU hotplug correctly using `scx_utils::NR_CPU_IDS` and fixes one minor bug related to preemption.
=> scx_lavd: support CPU hotplug correctly

.github/workflows/bpf-next-test.yml
Run integration tests against bpf-next kernel every 6 hrs.
This seems like a reasonable way to do this (i.e. don't add noise to folks developing/testing things, but also let us know if there are issues w/ our code and bpf-next).
Will add a comment to a successful job run on my fork once it runs.
=> Run integration tests against bpf-next kernel every 6 hrs.

scheds/rust/scx_rusty/src/bpf/main.bpf.c
Remove a short-circuit in cpu_to_dom_id that will return domain id 0 for any input.
This fixes a crash of scx_rusty when running with a single domain and any CPU is offline.
Fixes #723
=> scx_rusty: fix single dom short-circuit

scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
Basically addressing issue #720, described from @hodgesds:
> In `scx_layered` the time slice can be [configured per layer](https://github.com/sched ext/scx/blob/main/scheds/rust/scx_layered/src/main.rs#L493). This should be added to the [`LayerStats`](https://github.com/sched-ext/scx/blob/main/scheds/rust/scx_layered/src/stats.rs#L51) for each layer. During stats [refresh](https://github.com/sched-ext/scx/blob/main/scheds/rust/scx_layered/src/main.rs#L852) read the time slice duration (from the bpf skel) to the layer and add it to the stats. Finally, update the [format](https://github.com/sched-ext/scx/blob/main/scheds/rust/scx_layered/src/stats.rs#L218) method for `LayerStats` to print the per layer time slices.
=> scx_layered: Add per layer time slices to stats

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/layer_core_growth.rs, scheds/rust/scx_layered/src/main.rs
This PR addresses #730.
* scx_layered: Move layer core growth logic to separate module
* scx_layered: Break up layer_core_order function 
* `layer_core_order` provided multiple core growth implementation
* Break it up into smaller function. Also, attach the method to `LayerGrowthAlgo`. And `LayerCoreOrderGenerator` is added to make future growth algo extension easy.
* scx_layered: Add Reverse layer growth algo
* Add `LayerGrowthAlgo::Reverse` to be the reverse order of Linear.
=> scx_layered: Refactor topology algorithms to a separate module

scheds/rust/scx_rusty/src/bpf/intf.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/load_balance.rs
~I wasnt't able to reopen https://github.com/sched-ext/scx/pull/672 because I force pushed (just learned about that limit).~
~This is a continuation of that PR.~
~I closed that PR and opened https://github.com/sched-ext/scx/pull/710 because, while the first PR's approach passed stress tests and seemed to work, it kind of didn't make sense that I could deref the casted pointer to task_struct.~
~I updated that initial PR to explicltly deref that casted pointer to confirm this works/the verifier allows it and it seems to work so, this works?~
see latest comment
=> Replace PID with Task Pointer in Rusty

rust/scx_utils/src/topology.rs, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/layer_core_growth.rs, scheds/rust/scx_layered/src/main.rs
Add big cpumask to scx_layered and prefer selecting big idle cores when using the `BigLittle` growth algo. Future work can be preferring selecting little idle cores for the `LittleBig` growth algo.
=> scx_layered: Add big cpumask

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
In the non topology aware code the idle smt mask is used for finding idle cpus. Update topology aware idle selection to also use the idle smt mask. In certain benchmarks this can improve performance.
Tested on `12th Gen Intel(R) Core(TM) i3-1220P` with P/E cores and `stress-ng` configured with `BigLittle` growth algorithm on big cores.
With idle smt mask:
```
stress-ng -c 2 -t 10 -M
stress-ng: info:  [17956] setting to a 10 secs run per stressor
stress-ng: info:  [17956] dispatching hogs: 2 cpu
stress-ng: metrc: [17956] stressor       bogo ops real time  usr time  sys time   bogo ops/s     bogo ops/s CPU used per       RSS Max
stress-ng: metrc: [17956]                           (secs)    (secs)    (secs)   (real time) (usr+sys time) instance (%)          (KB)
stress-ng: metrc: [17956] cpu …
```
=> scx_layered: Use idle smt mask for idle selection

rust/scx_loader/README.md, rust/scx_loader/org.scx.Loader.xml, rust/scx_loader/src/main.rs
These methods allow switching between different schedulers without requiring manual stopping and starting.
=> scx_loader: Add SwitchScheduler methods to DBUS interface

scheds/rust/scx_rusty/src/bpf/main.bpf.c
This PR fixes the crash 2 in https://github.com/sched-ext/scx/issues/725
When hotplugging CPUs in rapid succession, scx_rusty would crash with:
```
scx_bpf_error (Failed to lookup dom[4294967295]
```
The root cause is if the scheduler is restarted fast enough, a task on a previously hotplugged CPU may not have moved off that CPU yet. Thus, the CPU -> domain map would contain an invalid domain (u32::max) and we would fail to lookup the domain correctly in rusty_select_cpu for prev_cpu.
To fix this, if the CPU is offline, we do not try to allocate to the same NUMA node (assuming hotplug is a rare operation) beyond domestic domain. Instead we use greedy allocation - first idle, then busy - then any CPU.
=> scx_rusty: Fix BPF crash during CPU hotplug

scheds/rust/scx_layered/src/bpf/main.bpf.c
Update the idle topology selection order, the current logic is:
core architecture (big/little) -> LLC -> NUMA -> Machine
It's probably better to try to keep cache lines clean and do:
LLC -> core architecture (big/little) -> NUMA -> Machine
=> scx_layered: Update idle topology selection order

scheds/rust/scx_layered/src/bpf/main.bpf.c
I *think* (like, *maybe* think) this improves the responsiveness of layered by fixing some off-by-1 error.
Interesting thing about the results below:
18.72/15.60=1.2 (main fork user sec / branch fork user sec)
146579/131561=1.114152370 (main bogo ops / branch bogo ops)
9/7.66 = 1.17493473  (main cpu used % per instance / branch cpu used % per instance)
I think that, in combination with the rest of the results, is saying:
This change reduces the absolute number of instructions executed for this test, but it decreases how long it takes (in terms of time) for those instructions to be executed and how much CPU% those insns cost.
```
main
STRESS OUTPUT
stress-ng: info:  [295] setting to a 14 secs run per stressor
stress-ng: info:  [295] dispatching hogs: 32 cpu, 32 fork
stress-ng: info:  [295] …
```
=> scx_layered: lighten/reduce nested loops in layered dispatch

meson-scripts/stress_tests.ini, meson-scripts/test_sched, scheds/rust/scx_layered/src/main.rs
Add a stress-ng example layer, which will be used for CI testing with stress-ng.
=> scx_layered: Add stress-ng example layer

scheds/rust/scx_layered/src/main.rs
Test CI hosts are VMs currently and making stress-ng exclusive may starve the host.
=> scx_layered: Make stress-ng non exclusive in example

meson-scripts/run_stress_tests, scheds/rust/scx_layered/src/bpf/main.bpf.c
this PR fixes CI.
the old stress test config wasn't testing much (it was testing something, but what, idk).
the new config tests things well.
the shortest path to fixing CI is reverting the loop reorganizing I merged this morning *and* setting vng configuration to the same settings used for `test_sched` (w/o this, w/ the new config, stress OOMs on high core machines).
=> scx_layered: fix ci

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_bpfland/src/stats.rs
Since per-CPU kthreads may show an inconsistent prev_cpu and/or cpumask, dispatch them directly to local DSQ and allow to preempt the current running task.
This allows to prevent per-CPU kthread stalls and it also helps to prioritize them, as are usually important for system performance and responsiveness.
Moreover, change the behavior of --local-kthreads to prioritize all kthreads when this option is used.
This addresses issue #728.
NOTE: ideally we may want to fix this in the kernel by making sure to always expose a consistent prev_cpu and cpumask also for kthreads, but at the moment this change allows to prevent some annoying stalls and performance-wise it doesn't seem to introduce any regression. In fact, the usual gaming/fps benchmarks show even a slight improvement in responsiveness …
=> scx_bpfland: prevent per-CPU DSQ stall with per-CPU kthreads

rust/scx_utils/src/lib.rs, rust/scx_utils/src/misc.rs, scheds/rust/scx_layered/src/stats.rs, scheds/rust/scx_rusty/src/load_balance.rs, scheds/rust/scx_rusty/src/stats.rs
This PR fixes https://github.com/sched-ext/scx/issues/609
When the machine is under-utilized when using scx_rusty (e.g. avg util < 99.9%), weights are ignored in the load balancer since all weights will be infeasible and therefore we should assume each task has equal weight. Thus, the default weight was assumed to be 1.
However, when the machine become >= 99.9% utilized, we end up using the real weights and correcting for infeasible weights. The default weight in the kernel is 100, so what ends up happening is we see load scale up by 100x which is a confusing experience for the user.
The fix is to set all weights = 100 in the load balancer if the machine is under-utilized so we don't see a major surprising jump in load metrics.
We end up using weight = 100 as opposed to 1 which might be …
=> [rusty] Fix load stats when host is under-utilized

scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
Rename the `load_adj` statistic to `load_frac_adj`, which is a more accurate representation of what the statistic is calculating. The statistic is a fractional representation of the load of a layer adjusted for infeasible weights.
I wasn't sure if it was worth reporting both the infeasible weighted load fraction and the weight adjusted duty cycle, but under high they are highly correlated.
```
tot=  16064 local=26.54 open_idle= 0.00 affn_viol= 2.27 proc=6ms nodes=1
busy= 46.0 util= 8071.1 load=     99.1 fallback_cpu= 70
excl_coll=13.30 excl_preempt=6.16 excl_idle=0.27 excl_wakeup=0.00
hodgesd  : util/dcycle/frac/ 24.5/  0.3/    0.3 load/load_frac_adj/frac=     0.03/0.04/  0.0 tasks=   207
tot=   3805 local=65.97 wake/exp/reenq=33.69/ 0.34/ 0.00
xlayer_wake= 1.05 xlayer_rewake= 0.42 …
```
=> scx_layered: Rename load_adj statistic

scheds/rust/scx_layered/src/bpf/main.bpf.c
Cleanup debug messages to use a common prefix when the scheduler is initialized.
=> scx_layered: Cleanup debug messages

.github/workflows/caching-build.yml, meson-scripts/run_stress_tests, meson.build, meson.options
scx_layered: setup matrix job to run key paths of layered through verifier/stress
this will increase delays wrt/ ci jobs (i.e. they'll still be fast, but they're probably going to be throttled a bit).
that being said, it these cover the fixes in #768, so idk lets do it?
also updates local stress runs a bit (fixes an issue w/ header pass option and enables arg passthrough).
seems to work fine + is better than what we have now wrt/ keeping main not broken.
=> scx_layered: setup matrix job to run key paths of layered through verifier/stress

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Change the default DSQ iter algo from round robin to linear in to be consistent. ***NOTE***, the actual default value is already [`linear`](https://github.com/sched-ext/scx/blob/main/scheds/rust/scx_layered/src/main.rs#L453).
=> scx_layered: Change default DSQ iter algo

scheds/rust/scx_layered/src/bpf/main.bpf.c
This PR addresses https://github.com/sched-ext/scx/issues/738 by implementing a reverse weight iteration algorithm in scx-layered. This means we iterate through DSQs from layers with the highest weight to lowest weight. The goal is to avoid stalls that happen from lower weighted layers consuming all available resources. Although the opposite problem could happen here, so this is just a temporary algorithm until we have more robust load balancing across layers.
=> [layered] Implement reverse weight DSQ algorithm

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/bpf/util.bpf.c
This is what I was talking about on https://github.com/sched-ext/scx/pull/778
It makes it nice to edit that file, and most folks editing this file get this benefit because of https://github.com/likewhatevs/scx/blob/main/.clangd
=> layered -- make lsp work nice on util include file

scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/layer_core_growth.rs, scheds/rust/scx_layered/src/lib.rs, scheds/rust/scx_layered/src/main.rs
Move the LayerConfig and its children from `main.rs` into `lib.rs`. This allows
other tooling, such as config managers or test executors, to modify layered
configs programmatically.
The end goal is to move everything in `layered` except for the argument parsing
into a `run_layered` function, but I haven't done it in this diff because it's
a larger change. This is a common pattern in Rust projects to do as little as
possible in `main.rs` for extensibility.
The only change here, other than publicity and where things are located, is the
signature of `CpuPool::alloc_cpus`. It previously relied on `&Layer`, and this
changes it to the two elements of `Layer` it uses. This allows `Layer` to stay
confined to `main.rs` (for now) to prevent scope creep in this PR.
This may be inconvenient in the …
=> layered: move configuration into library component

scheds/rust/scx_layered/src/bpf/main.bpf.c
More cleanup in the non topology path to remove copy/pasta declarations.
=> scx_layered: Cleanup non topology path

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/lock.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
If a task holding a lock (i.e., lock holder) is preempted for some reason, it will hinder the forward progress of a system and cause unnecessary task switches. To mitigate the lock holder preemption problem, this PR does the following:
- Track all blocking locks in kernel and userspace, so the scheduler can easily decide if a task holds a lock of not.
- When a task holds a lock, the lock holder task should be not preempted or should not yield its execution to other tasks.
- When a lock holder exhausts its time slice, it should be scheduled as soon as possible, so system-wide progress can be made.
In addition to the above major changes, this PR includes the bug fix in the preeemptability test (https://github.com/sched-ext/scx/issues/773)
Overall this brings more consistent results with …
=> scx_lavd: mitigate the lock holder preemption problem

rust/scx_rustland_core/assets/bpf/main.bpf.c
The symbol __handle_mm_fault isn't available anymore in 6.12, let's rely on handle_mm_fault that is available both on 6.12 and older kernels.
=> scx_rustland_core: use handle_mm_fault kprobe

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Get rid of the per-CPU DSQ logic, since it seems to add more issues than benefit.
With this set of changes bpfland seems to be more stable and it also shows better performance in terms of responsiveness (according to my benchmarks and feedback from the CachyOS community).
=> scx_bpfland: drop per-cpu DSQs

scheds/rust/scx_lavd/src/bpf/introspec.bpf.c
Print the task status of scx_lavd is not useful, so filter it out.
=> scx_lavd: do not inspect scx_lavd process itself

scripts/ftrace_trim, scripts/sched_ftrace.sh
Add a set of ftrace helper scripts for making perfetto compatible ftrace scheduler profiles. I've attached a
[perfetto profile](https://github.com/user-attachments/files/17350788/sched.CPUPROFILE) of the output (Github has dumb file name extensions, but the profile should load in perfetto). The script is a little buggy and could use some improvement, but should be a good starting point.
=> scripts: Add ftrace perfetto helper scripts

scheds/rust/scx_layered/integration/layer_node.bt, scheds/rust/scx_layered/integration/numa.json, scheds/rust/scx_layered/integration/numa_tests.sh
Add a bpftrace script that does a topology aware test. The test script runs a bpftrace script that asserts that `stress-ng` processes are scheduled on NUMA node 0 only. This is a first attempt so it won't be added to meson or CI, mostly just for local testing.
output when successful:
```
tot=  50848 local=91.46 open_idle= 2.02 affn_viol= 0.00 proc=4ms nodes=2
busy= 10.9 util=  849.4 load=     15.1 fallback_cpu=  8
excl_coll=0.00 excl_preempt=0.00 excl_idle=0.00 excl_wakeup=0.00
numa_0: util/dcycle/frac/302.0/ 35.6/   35.6 load/load_frac_adj/frac=     3.06/35.55/ 20.2 tasks=   162
tot=   6757 local=49.47 wake/exp/reenq= 0.49/50.04/ 0.00
xlayer_wake= 0.00 xlayer_rewake= 0.00
keep/max/busy= 1.30/ 0.04/ 0.06 kick=49.25 yield/ign= 0.00/    0 
open_idle= 0.00 mig= 0.77 xnuma_mig= 0.00 xllc_mig= …
```
=> scx_layered: Add topology integration test

scheds/rust/scx_layered/integration/layer_llc.bt, scheds/rust/scx_layered/integration/layer_node.bt, scheds/rust/scx_layered/integration/llc.json, scheds/rust/scx_layered/integration/run_tests.sh
Add an integration test for testing that the `llcs` field on the layer config works properly.
Tests pass on multi NUMA machine:
```
tot=  45982 local=92.08 open_idle=23.55 affn_viol= 0.00 proc=6ms nodes=2
busy= 11.7 util=  930.4 load=     14.6 fallback_cpu=  4
excl_coll=0.00 excl_preempt=0.00 excl_idle=0.00 excl_wakeup=0.00
llc_0: util/dcycle/frac/303.7/ 32.6/   32.6 load/load_frac_adj/frac=     3.05/32.64/ 20.9 tasks=    41
tot=   5632 local=49.52 wake/exp/reenq= 0.44/50.04/ 0.00
xlayer_wake= 0.05 xlayer_rewake= 0.00
keep/max/busy= 1.56/ 0.04/ 0.11 kick=49.24 yield/ign= 0.00/    0 
open_idle= 0.00 mig= 0.78 xnuma_mig= 0.00 xllc_mig= 0.00 affn_viol= 0.00
preempt/first/xllc/xnuma/idle/fail= 0.00/ 0.00/ 0.00/ 0.00/ 0.00/ 0.00 min_exec= 0.00/   0.00ms, slice=20ms
cpus=  4 [  4,  4] 00000003 …
```
=> scx_layered: Add LLC integration test

.github/workflows/caching-build.yml, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Remove DSQ iter algos to use the most obvious approach of using the layer that is currently running on the CPU and then iterating over the rest of the layers. This cleans up a bunch of extra mostly unnessary config that doesn't really provide a net positive impact in performance.
=> scx_layered: Remove layer iteration

scheds/rust/scx_mitosis/src/bpf/intf.h, scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c
Pinned tasks should just be routed to a fallback DSQ. kthreads are given a higher priority than non-kthreads so use two fallback DSQs.
=> scx_mitosis: Handle pinned tasks

Cargo.lock, rust/scx_rustland_core/Cargo.toml, rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/intf.h, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/Cargo.toml, scheds/rust/scx_rustland/src/main.rs
Some changes to improve stability and performance of the scx_rustland_core schedulers and properly support the 6.12 kernel.
Summary of the changes:
- scx_rustland_core now provides nvcsw, slice and dsq_vtime directly (user-space scheduler can now access this information quickly)
- keep CPUs alive with pending tasks (this fixes issue #788)
- restart scheduler on hotplug events (this makes scx_rustland_core schedulers more reliable)
- scx_rustland improvements: use the new metrics provided by scx_rustland_core, apply some idle selection changes from bpfland, prioritize WAKE_SYNC tasks
- scx_rlfifo: make it more work-conserving, so that it can be used as a better stress test for the sched_ext core
=> scx_rustland fixes and improvements

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/layer_core_growth.rs
Add an additional layer growth algorithm, named 'RandomTopo'. It follows these
rules:
- Randomise NUMA nodes. List each core in each NUMA node before a core from
another NUMA node.
- Randomise LLCs within each NUMA node. List each core in each LLC before a
core in a different LLC.
- Randomise the core order within each LLC.
This attempts to provide a relatively evenly distributed set of cores while
considering topology. Unlike `Topo`, it does not require you to specify the
ordering and instead generates it from the hardware, making desyncs between the
config and the hardware less likely.
Currently `RandomTopo` considers topology even with `--disable-topology=true`.
I can see the arguments for this going both ways. On one hand requesting
disable topology suggests you want no consideration …
=> layered: add RandomTopo layer growth algorithm

scheds/rust/scx_layered/src/main.rs
The recent changes to `disable_topology` making the arg an `Option<bool>`
instead of a `bool` caused an issue with it incorrectly attaching arguments.
Make the argument `require_equals` to fix this case.
This is a behaviour change for anybody previously relying on `-t true`,
`-t false`, `--disable-topology true`, or `--disable-topology false`. The
equals syntax worked before and continues to work after, as demonstrated in the
CI.
Test plan:
Before:
```sh
$ sudo target/release/scx_layered -t f:/tmp/test.json
error: invalid value 'f:/tmp/test.json' for '--disable-topology
[<DISABLE_TOPOLOGY>]'
[possible values: true, false]
For more information, try '--help'.
```
After:
```sh
$ sudo target/release/scx_layered -t f:/tmp/test.json
14:44:00 [INFO] CPUs: online/possible=176/176 nr_cores=88 …
```
=> layered: make disable_topology arg require equals

rust/scx_rustland_core/README.md, scheds/rust/scx_rlfifo/src/main.rs
Update the documentation adding the new task statistics provided by scx_rustland_core.
Fixes: be681c7 ("scx_rustland_core: pass nvcsw, slice and dsq_vtime to user-space")
=> scx_rustland_core: update documentation about the new API

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_bpfland/src/stats.rs
Rework lowlatency mode introducing the concept of task's "latency weight".
The latency weight is a dynamic priority, evaluated in function of the task's static weight and the average amount of voluntary context switches. When lowlatency mode is enabled tasks will use their latency weight to evaluate their vruntime and deadline, instead of their static weight.
The latency weight also determines the minimum vruntime for each tasks, enabling a natural priority boost to those that have a higher latency weight over those with a lower latency weight. This makes the classification of "interactive" and "regular" tasks unnecessary, and we can use a single global DSQ to dispatch all tasks when latency mode is enabled.
The new `--lowlatency` mode gives a better level of performance predictability, …
=> scx_bpfland: rework lowlatency mode

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/lock.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c, scripts/dsq_lat.bt
reset_lock_futex_boost() should be called every context switch of a
task. Otherwise, in the worst case, a task and that CPU could block
the preemption. To avoid such a situation, add missing
reset_lock_futex_boost() calls.
=> scx_lavd: add missing reset_lock_futex_boost()

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
Currently we have an approximation of LayerKind in the BPF code with `open` on
the layer, but it is difficult/impossible to tell the difference between an
Open and a Grouped layer. Add a `kind` field to the BPF `layer` and plumb
through an enum from the Rust side.
=> layered: bpf: add layer kind to layer

scheds/rust/scx_layered/src/bpf/main.bpf.c
scx_layered: fix exit_task ctx lookup err
when exit_task is called with the cancelled arg, tasks have not been run on sched_ext, so task_ctx may not exist.
do not attempt hard failing lookup when this occurs, just return.
=> scx_layered: fix exit_task ctx lookup err

scheds/include/scx/common.bpf.h
fix ci errors due to __str update in kfunc signature
per the following doc on verifier annotations:
https://www.kernel.org/doc/html/next/bpf/kfuncs.html#str-annotation
the argument to fmt__str needs to be const now.
=> fix ci errors due to __str update in kfunc signature

meson-scripts/stress_tests.ini, meson-scripts/test_sched
Always run schedulers in verbose mode to be able to catch the details of potential BPF failures.
=> ci: enable verbose mode when testing schedulers

.github/workflows/sched-ext.config
Enabling SCHED_MC in the kernel used for testing allows us to potentially run more complext tests, simulating different CPU topologies and have access to such topology data through the in-kernel scheduler's information.
This can be useful as we add more topology awareness logic to the sched_ext core (e.g., in the built-in idle CPU selection policy).
Therefore add this option to the default .config (and also fix a missing newline at the end of the file).
=> ci: enable SCHED_MC in the virtme-ng kernel config

scheds/include/scx/common.bpf.h
This reverts commit 29918c03c8293426ae4f9f5019cf8c0ef1e3e5c1.
This breaks compatibility in a way that's difficult to work around. The counterpart kernel changes have been reverted. Let's revisit this later.
=> Revert "fix ci errors due to __str update in kfunc signature"

Cargo.lock, rust/scx_loader/Cargo.toml, rust/scx_loader/configuration.md, rust/scx_loader/src/config.rs, rust/scx_loader/src/main.rs
Introduce configuration to specify scx flags for modes, and "pre-launch" scx scheduler with scx_loader launch (e.g on boot). potentially replacing `scx.service`. 
Also follow change of default flags as per https://github.com/CachyOS/kernel-manager/pull/23/
=> scx_loader: introduce configuration

meson.build
The new version of meson displays the following warnings:
```
The Meson build system
Version: 1.6.0
Source dir: /home/lucjan/Pobrane/scx-scheds/src/scx
Build dir: /home/lucjan/Pobrane/scx-scheds/src/scx/build
Build type: native build
WARNING: Project does not target a minimum version but uses feature introduced in '1.1': meson.options file. Use meson_options.txt instead
Project name: sched_ext schedulers
Project version: 1.0.5
C compiler for the host machine: cc (gcc 14.2.1 "cc (GCC) 14.2.1 20240910")
C linker for the host machine: cc ld.bfd 2.43.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program clang found: YES (/usr/bin/clang)
Program /home/lucjan/Pobrane/scx-scheds/src/scx/meson-scripts/veristat found: YES (/home/lucjan/Pobrane/scx-scheds/src/scx/meson-scripts/veristat) …
```
=> Set minimal meson version to silent new warnings

.github/workflows/caching-build.yml
add retries to kernel clone step
odds are that like, when we most care about cloning a fresh upstream (i.e. some fix was just pushed), things are going to be flakiest (i.e. no caches anywhere), so retry 10 times with ~3 minutes total between all tries when trying to clone kernel sources.
this only adds retries to the job that will block all merge queue jobs (i.e. tests) if it fails (to be polite to upstream servers etc.).
deleted caches to confirm that cloning still works here:
https://github.com/likewhatevs/scx/actions/runs/11490045108/job/31980248511
=> add retries to kernel clone step

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/bpf/timer.bpf.c, scheds/rust/scx_layered/src/bpf/timer.bpf.h
Add a forward declaration to be more kind to tools and fix int->u64 casting.
=> scx_layered: Fix declarations in timer

scheds/include/.gitignore, scheds/include/scx/common.bpf.h, scheds/include/scx/user_exit_info.h, scheds/include/vmlinux.h, scheds/rust/scx_layered/src/bpf/timer.bpf.c, scheds/rust/scx_layered/src/bpf/timer.bpf.h
Fix lsp to work after multiarch support
I think this is a good way to enable lsp etc. to keep working with multiarch support.
If someone is working on arm and wants lsp etc. to work, they'll can overwrite the symlink to the right one for their arch (and that override is gitignored/the default is what will work best for most folks).
=> fix lsp to work after multiarch support

scheds/rust/scx_layered/src/bpf/timer.bpf.c
Some of the new timer code doesn't verify on older kernels like 6.9. Modify the
code a little to get it verifying again.
Also applies some small fixes to the logic. Error handling was a little off
before and we were using the wrong key in lookups.
Test plan:
- CI
=> layered/timers: support verifying on older kernels and fix logic

.github/workflows/sched-ext.config
Set CONFIG_PROVE_LOCKING=y in the defalut virtme-ng config, to enable lockdep and additional lock debugging features, which can help catch lock-related kernel issues in advance.
=> ci: enable lockdep in the virtme-ng kernel config

scheds/rust/scx_layered/src/bpf/cost.bpf.c, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/bpf/timer.bpf.h
Add cost accounting for layers to make weights work on the BPF side. This is done at both the CPU level as well as globally. When a CPU runs out of budget it acquires budget from the global context. If a layer runs out of global budgets then all budgets are reset. Weight handling is done by iterating over layers by their available budget. Layers budgets are proportional to their weights.
There's still some issues to maybe make the budget updates to not have races, but it seems to work ok for now.
Simple two layer config:
```
[{
"name":"hodgesd",
"comment":"hodgesd user",
"matches":[
[{"UIDEquals":224791}]
],
"kind": {
"Open":{
"slice_us": 1000,
"preempt_first": false,
"exclusive": false,
"weight": 100
}
}
},{
"name":"rest",
"comment":"da rest",
"matches":[[]],
"kind": { …
```
=> scx_layered: Add cost accounting

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c
This PR includes two optimizations for preemption:
- Yield for preemption only when a task is ineligible. Since the greedy ratio is an important factor in determining virtual deadlines, an eligible task is unlikely to become a victim. So test the preemtability only when a task is ineligible.
- Kick CPU explicitly at the ops.enqueue() path. The sched_ext core does not call resched_curr() at the ops.enqueue() path, so resetting the task's time slice to zero does not trigger *immediate* preemption. The preemption will occur in the next ops.tick(). Instead, we explicitly kick the CPU even when the current CPU is a victim of immediate preemption.
This PR addresses https://github.com/sched-ext/scx/issues/849 .
=> scx_lavd: optimize preemption 

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c
This PR includes various tuning and optimization in calculating latency criticality. 
* calculate task's latency criticality in the direct dispatch path (addressed https://github.com/sched-ext/scx/issues/856)
* move reset_lock_futex_boost() to ops.running()
* boost task's latency criticality when pinned to a single CPU
=> scx_lavd: tuning and optimizing latency criticality calculation

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Add the layer name to the bpf representation of a layer. When printing debug output print the layer name as well as the layer index.
Example output from trace:
```
[061] ....1 5946587.990977: bpf_trace_printk: CFG: Dumping configuration, nr_online_cpus=80 smt_enabled=1 little_cores=0
<...>-995151  [061] ....1 5946587.990979: bpf_trace_printk: CFG LAYER[0][hodgesd] min_exec_ns=0 open=1 preempt=0 exclusive=0
<...>-995151  [061] ....1 5946587.990980: bpf_trace_printk: CFG   OR[00]
<...>-995151  [061] ....1 5946587.990981: bpf_trace_printk: CFG     AND[00]: USER_ID 224791
<...>-995151  [061] ....1 5946587.990983: bpf_trace_printk: CFG LAYER[1][stress-ng] min_exec_ns=0 open=1 preempt=0 exclusive=0
<...>-995151  [061] ....1 5946587.990983: bpf_trace_printk: CFG   OR[00]
<...>-995151  [061] …
```
=> scx_layered: Add layer name to bpf

scheds/rust/scx_lavd/src/bpf/main.bpf.c
The type of `taskc` within `lavd_dispatch()` was `struct task_struct *`, while it should be `struct task_ctx *`.
=> scx_lavd: Correct the type of taskc within lavd_dispatch()

scheds/rust/scx_lavd/src/bpf/util.bpf.c, scheds/rust/scx_lavd/src/main.rs
Fix "infomation" to "information"
=> scx_lavd: Fix typos

scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/main.rs
This PR contains the following misc optimizations:
* optimize consume_starving_task(): instead of looping until the theoretical maximum DSQs, looping until the actual max number of DSQs
* create DSQs on their associated NUMA nodes (addressed https://github.com/sched-ext/scx/issues/860)
Besides these two optimizations, it also contains a fix for a warning.
=> scx_lavd: optimize ops.dispatch() and DSQ placement

scheds/rust/scx_layered/src/bpf/cost.bpf.c, scheds/rust/scx_layered/src/bpf/main.bpf.c
Flip the order of layer id vs layer name so that the output makes sense. 
Example dump output:
```
LO_FALLBACK nr_queued=0 -0ms
COST GLOBAL[0][random] budget=22000000000 capacity=22000000000 COST GLOBAL[1][hodgesd] budget=0 capacity=0
COST GLOBAL[2][stress-ng] budget=0 capacity=0
COST GLOBAL[3][normal] budget=0 capacity=0
COST CPU[0][0][random] budget=62500000000000 capacity=62500000000000 COST CPU[0][1][random] budget=100000000000000 capacity=100000000000000 COST CPU[0][2][random] budget=124911500964411 capacity=125000000000000
```
init output:
```
x_layered-420826  [056] ....1  3433.008067: bpf_trace_printk: COST CPU[62][3][normal] budget 320000000000000
scx_layered-420826  [056] ....1  3433.008067: bpf_trace_printk: COST CPU[63][3][normal] budget 320000000000000
scx_layered-420826 …
```
=> scx_layered: Fix dump output format

scheds/rust/scx_layered/src/bpf/cost.bpf.c, scheds/rust/scx_layered/src/bpf/main.bpf.c
Fallback DSQs are not accounted with costs. If a layer is saturating the machine it is possible to not consume from the fallback DSQ and stall the task. This introduces and additional consumption from the fallback DSQ when a layer runs out of budget. In addition, tasks that use partial CPU affinities should be placed into the fallback DSQ. This change was tested with stress-ng --cacheline `nproc` for several minutes without causing stalls (which would stall on main).
=> scx_layered: Add additional drain to fallback DSQs

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_bpfland/src/stats.rs
Nothing significant, just minor cleanups / restyling and a small fix to restore the old max nvcsw limit that was incorrectly changed during the lowlatency mode refactoring.
=> scx_bpfland: minor cleanups

scheds/rust/scx_lavd/src/bpf/lock.bpf.c, scheds/rust/scx_lavd/src/main.rs
Revised the lock tracking code, relying on stable symbols with various kernel configurations. There are two changes:
- Entirely drop tracing rt_mutex, which can be on and off with kconfig
- Replace mutex_lock() families to __mutex_lock(), which is stable across kernel configs. The downside of such a change is it is now possible to trace the lock fast path, so lock tracing is a bit less accurate. But let's live with it for now until a better solution is found.
=> scx_lavd: fix CI error for missing kernel symbols

scheds/rust/scx_layered/src/bpf/main.bpf.c
Refactor cost struct usage so that it always is used as `costc` for clarity.
=> scx_layered: Refactor cost naming

services/scx
As the option of dropping lowlatency in bpfland is being considered, and to ensure the greatest performance, it would be a good idea to use the following flags in ``/etc/default/scx``
Source: https://github.com/CachyOS/kernel-manager/commit/9b4a3fdda18911188df9a8469d561963585cde3a
=> scx: sync default flags with CachyOS Kernel Manager

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
The ```struct layer``` that represents each ```scx_layered``` layer includes both an enum ```kind``` that represents whether the layer is open, grouped or confined, and a boolean ```open``` that represents whether the layer can expand past its current CPU mask. Whether the ```open``` variable is set depends completely on its kind, so the variable is not necessary. Remove it and update checks that use it to directly use ```kind``` instead.
=> scx_layered: remove ->open from layer struct

scheds/rust/scx_layered/src/bpf/cost.bpf.c
During ```initialize_budgets()``` the ```costc``` pointer is used to initialize the global and local cost structs with the layer weights. However, the code only initializes the global cost struct for the first loop, after which the ```costc``` pointer points to a local cost struct instead. Initialize ```costc``` on every loop to point to the global cost struct and initialize all of its weights.
=> scx_layered: point costc to global struct when initializing budgets

scheds/rust/scx_rusty/src/load_balance.rs
The PR includes 2 main fixes
Inside the function `try_find_move_task()`, it returns directly when there's no task found to be moved. If the cause is from lack of ability to fulfilled the condition by `task_filter()`, load balancer will try to find move task again and remove `task_filter()` by setting it directly to a function returns true.
However, in the fallback case, the tasks within the domains will be empty. Swap the tasks back into domains vector before returning can solve the issue.
The logic for task filtering was
```
task.dom_mask & (1 << pull_dom_id) != 0
&& !(self.skip_kworkers && task.is_kworker)
&& !task.migrated.get()
```
Which might cause the tasks already be migrated to be migrate again. Causing warnings like belows
```
slice=20000us
direct_greedy_cpus=ffff …
```
=> scx_rusty: Restore push domain tasks when no task found

scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c
Two changes are incorporated to fix the performance regression in `perf bench -f simple sched messaging`.
- Avoid self-IPI at preemption: sending a self-IPI can trigger immediate preemption but it imposes prohibitive overhead in some workloads. So let's go back to the old way, resetting task's time slice to zero.
- 
- Deprioritize a long runtime by prioritizing frequencies further: directly using runtime gives too much penalty so penalize the long runtime task indirectly by prioritizing frequencies.
=> scx_lavd: fix a performance regression bug (`perf bench -f simple sched messaging`)

scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c
Two (significant) related commits here:
1) refactor enqueue() so it works on !wakeup (where tasks bypass select_cpu)
2) Fix the synchronization to actually ensure enqueue() has been invoked with some RCU-like pattern.
=> Refactor select_cpu + enqueue for proper synchronization and handle of !wakeup

.github/workflows/bpf-next-test.yml, .github/workflows/caching-build.yml, .github/workflows/sched-ext.config
add CONFIG_IKCONFIG to ci Kconfig to enable CONFIG_IKCONFIG_PROC and bump cache ver so new kernels are build for CI with this.
=> add CONFIG_IKCONFIG to ci Kconfig and bump cache ver

scheds/rust/scx_layered/src/bpf/cost.bpf.c, scheds/rust/scx_layered/src/bpf/cost.bpf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c
Add fallback DSQ cost accounting so that fallback DSQ costs are accounted for and so that dispatch of fallback DSQs can be done in a standardized way.
Signed-off-by: Daniel Hodges <hodges.daniel.scott@gmail.com>
=> scx_layered: Add fallback DSQ cost accounting

scheds/rust/scx_layered/src/bpf/cost.bpf.c
```
$ cargo build --release && sudo ./target/release/scx_layered  --run-example -vvv
14:44:59 [DEBUG] layer: batch algo: Sticky core order: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
14:44:59 [DEBUG] layer: immediate algo: Sticky core order: [36, 37, 38, 39, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
14:44:59 [DEBUG] layer: stress-ng algo: Topo core order: [33, 5, 36, 14, 31, 18, 24, 12, 35, 9, 39, 16, 30, 2, 32, 8, 38, 13, 22, 15, 23, 6, 25, 11, 27, 10, 28, 17, 20, 3, 37, 7, 26, 4, 21, 1, 34, 19, 29, 0]
14:44:59 [DEBUG] layer: normal algo: Linear core order: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, …
```
=> scx_layered: Fix verifier issue when tracing

rust/scx_loader/src/config.rs
With the recent rework of scx_bpfland the default options for the different profiles in scx_loader are not valid anymore.
Update them with some appropriate options.
=> scx_loader: tune scx_bpfland default options

scheds/rust/scx_layered/src/bpf/cost.bpf.c
On some older kernels layered fails to validate. Prevent certain helpers from being inlined to pass the verifier.
=> scx_layered: Fix verifier issue on older kernels

scheds/rust/scx_layered/src/bpf/main.bpf.c
Cleanup remaining cpumasks to use `cast_mask`.
=> scx_layered: Cleanup cpumask

.gitignore, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/stats.rs
Fixed some typos in the comments and stats message of scx_lavd.
=> scx_lavd: docs: fix typos

.github/workflows/caching-build.yml, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/bpf/timer.bpf.h, scheds/rust/scx_layered/src/main.rs
This PR adds a timer to layered that will, once per second, replace dispatch logic with logic to check all DSQs for tasks which have not been ran within the past 5 seconds.
When this check finds such a task, dispatch consumes that DSQ.
This is continued for all runs of dispatch until there are no such tasks.
This makes `stress-ng -c 80 -M --affinity 80 -t 60` (which reproduces stalls on my machine on main) not reproduce stalls.
The configs used were:
```
❯ cat repos/layered-config.json 
[
{
"name":"patso",
"comment":"patso user",
"matches":[
[{"UIDEquals":1000}]
],
"kind": {
"Open":{
"slice_us": 1000,
"preempt_first": false,
"exclusive": false,
"weight": 100
}
}
},{
"name":"stress-ng",
"comment":"stress-ng slice",
"matches":[
[
{"CommPrefix":"stress-ng"}
],[ …
```
=> scx_layered: add timer antistall

scheds/rust/scx_layered/src/bpf/cost.bpf.c, scheds/rust/scx_layered/src/bpf/main.bpf.c
Fix bug is consume_non_open where it improperly returns 0 when the DSQ is not consumed due to the layer mask not being found.
=> scx_layered: Fix error in dispatch consumption

scheds/rust/scx_layered/src/bpf/main.bpf.c
Add a helper for returning the appropriate slice duration for a layer and replace a various instances where the slice value was being recalculated.
=> scx_layered: Add helper for layer slice duration

scheds/rust/scx_layered/src/bpf/main.bpf.c
Fix a small bug where incorrect per CPU costs were being dumped. The output format should now appropriately match the per-CPU costs. The following dump shows the correct format:
HI_FALLBACK[1024] nr_queued=46 -25755ms
HI_FALLBACK[1025] nr_queued=43 -25947ms
LO_FALLBACK nr_queued=0 -0ms
COST GLOBAL[0][random] budget=16791955959896739
capacity=16791955959896739
COST GLOBAL[1][hodgesd] budget=16791955959896739
capacity=16791955959896739
COST GLOBAL[2][stress-ng] budget=43243243243243243
capacity=43243243243243243
COST GLOBAL[3][normal] budget=33583911919793478
capacity=33583911919793478
COST FALLBACK[1024][0] budget=16791955959896739
capacity=16791955959896739
COST FALLBACK[1025][1] budget=16791955959896739
capacity=16791955959896739
COST CPU[0][0][random] budget=5405405405405405 …
=> scx_layered: Fix dump format

scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/lib.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
We duplicate the definition of most fields in every layer kind. This makes
reading the config harder than it needs to be, and turns every simple read of a
common field into a `match` statement that is largely redundant.
Utilise `#[serde(flatten)]` to embed a common struct into each of the LayerKind
variants. Rather than matching on the type this can be directly accessed with
`.kind.common()` and `.kind.common_mut()`. Alternatively, you can extend
existing matches to match out the common parts as demonstrated in this diff
where necessary.
There is some further code cleanup that can be done in the changed read sites,
but I wanted to make it clear that this change doesn't change behaviour, so
tried to make these changes in the least obtrusive way.
Drive-by: fix the formatting of the …
=> layered: split out common parts of LayerKind

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/stats.rs
- Fix layered treating all layers as preempting w/ `--local-llc-iterations`.
- `layered_select_cpu()` considered the waking CPU's llc/node as local instead of the wakee's previous CPU's. Fixed.
- Performance optimizations leading ~1.5% less cpu consumption while running saturating rd-hashd on ryzen 3900x.
- Stat output updates.
=> scx_layered: Perf improvements and a bug fix

scheds/rust/scx_layered/src/bpf/main.bpf.c
On 6.9 kernels the verifier is not able to track `struct bpf_cpumasks` properly on nested structs. Move the cpumasks from the `cached_cpus` struct back to the `task_ctx` struct so older versions of the verifier can pass.
=> scx_layered: Fix verifier issues on older kernels

rust/scx_utils/src/topology.rs, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
- Fix a couple bugs around layer -> DSQ ID mapping.
- Use fields cached in `cpu_ctx` instead of recalculating them repeatedly.
- Supply matching topology information when `--disable-topology` is specified so that it matches how the scheduler is going to behave. Reduce code branches.
=> scx_layered: Cleanups around topology handling

rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/lib.rs, rust/scx_utils/src/netdev.rs, scheds/rust/scx_layered/src/lib.rs, scheds/rust/scx_layered/src/main.rs
Add support for netdev IRQ balancing on available CPUs . This adds a module to the `scx_utils` crate that parses network devices and is able to update the associated IRQ affinity masks. This idea is was inspired from conversations with @danobi.
After running layered with the flag enabled IRQs from watching `/proc/interrupts` are balanced across available CPUs from the scheduler's perspective. This can be observed where the large number of interrupts were routed to single cores.
```
CPU0       CPU1       CPU2       CPU3       CPU4       CPU5       CPU6       CPU7       CPU8       CPU9       CPU10      CPU11
168:          0          0          0          0          0          0          0          0          0          0          1          0  PCI-MSIX-0000:56:00.0    0-edge      eth1
171: …
```
=> [RFC] scx_layered: Add netdev IRQ balancing

Cargo.lock, rust/scx_rustland_core/Cargo.toml, rust/scx_utils/Cargo.toml, scheds/rust/scx_bpfland/Cargo.toml, scheds/rust/scx_flash/Cargo.toml, scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_mitosis/Cargo.toml, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml, scheds/rust/scx_rusty/Cargo.toml
9bdccdd Merge pull request #943 from JakeHillion/pr943
b4b1879 Merge pull request #947 from sirlucjan/scx_loader_update
f2384fe scx_loader: update docs
198f079 Merge pull request #930 from hodgesds/topo-irq
41781fe scx_layered: Add netdev IRQ balancing node support
e30e5d8 scx_utils: Add netdev support
8c09ae2 Merge pull request #942 from CachyOS/feat/loader-add-flash
c258199 replace goto with unrolled loop in antistall_set
d5d4f46 scx_loader: add scx_flash as supported scheduler
489ce8a Merge pull request #939 from sched-ext/htejun/layered-updates
dbcd233 scx_layered: Work around verification failure in antistall_set() on old kernels
61f378c Merge pull request #931 from multics69/lavd-osu
88c7d47 Merge pull request #934 from sched-ext/htejun/layered-updates
aec9e86 Merge branch 'main' …
=> scx_utils/scx_layered: bump to 1.0.7

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/introspec.bpf.c, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/lock.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
Reduce the size of struct task_ctx from 3 cache lines to 2 cache lines by dropping unnecessary fields and optimizing the struct layout.
=> scx_lavd: Optimize the layout of struct task_ctx

scheds/rust/scx_lavd/src/bpf/main.bpf.c
The scheduler does not rely on PID, so there is no reason to exclude handling exiting tasks and add SCX_OPS_ENQ_EXITING to the scheduler flag.
=> scx_lavd: Do not exclude exiting tasks

rust/scx_rustland_core/assets/bpf/main.bpf.c
Automatically wake up an idle CPU when the user-space scheduler selects it via BpfScheduler->select_cpu().
This helps to speed up the enqueue->user-space->dispatch pipeline, particuarly after the pick_next_task() rework in kernel 6.12 and later.
This seems to address issue #788.
=> scx_rustland_core: proactively wake up CPUs when selected by user space

INSTALL.md
Currently, if you try to open the installation instructions for Gentoo from the README, it just opens the top of the INSTALL.md file, since the link is incorrect. This simple pull request fixes that.
=> docs: Fix link to Gentoo installation instructions

rust/scx_utils/src/clang_info.rs
This commit fixes the following error when building for ppc64le arch:
```
[   71s]   --- stderr
[   71s]   thread 'main' panicked at rust/scx_utils/src/builder.rs:42:51:
[   71s]   called `Result::unwrap()` on an `Err` value: CPU arch powerpc64le not found in ARCH_MAP
[   71s]   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> utils: add powerpc64le to arch map

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
The existing load calculation was incorrect. It could enter feedback loops where a layer which is using more CPU cycles keeps getting more CPUs and vice-versa regardless of their weights. Also, as the growth and shrinking decisions are made locally in each layer, they couldn't account for global competition state which is necessary to consider for weight based distribution.
Reimplement CPU allocation so that CPUs are distributed globally and layers are converged to the target state.
While at it, make a few misc changes including printing stats in config order and correctly accounting for layer CPU time.
=> scx_layered: Reimplement CPU allocation and some other fixes

scheds/rust/scx_rusty/src/bpf/main.bpf.c
Tested on 6.12-rc6 as well with various versions of clang 18.X
=> scx_rusty: Fix verifier errors on older kernels

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c
- Both `select_cpu[_no_topo]()` were broken. Each missing different idle CPU search steps. This is likely cause of some of the regressions seen with new versions. Fixed.
- There are no meaningful differences between `no_topo` and regular versions after dead code elimination. Drop the duplicate.
- Short-circuit `select_cpu()` when layers' CPUs are saturated. This saves ~0.6% cputime when running saturating `rd-hashd` on Ryzen 3900x.
=> scx_layered: select_cpu() fixes and updates

scheds/rust/scx_lavd/src/bpf/main.bpf.c
Even when a task is greedy, boost its time slice if the task fully consumes its time slice consecutively. That is okay since the greedy task will be handled by latency calculation and preemption anyway.
=> scx_lavd: Boost time slice more generously

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c
Move the performance criticality calculation to the ops.enqueue() path, where the performance criticality information is used. Also, skip the calculation if the processor architecture is not hybrid (i.e., no little core).
=> scx_lavd: Optimize performance criticality calculation

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/lock.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
Squeeze the size of cpuc_ctx by reducing some member sizes and reorganizing the structure layout to improve cache locality. Also,  drop less useful stat fields to optimize cache locality.
=> scx_lavd: Optimize the cpuc_ctx layout for cache friendliness

rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/topology.rs, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
`try_preempt()` is rather complex for doing something which isn't all that dynamic. Instead of doing the tiered trial dynamically, pre-compute the proximity order for each CPU and just try preemption following that order. This maintains or improves the behavior while significantly simplifying the code. It's no longer necessary to separate out `no_topo` variant afterwards. Drop it.
=> scx_layered: Reimplement `try_preempt()`

scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c
Optimize the preemption logic. Use p->scx.slice to control concurrent preemption instead of taskc->last_kick_clk as a micro optimization.
=> scx_lavd: Optimize preemption

scheds/rust/scx_layered/src/bpf/main.bpf.c
Fix verifier errors on big/little architectures where extra null checks are needed. Tested on 6.12-rc6 with clang 18.1.8.
=> scx_layered: Fix verifier errors on big/little

scheds/rust/scx_layered/src/bpf/cost.bpf.c, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
- Remove `disable_toplogy` special case from DSQ init path.
- Rename `cpu_ctx->layer_cycles` to `cpu_ctx->layer_usages`.
- Rename `idx` to `id` and other name related cleanups.
- `layer_id` type and uninit state cleanups.
- Fix `antistall_consume()` skipping incorrectly.
=> scx_layered: More cleanups and an antistall fix

scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
Add two command line options, --slice-max-us and --slice-min-us, to adjust task's maximum and minimum time slice values, respectively.
=> scx_lavd: add tunables for adjusting time slices

scheds/meson.build
Install scx headers to /usr/include/scx for easier packaging.
=> meson: Install scx header files

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
- Track owned/open execution times per layer and base layer growth decision on owned time only.
- Track per-LLC-layer number of scheduling events and running avg of queue latencies and report them. Will be used to modulate open executions.
- Fix the problem where a zeor sized layer couldn't grow due to core quantization in CPU free/alloc paths.
- Code cleanups.
- Bail early with a clear error message if node, LLC or core IDs are not consecutive. This should be fixed in the future.
=> scx_layered: Track owned/open execution times and per-LLC-layer stats

scheds/rust/scx_layered/src/layer_core_growth.rs, scheds/rust/scx_layered/src/lib.rs, scheds/rust/scx_layered/src/main.rs
Refactor layer growth order to be more sticky to cores by using the core growth order to shrink layers. Move layer core growth order creation to a separate helper that has context on all layers. This will be used in the future for more topology aware core growth.
Layers have a tendency to "walk" across cores when growing/shrinking which can lead to suboptimal layouts over time. Consider the following simple configuration for a machine with Big/Little cores:
```
[
{
"name": "powersave",
"comment": "powersave",
"matches": [[]],
"kind": {
"Confined": {
"util_range": [
0.4,
0.8
],
"slice_us": 800,
"growth_algo": "LittleBig",
"idle_smt": true,
"perf": 256,
"preempt_first": false,
"exclusive": false
}
}
}
]
```
When load is placed on the layer the growth should happen towards …
=> scx_layered: Refactor layer growth order

rust/scx_utils/src/topology.rs, scheds/rust/scx_layered/src/main.rs
On systems with multiple NUMA nodes core_ids can be reused. Add monotonically increasing fields `core_id`/`llc_id` to uniquely identify cores/llcs. This does not implement the problem in #981 however.
=> scx_utils: Add core_id/llc_id to topology as a unique identifiers

scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_flash/src/main.rs
Use llc_id instead of l3_id to build scheduling domain in scx_bpfland and scx_flash.
=> scheds: use llc id

scripts/freq_trace.bt
Add a bpftrace script for tracing frequency changes.
example output:
```
@avg_freq[154]: 1100000
@avg_freq[164]: 1100000
@avg_freq[115]: 1100000
@avg_freq[169]: 1100000
@avg_freq[9]: 1104761
@avg_freq[82]: 1110000
@avg_freq[37]: 1112500
@avg_freq[174]: 1125000
@freq_hist: 
[1000000, 1050000)     448 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ |
[1050000, 1100000)       0 |                                                    |
[1100000, 1150000)      35 |@@@@                                                |
[1150000, 1200000)       0 |                                                    |
[1200000, 1250000)     451 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
```
=> scripts: Add bpftrace script to trace CPU frequency

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/lock.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c
The scheduler extends the lock holder's time slice at ops.dispatch() to avoid preempting the lock holder, so slowing down the system-wide progress. However, this opens the possibility that the slice extension is abused by a lock holder. To mitigate the problem, check if a task's time slice is extended (lock_holder_xted) but the task is not lock holder. That means a task's time slice was extended, but it released the lock after that. In this case, give up the rest of the extended time slice of the task.
=> scx_lavd: Limit the slice extension of a lock holder

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Layer and LLC orderings are now determined by userspace and BPF uses two helpers to iterate over the combinations. The overhead is lower for both topo and no-topo cases. See the reimplement commit for details.
Remaining todos:
- Layer growth doesn't always work as expected likely due to owned execution accounting and protection issue.
- scx_layered process itself should be prioritized by queueing to hi fallback.
- Implement DSQ latency based in-layer execution protection so that latency sensitive workloads can be protected from preempt workloads.
- Integrate stickiness mechanism.
- Split on node boundaries.
=> scx_layered: Reimplement layered_dispatch()

scheds/rust/scx_bpfland/src/main.rs
Use BTreeMap to store cache_id_map so that prog can show L2/L3 cache info in ascending order, make it easy to lookup by human.
=> scx_bpfland: dump cache_id_map in ascending order

rust/scx_utils/Cargo.toml, rust/scx_utils/src/bpf_builder.rs, rust/scx_utils/src/builder.rs
`bindgen` version was previously fixed to `v0.68` and `v0.69` due to `v0.69` not being available on Fedora at the time.
This update removes support for `bindgen v0.68` and migrates to the new API, as Fedora now includes `v0.69`.
Closes #1001
=> scx_utils: remove use of deprecated bindgen API; require bindgen >=0.69

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
- Always put scx_layered userspace in hi fallback DSQ to guarantee timely execution of scheduler userspace code. This is required as reasonable forward progress depends on userspace code running. This assumes that scx_layered is running in the root PID namespace. It might be useful to add a warning when that's not the case - e.g. look up the task from the BPF side and verify that it actually is scx_layered.
- Owned execution protection had a couple bugs which could weaken protection and prevent a layer with high util growth bound from growing. Fix them. After this change, a saturating workload can reliably grow from empty under competition from preempting layers.
=> scx_layered: Prioritize sched userspace and fix owned execution protection

meson-scripts/get_sys_incls, rust/scx_utils/src/bpf_builder.rs
- Use single dollar sign instead of double since it is already single-quoted, so no need to escape.
- ~~Remove vmlinux.h in scheds/include that points to x86's. It overrides the vmlinux.h include in arch/*.~~
- Reorder include arguments so that scheds/include/vmlinux.h does not override arch/*/vmlinux.h.
Tested and built successfully on real RISC-V hardware after applying the patch.
=> Fix build on non-x86 architectures

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
Perform load balancing across compute domains (e.g., hybrid cores, CCX, or NUMA). The load balancing tries to make the average length of per-compute domain DSQ similar (+/- 12.5%). If not, an under-loaded domain (stealer) will steal a task from an over-loaded domain (stealee). To avoid a central hotspot, all the operations are done in a distributed and probabilistic manner.
=> scx_lavd: Load balancing across compute domains

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
24fba4ab8de9 ("scx_layered: Add idle smt layer configuration") added the idle_smt layer config but
- It flipped the default from preferring idle cores to not having preference.
- Misdocumented what it meant. It doesn't only pick idle cores. It tries to pick an idle core first and if that fails pick any idle CPU.
A follow-up commit 637fc3f6e136 ("scx_layered: Use layer idle_smt option") made it more confusing. If idle_smt is set, the idle core prioritizing logic is disabled.
The first commit disables idle core prioritization by overriding idle_smtmask to be idle_cpumask if idle_smt is *clear* and the second commit disables the same by disabling the code path when the flag is *set*. ie. Both options did exactly the same thing.
Recently, 75dd81e3e657 ("scx_layered: Improve topology aware …
=> scx_layered: Deprecate idle_smt layer config

Cargo.lock, scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_lavd/src/main.rs
Current implementation of `--autopower` reads `energy_performance_preference` to determine which power profile is active. IMO this is sub-optimal and does not play well with CPUs without EPP and alternative power management daemons like `tuned-ppd`. This PR implements a better method that fetching active power profile from the dbus interface [`net.hadess.PowerProfiles`](https://hadess.fedorapeople.org/power-profiles-daemon-docs/gdbus-net.hadess.PowerProfiles.html), which is exposed by `power-profiles-daemon` and `tuned-ppd`. (There is a standardized interface [`org.freedesktop.UPower.PowerProfiles`](https://upower.pages.freedesktop.org/power-profiles-daemon/gdbus-org.freedesktop.UPower.PowerProfiles.html); unfortunately, it is currently not implemented by `tuned-ppd`.)
This is a RFC. …
=> [RFC] scx_lavd: Fetch active profile from power-profiles-daemon dbus interface when using autopower

scheds/include/arch/arm/vmlinux-v6.12-rc2-g5b7c893ed5ed.h, scheds/include/arch/arm64/vmlinux-v6.12-rc2-g5b7c893ed5ed.h, scheds/include/arch/mips/vmlinux-v6.12-rc2-g5b7c893ed5ed.h, scheds/include/arch/powerpc/vmlinux-v6.12-rc2-g5b7c893ed5ed.h, scheds/include/arch/riscv/vmlinux-v6.12-rc2-g5b7c893ed5ed.h, scheds/include/arch/s390/vmlinux-v6.12-rc2-g5b7c893ed5ed.h
The size of CPU mask (struct cpumask) is defined as too small in all architectures (e.g., unsigned long * 4) except for x86. It triggers a verifier error in lavd (e.g., arm64), so increase its size to the same as x86. The changes were tested on an arm64 platform.
This solves the following issues (on arm64).
https://github.com/sched-ext/scx/issues/810
=> vmlinux: Increase cpumask size in vmlinux.h for all arch

meson-scripts/build_libbpf
This enables sccache to work with meson builds (it already works w/ cargo).
sccache and ccache make working on scx nicer (i.e. lsp works immediately, nice iteration time, etc.), it works so well i kinda recommend folks use it tbh.
tested a couple times w/ local meson test script:
```
❯ cat local-e2e.sh 
#!/bin/bash
set -euxo pipefail
REPOS=$HOME/repos
SCX=scx
KERNEL=sched-ext-linux
SCHED="$1"
cd $REPOS/$KERNEL
vng -v --build --pwd $REPOS/$KERNEL --config "$REPOS/$SCX/.github/workflows/sched-ext.config"
cd $REPOS/$SCX
BUILDDIR=../../../../tmp/scxbuild/
rm -rf /tmp/scxbuild
mkdir -p $BUILDDIR
meson setup -Dkernel=$REPOS/$KERNEL -Dkernel_headers=$REPOS/$KERNEL/usr/include -Denable_stress=true $BUILDDIR $REPOS/$SCX -Dbuild_outside_src=true
meson compile -C $BUILDDIR "$SCHED"
#meson compile -C …
```
=> scx: enable using sccache

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c
On multi-LLC machines, a layer uses one DSQ per LLC; however, the DSQs all
share one per-layer vtime_now. Cacheline contention aside, this makes
vtime_now progression erratic as a single DSQ executing can easily progress
the per-layer vtime_now past the heads of other DSQs which in turn can
collapse vtime based ordering in other DSQs.
Make vtime_now per DSQ and translate between vtimelines when a tasks jumps
between LLCs. In rd-hashd CPU saturation scenario on ryzen 3900x, this
reduces the gap from EEVDF from >10% to ~5%.
=> scx_layered: Make vtime_now per-LLC

scheds/include/scx/common.bpf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c
Add scx_bpf_dump_header helper to dump common system information which can be used during scheduler dumping to provide a standard set of debugging information. This implements #1009.
Tested with patch:
```
diff --git a/scheds/rust/scx_layered/src/bpf/main.bpf.c b/scheds/rust/scx_layered/src/bpf/main.bpf.c
index c8c1dad..04e6a36 100644
--- a/scheds/rust/scx_layered/src/bpf/main.bpf.c
+++ b/scheds/rust/scx_layered/src/bpf/main.bpf.c
@@ -993,20 +993,21 @@ void BPF_STRUCT_OPS(layered_enqueue, struct task_struct *p, u64 enq_flags)
struct cpu_ctx *cpuc, *task_cpuc;
struct task_ctx *taskc;
struct llc_ctx *llcc;
struct layer *layer;
s32 task_cpu = scx_bpf_task_cpu(p);
u64 vtime = p->scx.dsq_vtime;
u32 layer_id;
bool try_preempt_first;
u64 queued_runtime;
u64 *lstats;
+       scx_bpf_error("oh …
```
=> scx: Add scx_bpf_dump_header helper

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/lib.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
Now that per-DSQ queued runtimes are tracked, we can modulate cross-LLC
migrations based on them. Add a per-layer config option to skip cross-LLC
migrations if the queued runtime is below the configured value. Default to
100us which should be a safe value in most cases.
=> scx_layered: Implement layer config xllc_mig_min_us

.github/workflows/caching-build.yml
fix ci document generation job (i broke it when setting rust version to stable).
works here: https://github.com/likewhatevs/scx/actions/runs/12149452075/job/33880144230
=> override rust version used for document generation

rust/scx_utils/src/topology.rs, scheds/rust/scx_lavd/src/main.rs
Snapdragon X Elite processor has an unusual CPU and cache topologies. It does not have an L3 cache, and a CPU cluster with four CPUs shares the same L2 cache -- so the L2 cache is the LLC. Moreover,  CPUs in a single core span across multiple L2 domains. Lastly, the sysfs does not exports an cache id file. Specifically, it has the following topology from the scx's point of view:
```
LLC0 - core 0 - cpu 0
\ core 1 - cpu 1
\ core 2 - cpu 2
\ core 3 - cpu 3
LLC1 - core 0 - cpu 4
\ core 1 - cpu 5
\ core 2 - cpu 6
\ core 3 - cpu 7
LLC2 - core 0 - cpu 8
\ core 1 - cpu 9
\ core 2 - cpu 10
\ core 3 - cpu 11
```
To support the above architecture, changed three things:
- When there is no L3 cache, use L2 cache ID as LLC ID.
- When there is no cache id file under sysfs, assign an id based on …
=> scx_utils: Extend topology to support Snapdragon X Elite

scheds/rust/scx_rusty/src/bpf/main.bpf.c
Within `task_set_preferred_mempolicy_dom_mask()`, it tries to access the nodemask of the task directly. BPF verifier might not allow it under all situation.
Use BPF_CORE_READ() macro to let libbpf handle CO-RE relocate to make sure it can pass the verifier.
=> scx_rusty: Refactor access operation of nodemask

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c
When a CPU is released to serve a higher-priority scheduler class, reset per-CPU preemption information of that CPU so not choose the CPU as a victim by mistake. This solves the issue https://github.com/sched-ext/scx/issues/1039
=> scx_lavd: Reset per-CPU preemption information when a CPU is released

scheds/rust/scx_layered/src/bpf/main.bpf.c
Fix:
- vtime could go wildly wrong.
- queue_runtime tracking was broken for LLC IDs >= 16  because MAX_LAYERS was incorrectly used as the invalid value instead of MAX_LLCS.
=> scx_layered: Fix vtime and llc_id handling bugs

scheds/rust/scx_layered/src/bpf/main.bpf.c
When creating an llc mask for a node by iterating all cpus, OR llc_mask with the new value instead of AND'ing it.
=> scx: fix bug in llc mask creation

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
Fix buid warning by removing unnecessary cast_mask().
=> scx_bpfland: fix build warning

lib/include/lib/sdt_task.h, lib/meson.build, lib/sdt_task.bpf.c, meson-scripts/bpftool_build_skel, meson-scripts/compile_scx_lib, meson.build, scheds/c/meson.build, scheds/c/scx_nest.bpf.c, scheds/c/scx_sdt.bpf.c, scheds/c/scx_sdt.c, scheds/include/lib, scheds/include/scx/common.bpf.h, scheds/include/scx/common.h, scheds/meson.build
Add to the build system the option to link a common library of BPF functions into a scheduler. This patch includes the arena-based allocator as the first component of this common library, and will automatically add into the library any code added inside the lib/ directory.
=> introduce common BPF library for C schedulers

meson-scripts/bpftool_build_skel
The build system currently tries to create a skeleton file out of the library,  which fails and subsequently causes unrelated tests to fail. Change Meson to only create a skeleton out of scheduler object files.
=> skip skeleton creation for library

lib/include/lib/sdt_task.h, lib/sdt_task.bpf.c
The arena allocation code compiles and verifies fine for LLVM <= 18, but fails for LLVM 19 (#1051). Update the code to work for LLVM 19.
=> update the arena allocator to work with LLVM 19

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
- Fix a silly bug critical bug in `select_cpu()`.
- Fix layer sizing when weights are not specified.
- Implement per-layer fifo mode.
=> scx_layered: Fix a silly bug in `select_cpu()` and implement per-layer fifo mode

scripts/vtime_dist.bt
Refactor the vtime_dist script to show the distribution in the change of vtime rather than the histogram of the vtime. The histogram of the vtime is not really that useful as it should continuously be increasing. Attach to the `scx_bpf_dsq_insert_vtime` kprobe event rather than on `sched_wakeup`. Support filtering by DSQ with a script parameter and include the slice interval average and distribution to the output.
Example `scx_rusty` filtering DSQ 1:
```
$ sudo ./vtime_dist.bt 0 1
-----------------------------------
@dsq_vtime[1]: 
(..., 0)             437 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
[0]                    1 |                                                    |
[1]                    0 |                                                    |
[2, 4) …
```
=> scripts: Refactor vtime_dist script

scheds/rust/scx_layered/src/bpf/main.bpf.c
It used to be that open or grouped layers are always executed from all CPUs and thus tasks with custom CPU affinities could be queued in the layer DSQs without causing stalls. However, this is no longer true as a saturated layer can close off its CPUs for open execution.
For now, work around by putting all tasks with custom affinities into hi fallback DSQs. Down the line, we should implement starvation prevention for lo fallback DSQs and put these tasks there.
=> scx_layered: Put all tasks with custom affinities into the hi fallbak DSQs

scripts/slicesnoop.bt
Add slicesnoop.bt bpftrace script that allows the introspection of slice durations aggregated by DSQs.
Example of `scx_layered` tracing the distribution of high fallback dsq (1024) slice duration:
```
$ sudo ./slicesnoop.bt 0 1024
@dsq_slice[1024]: 
[512K, 1M)           528 |@@@@@@@@@@@@@                                       |
[1M, 2M)               0 |                                                    |
[2M, 4M)               0 |                                                    |
[4M, 8M)               0 |                                                    |
[8M, 16M)              0 |                                                    |
[16M, 32M)          2051 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
@dsq_slice_avg[1024]: 16069174
```
=> scripts: Add slicesnoop script

scripts/dsq_lat.bt
Refactor the dsq_lat.bt script to be more precise with accounting for DSQ latencies by timestamping when a task is put onto a DSQ. Track the DSQ that the task was dispatched onto in a separate BPF map. Add support for filtering by DSQ.
Example with `scx_layered`:
```
@dsq_hist_usec[4]: 
[4, 8)               195 |                                                    |
[8, 16)            10438 |@@@@@                                               |
[16, 32)            7056 |@@@                                                 |
[32, 64)            3010 |@                                                   |
[64, 128)            699 |                                                    |
[128, 256)           381 |                                                    |
[256, 512)           153 | …
```
=> scx_layered: Refactor dsq_lat script

scheds/rust/scx_bpfland/src/main.rs
Relying on scx_utils::autopower reuires power-profiles-daemon running, this has introduced a regression in certain systems that don't have this service available.
Restore the old behavior for now, we will fix scx_utils::autopower later.
Fixes: 939d4f5 ("scx_utils: move autopower into scx_utils")
=> scx_bpfland: do not rely on scx_utils::autopower

.github/workflows/stable.yml
scx: add ci job to test rolling stable
this should run every 4 hours
will merge once I see this run on my fork, should just work (err well just fail because I think this is broke atm).
@ptr1337
=> scx: add ci job to test rolling stable

rustfmt.toml
I think this fixes #1065
It looks like the issue is without a rustfmt.toml in every package dir, builds in arch's build system will try to read a format config file in HOME, causing a permission denied errors. IIUC, this should avoid that.
I also added a comment to the noop rustfmt.toml files so we know why they're there in the future.
=> scx: add rustfmt.toml files to avoid lookup to $HOME/.rustfmt.toml

INSTALL.md
The Ubuntu kernel team is now maintaining a kernel >= 6.12 in the linux-unstable ppa, so we don't have to maintain a custom ppa anymore to provide a sched_ext kernel.
Update the installation notes to reference the linux-unstable kernel. Once 25.04 is released and linux-unstable becomes the official stock kernel, we can remove the section about installing the linux-unstable kernel.
=> docs: Update installation notes for Ubuntu

meson-scripts/compile_scx_lib, meson.build
This PR introduces a dependency on scx_lib in gen_bpf_o.
Without this dependency the build fails intermittently with the
following error:
```
FAILED: scheds/c/scx_pair.p/scx_pair.bpf.skel.h scheds/c/scx_pair.p/scx_pair.bpf.subskel.h
/home/frelon/src/scx/meson-scripts/bpftool_build_skel /usr/sbin/bpftool scheds/c/scx_pair.p/scx_pair.bpf.o scheds/c/scx_pair.p/scx_pair.bpf.skel.h scheds/c/scx_pair.p/scx_pair.bpf.subskel.h /home/frelon/src/scx/build/lib/lib
libbpf: failed to get ELF header for /home/frelon/src/scx/build/lib/lib.bpf.o: invalid `Elf' handle
/home/frelon/src/scx/meson-scripts/bpftool_build_skel: line 25: 3400506 Segmentation fault      (core dumped) "$bpftool" gen object "$stem".l1o "$input" "$lib".bpf.o
```
Also updates a usage of bpftool to use the passed in path.
=> meson: Add scx_lib dep to gen_bpf_o

lib/meson.build, meson-scripts/compile_scx_lib
Make sure to use the right bpftool when building scx_lib, instead of always relying on the system's bpftool.
Fixes: 3d72a8e ("add library infrastructure and turn allocator into a library")
=> scx_lib: use the proper bpftool

scheds/rust/scx_layered/src/main.rs
The variable `nr_to_free` in `scx_layered/src/main.rs` is assigned an incorrect value due to a subtraction overflow, as reported in this issue #1072.
Ensure `nr_to_free` is correctly handled to prevent subtraction overflow, adding a check to set `nr_to_free` to 0 if `nr_freed` > `nr_to_free`.
=> scx_layered: handle nr_to_free calculation

scripts/scxtop.bt
Add a top like script for schedulers using bpftrace. This can be rewritten in bpf/rust in the future to be a more useful tool.
Output:
Help menu (`h` key), which also shows the state of the options:
Toggle off CPU chart with `c`:
When a scheduler is not running a default messages appears:
This is mostly a proof of concept of what kind of tools could be built as this is really pushing the limits of `bpftrace`.
***Note***, this requires a really recent build of `bpftrace` that has the `has_key` support. The formatting may not scale well to machines with high CPU counts and is buggy in some places.
=> scripts: Add scxtop

scripts/dsq_lat.bt
- Fix to ensure that we can track dsq id 0
- Cleans up some warnings
- Clean up some maps to avoid them printing out a bunch of output that was not really helpful
=> Fixes for dsq_lat.bt

rust/scx_loader/Cargo.toml, rust/scx_loader/src/config.rs, rust/scx_loader/src/dbus.rs, rust/scx_loader/src/lib.rs, rust/scx_loader/src/main.rs
provide library crate to be used by other crates, e.g CachyOS KernelManager
also provides Rust typed-interface for schedulers, with changed error for callers:
```
❯ dbus-send --system --print-reply --dest=org.scx.Loader /org/scx/Loader org.scx.Loader.SwitchScheduler string:scx_lvd uint32:2
Error org.freedesktop.zbus.Error: unknown variant `scx_lvd`, expected one of `scx_bpfland`, `scx_rusty`, `scx_lavd`, `scx_flash`
```
instead of
```
❯ dbus-send --system --print-reply --dest=org.scx.Loader /org/scx/Loader org.scx.Loader.SwitchScheduler string:scx_lvd uint32:2
Error org.freedesktop.DBus.Error.Failed: scx_lvd is not supported
```
=> scx_loader: provide library crate to be used by other crates

lib/meson.build, meson-scripts/bpftool_build_skel, meson.build, scheds/c/meson.build
Some scx users have bpftool versions < 7.5.0, causing Meson system to throw errors when linking in the BPF library to schedulers. Add a workaround by only compiling the library when the bpftool is new enough.
=> only compile library when using recent bpftool versions

lib/meson.build
Fix the source path for the library headers Meson is trying to install when compiling the ```lib``` target (thanks @sirlucjan for the report).
=> fix header install path for library

rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/lib.rs, rust/scx_utils/src/topology.rs, scheds/rust/scx_layered/src/lib.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs, scheds/rust/scx_rusty/src/domain.rs, scheds/rust/scx_rusty/src/main.rs, scheds/rust/scx_rusty/src/tuner.rs
Things got a bit messy over time e.g. with `TopologyMap` duplicating parts of `Topology` and `CpuPool` having a lot of `Topology` features. Let's clean them up. This shouldn't cause any behavior changes.
=> scx_layered, cpumask, topology: Cleanups

rust/scx_utils/src/cpumask.rs, scheds/rust/scx_layered/src/lib.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_rusty/src/domain.rs, scheds/rust/scx_rusty/src/main.rs, scheds/rust/scx_rusty/src/tuner.rs
No reason to consume the cpumask for iteration. Replace `.into_iter()` with `.iter()` and use it in layered.
=> cpumask, scx_layered: Clean up Cpumask iterator

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
A layer is served by per-LLC DSQs. Only tasks that can be serviced by all
CPUs in an LLC are put in the DSQ, so as long as a CPU is assigned to the
layer in the LLC, forward progress is guaranteed. However, if a layer-LLC
loses all its CPUs, there is no forward progress guarantee ignoring the
antistall mechanism. For a confined layer, no CPU will be visiting the empty
LLCs and even for a grouped or open layer, execution from an LLC without
CPUs assigned is lower priority than owned execution and can easily starve.
To resolve the problem, implement LLC draining mechanism. When layer-LLC
loses all CPUs with tasks in it, draining is turned on and other CPUs
assigned to the layer will alternate between their own execution and
draining LLCs without any CPU. The interlockings between the …
=> scx_layered: Implement empty LLC draining

INSTALL.md
scx-scheds and the 6.12 Kernel is now available in the official archlinux repository.
Therefore remove the instructions via the cachyos repository.
The only outstanding thing, is to get a proper unstripped vmlinux, which is used to debug sched-ext.
There is some ongoing [work](https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/merge_requests/3) to get this into the official archlinux repository.
=> Install: Rework Arch Linux section

scheds/rust/scx_layered/src/main.rs
Refactor proximity map iteration order to radiate based on distance from current cpu. Example output from initialization:
```
22:56:44 [DEBUG] CPU[77] proximity map[2/40/40/80]: [77, 37, 78, 39, 76, 38, 79, 36, 75, 35, 74, 34, 73, 33, 72, 32, 71, 31, 70, 30, 69, 29, 68, 28, 67, 27, 66, 26, 65, 25, 64, 24, 63, 23, 62, 22, 61, 21, 60, 20, 59, 19, 58, 18, 57, 17, 56, 16, 55, 15, 54, 14, 53, 13, 52, 12, 51, 11, 50, 10, 49, 9, 48, 8, 47, 7, 46, 6, 45, 5, 44, 4, 43, 3, 42, 2, 41, 1, 40, 0]
22:56:44 [DEBUG] CPU[78] proximity map[2/40/40/80]: [78, 38, 79, 39, 77, 37, 76, 36, 75, 35, 74, 34, 73, 33, 72, 32, 71, 31, 70, 30, 69, 29, 68, 28, 67, 27, 66, 26, 65, 25, 64, 24, 63, 23, 62, 22, 61, 21, 60, 20, 59, 19, 58, 18, 57, 17, 56, 16, 55, 15, 54, 14, 53, 13, 52, 12, 51, 11, 50, 10, 49, 9, 48, 8, 47, …
```
=> scx_layered: Refactor proximity map iteration

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
A set of improvements for scx_bpfland to enhance performance in server-oriented workloads.
When interactive task classification is disabled (`-c 0`), scx_bpfland can be suitable for more server-oriented scenarios, such as build servers. It can also serve as a "server profile" scheduler when used with tools like `cachyos-kernel-manager` in CachyOS.
With these changes and this "server profile" enabled, I'm able to speed up parallel kernel builds by ~2-3% (that seems to be consistent both AMD and Intel systems).
=> scx_bpfland: server workload improvements

scheds/rust/scx_layered/src/layer_core_growth.rs
Improve layer core growth algos to be aware of the number of layers. When applying layer core growth stategies offset core iteration order by a chunked layer offset. This makes `Linear`, `Reverse` and other growth algos more useful in that when multiple layers use the same growth strategy they will not longer attempt to grow using the same core order.
Example with changing the default `stress-ng` layer to `Sticky`:
=> scx_layered: Improve layer core growth algos

scheds/include/scx/namespace.bpf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Add an additional helper function to translate the scx_layered userspace tgid when running in a pid namespace.
Tested by running layered in a separate pid namespace:
```
$ cargo build --release && sudo unshare --mount-proc --fork -p ./target/release/scx_layered --run-example --stats 1 -vvv
```
Output from trace:
```
$ sudo bpftool prog trace | grep tgid
<...>-242372  [061] ....1 3574039.989305: bpf_trace_printk: CFG layered running with tgid: 242372
$ pidof scx_layered
242372
```
=> scx_layered: Make layered work in pid namespaces

rust/scx_loader/src/config.rs, rust/scx_loader/src/lib.rs, rust/scx_loader/src/main.rs
Into trait was calling the Into<&SupportedSched> which was calling Into<SupportedSched> and so on.
```
#0 0x622450e96149 in scx_loader::_$LT$impl$u20$core..convert..From$LT$scx_loader..SupportedSched$GT$$u20$for$u20$$RF$str$GT$::from::h13ba9d4271e33441 /tmp/scx/rust/scx_loader/src/lib.rs:60:9
#1 0x622450e91af3 in _$LT$T$u20$as$u20$core..convert..Into$LT$U$GT$$GT$::into::h9481856c4f80c765 /home/vl/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:759:9
#2 0x622450e9614a in scx_loader::_$LT$impl$u20$core..convert..From$LT$scx_loader..SupportedSched$GT$$u20$for$u20$$RF$str$GT$::from::h13ba9d4271e33441 /tmp/scx/rust/scx_loader/src/lib.rs:60:9
#3 0x622450e91af3 in _$LT$T$u20$as$u20$core..convert..Into$LT$U$GT$$GT$::into::h9481856c4f80c765 …
```
=> scx_loader: fix recursion of type convertion

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
Tested with config:
```
...
{
"name":"pid_ns",
"comment":"pid_ns",
"matches":[
[{"NSPIDEquals":[4026531836, 132449]}]
],
"kind": {
"Confined":{
"util_range": [0.25, 0.7],
"growth_algo": "Random",
"llcs": [1, 0],
"slice_us": 500,
"exclusive": false
}
}
},
...
```
Shell:
```
$ echo $$
132449
$ readlink /proc/$$/ns/pid
pid:[4026531836]
```
layered output:
```
pid_ns   : util/open/frac=   0.0/100.0/    0.0 tasks=     1
tot=      0 local= 0.00 wake/exp/reenq= 0.00/ 0.00/ 0.00
keep/max/busy= 0.00/ 0.00/ 0.00 kick= 0.00 yield/ign= 0.00/    0 
open_idle= 0.00 mig= 0.00 xnuma_mig= 0.00 xllc_mig/skip= 0.00/ 0.00 affn_viol= 0.00
preempt/first/xllc/xnuma/idle/fail= 0.00/ 0.00/ 0.00/ 0.00/ 0.00/ 0.00
xlayer_wake/re= 0.00/ 0.00 llc_drain/try= 0.00/ 0.00
slice=0.5ms min_exec= 0.00/ …
```
=> scx_layered: Add pid namespace layer matching

scheds/include/scx/common.bpf.h
The generated helper and kfunc prototypes in vmlinux.h are missing address
space attributes leading to build failures. Until the generation is fixed,
suppress the generated prototypes.
=> common.bpf.h: Suppress generated prototypes in vmlinux.h

scheds/rust/scx_lavd/src/bpf/power.bpf.c
In the Snapdraon X Elite platform (Thinkpad T14s Gen6), changing  CPU frequency is more expensive than in x86. This PR optimizes the autopilot implementation to reduce the CPU frequency changes and the overhead of power mode switches.
=> scx_lavd: Optimize autopilot mode for ARM platform

scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/main.rs
The maximum time slice of 5 msec gets more stable results in various workloads. One example is as follows:
https://flightlesssomething.ambrosia.one/benchmark/833
Tested-by: Eric Naim <dnaim@cachyos.org>
=> scx_lavd: Change the default time slice to 5 msec

scheds/rust/scx_lavd/src/bpf/main.bpf.c
This PR ensures task stealing from all compute domains by changing the way to iterate neighbor bits. Also, it includes a minor (latency) optimization in ops.select_cpu() path and code refactoring at ops.dispatch() for readability.
=> scx_lavd: Ensure task stealing from all compute domains

scheds/rust/scx_flash/src/bpf/main.bpf.c
To elimate warning `src/bpf/main.bpf.c:268:2: error: non-void function '____fexit_vfs_fsync_range' should return a value [-Wreturn-type]` during compilation, explicitly return 0 within `fexit_vfs_fsync_range()`.
=> scx_flash: Explicitly return in "fexit_vfs_fsync_range"

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Open layers get all the CPUs that aren't currently allocated to other types
of layers. If there are multiple open layers, they all share the unallocated
CPUs - ie. an otherwise unallocated CPU belongs to all open layers in the
system.
This wasn't handled correctly. An unallocated CPU was assigned to the first
open layer vai cpuc->layer_id and owned execution tracking and protection
only applied to the first open layer. Fix it by implementing dedicated paths
for open layers and treating all of them as the owners.
=> scx_layered: Fix open layer handling

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
- Disable owned protection against preemption between open layers.
- Improve accounting accuracies.
=> scx_layered: Open layer owned protection updates

lib/sdt_alloc.bpf.c, scheds/include/lib/sdt_task.h
Fix a compilation error on Clang 19 caused by defining multiple arena pointers in a single comma separated statement. Also fix a duplicate use of ```__arena``` that causes LLVM to emit a warning.
=> lib/sdt_alloc: fix LLVM19 compilation error

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Allow to run scx_bpfland on kernels with CONFIG_SMP disabled.
=> scx_bpfland: support !CONFIG_SMP kernels

scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
Implement an option for users to choose whether to boost the owner of user-space lock or not. As in some scenario it might be better to not prioritize user-space lock owner, such as database transaction.
Check #1118 for details.
See #1118 for all the tests.
=> scx_flash: Option for userspace lock boosting

rust/scx_utils/src/bpf_builder.rs
Use the new feature in libbpf-cargo to emit warnings from clang when building.
There are a fair amount of warnings but I won't fix them here.
Closes #895
Test plan:
- `cargo build --release` - warnings look good!
- CI
=> bpf_builder: emit warnings from clang

rust/scx_rustland_core/assets/bpf/main.bpf.c
Cleans up `-Wunused-function` in rustland_core dependents. It's a little odd
that these warnings show up with every rustland_core based scheduler, but I'm
not sure that there's a good way to address that.
=> rustland_core: clean up unused functions

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
A set of changes to simplify the deadline evaluation code and the idle CPU wake up, which also appear to enhance performance and make the scheduler more robust.
Testing conducted with the help of the CachyOS community.
=> scx_bpfland: improve/simplify deadline

scheds/rust/scx_rusty/src/bpf/main.bpf.c
Selecting an idle CPU without dispatching a task to it can lead to scheduling bubbles, as the CPU remains incorrectly marked as busy and is excluded from the ops.select_cpu() selection, resulting in inefficient core utilization.
To prevent this, always check the idle state of the CPUs that we want to wake up, but avoid marking them as busy, unless we are certain that a task will be dispatched on them.
Note that this issue occurs only in kernel 6.12 and later (following the pick_next_task() refactoring), as the in-kernel CPU idle state update happens only during transitions between a non-idle task and the idle task, whereas earlier kernels refreshed the CPU idle state on every idle task cycle (as a result of the put_prev_task() call).
=> scx_rusty: prevent scheduling bubbles on kernels >= 6.12

scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c
Fixes `warning: non-void function does not return a value in all control paths [-Wreturn-type]`
=> mitosis: add missing return to select_cpu

rust/scx_utils/src/bpf_builder.rs
Commit a4739e9 introduces code in ```scx_utils``` to capture and emit Clang warnings when compiling the BPF schedulers.  Schedulers like ```scx_layered``` use a separate code path in ```scx_utils``` in which we still do not emit Clang warnings. Reuse the code from a4739e9 in those code paths to emit warnings for schedulers that use multiple compilation units.
=> scx_utils: emit compilation warning when compiling multiple *.bpf.c files

scheds/rust/scx_layered/src/bpf/main.bpf.c
Fix compilation warnings for ```scx_layered``` by removing ```preempt_cursor``` and ```is_fb_dsq```, both of which are currently unused.
=> scx_layered: fix compilation warnings

meson-scripts/build_bpftool
On systems which use clang, instead of GCC, as the main compiler, building any part of the Linux monorepo often requires passing `LLVM=1` in the `m̀ake` invocation. Otherwise it assumes that the system has GCC and ends up invoking `gcc` explicitly. That's the case with bpftool.
To avoid such issues, check whether the default `cc` compiler is clang and if yes, set the `LLVM` parameter accordingly.
Fixes #1143
=> build: Allow to build bpftool with clang
