Cargo.toml
Related to https://github.com/sched-ext/scx/issues/1010 but doesn't completely resolve it
=> Enable Link-Time Optimization (LTO) for the Rust part

.github/workflows/caching-build.yml
fix ci, looks like vng was updated making `--net` ambiguous.
=> [scx] fix ci

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c
If a task is not migratable, do not go through the complete idle CPU selection logic.
=> scx_lavd: Add a fast path for a migration-disabled task in pick_idle_cpu()

meson-scripts/bpftool_build_skel, meson-scripts/bpftool_build_skel_lib, meson.build, scheds/c/meson.build
Meson currently defaults to building and linking the BPF library into all existing C schedulers, but that has caused build errors even for schedulers that do not use it (most recently scx_vder). Split the existing Meson build path in two, depending on whether the library should be linked into the scheduler. 
This change does not affect Rust schedulers.
=> meson: do not link BPF library into C schedulers by default

lib/sdt_alloc.bpf.c, scheds/include/scx/bpf_arena_common.h
The allocator code currently uses bpf_for invocations inside a spinlock critical section, which is not allowed for kernel versions <6.14. Current kernels include the cond_break/can_loop/may_goto directives which act as hints to the verifier that a loop terminates. Replace bpf_for/bpf_repeat in the allocator with these directives to get it running in current kernels.
=> lib/sdt_alloc: replace bpf_for with can_loop

lib/meson.build
The library headers got moved to scheds/include a while ago, so they get installed along with them. Remove the now unnecessary header install command from lib/.
=> lib: remove header install step now that headers are in scheds/include

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
A set of changes to enhance scx_bpfland's robustness in presence of tasks running in higher scheduling classes (e.g., real-time) and improve throughput via proactive CPU wakeups.
=> scx_bpfland: improve robustness with real-time tasks and throughput

INSTALL.md
openSUSE already has kernel 6.12 and scx in the repo so update the manual. 
@frelon Could you take a look?
=> INSTALL.md: update for openSUSE

rust/scx_utils/src/build_id.rs, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_flash/src/main.rs, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_rusty/src/main.rs
For bpfland, flash, lavd and rusty this changes the --version to report
the version in the Cargo.toml for each scheduler, instead of the version
of scx_utils.
Fixes #1168 
=> scheds: Use crate version for --version

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs
- Simplify bpf program attachment
- Refactor bpf handling of sched_swith events
- Add barchart support for LLCs
- Add DSQ slice consumed metrics
Scheduler view now shows stats for DSQ slice consumption:
LLC view now supports barcharts:
=> scxtop: Refactor bpf event handling and TUI fixes

tools/scxtop/src/main.rs
Updated kernels and noticed `scxtop` wasn't working properly on new probes. This simplifies attachment and works with the `for-6.14` branch:
=> scxtop: Fix attach on newer kernels

scheds/c/scx_central.bpf.c, scheds/c/scx_flatcg.bpf.c, scheds/c/scx_pair.bpf.c, scheds/c/scx_simple.bpf.c, scheds/include/scx/common.bpf.h, scheds/include/scx/compat.bpf.h, scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c, scheds/rust/scx_rusty/src/bpf/main.bpf.c
As the kernel patch for scx_bpf_now() and time helpers are merged (https://lore.kernel.org/lkml/20250109131456.7055-1-changwoo@igalia.com/), sync up the relevant headers and scx schedulers to use time helpers.
=> scheds: Sync scx schedulers with the kernel changes: time_helpers and scx_bpf_now()

rust/scx_utils/src/user_exit_info.rs
it is dealing with pointer with various sizes/types thus dereferencing these could be considered UB. Thus marking it as unsafe overall. reported by clippy.
=> scx_utils: Fix UserExitInfo::new() usage.

rust/scx_utils/src/lib.rs, tools/scxtop/src/app.rs, tools/scxtop/src/keymap.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/util.rs
Add CPU frequency to the sparkline default view.
sparkline:
barchart:
Can be toggled with the `f` key.
=> scxtop: Add CPU frequency to default sparkline view

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
The following scenario can lead to starvation of per-CPU tasks:
- only task T1 and T2 are running in the system
- T1 is allowed to run only on CPU1 (per-CPU task)
- T2 is currently running on CPU1
- T1 is queued to the shared DSQ, because CPU1 is busy
- T2 keeps running on CPU1 and it's periodically re-enqueued to CPU1's local DSQ, because no other tasks are running in the system (so the local DSQ is empty)
- T1 is sitting forever in the shared DSQ => starvation!
Example trace:
```
CPU 5   : nr_run=3 flags=0x1 cpu_rel=0 ops_qseq=8897270 pnt_seq=7289174
curr=git[143180] class=ext_sched_class
*R git[143180] -3ms
scx_state/flags=3/0xd dsq_flags=0x0 ops_state/qseq=0/0
sticky/holding_cpu=-1/-1 dsq_id=(n/a) dsq_vtime=281946533817 slice=19074269
cpus=ff
R kworker/5:2[139607] -5248ms …
```
=> scx_bpfland: avoid starvation of per-CPU tasks

tools/scxtop/src/app.rs
Fix a bug where LLC data is used in the node barchart view. 
Tested on multi NUMA machine:
=> scxtop: Fix node barchart

lib/sdt_alloc.bpf.c, lib/sdt_task.bpf.c, scheds/include/lib/sdt_task.h
The sdt_arena_verify function has a misleading name, leading to the mistaken assumption it verifies arena variables. The function is in fact a workaround that ensures all subprograms explicitly access the arena map, even if they do not need to. This is because the verifier finds the arena associated with a subprogram by identifying these accesses in the bytecode, and forbids use of arena variables if it finds none.
=> lib/sdt_alloc: rename sdt_arena_verify to avoid confusion

scheds/rust/scx_layered/src/bpf/main.bpf.c
It was incorrectly using layer @id to index into $buf. Use a separate $idx and drop confusing noop ++'s.
=> scx_layered: Fix dump_layer_cpumask()

scheds/c/scx_central.c
at startup it crashes directly:
```shell
% sudo scx_central
malloc(): unsorted double linked list corrupted
Aborted
```
it appears it comes down to the cpu binding.
Note: another fix would be to use the stack.
=> scx_central: fix cpu affinity corrupted allocation (glibc).

scheds/rust/scx_rusty/src/bpf/lb_domain.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/load_balance.rs, scheds/rust/scx_rusty/src/main.rs
Rename functions, variables, and data structures relevant to domains to have consistent and more descriptive naming.
=> scx_rusty: Cleanup naming

tools/scxtop/src/perf_event.rs
if the hardware does not have PMUs, the graph just does not provide any data.
Can have its use for memory intensive tasks for example.
=> scxtop: proposing to add bus-cycles event.

meson-scripts/install_rust_user_scheds
Update meson-scripts/install_rust_user_scheds to also install
rust projects found in the tools/ directory.
This will install scxtop when running 'meson install'.
Fixes #1182
=> meson: Install rust projects in tools dir

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
While cpu allocations aren't node-aware yet, an open layer can work fine with tasks with a node aligned custom cpumask as long as the machine doesn't stay fully saturated for a long time. Add allow_node_aligned layer property which puts node-aligned tassk into layer DSQs instead of the lo fallbacks.
This isn't by any chance a full-fledged NUMA support but setting `allow_node_aligned` on an open layer restores the old behavior which assumed that an open layer can almost always consume from all nodes on the system. This can still lead to stalls but can be useful in specific situations. This should be deprecated once proper numa support is implemented.
=> scx_layered: Implement `allow_node_aligned` layer property

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_bpfland/src/stats.rs
A set of changes to improve bpfland performance and stability:
- use a new virtual deadline algorithm (`deadline = vruntime + exec_vruntime`)
- get rid of the interactive task classification logic via nvcsw
- allow tasks to overflow from the primary domain more aggressively (fixes #1145)
- add a new `--cpufreq` option to enable frequency scaling (otherwise cpu frequency will be only adjusted when running in powersave mode)
- add a new `--local-pcpu` option to prioritize per-cpu tasks
- allow to prioritize all kthreads using `--local-kthreads`
=> scx_bpfland: improvements

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c
This PR optimizes the use of idle CPUs in ops.select_cpu() and ops.enqueue() paths. It harvests opportunities for direct dispatch in ops.enqueue() when an ops.select_cpu() is skipped. Also, the ops.enqueue() path proactively kicks the idle CPU to reduce the latency, but it does not mark it busy since there is no guarantee that the found idle CPU schedules the task.
=> scx_lavd: Optimize the use of idle CPUs

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
Add a matcher, `TgidPidEq`, which accepts a c boolean (i.e. 0 is false, non-zero is true), for when TGID is (or is not) equal to PID.
The intent is to be able to use this matcher to express either of the following:
* "Scope matched tasks to those where PID is TGID"
* "Scope matched tasks to those where PID is NOT TGID"
in combination with other matchers (i.e. `CommPrefix`).
Need to write a cfg to test this still.
=> scx_layered: Add matcher for when tgid is or is not equal to pid

tools/scxtop/src/app.rs
Fix bounds check on page up scrolling when scrolling on the event selection list.
=> scxtop: Fix scroll on page up

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Add three fixes for the MATCH_SCXCMD_JOIN command:
- Remove stray printf when processing a user command
- Add debug printf command for the layer type during layer initialization
- Use the right enum when initializing the layer from the Rust side
=> scx_layered: fixes for MATCH_SCXCMD_JOIN

tools/scxtop/src/app.rs
When an event is selected add it to the default set of events to quicky scroll through events using the j/k keybindings by default.
=> scxtop: Add event to default list after selection

Cargo.lock, rust/scx_loader/Cargo.toml, rust/scx_loader/src/main.rs
When RunnerMessage::Switch is called frequently, start_scheduler could encounter a race condition issue, where more than one tokio async task would start the same time, messing with the child_id state.
To resolve this issue, the JoinHandle got in start_scheduler is recorded, and instead of using child_id to send SIGINT, a cancellation token from tokio-util is used, and stop_scheduler uses it to inform the async task to kill its child. And we could ensure that only one task is managing spawned scheduler process.
=> scx_loader: Avoid race condition with start_scheduler

tools/scxtop/src/app.rs, tools/scxtop/src/event_data.rs
Scale the max number of events by setting the max number of events based on the rendered area. This ensures that events fill the window space when rendering. fixes #1167
=> scxtop: Fill render area by setting max events

rust/scx_utils/src/gpu.rs, rust/scx_utils/src/topology.rs
code using more modern construct to replace simple match patterns
mostly, simplifying loops.
=> scx_utils: cleanup gpu topology part

Cargo.lock, tools/scxtop/Cargo.toml, tools/scxtop/src/app.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs
Add scx_stats support for scxtop to the scheduler view. Implements #1238 
Right now the stats rendering is super basic and just prints the json, but this can be made into more structured output in the future. For schedulers with few numbers of stats the output is reasonable:
=> scxtop: Add scx_stats support

rust/scx_utils/src/autopower.rs, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_lavd/src/main.rs
This PR adds retries and fallback path for `fetch_power_profile()` to fix issues in the case ppd is not available or not started yet. This is generally a better solution than that in #1231. I also re-enable use of autopower in scx_bpfland.
@multics69 @arighi PTAL
=> scx_utils: add retries and fallback path for autopower

rust/scx_loader/README.md, rust/scx_loader/configuration.md, rust/scx_loader/src/config.rs, scheds/rust/scx_bpfland/src/main.rs, services/scx
Update doc and default options for the different performance profiles in scx_bpfland to align with the recent changes.
=> scx_bpfland: update default options and performance profiles

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/bpf/timer.bpf.c, scheds/rust/scx_layered/src/bpf/timer.bpf.h, scheds/rust/scx_layered/src/bpf/util.bpf.c, scheds/rust/scx_layered/src/bpf/util.bpf.h
Misc cleanup to keep LSP nice. I think how this works is a lot more flexible now that we have object linking. 
Keeping the "everything is included as text" approach working is good though because it enables LSP etc. to work nice w/o additional effort and it enables using bindgen manually (which is fantastic wrt/ alternative build systems).
=> [scx-layered] misc. lsp cleanup

Cargo.lock, scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
scx_layered: initial attempt at adding gpu layer match filter
I figure once this works/we use it a bit, we'll know a decent interface (and impl. tbh) and can pull it out into scx_utils.
ATM I've got pids making it through to where I try to write it to the bpf.
I kind of wanted use user ringbuf's for this and started trying to use tests to figure out how to do that, but the docs scared me off a bit: https://docs.ebpf.io/linux/map-type/BPF_MAP_TYPE_USER_RINGBUF/
I'm not sure if how I'm doing this would work at all or if there's a bug in it atm causing pids to not get to bpf side (nor if this approach would be performant enough to be usable if it worked, tbh).
=> scx_layered: initial attempt at adding gpu layer match filter

rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/include/scx/common.bpf.h, scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c
Introduce a new helper for BPF schedulers to determine whether a task can migrate or not (supporting both SMP and UP systems).
This re-aligns the code with kernel commit 5f52bbf2f6e0 ("tools/sched_ext: Add helper to check task migration state").
Moreover, update the schedulers that are relying on p->migration_disabled to use the common helper instead.
=> scx/common.bpf.h: Add helper to check task migration state

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Allow tasks with an earlier deadline to preempt other tasks before their assigned time slice expires.
Moreover, introduce a new option --no-preempt/-n to disable task preemption and rollback to the previous behavior.
=> scx_bpfland: enable task preemption

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c
This PR improves the preemption of in the following two ways:
- Perform preemption when ops.select_cpu() was skipped
- Clean up taskc->vdeadline_log_clk and replace it to p->scx.dsq_vtime
=> scx_lavd: Improve preemption for non-migratable tasks

.github/workflows/bpf-next-test.yml, .github/workflows/for-next-test.yml
make ci use a stable branch for MRs etc.
this changes CI such that:
* every 6 hours sched_ext for-next is used for a job
* every 6 hours bpf for-next is used for a job
* for everything else, for-6.13 is used (i.e. it uses for-6.13 as stable).
We need to update that as releases are cut etc. . An alternative is to have CI use a git repo which always has the latest upstream stable on some branch, but I think this should work fine for now.
=> make ci use a stable branch for MRs etc.

.github/workflows/bpf-next-test.yml, .github/workflows/for-next-test.yml, .github/workflows/stable.yml
add hooks to notify when periodic jobs fail
i think this is a decent way to be notified of CI failures from the periodic jobs, lmk thoughts
this will probably take a few tries to get right
=> add hooks to notify when periodic jobs fail

tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/main.rs
Fix handling non scx handling sched_switch events by properly setting the header on the event so that it can be processed by userspace correctly. Remove the use of tokio for ringbuffer callbacks . Will add some counters later for collecting dropped events.
traces are now working for when a scheduler is loaded or when eevdf is running.
no scheduler:
layered:
example trace:
[scxtop_trace_0.log](https://github.com/user-attachments/files/18596118/scxtop_trace_0.log)
=> scxtop: Fix handling non scx scheduled switch events

tools/scxtop/src/app.rs, tools/scxtop/src/main.rs
Add a warmup option so that events are continously collected before actually consuming events. Add CLI options for controlling tick warmup and trace duration option.
=> scxtop: Add trace options

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c
Don't try to perform preemption for greedy tasks. This improves the fairnes.
=> scx_lavd: Don't try preemption for greedy tasks

rust/scx_rustland_core/assets/bpf/main.bpf.c
Re-introduce a softer version of idle polling to keep re-scheduling the user-space scheduler from ops.update_idle() if it still has pending tasks waiting to be dispatched.
This allows to achieve good core utilization both with v6.12 and v6.13 kernels.
=> scx_rustland_core: re-introduce ops.update_idle()

Cargo.lock, rust/scx_rustland_core/Cargo.toml, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml
Minor version bump to include the new backward-compatible changes.
=> scx_rustland_core: bump up version to 2.2.6

.github/workflows/caching-build.yml, .github/workflows/flake.lock, .github/workflows/flake.nix
Begin migration of CPU heavy tasks from GitHub free runners to self hosted dedicated Linux runners. Start with the build-kernel job as it's pretty simple and doesn't run very often. Will come back for the other copies of `build-kernel` once this is proven.
Changes to enable this:
- Set `runs-on` correctly for this job.
- Switch dependency management to a Nix develop shell for this job. This means we get the same dependencies whether we stay on a self-hosted runner or switch back to GitHub. This is much easier than chasing the ever moving target of software installed on the GitHub runners, and has the added benefit of pinning dependencies.
- Use my branch of nixpkgs with `virtme-ng` packaged. Will upstream this once `virtme-ng` is confirmed working for all of our use cases.
- Bump the …
=> ci: add build-kernel-nix job using dedicated server

scheds/c/README.md, scheds/c/meson.build, scheds/c/scx_prev.bpf.c, scheds/c/scx_prev.c
A FIFO-only variation on scx_simple with CPU selection that prioritizes an idle previous CPU over a fully idle core (as is done in scx_simple and scx_rusty).
scx_prev outperforms a few other schedulers on OLTP workloads run on systems with relatively flat topology (i.e. non-NUMA, single LLC) by changing CPU selection as above and by taking advantage of the more aggressive work conservation (i.e. idle balancing) that comes with sched_ext by default.
It's far from being a full-fledged scheduler, but it demonstrates how a small change to an existing scheduler can improve performance in a real application.
Notes:
- AMD EPYC 7J13 (16-CPU VM) server running v6.12-based UEK-next kernel, scx (688bffcd "Merge pull request #1192 from devnexen/code_simpl3"), and MySQL Community Edition 8.4[0]
- AMD …
=> scx_prev: a simple scheduler tested on OLTP workloads

scheds/c/scx_prev.bpf.c
As Andrea points out[0], select_cpu() is never called for such tasks, so this branch is dead code.  Remove it.
[0] https://github.com/sched-ext/scx/pull/1275
=> scx_prev: delete unused logic for nr_cpus_allowed == 1 tasks

Cargo.lock, rust/scx_rustland_core/Cargo.toml, rust/scx_utils/Cargo.toml, scheds/rust/scx_bpfland/Cargo.toml, scheds/rust/scx_flash/Cargo.toml, scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_mitosis/Cargo.toml, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml, scheds/rust/scx_rusty/Cargo.toml, tools/scxtop/Cargo.toml
Release a new scx_utils to fix scx_rustland_core dependency.
=> scx_utils: Bump up version to 1.0.10

.github/workflows/bpf-next-test.yml, .github/workflows/build-kernel.yml, .github/workflows/caching-build.yml, .github/workflows/for-next-test.yml, .github/workflows/stable.yml
Adds a reusable workflow `build-kernel.yml` to cover the build-kernel job using the new Nix based build process on the dedicated runner.
All of the `build-kernel` jobs are identical except for their git repo and git branch name. Factor these out into a reusable workflow to reduce code duplication.
This also removes any suffixes from the cache, which might (unlikely) increase hit rates. Each build was suffixing their kernels separately even though the build was identical, which was slightly wasteful. It is unlikely any of these repos/branches have identical states though.
Test plan:
- Ran the CI and waited for build-kernel-nix to succeed in each workflow (added a temporary `push:` condition to make sure they all build). Cancelled the rest as this built kernel isn't used yet so there's no …
=> ci: create reusable workflow for nix kernel builds

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c
Note that at ops.enqueue() path, setting a task's slice to zero is risky because we don't know the exact status of the task, so it could cause a zero time slice error as follows:
[ 8271.001818] sched_ext: ksoftirqd/1[70] has zero slice in pick_task_scx()
The zero slice warning is harmful because the sched_ext core ends up setting the time slice to SCX_SLICE_DFL (20 msec), increasing latency spikes.
Thus, we do not set the time slice to 0 at the ops.enqueue() path and rely on scx_bpf_kick_cpu(SCX_KICK_PREEMPT) all the time. Also, use 1 (instead of 0) as a marker to perform scx_bpf_kick_cpu().
This should solve the following issue:
https://github.com/sched-ext/scx/issues/1283
=> scx_lavd: Do not set task's time slice to zero at the ops.enqueue() path

scheds/include/scx/common.bpf.h
When (s64)(after - before) > 0, the code returns the result of (s64)(after - before) > 0 while the intended result should be (s64)(after - before). That happens because the middle operand of the ternary operator was omitted incorrectly, returning the result of (s64)(after - before) > 0. Thus, add the middle operand -- (s64)(after - before) -- to return the correct time calculation.
=> scx_util: Fix incorrect time delta calculation in time_delta()

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c
This reverts commit 22057be29a4308861e0c05759fcc80c00a915e47
That particular commit has more harm than good. It causes latency spikes and performance drops in many workloads, including WebGL Aquarium, osu-wine, Bitwig, and slowroads.io. Thus revert the commit.
=> scx_lavd: Revert "scx_lavd: Preemption when ops.select_cpu() was skipped"

rust/scx_utils/src/gpu.rs
on 32 bits packing the value by high and low bits with an always even sized Vec.
=> scx_utils: addressing #1282 concerns

.github/workflows/sched-ext.config
Disable CONFIG_DEBUG_INFO_REDUCED, as it blocks CONFIG_DEBUG_INFO_BTF, preventing BTF from being generated.
=> ci: disable DEBUG_INFO_REDUCED for arm64

.github/workflows/bpf-next-test.yml, .github/workflows/for-next-test.yml, .github/workflows/stable.yml
Currently the Slack notification gets sent even if the failing branch is not
`main`. This means that any testing done on these workflows (by temporarily
enabling `push`) triggers the notification if they fail or are cancelled.
Replace the `always()` condition with `failure()`. This omits the previous
`cancelled()` case, but that should be fine. Will add it back if there are
objections. Also add the same filter as the `pages` job to only run on `main`.
Test plan:
- __shrugs__
=> ci: only trigger slack notification on failure of main for scheduled runs

Cargo.lock, scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_layered/src/main.rs
Refactor gpu support to workaround nvml issues.
This changes default behavior when `--enable-gpu-support` is set to use NVML less. It also adds a flag `--aggressive-nvml-polling` to restore prior behavior (poll NVML on each iteration of the userspace update loop).
By default, NVML will now be called super conservatively. In addition to only initializing NVML once  (which is done either way), the existence of PIDs seen previously by NVML will be used to limit updates to the map of GPU pids (and, more importantly, reading PIDs using GPUs via NVML).
The ruleset is now as follows:
* If all previously seen PIDs using GPUs are not dead, check NVML again in 10 minutes.
* If no PIDs were previously seen using GPUs, check NVML every 30 seconds.
* When a PID using a GPU dies, check NVML.
* "dead" …
=> scx_layered: refactor gpu support to workaround nvml issues

.github/actions/restore-kernel-cache/action.yml, .github/workflows/bpf-next-test.yml, .github/workflows/for-next-test.yml, .github/workflows/stable.yml
Create a reusable GitHub action to restore the kernel cache. This takes an
argument for `git-repo` and `branch`, like the equivalent reusable workflow for
building a Nix kernel. Enable this action for the Nix built kernels in the
scheduled runs.
This reduces the possibility for a mis-copy and significantly simplifies the
files compared to duplicating the code.
Note that this is deliberately ordered before the `tar` setuid bit in the
actions, as the new cache and that change don't interact well. Will drop that
setuid step in future changes but leaving it there for now to load the other
caches.
Drive by: remove lint from the for-next scheduled run. It's already checked on
PRs, in the merge queue, and on the scheduled main run.
Test plan:
- Changed one of the cache loads to the `master` …
=> ci: switch scheduled jobs to nix built kernel

lib/sdt_alloc.bpf.c, scheds/include/lib/sdt_task.h
The arena allocation functions are currently marked as __hidden, so the verifier treats them as static even if they are in a separate compilation unit from their caller. However, the allocation functions are relatively complex and lead to verification failures if called multiple times from the same function. The __weak keyword prevents the verifier from verifying the function on every call site, preventing this problem.
=> sdt_alloc: mark allocation functions as weak

lib/sdt_alloc.bpf.c, scheds/include/lib/sdt_task.h, scheds/rust/scx_rusty/src/bpf/intf.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c
Add a simple typeless, single threaded arena allocator to be used at initialization time. This is useful because:
1) Arena allocators are currently typed. We have to create a new allocator for each new type we want to add into the arena.
2) The existing allocator's retry and tree traversal logic is complex enough that naively making too many allocator calls in a single function can cause verification to fail, e.g., allocating an array of structs in a loop.
With this new allocator we avoid these problems for initialization-time struct instances.
=> lib/sdt_alloc: introduce typeless init-time arena allocator

scheds/rust/scx_lavd/src/bpf/main.bpf.c
There could be a case such that the scheduler is compiled against the latest vmlinux.h, which has SCX_ENQ_CPU_SELECTED, but runs on the old kernel, which does not have SCX_ENQ_CPU_SELECTED. In this case, !(enq_flags & SCX_ENQ_CPU_SELECTED) will be always true, which is unintended. So use BPF CO-RE to check if SCX_ENQ_CPU_SELECTED exists in runtime.
=> scx_lavd: Use BPF CO-RE for SCX_ENQ_CPU_SELECTED

.github/workflows/bpf-next-test.yml, .github/workflows/caching-build.yml, .github/workflows/for-next-test.yml, .github/workflows/stable.yml
Every 6 hours 4 scheduled workflows trigger at exactly the same time, and because
each currently requires our full quantity of 20 scheduled runners in parallel
this guarantees a lot of queueing if you push a change just after.
Set each scheduled workflow to a random minute and manually specify the "every
6 hours" part with a rotation for the 3 jobs that run every 6 hours. This means
that there's a far better chance you'll be behind 1 job instead of 4 when you
push.
Drive by: make the alignment of the `on:` section consistent with the other
files and with the `jobs:` section.
=> ci: avoid synchronising scheduled jobs

.github/workflows/build-kernel.yml
The build Nix kernel jobs currently fail in external forks because they expect access to the self-hosted runner. Change this to dynamically selecting the self-hosted runner when running in a repo owned by "sched-ext" (the only repos with access to our runner) and "ubuntu-latest" otherwise. Install Nix on GitHub runners but not on self-hosted runners (assume it's already there for now).
This involves
Test plan:
- Pushed to my fork and (after re-enabling actions) both builds passed.
- Runs in the CI on this PR. Will check it hits the right machine.
=> ci: enable running on github runners when outside of repository

.github/workflows/caching-build.yml, .github/workflows/for-next-test.yml
This is a fun one that's been bothering me for a while. The Rust test jobs in the CI have been completely rebuilding the test targets in the VM really slowly even though they are built before the vng VM is entered.
I thought this was something to do with the virtual filesystem before, but it turned out to be much more mundane. The caches for rustup and cargo are stored in $HOME/.rustup and $HOME/.cargo, and vng runs under a different user in the VM (root I assume) so is looking in the wrong place.
Pass through `RUSTUP_HOME` and `CARGO_HOME` to the `cargo test` call in the VM. This prevents the re-sync and download of the rustup components and prevents the rebuild/redownload of the Rust crates.
This makes the performance of the CI drastically better. Comparing [this …
=> ci: pass through rust test paths to prevent a rebuild

scheds/rust/scx_lavd/src/bpf/main.bpf.c
There is a place in update_stat_for_stopping() where time_delta() should be used. Thus use time_delta() for the place.
=> scx_lavd: Use time_delta() in a missing place

.github/workflows/caching-build.yml
This has been building for a while and is stable, and now has been running on the scheduled jobs for a day or so. Merging to enable the `caching-build` workflow which covers push/PRs/merge queue events, and removes the non-nix non-self-hosted kernel build from the final workflow.
Test plan:
- CI
=> ci: move caching-build to nix built kernel

tools/scxtop/src/perf_event.rs, tools/scxtop/src/protos/perfetto_scx.proto
Gives a hint if the there is a suboptimal CPU cache locality, forcing
to slower CPU levels.
=> scxtop: adding one perf event type `L1-dcache-load-misses`.

scheds/rust/scx_lavd/src/bpf/main.bpf.c
Kicking a CPU at ops.select_cpu() causes performance regression in some scenarios. The reported case is as follows:
- Game: Space Marine 2
- Kernel:  6.13.1-2-cachyos
- CPU: i9-13900KF
- GPU: RTX 3700 Ti 570 drivers closed source GSP disabled
- KDE Plasma Wayland with VRR Automatic
Since kicking a CPU at ops.select_cpu() is redundant -- after the ops.select_cpu(), the kernel will kick the CPU if necessary, it is safe to drop the kick CPU here.
Tested-by: Eric Naim <dnaim@cachyos.org>
=> scx_lavd: Revert "scx_lavd: Kick an idle cpu as early as possible on ops.select_cpu()"

scheds/rust/scx_lavd/src/bpf/introspec.bpf.c, tools/scxtop/src/bpf/main.bpf.c
clang can still generate a memcpy call with __builtin_memcpy __builtin_memcpy_inline takes it a step further with compile time size value in exchange of a little binary size increase. supported since clang 15 and we want clang 16 min.
=> scx_lavd, scx_top: inlining builtin copies.

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs, tools/scxtop/src/perfetto_trace.rs
Trace sched_waking and output them in the scxtop perfetto traces. This fills in
the per-process timelines with "Uninterruptible Sleep" and "Runnable".
It has the annoying side effect of sometimes putting "Wake Kill" at the end of
the trace. I think this is because we see the thread as not-runnable for the
last time then the trace terminates, but am unsure.
Drive by: removes the `run` function that is wrapped by `main` in favour of
calling it `main`.
Test plan:
Now some processes show states like this in places that fit the timeline:
I think we may be dropping some events because of this. I'm adding monitoring for it and hopefully have some solutions in follow up PRs.
=> scxtop: track sched_waking events

scheds/rust/scx_p2dq/Cargo.toml, scheds/rust/scx_p2dq/README.md, scheds/rust/scx_p2dq/src/bpf/intf.h, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/main.rs, scheds/rust/scx_p2dq/src/stats.rs
- Fix vtime handling so that it progresses properly and tasks get vtime initialized.
- Remove workaround logic in dispatch for broken vtime handling.
- Add variable to control whether or not to store stats. If metric collection is disabled then stat collection is paused.
- Cleanup unused/unimplemented code.
=> scx_p2dq: Fix vtime handling and cleanup

scheds/rust/scx_layered/src/main.rs
nvml attempts to load the C library being, but scx_layered exits in a AMD setting.
=> scx_layered: making unexpected gpu error smoother.

scheds/rust/scx_layered/Cargo.toml
this change enables using cargo appimage to make running sched_ext in less supported places simpler
how to use this:
1) https://github.com/AppImage/appimagetool/releases/tag/continuous -- put that appimage, renamed as appimagetool and chmod +x'ed, on your path.
2) install cargo-appimage.
3) cargo appimage from the scx_layered directory.
runs fine and the appimage contents looks right:
=> scx_layered: enable creating scx appimage

tools/scxtop/src/app.rs
I cannot wrap my head around not pressing 'q' to close the help screen. Make
pressing 'q' while help is open quit the help screen rather than the
application.
Test plan:
- Opened help, pressed q, help closed. Pressed q again and the app quit.
- Pressed q without opening help, app quit.
=> scxtop: make q exit help if in help instead of quitting

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/bpf_stats.rs, tools/scxtop/src/lib.rs
Adds a stat to track events which can't be inserted into the ringbuf. I can't
get this to hit on my big AMD machines which is a good sign. I've tried a
couple of prod services and some stress-ng configurations. Seems like dropping
events isn't an issue at the minute, but we should keep an eye on it.
There are likely better ways to render this, but at least this way we keep
track of it and can render it more appropriately in the future.
Test plan:
- Artificially added failures on the BPF side. They render as expected in
`scxtop` during a trace.
=> scxtop: track number of dropped events and render it

lib/sdt_alloc.bpf.c, scheds/rust/scx_rusty/src/bpf/main.bpf.c
Fix the issues highlighted in #1320 to compile on systems with 16~KiB page sizes and for kernel configs without NUMA support.
=> aarch64 build fixes

scheds/rust/scx_p2dq/src/main.rs
Update interactive default slice to be 0.1ms and adjust scaling of non-interactive DSQs.
=> scx_p2dq: Update defaults

.github/workflows/caching-build.yml, tools/scxtop/src/app.rs, tools/scxtop/src/bpf_stats.rs, tools/scxtop/src/cpu_data.rs, tools/scxtop/src/keymap.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/llc_data.rs, tools/scxtop/src/main.rs, tools/scxtop/src/node_data.rs, tools/scxtop/src/perf_event.rs, tools/scxtop/src/perfetto_trace.rs, tools/scxtop/src/stats.rs
Ran `clippy` against `scxtop` and kept iterating until no more warnings. I was
very happy with the quality of these warnings.
The main change to the code is things are less indented because of some
restructuring. This is another PR to review with GitHub set to not show
whitespace changes.
Test plan:
- Build scxtop and run any tests we write in the CI in the future.
- Run `cargo clippy` only for scxtop in the CI too to keep things clean.
=> scxtop: run clippy and implement fixes

scheds/rust/scx_layered/src/bpf/main.bpf.c
Fix two issues which can lead to pick_idle_cpu() occasionally returning a disallowed CPU triggering ops error and ejecting the scheduler.
=> scx_layered: Fix pick_idle_cpu() sometimes returning a disallowed CPU

scheds/rust/scx_p2dq/src/bpf/intf.h, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/main.rs
Update load balancing so that pick2 load balancing is done on both the select_cpu and dispatch path by default. Add a BPF timer that periodically resets LLC load values that are used in pick2 balancing. Update idle selection to be more SMT aware.
=> scx_p2dq: Update load balancing

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c
The performance regression has been reported in recent changes. The scenario to produce the problem is running 'algorithm3.pl 2e12' [1] and 'schbench' concurrently.
Two sources of the problem are:
1) Aggressive direct dispatch
2) Delayed preemption by setting the time slice to zero when a victim CPU is local
So, we removed the above changes and hardened the code a bit more.
[1] https://github.com/marioroy/mce-sandbox/blob/0a6386e344aa061d7042bacf975861348db2da74/bin/algorithm3.pl
Reported-by: Mario Roy <marioeroy@gmail.com>
Tested-by: Mario Roy <marioeroy@gmail.com>
=> scx_lavd: Fix the performance regression in recent changes.

scheds/rust/scx_rusty/src/bpf/main.bpf.c
Using BPF_CORE_READ() still fails for arm64 using our current vmlinux.h, because the macro still assumes the field exists. Temporarily turn off mempolicy setting for arm64 until we regenerate the arm64 header with NUMA support.
=> scx_rusty: turn off mempolicy setting for arm64 until we regen the headers

tools/scxtop/src/app.rs, tools/scxtop/src/main.rs, tools/scxtop/src/perf_event.rs
checking if scheduler A fits well with a specific application. In that case, it is probably fair to think that child processes created (e.g. web servers) should be included.
=> scxtop: propose to give the ability to focus on one process.

scheds/include/scx/enums.h
Similar to commit 42ec582b ("scx_utils/enums: Don't panic on missing enums"), avoid panics when an enum is not found also in the C schedulers and default to 0, consistent with the Rust schedulers.
=> scx: Don't panic on missing enums in C schedulers

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/keymap.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs
Adding an experimental feature to automatically start a perfetto trace when a
named function takes a specified long time to return. This can be used to get a
trace of an event when a group of long tail events happen together.
Prefacing this all with experimental as the implementation is a little funky.
Implementation notes:
- Starts the trace entirely from BPF space and relies on ordering of the
ringbuffer to make sure userspace notices before the first events come
through.
- Misses early softirq events because they require userspace to attach the
programs.
- Starts the trace from `trace_tick_warmup` ticks to events aren't dropped.
- Extends the trace if another such event comes from, meaning this can generate
an infinitely long trace and probably get scxtop OOM killed if you get the …
=> scxtop: add experimental_long_tail_tracing

rust/scx_utils/src/compat.rs, scheds/rust/scx_bpfland/src/main.rs
This seems to introduce potential stall conditions, so disable the auto dispatch of tasks that cannot migrate and route them through ops.enqueue(), restoring the old behavior.
=> scx_bpfland: disable auto local dispatch for migration-disabled tasks

tools/scxtop/src/bpf/main.bpf.c
Think that ENOENT is not necessarily appropriate in this case. Seems more likely a potential error occurs when we run out of space in the ring buffer.
=> scxtop: __bpf_ringbuf_reserve() failure set to ENOMEM instead.

scheds/rust/scx_wd40/src/bpf/common.bpf.c, scheds/rust/scx_wd40/src/bpf/cpumask.bpf.c, scheds/rust/scx_wd40/src/bpf/cpumask.h, scheds/rust/scx_wd40/src/bpf/deadline.bpf.c, scheds/rust/scx_wd40/src/bpf/lb_domain.bpf.c, scheds/rust/scx_wd40/src/bpf/lb_domain.h, scheds/rust/scx_wd40/src/bpf/main.bpf.c, scheds/rust/scx_wd40/src/bpf/placement.bpf.c, scheds/rust/scx_wd40/src/bpf/types.h
Initial series of refactorings for scx_wd40. The two most important are:
- Domains now directly point to the CPU mask of their respective NUMA node instead of each having their own copy.
- Domain CPU masks are now directly in the dom_ctx struct, so the lb_domain is almost removed from the codebase.
=> scx_wd40: start simplifying

rust/scx_utils/src/compat.rs
The test function `test_ksym_exists` in `scx_utils` currently requires
`scx_bpf_consume` which means Linux kernel >=6.12 <6.15 (as that function has
been renamed to be removed). The function, however, is testing whether a valid
and invalid ksym exist.
This change changes the ksym to `bpf_task_acquire` which should work on any
kernel >6.1, which means `cargo test` can run on more machine kernels. This
includes our CI machines which opens up the possibility of not running our CI
tests in a VM (change not made here).
Test plan:
- `cargo test` - Linux 6.13.1 machine
- `cargo test` - Ubuntu 24.04 machine, Linux 6.8.0-53
=> scx_utils: remove test dependency on a sched_ext kernel

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
scx_layered: add debug logging for gpu support and fix UsingGpu matcher.
add gpu pid debug logging:
UsingGpu works like it should now (cfg to constrain GPU processes to 2 cores):
=> scx_layered: add debug logging for gpu support and fix UsingGpu matcher

rust/scx_utils/src/cpumask.rs
This example creates a Cpumask from an explicit string which required certain
CPUs to be present. Previously this succeeded on machines with 2/3 CPUs but not
4/5/6/7. This wasn't testing anything useful and reduced the number of machines
that can cleanly run these tests, so stop running it. Use `no_run` instead of
`ignore` so the snippet still gets compiled.
Drive-by: remove unnecessary String and use a str literal instead.
=> scx_utils: make cpumask example no_run

Cargo.lock, scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_layered/src/main.rs
change sysinfo version to 0.30
this will make downstream consumption simpler in places with this version and less-flexible dep management than cargo.
=> scx_layered: change sysinfo version to 0.30

rust/scx_utils/src/topology.rs
Using CPU frequency alone to identify hybrid cores can lead to incorrect classifications. Some processors (i.e., some NVIDIA Grace CPUs) may have cores operating at different frequency ranges, due to power management or other design factors, but that doesn't necessarily mean they are hybrid cores, in the sense of having different microarchitectural designs (e.g., big.LITTLE or Intel's P/E cores).
To achieve more accurate big.LITTLE core detection, rely both on the cluster_id and CPU frequency information.
Moreover, add the "cluster_id" property to struct Core and struct Cpu.
=> scx_utils: use clsuter_id to detect if big.LITTLE CPUs

Cargo.lock, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
scx_layered: fix gpu matcher bugs ~and add flag to enable affinitizing gpu tasks~
this fixes pid serialization across ffi, confirmed via bpftool that the gpu pid map has all GPU pids in it:
```
[{
"key": 558103,
"value": 0
},{
"key": 558106,
"value": 0
},{
...
```
~this also adds a flag, ` --affinitize-gpu-tasks`, which has the scheduler grab some topo info when it uses nvml and affine gpu processes to those CPUs nvml recommends as ideal.~
I think this tested well (it looked like there was enough load for the results to be valid),
=> scx_layered: fix gpu matcher bugs

Cargo.lock, tools/scxtop/Cargo.toml, tools/scxtop/src/app.rs, tools/scxtop/src/keymap.rs, tools/scxtop/src/lib.rs
I might put this as a runtime option because it makes the output rather verbose:
=> scxtop: Add localization on number formatting

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
Implement a more conservative task migration strategy:
- consider cache locality for proactive CPU wake up in ops.enqueue(),
- perform local direct dispatch on non-wakeup paths when the local DSQ has just one or zero tasks waiting.
This change improves cache locality while still maintaining a good level of work conservation.
=> scx_bpfland: reduce task migrations

rust/scx_utils/src/topology.rs
In presence of multiple sockets with shared NUMA nodes the package_id must be considered to determine a unique key to identify cores / LLCs, otherwise some information may be missed due to key duplication.
For example, let's simulate a VM with 2 sockets, each one with a single SMT core and just one NUMA node, using virtme-ng:
$ vng --cpu 4,sockets=2,cores=1,threads=2 -- lscpu -e
CPU NODE SOCKET CORE L1d:L1i:L2:L3 ONLINE
0    0      0    0 0:0:0:0          yes
1    0      0    0 0:0:0:0          yes
2    0      1    1 1:1:1:1          yes
3    0      1    1 1:1:1:1          yes
And let's run the following test case inside the vng instance:
let topo = Topology::new().unwrap();
let smt_siblings = topo.sibling_cpus();
info!("SMT sibling CPUs: {:?}", smt_siblings);
The result is the following: …
=> scx_utils: topology: Add package_id to the LLC and Core keys

Cargo.lock, tools/scxtop/Cargo.toml, tools/scxtop/src/app.rs, tools/scxtop/src/cli.rs, tools/scxtop/src/config.rs, tools/scxtop/src/keymap.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs, tools/scxtop/src/perfetto_trace.rs
Add option to load default values from a config file defined following XDG base directory specification. This will allow for custom keymaps to be defined in config files. The handling between the clap CLI args and the config file is a little awkward, but that can be cleaned up in the future.
After running `scxtop` the default config file will be created:
```
$ cat $HOME/.config/scxtop/scxtop.toml
tick_rate_ms = 250
debug = false
exclude_bpf = false
stats_socket_path = "/var/run/scx/root/stats"
trace_file_prefix = "scxtop_trace"
trace_ticks = 5
worker_threads = 4
trace_tick_warmup = 3
```
=> scxtop: Add config file

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
Always use scx_bpf_now() to track time consistently. This fixes a bad regression with the 6.14 kernel, as scx_bpf_now() is no longer redirected to bpf_ktime_get_ns() and comparing the TSC timestamp with the timestamp cached in struct rq can lead to inaccurate time measurements.
Fixes: 97495ced ("scx_bpfland: Replace bpf_ktime_get_ns() to scx_bpf_now()")
=> scx_bpfland; use scx_bpf_now() consistently

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/lock.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c
Using ftrace is handy. However, it could be unreliable across kernel versions and kernel configs because ftraced-functions can be renamed or inlined. Thus, for reliable tracing, replace ftrace to tracepoint. With tracepoint, there is no easy/efficient way to get arguments and return values, so drop tracking uaddr was used to distinguish indivisual futexes.
=> scx_lavd: Use tracepoints for futex for reliable tracing

scheds/rust/scx_lavd/src/bpf/lock.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c
Fixes: 9a67bd7f ("scx_lavd: Use tracepoints for futex for reliable tracing")
=> scx_lavd: Fix BPF verifier errors in old kernels.

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
When calculating load sums if the load is zero then reset the load count. Handle edge case when resetting load to only update time slices if autoslice is enabled.
=> scx_p2dq: Handle invalid load sum calculations

Cargo.lock, tools/scxtop/Cargo.toml, tools/scxtop/src/main.rs
scxtop logs, including panics, are currently lost because the TUI overwrites
them. Add environment variables to write the log to a file and control the log
level.
Test plan:
- Caught a panic that was lost before. It works.
- Handles bad levels correctly.
=> scxtop: add logging to file with panics

scheds/rust/scx_wd40/src/bpf/common.bpf.c, scheds/rust/scx_wd40/src/bpf/lb_domain.bpf.c, scheds/rust/scx_wd40/src/bpf/lb_domain.h, scheds/rust/scx_wd40/src/bpf/main.bpf.c, scheds/rust/scx_wd40/src/main.rs, scheds/rust/scx_wd40/src/tuner.rs
Introduce 2 refactoring steps to simplify the code:
- Split arena allocation and kernel-side initialization into two steps to remove the intermediate masks we are currently using to communicate between userspace and BPF.
- Move the tuner completely in userspace by directly updating arena memory from the Rust module
=> scx_wd40: simplify BPF component

tools/scxtop/src/app.rs
Received a panic using the new logging feature:
```
16:04:06 [ERROR] thread 'main' panicked at 'Ratio should be between 0 and 1 inclusively.': /home/jakehillion/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.29.0/src/widgets/gauge.rs:95
0: <backtrace::capture::Backtrace as core::default::Default>::default
1: log_panics::Config::install_panic_hook::{{closure}}
2: std::panicking::rust_panic_with_hook
3: std::panicking::begin_panic_handler::{{closure}}
4: std::sys::backtrace::__rust_end_short_backtrace
5: rust_begin_unwind
6: core::panicking::panic_fmt
7: scxtop::app::App::render
8: ratatui::terminal::terminal::Terminal<B>::draw
9: tokio::runtime::runtime::Runtime::block_on
10: scxtop::main
11: std::sys::backtrace::__rust_begin_short_backtrace
12: main
13: …
```
=> scxtop: clamp gauge ratio

Cargo.lock, tools/scxtop/Cargo.toml, tools/scxtop/src/app.rs, tools/scxtop/src/cpu_data.rs, tools/scxtop/src/event_data.rs, tools/scxtop/src/llc_data.rs, tools/scxtop/src/node_data.rs
EventData has a lot of string copies and a `Vec::remove(0)`.
Changes made:
- Replace the `std::collections::BTreeMap` with a `hashbrown::HashMap`. This is
very similar to `std::collections::HashMap` now but has the benefit of not
needing a nightly compiler to use the `raw_entry_mut` API.
- Use the `event_data_mut` API to avoid cloning the `String` in the common
(hit) case.
- Proliferate that String change everywhere.
- Change the `Vec` to a `std::collections::VecDeque` to make popping from the
front cheap.
=> scxtop: make event_data faster

tools/scxtop/build.rs
Update the build script to be less aggressive about recompiling protobuf files. This should improve build times.
=> scxtop: Update build script to not recompile protos

Cargo.toml
Add `release-fast` build mode for fast local builds for testing.
`release` build:
`release-quick` build:
Build timings generated with:
```
cargo build --timings --profile release
```
=> build: Add release-fast build mode

Cargo.lock, tools/scxtop/Cargo.toml, tools/scxtop/src/app.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs, tools/scxtop/src/perfetto_trace.rs
We pass around a bunch of Comm strings in scxtop that comfortably fit in the
allocation of the string, but were each doing an allocation/deallocation and
being copied multiple times.
Use a crate `smartstr` to get a string with Small String Optimization. This
string fits 23 bytes in the string itself without a heap allocation.
Test plan:
- Took a perfetto trace, comms look good.
=> scxtop: use smartstr with SSO for comms

Cargo.lock, scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
redo gpu support for layered
* remove the hacks to avoid using nvml and replace that with a kprobe on nvidia-open.
* have the kprobe be conditionally loaded such that layered loads/runs with and without the symbol nvidia_open present.
* remove no_prealloc from the gpu pid map and make the gpu pid map lru.
this seems to work better than the prior solution:
radeon machine:
nvidia machine:
=> scx_layered: revamp gpu support

tools/scxtop/src/cli.rs, tools/scxtop/src/config.rs, tools/scxtop/src/main.rs
The `Config::merge_tui_args` method is quite complicated and needs modifying
each time. It leaves the `Config` in a mostly-Some state, meaning combining
more than one `TuiArgs` for whatever reason wouldn't work.
Generalise this into a `Config::merge` method which prefers the left-most
value. This is done with an extension of the `Option::or` method for all fields
in the config struct, meaning the left-most set value will win. We can then
replace `Config::merge_tui_args` with a combination of `From<TuiArgs> for Config`
and `Config::merge`. This turns the quite complicated function into two simple
ones.
Test plan:
- Wrote a test to confirm fields get merged as expected.
=> scxtop: add config merging interface

tools/scxtop/src/app.rs
Set the max on the LLC sparkline view to be the maximum aggregated across all LLCs. This makes the TUI far more easier to intrepret across LLCs.
=> scxtop: Set correct max on LLC sparkline view

tools/scxtop/src/app.rs, tools/scxtop/src/edm.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs
Add the EventDispatchManager as an abstraction to decouple handling BPF events from TUI Actions. This allows scxtop to be used in other contexts where BPF event handling is done outside the context of the TUI.
=> scxtop: Add EventDispatchManager for handling events

tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs
scxtop currently waits for a TUI event, then try_recvs every waiting action. This
works okay when every action can be consumed in under one frame time, but
poorly when there is a large queue of actions. Bad behaviour shows up under a
large queue such as 'q' taking a long time to exit the application or render
events not getting through at all.
Changes the main wait loop to a `tokio::select!` which waits for both events.
This means events still get handled. It's not a complete solution given many of
those events get converted directly into actions, but it works for now. Also
cleans up `Action::Render` which doesn't have a clear use case.
To get the full interactivity win here we need to stop relying on Events
passing through `action_tx` quickly, but this is a start.
Test plan:
- Launched …
=> scxtop: concurrently await tui events and actions

scheds/include/scx/common.bpf.h, scheds/include/scx/compat.bpf.h, scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Use the new sched_ext node-aware APIs to account for NUMA topologies in the scheduling decisions.
=> scx_bpfland: NUMA-aware scheduling

tools/scxtop/src/app.rs
Use the max aggregated across all NUMA nodes when rendering NUMA sparklines. This makes it easier to make comparisons across NUMA nodes.
=> scxtop: Fix max sparkline value across NUMA nodes

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs, tools/scxtop/src/perfetto_trace.rs
when for a given GPU, its memory activity fluctuates, this event is triggered. Could be on a process basis or globally.
=> scxtop: adding gpu_mem_total tracepoint.

scheds/c/scx_qmap.bpf.c, scheds/include/scx/compat.bpf.h
Introduce __COMPAT_scx_bpf_events() to use scx_bpf_events() in a compatible way also with kernels that don't provide this kfunc.
This also fixes the following error with scx_qmap when running on a kernel that does not provide scx_bpf_events():
; scx_bpf_events(&events, sizeof(events)); @ scx_qmap.bpf.c:777
318: (b7) r2 = 72                     ; R2_w=72 async_cb
319: <invalid kfunc call>
kfunc 'scx_bpf_events' is referenced but wasn't resolved
Fixes: d3844539 ("kernel: Sync at ad3b301aa05a ("sched_ext: Provides a sysfs 'events' to expose core event counters")")
=> compat: Provide a compatible helper for scx_bpf_events()

tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/main.rs
Only attempt to attach GPU probes if the symbol exists. Fixes failure to launch on systems without GPU tracepoints.
Happy trace:
=> scxtop: Conditionally attach GPU probes

scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
Drop the logic that tries to track user-space futexes and extends task time slices when tasks is holding a user-space lock.
This improves scheduler portability and maintainability across kernel versions. For the scheduler's primary use case (audio/multimedia), the user lock priority boosting provided minimal benefits and sometimes negatively impacted performance predictability by over-prioritizing lock-heavy tasks.
Moreover, conditionally load the remaining kprobe (vfs_fsync_range) to improve scheduler portability and allow to run the scheduler also in kernels where this function is not available.
=> scx_flash: drop user lock priority boosting

tools/scxtop/src/bpf/main.bpf.c
On sched_switch there can be tasks that aren't handled by sched_ext schedulers. Be less aggressive in filtering tasks without a recorded DSQ.
This makes kthreads get collected properly:
=> scxtop: Filter sched_switch events less aggressively

tools/scxtop/src/app.rs, tools/scxtop/src/cli.rs, tools/scxtop/src/config.rs, tools/scxtop/src/perf_event.rs
Allow attaching hardware specific perf events using the CLI or the config file. This allows for a range of hardware specific events to be collected. The list of available perf events can be found in the perf tool configuration in the kernel source:
https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/perf/pmu-events/arch/x86
An example of the config file is as follows:
```
$ head ~/.config/scxtop/scxtop.toml
perf_events = ["ls_dmnd_fills_from_sys.local_l2:0x243:4", "ucode_ops:0x1c2:4", "ls_smi_rx:0x2b:4"] theme = "MidnightGreen"
tick_rate_ms = 250
debug = false
exclude_bpf = false
trace_ticks = 5
worker_threads = 4
trace_tick_warmup = 3
```
=> scxtop: Allow attaching hardware specific perf events

tools/scxtop/README.md, tools/scxtop/src/config.rs
Update the `scxtop` README to include documentation about the config file.
=> scxtop: Add docs for configuration

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs, tools/scxtop/src/perfetto_trace.rs
Although this BPF timer work started with the intention of making sure the
trace always terminated, the initial implementation makes it less likely to
terminate. This is because the userspace ticks are guaranteed to happen since
#1433, but the single timer callback cannot guarantee it will insert into the ring
buffer.
Add an additional mode called TRACE_STOPPING for the case where there was a
previous trace that should have stopped but userspace hasn't been informed yet.
Retrigger the timer every 5ms until it manages to enter the ringbuf, which is
made more likely by having already reduced the sample rate from BPF side.
Finally, clean up any events that came after the true end of the trace in
userspace, as these events will be partial due to the sample rate.
There's an exceedingly …
=> scxtop: always send bpf event to terminate trace

meson-scripts/stress_tests.ini, rust/scx_utils/src/compat.rs, scheds/rust/scx_layered/src/main.rs
This adds a helper, `cond_kprobe_enable` to common. 
This will enable the passed in kprobe or print a warning if the symbol is missing. 
To support this, this switches `compat::ksym_exists` to using `/proc/kallsyms` (which, IIUC, will always work, vs the current approach which does not work with symbols in (some?) modules).
This also updates layered to use this for one conditional kprobe it has (nvidia_open) and updates stress-test config to have CI cover this code.
nvidia gpu machine (w/ symbol present) using this:
amd gpu machine (w/ symbol missing) using this:
=> compat: add kprobe helper and update ksym helper

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
add kprobes for nvidia_mmap, nvidia_poll, nvidia_open.
these in combination with IsGroupLeader seem to identify pids using gpus reasonably well (including when layered is started after the PIDs using GPUs are).
=> scx_layered: expand kprobes used for gpu support

rust/scx_utils/src/compat.rs, scheds/rust/scx_lavd/src/bpf/lock.bpf.c, scheds/rust/scx_lavd/src/main.rs
When a kernel is compiled without CONFIG_FTRACE_SYSCALLS, the relevant tracepoints for futex boosting do not exist. For this case, conditionally enable futex holder boost when the tracepoints exist and '--no-futex-boost' option is not provided.
This PR addresses **https://github.com/sched-ext/scx/issues/1418**
=> scx_utils, scx_lavd: Enable futex holder boosting conditionally.

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
In is_wake_sync() we want to check if the waker is a per-CPU kthread, but instead we're checking the number of allowed CPU of the wakee.
Fix this by properly check if the waker is a per-CPU kthread.
=> scx_bpfland: Fix is_wake_sync()

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Bugs in `keep_running()` and preemption logic made `ksoftirqd` latencies frequently go over hundreds of msecs on moderately loaded systems. Fix the bugs and promote per-cpu kthreads such that they're considered preempting by default. This brings down ksoftirqd latency outliers by more than a couple orders of magnitude.
=> scx_layered: Improve kthread handling

tools/scxtop/src/bpf/main.bpf.c
Userspace correctly handles conditional attachment based on available kfuncs so no need to conditionally attach on the bpf side.
DSQ stats render properly:
=> scxtop: Disable bpf conditional attachment

rust/scx_utils/src/topology.rs, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/main.rs
There are various sysfs sources that somehow represent each CPU's capacity even if the kernel does not properly implement arch_scale_cpu_capacity(), which is used for scx_bpf_cpuperf_cap().
This PR tries to make a best guess about CPU capacity based on available sysfs entries by checking the most precise (e.g., vendor-specific information) to the least precise (CPU max frequency).
Also, scx_lavd is changed to use cpu_capacity exposed by Topology.
=> scx_utils, scx_lavd: Add cpu_capacity to Topology and use it in scx_lavd.

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c
Optimize the core compaction to minimize the number of using CPUs and to reduce latency by more conservatively activating a CPU and more proactively finding a task that cannot be run on the current active/overflow set. In addition to that, add SCX_OPS_ENQ_LAST to avoid latency spikes in under-utilized cases.
=> scx_lavd: Optimize core compaction at ops.dispatch() and more

Cargo.lock, scheds/rust/scx_p2dq/Cargo.toml, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/main.rs
Add a config option for requiring a minimum number of enqueued tasks before attempting to do pick2 migrations. This option allows tuning the stickiness of a tasks to their local LLC. This is just a rough first pass, will try to add a more comprehensive pick2 handling later.
Example: run `stress-ng` using 60 CPUs on a 80 CPU (dual 40 core sockets) NUMA machine. This provides an imbalanced load.
Running with `-m 0` to aggressively pick2 can cause thrashing
```
scx_p2dq --stats 1  -g -m 0
...
direct/idle/greedy 374/31710/0
dsq same/migrate 52837/6578
keep 0 pick2 130
migrations llc/node: 386/386
```
As `-m` increases pick2 runs less frequent:
```
sudo ./target/release/scx_p2dq --stats 1  -g -m 5
direct/idle/greedy 206/13502/0
dsq same/migrate 32798/1929
keep 0 pick2 6
migrations llc/node: …
```
=> scx_p2dq: Add config for minimum queue size for pick2

scheds/rust/scx_p2dq/src/bpf/intf.h, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/main.rs
Add a config that tracks the number of runs the task has run on the local LLC and do not consider tasks below the threshold available to pick2 load balance on the wakeup path.
Test on 80 core dual socket (40 CPUs per socket) machine with `stress-ng`:
```
$ stress-ng -c 60
```
Run with 100 slices before migrating on the local LLC to make tasks sticky:
```
$ scx_p2dq --stats 1  -g -l 100
direct/idle/greedy 208/29342/0
dsq same/migrate 30415/3400
keep 0 pick2 4
migrations llc/node: 1559/1559
direct/idle/greedy 194/31168/0
dsq same/migrate 32933/3320
keep 0 pick2 3
migrations llc/node: 2433/2433
direct/idle/greedy 321/28467/0
dsq same/migrate 29682/3378
keep 0 pick2 31
migrations llc/node: 1467/1467
```
Run with 1 slice for thrashing:
```
$ scx_p2dq --stats 1  -g -l 1
direct/idle/greedy …
```
=> scx_p2dq: Add config for min runs for pick2

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/main.rs
Add a config to allow disabling pick2 load balancing on the dispatch path.
=> scx_p2dq: Allow disabling pick2 load balancing on dispatch

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/main.rs
Add a configuration option to only pick2 load balance tasks that are in the least interactive DSQ. This allows for configuration that balances the cost of task migration to the expected runtime of the task.
=> scx_p2dq: Add option to only load balance max DSQ tasks

rust/scx_rustland_core/assets/bpf.rs, rust/scx_utils/src/topology.rs, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_flash/src/main.rs, scheds/rust/scx_lavd/src/bpf/util.bpf.c, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_p2dq/src/main.rs, scheds/rust/scx_tickless/src/main.rs
Add the new property smt_enabled in Topology that can be used by the schedulers to check if SMT is enabled in the system.
Also change all the schedulers to use this property and get rid of all the duplicate code.
=> scx_utils: Topology: Provide smt_enabled

rust/scx_utils/src/compat.rs
tracepoint_exists() assumed that "/sys/kernel/tracing/available_events" always exists, which is not true in some kernel configurations. So let's check both "/sys/kernel/tracing/available_events" and "/sys/kernel/debug/tracing/available_events".
This fixes the following issue:
https://github.com/sched-ext/scx/issues/1482
=> scx_utils: Fix the failure in tracepoint_exists() in some kernel configs.

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Add helper to scale vtime by task weight and scale task vtime in the stopping callback. This should improve task vtime accuracy.
=> scx_p2dq: Add helper to scale vtime by task weight

scheds/include/scx/common.bpf.h, scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_tickless/src/bpf/main.bpf.c
Add scale_task_fair and scale_task_inverse_fair helpers and refactor schedulers to use shared helpers.
=> common: Add helpers for scaling by task weight

rust/scx_utils/src/compat.rs
Fix cargo linter warning for a variable being unnecessarily mutable.
=> scx_utils: Fix cargo warning

scheds/rust/scx_wd40/src/bpf/bpf_arena_spin_lock.h, scheds/rust/scx_wd40/src/bpf/bpf_atomic.h, scheds/rust/scx_wd40/src/bpf/bpf_experimental.h
Support for arena spin locks has recently landed on the bpf-next branch of the Linux kernel, allowing us to directly embed spin locks in data structures that reside in arenas. This support is in the form of headers that define a spin lock struct backed by arena memory along with lock/unlock operations that can replace the existing bpf_spin_lock data structure we are using. 
These new spinlocks are useful because we can replace with them all  bpf_spin_lock instances in our schedulers. The bpf_spin_lock type cannot be embedded in arenas, and has required us to use maps along our arena-allocated scheduler structures.
Import the headers defining the spinlock types into WD40 in anticipation of using them to simplify the codebase.
=> scx_wd40: import kkd's arena spinlocks from the kernel

scheds/include/scx/common.bpf.h, scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_tickless/src/bpf/main.bpf.c
Rename scale_task_fair and scale_task_inverse_fair to scale_by_task_weight and scale_by_task_weight_inverse to have more precise naming. Follow up from #1485.
=> common: Rename scale_task_fair and scale_task_inverse_fair

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
The .select_cpu() method always enqueues on the local CPU even if another one is selected because it uses SCX_DSQ_LOCAL. Use SCX_DSQ_LOCAL_ON | cpu instead to enqueue to the CPU picked by pick_idle_cpu().
=> scx_p2dq: enqueue to selected_cpu

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Add check when trying to load balance from the llc context using pick_two_llc_ctx to enforce min_nr_queued_pick2 config is respected.
=> scx_p2dq: Add min_nr_queued_pick2 check on pick_two_llc_ctx

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/main.rs
Refactor idle CPU selection to make interactive tasks more sticky to LLCs. Update default value for eligible llc task migration to be less sticky for non interactive tasks.
=> scx_p2dq: Refactor idle cpu selection for LLC stickiness

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
After enabling `SCX_DSQ_LOCAL_ON` in the select path p2dq would sometimes get kicked:
```
[2427581.529156] sched_ext: BPF scheduler "p2dq" disabled (runtime error) [2427581.543695] sched_ext: p2dq: SCX_DSQ_LOCAL[_ON] verdict target cpu 21 not allowed for rcu_exp_par_gp_[313]
[2427581.565551]    task_can_run_on_remote_rq+0x6e/0x80
[2427581.576607]    dispatch_to_local_dsq+0x66/0x170
[2427581.587074]    run_deferred+0x7c/0xa0
[2427581.595631]    wake_up_process+0x65b/0xbe0
[2427581.605141]    kthread_queue_work+0x3f/0x60
[2427581.605147]    rcu_exp_sel_wait_wake+0x32d/0xe40
[2427581.625499]    kthread_worker_fn+0xcc/0x250
[2427581.635211]    kthread+0xdd/0x120
[2427581.642980]    ret_from_fork+0x2f/0x40
[2427581.651707]    ret_from_fork_asm+0x11/0x20
```
Revert back to using SCX_DSQ_LOCAL …
=> scx_p2dq: Revert SCX_DSQ_LOCAL_ON in select_cpu

rust/scx_rustland_core/src/rustland_builder.rs
This enables caches to cache the builds for rustland and rlfifo. 
Build times were getting a bit iffy locally for me, so I set up sccache and using mold as linker in addition to ccache.
This matters less for builds where -p scheduler_i_want_to_build can be passed, but matters more for LSP (i.e. startup time before go to definition/hover info etc. works).
This change enables a cache within all of those to cache better (making build times instant when no changes).
These are warm cache build times before and after this change:
=> scx_rustland: write generated files only when needed

rust/scx_utils/src/compat.rs, tools/scxtop/src/perf_event.rs
Move helpers from scxtop to scx_utils for finding tracefs/debugfs mount points.
=> scx_utils: Add helpers for finding mount points

rust/scx_utils/src/compat.rs
In tracepoint_exists(), unwrap_or() was used to get a result of either tracefs_mount() or debugfs_mount(). However, in Rust, unwrap_or() is eager so both tracefs_mount() and debugfs_mount() are evaluated. Hence, if one of them does not exist, an error is raised.
So, we replace unwrap_or() with unwrap_or_else(), which conducts lazy evaluation, meaning that if tracefs_mount() succeeds, debugfs_mount() is never evaluated.
Also, added "/tracing" to the debugfs mount point since the debugfs mount point is "/sys/kernel/debug" not "/sys/kernel/debug/tracing".
This should fix the following issue:
https://github.com/sched-ext/scx/issues/1502
=> scx_utils: Fix tracepoint_exists()

meson.build, rust/scx_utils/src/clang_info.rs
This PR uses the [cross-compilation](https://mesonbuild.com/Cross-compilation.html) features of meson to pass the correct `--target` to cargo.
We also need to pass target to clang when compiling bpf programs using scx_util to include the correct `vmlinux.h` headers.
Cross-compilation also needs a `.cargo/config.toml`, the following is from an openSUSE machine:
```toml
[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/aarch64-suse-linux-gcc"
ar = "/usr/bin/aarch64-suse-linux-ar"
```
And a cross-file (with a corresponding sys-root with libbpf installed):
```toml
[binaries]
c = 'aarch64-suse-linux-gcc'
cpp = 'aarch64-suse-linux-g++'
strip = 'aarch64-suse-linux-strip'
pkg-config = '/usr/bin/pkg-config'
cmake = '/usr/bin/cmake'
[properties]
sys_root = '/usr/aarch64-suse-linux/sys-root' …
```
=> meson: Cross-compiling with cargo

scheds/rust/scx_layered/examples/cpus_pct.json, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
scx_layered: add cpus_pct config param.
An issue we have ran into is that we want some "fixed" amount of a machines CPUs to be allocated to different layers.  Fixed in the sense of "I want a few CPUs running ansible and many CPUs running nginx", and I don't want those CPUs changing.
CPUs range works fine for this when the number of CPUs is static across hosts, but does not work when we want to use the same configuration across hosts with different numbers of CPUs.
This PR pulls some of the `cpus_range` setup logic out into a helper function and overrides it when cpus_pct is set, enabling layered configs to better err, "do what we want" if that makes sense.
I get 16 cores on layer 1 when I set a layer's cpus_pct to 50 on a 9950x (32 logical cpu machine).
=> scx_layered: add cpus_pct cfg param

rust/scx_utils/src/lib.rs, rust/scx_utils/src/pm.rs
Add a set of idle power management helpers to scx_utils. This is an initial userspace implementation and if the interface shows promising results then similar idle power management helpers can be exposed via kfuncs. See the kernel docs for information on the userspace API:
https://www.kernel.org/doc/html/latest/admin-guide/pm/cpuidle.html#power-management-quality-of-service-for-cpus
Tested with [`p2dq-idle`](https://github.com/sched-ext/scx/compare/main...hodgesds:scx:p2dq-idle) branch:
```
./target/release/scx_p2dq --idle-qos
02:25:19 [INFO] Setting idle QoS to 100us
02:25:19 [INFO] Running scx_p2dq (build ID: 1.0.10-g8545a626-dirty x86_64-unknown-linux-gnu)
02:25:20 [INFO] DSQ[0] slice_ns 100000
02:25:20 [INFO] DSQ[1] slice_ns 3200000
02:25:20 [INFO] DSQ[2] slice_ns 6400000
02:25:20 …
```
=> [RFC] scx_utils: Add idle power management helpers

scheds/rust/scx_wd40/Cargo.lock, scheds/rust/scx_wd40/src/bpf/bpf_arena_spin_lock.h, scheds/rust/scx_wd40/src/bpf/bpf_experimental.h, scheds/rust/scx_wd40/src/bpf/common.bpf.c, scheds/rust/scx_wd40/src/bpf/deadline.bpf.c, scheds/rust/scx_wd40/src/bpf/lb_domain.bpf.c, scheds/rust/scx_wd40/src/bpf/lb_domain.h, scheds/rust/scx_wd40/src/bpf/main.bpf.c, scheds/rust/scx_wd40/src/bpf/placement.bpf.c, scheds/rust/scx_wd40/src/bpf/types.h
Use arena spinlocks to replace the BPF ones for WD40's load balancing domains on the BPF side. Having removed the spinlocks from the domains, move the entire domain structure into arenas and remove the associated BPF map data structure.
=> scx_wd40: remove lb_domain map

scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
Add per layer configuration that allows setting the idle QoS resume latency value. Using this configuration allows for better control of idle cstates. This allows layers to set the idle exit latency. From the docs:
> CPU idle time governors are expected to regard the minimum of the
> global (effective) CPU latency limit and the effective resume latency
> constraint for the given CPU as the upper limit for the exit latency of
> the idle states that they are allowed to select for that CPU. They
> should never select any idle states with exit latency beyond that limit.
See the kernel documentation for more details:
https://www.kernel.org/doc/html/latest/admin-guide/pm/cpuidle.html#power-management-quality-of-service-for-cpus
=> scx_layered: Add idle qos config

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs, tools/scxtop/src/perfetto_trace.rs
tracks hardware related contention in a cpu scheduling context. could cpu frequency related, high cpu cache miss rate, poor cpu locality
but also memory ; thermal throttling.
=> scxtop: adding hw_pressure event trace.

rust/scx_utils/src/lib.rs, rust/scx_utils/src/pm.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_p2dq/src/main.rs
Add a helper to check if idle qos is supported and use the helpering in scx_layered/scx_p2dq to emit warnings when the functionality is not supported.
`scx_p2dq` test:
```
$ sudo ./target/release/scx_p2dq --idle-resume-us 500
13:08:46 [WARN] idle resume latency not supported
13:08:46 [INFO] Running scx_p2dq (build ID: 1.0.10-g0206c6b1-dirty x86_64-unknown-linux-gnu)
13:08:46 [INFO] DSQ[0] slice_ns 100000
13:08:46 [INFO] DSQ[1] slice_ns 3200000
13:08:46 [INFO] DSQ[2] slice_ns 6400000
13:08:47 [INFO] P2DQ scheduler started! Run `scx_p2dq --monitor` for metrics.
^CEXIT: unregistered from user space
```
`scx_layered` test:
```
$ sudo ./target/release/scx_layered f:/home/hodgesd/user2.json
13:13:21 [INFO] Topology awareness not specified, selecting enabled based on hardware
13:13:21 [INFO] …
```
=> scx_utils: Add helper for cpu idle qos support

scheds/rust/scx_wd40/src/bpf/deadline.bpf.c, scheds/rust/scx_wd40/src/bpf/lb_domain.h, scheds/rust/scx_wd40/src/bpf/main.bpf.c
The vtime update functions in WD40 take the task's domain context as an argument, but the domain is already accessible through the task context. Remove the  unnecessary arguments to shorten the function signatures.
=> scx_wd40: remove unnecessary argument to vtime update functions

.github/workflows/flake.nix
Add a couple of dependencies missed when running on GitHub Hosted runners instead of the self-hosted one.
=> ci: add missing dependencies for update-kernels

.github/workflows/update-kernels.yml
Well, both pieces of this workflow that I couldn't test out of the main repo didn't work. Lucky me.
The `--delete-branch` argument is incompatible with merge queues. Remove it. We also don't need the `--merge` as that's the default.
Test plan:
- Ran locally: `cd scx-git && gh pr pull 1527 && gh pr merge --auto` - pressed the "Enable auto merge" button in the UI as expected.
=> ci: remove --merge and --delete-branch in update-kernels

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Refactor the eager load balancing path to use the pick_two_cpu method for load balancing. This makes the code easier to understand as the llc_ctx is not being updated to the load balanced llc.
=> scx_p2dq: Refactor eager load balancing

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/main.bpf.c
Add additional sanity checks for when DSQ latency is added in the TUI. DSQ latency of 0 should not be considered valid.
=> scxtop: Add checks when updating DSQ latency

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs, tools/scxtop/src/perfetto_trace.rs
Add bpf event tracing for fork events and collect fork events into perfetto traces.
=> scxtop: Add fork event tracing

scheds/rust/scx_layered/examples/exclude.json, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
Add matching rules for excluding tasks/processes/cgroups with a given name from a layer. This lets us more finely specify task membership for a layer without overly depending on the order we specify the layers.
=> scx_layered: add exclude match rule

scheds/rust/scx_lavd/src/bpf/balance.bpf.c, scheds/rust/scx_lavd/src/bpf/idle.bpf.c, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
This PR contains the following changes:
- Enable SCX_OPS_ALLOW_QUEUED_WAKEUP when supported.
- Correctly account cross-domain migration.
- Replace the for loop to bpf_for loop.
=> scx_lavd: Enable SCX_OPS_ALLOW_QUEUED_WAKEUP and misc.

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
When a task stops running fix the fix time by adding the weighted vtime to the current vtime.
Reported-by: Changwoo Min <changwoo@igalia.com>
=> scx_p2dq: Fix vtime accounting

rust/scx_utils/src/misc.rs, rust/scx_utils/src/topology.rs
Add the reported NUMA node distance to the Node struct in topology. The distance is useful in determining the migration cost across nodes.
=> scx_utils: Add NUMA node distance to topology

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs, tools/scxtop/src/perfetto_trace.rs
Adds the exit ftrace event to the perfetto trace which is a nice (semi useful) pairing for the fork event recently added by #1535 .
=> scxtop: Add exit event tracing

tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/main.rs
Change #1543 added the `sched_process_exec` event. However, the bpf program wasn't being attached when executing a trace (scxtop trace ...) and, more importantly, when it was attached sxctop panicked. This is owing to the fact that event payload for the exec event was being marked as a FORK and not and EXEC.
To test this I simply ensured we now attach the program using `bpftool`:
```
<elided>
56269: raw_tracepoint  prog 512134
tp 'sched_process_fork'
pids scxtop(604902)
56270: raw_tracepoint  prog 512135
tp 'sched_process_exec'
pids scxtop(604902)
56271: raw_tracepoint  prog 512133
tp 'sched_process_exit'
pids scxtop(604902)
<elided>
```
As a side note, I think that the way bpf program attaches are done could be reworked to make this kind of oversight much more difficult to do. I'll try …
=> scxtop: fix exec event handling when tracing

scheds/rust/scx_bpfland/src/main.rs
Enable ttwu_queue optimization (SCX_OPS_ALLOW_QUEUED_WAKEUP) if the kernel supports it.
This optimization allows to process a task wakeup on the wakee's CPU (via IPI), saving some locking overhead on the waker's CPU, which can be expensive on large machines, due to cache and node boundaries.
This results in ops.select_cpu() being skipped when this path is taken; however, scx_bpfland explicitly checks whether ops.select_cpu() is skipped and still provides the task an opportunity to be directly dispatched from ops.enqueue(), so it is fair to enable this optimization.
=> scx_bpfland: Enable SCX_OPS_ALLOW_QUEUED_WAKEUP

rust/scx_rustland_core/assets/bpf.rs, rust/scx_utils/src/compat.rs, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_flash/src/main.rs, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_mitosis/src/main.rs, scheds/rust/scx_p2dq/src/main.rs, scheds/rust/scx_rusty/src/main.rs, scheds/rust/scx_tickless/src/main.rs
Rust macros aren't scoped the same as functions, and this `import_enums` reference
expects you to have it already imported. Reference this with the full reference
to the crate and remove the now unnecessary imports from all the usage sites.
Test plan:
- `cargo build`
- CI
=> scx_utils: explicitly reference scx_utils::import_enums

scheds/rust/scx_p2dq/src/bpf/intf.h, scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Refactor dispatch load balancing to into separate helper methods. When load balancing in the dispatch path take into account configuration values for load balancing parameters and use a DSQ iterator for selecting tasks to load balance. Refactor enqueue to use pick_idle_cpu rather than reimplementing idle CPU selection.
=> scx_p2dq: Refactor load balancing

scheds/rust/scx_bpfland/src/main.rs
Introduce an option to configure the CPU idle QoS latency when the scheduler is loaded.
=> scx_bpfland: Introduce --idle-resume-us

rust/scx_utils/src/topology.rs, scheds/rust/scx_bpfland/src/main.rs
Restore the correct value of pm_qos_resume_latency_us when the scheduler is stopped.
=> scx_bpfland: restore the correct value of pm_qos_resume_latency_us

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
When weighted tasks are run use scaled vtime to appropriately account the vtime on the LLC/DSQ of the task.
@JakeHillion and I noticed some issues with vtime handling going through the code. There's still probably more to cleanup, but this is an easy fix.
Performance remains good with `stress-ng` tests:
`sudo ./target/release/scx_p2dq --stats 1 -s 1000 -x 1`:
```
$ stress-ng -c 60 -t 15 -M
stress-ng: info:  [394158] setting to a 15 secs run per stressor
stress-ng: info:  [394158] dispatching hogs: 60 cpu
stress-ng: metrc: [394158] stressor       bogo ops real time  usr time  sys time   bogo ops/s     bogo ops/s CPU used per       RSS Max
stress-ng: metrc: [394158]                           (secs)    (secs)    (secs)   (real time) (usr+sys time) instance (%)          (KB)
stress-ng: metrc: …
```
=> scx_p2dq Add scaled vtime to accounting

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Load values should not be scaled by weight in the same way vtime is progressed for tasks/DSQs. Use absolute values for load metrics so that load balancing works appropriately.
=> scx_p2dq: Fix load calculation

scheds/rust/scx_lavd/src/bpf/idle.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
Handling of per-CPU/non-migratable tasks was inconsistent. For non-migratable tasks, the sched_ext core bypassed the BPF scheduler and directly enqueued to the local DSQ with the default time slice. But for the pinned per-CPU tasks were forwarded to the BPF scheduler for enqueuing.
This PR addressed such inconsistent handling of per-CPU/non-migratable tasks. In particular, this PR contains the following changes:
1) Enable SCX_OPS_ENQ_MIGRATION_DISABLED, so the sched_ext core always forwards tasks to the BPF scheduler.
2) Add fast path for per-CPU/non-migratable tasks to ops.dispatch() and ops.enqueue().
3) Add a direct dispatch optimization at ops.enqueue() when the chosen CPU is idle, and there is nothing to do in the chosen domain.
4) As a fallback of the kernel does not support …
=> scx_lavd: Better control and handling of per-CPU tasks.

.github/workflows/build-kernel.nix, .github/workflows/flake.nix, .github/workflows/update-kernels.py, .github/workflows/update-kernels.yml, kernel-versions.json
This commit adds Nix infrastructure to build the tracked kernels easily on any machine with Nix installed. You can run:
nix build ./.github/workflows#kernels."sched_ext/for-next"
To get a very similar kernel to that the CI is using locally, available at `result/bzImage`. It uses `virtme-ng` as the CI does to generate a valid config, then the existing `nixpkgs` build infrastructure to build the kernel from that.
This does not yet change the way the CI kernels are built, as I'm still working out the Nix caching story.
Also adds a step to `update-kernels.yml` to do the Nix build for updated kernels, simply to track whether the build stays working manually. It does not at this time block updating the kernel lock for the existing CI build.
Test plan:
- Merged into main of …
=> nix: add package to build pinned kernels

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
With these changes, bpfland tries more aggressively to keep tasks running within the same node, prioritizing partially idle SMT cores before considering cross-node migrations.
Moreover, it tries more aggressively to perform migrations + direct dispatch attempts from ops.enqueue() to reduce pressure on the shared per-node DSQs.
=> scx_bpfland: Improve NUMA node locality

.editorconfig
Add the `.editorconfig` used by Linux, only taking the section related to
C-like files. This lets contributors use their existing `vimrc` or whatever
other editorconfig while overriding the settings for consistent formatting in C
files. Often when you get a new contributor they insert tabs and don't view the
files with the correct indent size, this change fixes that in future.
=> add linux .editorconfig for c and related files

scheds/rust/scx_lavd/src/bpf/idle.bpf.c, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c
p->nr_cpus_allowed does not always tell the number of allowed CPUs when
p->cpus_ptr does not point to p->cpus_mask [1]. The previous implementation
of is_affinitized() didn't consider that.
So, track the number of allowed CPUs under task_ctx (taskc->nr_cpus_allowed)
and update it whenever task's cpumask is updated. Change is_affinitized() and
its callers accordingly.
[1] https://lore.kernel.org/lkml/Z-sOIwUNgrjbQJkx@slm.duckdns.org/
In addition to this, this PR contains a code cleanup without functional change.
=> scx_lavd: Fix incorrect task affinity testing and more.

scheds/rust/scx_p2dq/src/bpf/intf.h, scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Fix the definition of task_ctx->all_cpus to do a proper check of both p->cpus_ptr == &p->cpus_mask and p->nr_cpus_allowed == num_possible_cpus().
=> scx_p2dq: Fix affinitized task handling

scheds/rust/scx_lavd/src/bpf/idle.bpf.c, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c
Instead of storing nr_cpus_allowed under task_ctx, let's directly store if a task is affinized or not (taskc->is_affinitized). That reduces the space in task_ctx and memory accesses in testing is_affinitized(). Also, remove is_affinitized() since now task_ctx has a field with the same name.
=> scx_lavd: Revise task affinity testing.

scheds/rust/scx_p2dq/src/main.rs
Update the default load balancing config to allow load balancing from all non interactive DSQs by default. This provides better load balancing characteristics on workloads that have a mix of interactive and CPU bound tasks.
Example from running `schbench` with `scxtop` to show load:
=> scx_p2dq: Update default load balancing config

scheds/rust/scx_layered/src/bpf/main.bpf.c
Remove extra call to scx_bpf_test_and_clear_cpu_idle in pick_idle_cpu_from which would happen if smt_enabled and prev_over_idle_core when prev_cpu is busy and sibling_cpu is idle.
=> scx_layered: remove extra call to test_and_clear_cpu in pick_idle_from

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Refactor frequency boosting so that the most CPU throughput bound DSQ gets a frequency boost before running.
=> scx_p2dq: Refactor freq boost

.github/workflows/caching-build.yml, Cargo.lock, Cargo.toml, README.md, meson-scripts/stress_tests.ini, meson.build, scheds/rust/scx_chaos/Cargo.toml, scheds/rust/scx_chaos/build.rs, scheds/rust/scx_chaos/src/bpf/intf.h, scheds/rust/scx_chaos/src/bpf/main.bpf.c, scheds/rust/scx_chaos/src/bpf_intf.rs, scheds/rust/scx_chaos/src/bpf_skel.rs, scheds/rust/scx_chaos/src/lib.rs, scheds/rust/scx_chaos/src/main.rs, scheds/rust/scx_p2dq/Cargo.toml, scheds/rust/scx_p2dq/src/bpf/intf.h, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs, scheds/rust/scx_p2dq/src/main.rs
This commit initialises scx_chaos, a sched_ext scheduler designed for concurrency
testing programs. It is extremely lightly tested at the minute, but should implement
most of the behaviour of concurrency-fuzz-scheduler[0].
scx_chaos uses scx_p2dq as a base, and rather than copy-pasting code it makes
some changes to the structure to be able to use it directly. It turns out this
is pretty simple as we load the scheduler from the skeleton by name. It is then
pretty easy to wrap methods in chaos's BPF side while still maintaining all of
the necessary functionality from p2dq. The biggest change to p2dq comes in
enqueue, where the structure is changed to return a "promise". This is a C
structure detailing either what happened or how to do it, allowing chaos to
choose not to execute the enqueue …
=> scx_chaos: init with basic functionality

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Rather than dispatching affinitized tasks into their allowed CPU mask first attempt to find an idle CPU in the local LLC/node if available. This should improve locality for affinitized tasks.
=> scx_p2dq: Improve locality for affinitized tasks

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Avoid returning early if there are no idle CPUs. Returning the previous CPU if there are no idle CPUs is overly aggressive and causes affinitized tasks to hang if there are no idle CPUs.
=> scx_p2dq: Avoid aggressive return on cpu selection

cargo-publish.py, tools/scxctl/Cargo.toml
The crate can't be published otherwise.
=> scxctl: Add version to scx_loader dependency

scheds/include/scx/common.bpf.h
scx_bpf_error takes a user provided format string and args to exit the scheduler
with an error. When deploying a scheduler at scale this can be tricky to convert
back to a line of code. Add the `__FILE__` and `__LINE__` macros to give us a
fighting chance of finding the line the error occurred on.
Uses string literal concatenation rather than printf parameters to avoid using
up the 6 argument limit in BPF-C. This string should end up as a compile time
constant instead of on the BPF stack, and is passed directly to the kfunc.
Test plan:
- Built everything (local for Rust & CI for all).
Tested by injecting a failure into p2dq. Before:
Error: EXIT: scx_bpf_error (failed)
After:
Error: EXIT: scx_bpf_error (src/bpf/main.bpf.c:1047: failed)
=> common: include file and line number in scx_bpf_error

rust/scx_utils/src/gpu.rs, rust/scx_utils/src/misc.rs, rust/scx_utils/src/netdev.rs, rust/scx_utils/src/topology.rs, tools/scxtop/src/app.rs
On some systems, the file `/sys/devices/system/cpu/cpu<N>/topology/cluster_id` may contain `-1` to indicate the lack of a defined cluster ID for a given CPU.
The existing code assumes unsigned integers, which causes parsing failures (e.g., `parse::<usize>()`) when reading such values.
Introduce a generic `read_from_file<T>()` function that supports any type implementing `FromStr`, including `isize`. Update the topology code to use `read_from_file::<isize>()` when reading `cluster_id` to correctly handle negative values.
While we are here, slightly improve the message in `bail()` statement in `read_from_file()`.
Signed-off-by: Metin Kaya <metin.kaya@arm.com>
=> scxtop: scx_utils: Correctly handle signed values in CPU topology files

scheds/rust/scx_chaos/src/bpf/main.bpf.c, scheds/rust/scx_chaos/src/lib.rs
scx_chaos uses dispatch to perform delayed enqueue of tasks. If dispatch doesn't
run for an arbitrarily long time, these tasks sit in the queue. This doesn't
appear to cause stalls on a system where all CPUs are online, but it does mean
the tasks get delayed for a long time, particularly when the CPU goes idle.
Add a timer that walks each per-CPU delay queue and kicks the CPU if the task is
due an enqueue. Use a slack factor to kick the CPU gently for a couple of milliseconds,
then preempt if the queue still hasn't been dealt with.
The numbers for this timer probably need tuning on smaller systems, but leaving
them hardcoded for now. They're const volatiles so easy to add CLI args for in
the future.
Drive by:
- Correct random_delays_{min,max}_ns from u32->u64.
- Add a macro for the number …
=> chaos: guarantee dispatch of tasks on quiet cpus

scheds/rust/scx_chaos/src/bpf/intf.h, scheds/rust/scx_chaos/src/bpf/main.bpf.c
scx_chaos uses a different vtime timeline in its delay queues, where vtime is
in the same timeline as bpf_ktime_get_ns(). Existing behaviour is to run p2dq's
enqueue for the second time after removing the task from its delay queue. This
is incorrect as the task goes into enqueue with an incorrect vtime.
Save the p2dq vtime into `chaos_task_ctx` before the first enqueue attempt and
restore it before the second enqueue attempt. This is still imperfect as if the
task has been delayed for a long time it will have a much lower vtime and
therefore always hit the:
vtime = vtime_now - slice_ns;
Case in p2dq's enqueue, but for short delays it should be much more accurate.
Test plan:
- `sudo target/release/scx_chaos --random-delay-frequency 0.1 --random-delay-max-us 500000 --random-delay-min-us …
=> chaos: store p2dq vtime and restore it before enqueue

scheds/rust/scx_lavd/src/bpf/intf.h
On ARM64, the BPF verifier complains that the program is too large. So, let's reduce LAVD_CPDOM_MAX_NR to 16, which is a more realistic maximum.
=> scx_lavd: Fix a verifier error on ARM64.

rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/energy_model.rs, rust/scx_utils/src/lib.rs, rust/scx_utils/src/topology.rs
Schedulers need to know the energy model of a system to make energy-aware
scheduling decisions. The EnergyModel (energy_model.rs) represents the energy
model of a system. It loads the energy model data from debugfs (typically at
/sys/kernel/debug/energy_model), so the kernel should support not only the
energy model (CONFIG_ENERGY_MODEL) but also debugfs.
A system's energy model (EnergyModel) consists of one or more performance
domains (PerfDomain). A group of CPUs belonging to the same performance domain
is frequency-scaled altogether (i.e., the same frequency domain), so it has
the same performance-power characteristics. The performance-power attributes
of a performance domain are represented by a collection of performance states
(PerfState). Each performance state includes
1) CPU …
=> scx_utils: Add EnergyModel (energy_model.rs).

rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/lib.rs, scheds/rust/scx_lavd/src/main.rs
Add a new option, "--cpu-pref-order", to `scx_lavd` to easily experiment with various CPU allocation policies.
Additionally, refactor `scx_utils::cpumaks` to make `cpumask::read_cpulist()` public.
=> scx_utils, scx_lavd: Add a new option, "--cpu-pref-order".

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Adjust max vtime so that the maximum amount of vtime accumulated is equal to the max slice size rather than the max current assigned DSQ slice. This yields better prioritization when tasks move between layers and lowers wakeup latencies.
`main` branch:
```
Wakeup Latencies percentiles (usec) runtime 30 (s) (92266 total samples)
50.0th: 18         (27791 samples)
90.0th: 189        (34882 samples)
* 99.0th: 997        (8362 samples)
99.9th: 1622       (772 samples)
min=1, max=4165
Request Latencies percentiles (usec) runtime 30 (s) (92429 total samples)
50.0th: 6552       (27942 samples)
90.0th: 8056       (36773 samples)
* 99.0th: 13040      (8309 samples)
99.9th: 17696      (834 samples)
min=3317, max=24260
20.0th: 3076 …
```
=> scx_p2dq: Adjust max vtime calculation

scheds/rust/scx_lavd/src/bpf/introspec.bpf.c, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c
Simplify CPU frequency scaling to decide the frequency based on CPU utilization without considering the task's performance criticality. The running average of tasks' performance criticality converges to a constant, making no significant difference. To respond quickly upon load spikes, use the bigger one between the running average and the recent utilization. When the utilization is greater than LAVD_CPU_UTIL_MAX_FOR_CPUPERF (85%), ceil to 100%.
=> scx_lavd: Simplify CPU frequency scaling.

scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
Disable auto-dispatch of migration disabled tasks and ensure all tasks are always processed via ops.enqueue().
This seems to prevent stall scenarios where, under certain conditions, migration-disabled tasks are repeatedly rescheduled on the same CPU, leading to starvation of per-CPU tasks queued in the per-node DSQs (reported and tested by the CachyOS community).
=> scx_flash: Always bounce tasks to ops.enqueue()

scheds/rust/scx_lavd/src/bpf/idle.bpf.c, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/introspec.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c, scheds/rust/scx_lavd/src/main.rs
The main changes of this PR is 1) prioritizing kworkers to improve IO performance, 2) reducing the cost of preemption, and 3) reducing the cost of switching to the performance mode.
Besides these main changes, the PR includes code clean-ups -- including removing unused function args, caching repeatedly calculated time slices to sys_stat,  and relaxing the atomic visibility of sys_stat. Note that there is no functional change in the code clean-ups.
=> scx_lavd: Further prioritize kworkers and a few more.

scheds/include/scx/common.bpf.h, scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Update the is_kthread field on the task_context to include checks of if the task is a kworker, io, or wq worker.
=> scx_p2dq: Update kthread selection on task context

scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c
Previously, one overflow CPU was allocated by default to avoid overutilizing active CPUs proactively. However, it is not necessary in practice because there are almost always affinitized tasks, causing overflow CPUs to be assigned. So, drop proactive allocation of an overflow CPU and let's rely on the real overflow CPUs.
In addition, this PR contains code clean-ups without functional changes.
=> scx_lavd: Do not proactively reserve overflow CPUs, and more. 

tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/main.rs
Owing to a simple omission we weren't attaching to the `sched_waking` tracepoint and therefore no corresponding ftrace events were being captured in the perfetto traces.
I've also made the `on_sched_waking` bpf program follow the same pattern as the other programs as it was non-standard. There are some other minor bpf inconsistencies around here but I'll fix those in a follow up diff.
The image below shows that the perfetto trace now contains `sched_waking` ftrace events.
=> scxtop: attach sched_waking porgram

scheds/include/scx/bpf_arena_spin_lock.h
The arena code fails on some machines that specify higher than usual numbers of CPUs. Bump _Q_MAX_CPUS to handle those use cases. Also use the _Q_MAX_CPUS macro in arena_spin_lock instead directly using its value.
=> include/scx: Bump _Q_MAX_CPUs for arena spinlocks

rust/scx_utils/src/bpf_builder.rs, scheds/rust/scx_wd40/build.rs
The code in scx_utils responsible for compiling schedulers as separate compilation units currently does not retain separate output files for each file compiled, and instead only keeps the final combined object file produced by the linker. This happens because the code uses the same name for all object files, causing them to overwrite each other during compilation. However, the intermediate *.o files are useful for debugging.  Modify the code to properly name the object files so they are retained during compilation. Also change the name of the *.o file for main.bpf.c from bpf.bpf.o to main.bpf.o for consistency.
=> scx_utils: retain all BPF output files for multiple compilation units

lib/cpumask.bpf.c, lib/include/lib, lib/sdt_alloc.bpf.c, lib/sdt_task.bpf.c, scheds/c/scx_sdt.bpf.c, scheds/c/scx_sdt.c, scheds/include/lib/sdt_task.h, scheds/rust/scx_rusty/src/bpf/lb_domain.h, scheds/rust/scx_rusty/src/bpf/main.bpf.c, scheds/rust/scx_rusty/src/bpf/sdt_alloc.bpf.c, scheds/rust/scx_rusty/src/bpf/sdt_task.bpf.c, scheds/rust/scx_rusty/src/bpf/sdt_task.h, scheds/rust/scx_wd40/Cargo.lock, scheds/rust/scx_wd40/src/bpf/lb_domain.bpf.c, scheds/rust/scx_wd40/src/bpf/lb_domain.h, scheds/rust/scx_wd40/src/bpf/main.bpf.c
The allocator code currently uses the sdt_* prefix that initially stood for "scx data task", as it was used exclusively for task contexts. However, the allocator is now used for more data structures and the prefix has become more confusing than helpful. Even worse, we still have a task allocator in sdt_task.c, where we expand the sdt_* prefix to sdt_task to avoid a namespace conflict with the generic allocator code. Go through the common allocator code and replace or remove the sdt_* prefix as needed. 
The resulting code still uses the sdt_* prefix for pools, descriptors, and chunks. These are data structures that will be used exclusively for the task allocator in the future and will be moved into sdt_task.c, so we leave them as-is.
=> lib/sdt_alloc: remove sdt_* prefix from most of the allocator

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Allowing tasks to interrupt others before their time slice expires is often introducing more issues than benefits, specifically when the system is overloaded we may trigger a storm of context switches, that are never beneficial and can lead to massive system lags.
Therefore, rework preemption by tying it to the concept of direct dispatch: tasks are always allowed to run for their entire assigned time slice and the --no-preempt option effectively disables direct dispatching.
In this context, preemption can be interpreted as the ability to interrupt or bypass the regular scheduling flow.
Disabling direct dispatches (now controllable via --no-preempt) can help to improve fairness at the cost of system responsiveness, which can be an acceptable trade-off for certain server workloads. …
=> scx_bpfland: Rework preemption behavior

scheds/include/scx/common.bpf.h, scheds/rust/scx_lavd/src/bpf/idle.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c
It is necessary to pinned tasks (nr_allowed_cpus == 1) and migration-disabled tasks (migration_disabled == ture) differently. The pinned tasks are pinned by the program so they are very likely to run on the pinned CPU for a while. However, disabling migration is temporary for the sake of kernel implementation (e.g., running a BPF code). 
Therefore, let's extend the overflow set only for the pinned tasks.
=> scx_lavd: Do not extend the overflow set for migration-disabled tasks.

Cargo.lock, Cargo.toml, tools/vmlinux_docify/Cargo.toml, tools/vmlinux_docify/README.md, tools/vmlinux_docify/src/main.rs
Add a tool to document vmlinux.h files.
When we move to using vmlinux.h instead of stubs in common.h, this will enable IDEs etc. to work nice.
I would also open a PR moving the kernel docs on scx enums/structs to the format that I think is more often used/which this tool handles (the format in the diffs of enum/structs below):
enum:
struct:
bpf kfunc:
=> add tool to document vmlinux.h files

lib/sdt_alloc.bpf.c, scheds/include/scx/ravg_impl.bpf.h, scheds/rust/scx_wd40/src/bpf/lb_domain.h
Compilation times for WD40 have become unreasonable, often reaching above a minute. One way to reduce them is compiling the scheduler as a single compilation unit using the "include all *.c files in main.bpf.c" hack. To get this working with WD40:
1) Add #pragma once to headers from which it is missing so that we can safely include them multiple times
2) Remove the GPL license string from the allocator library. The license is still present in the beginning of the file, and the scheduler code has its own copy of the license string.
=> wd40: fixups for getting single unit compilation working

scheds/rust/scx_layered/src/main.rs
change default gpu kprobe level to prior behavior
previously, the behavior was 3 by default (and only 3 at all), so default to 3.
=> scx_layered: change default gpu kprobe level to prior behavior

scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c
Let's use u64 clamp_time_slice_ns() for consistency since u64 is used for all the other slice-related code.
=> scx_lavd: Change type in clamp_time_slice_ns().

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
Skip migration when performing a direct dispatch in ops.enqueue() for per-CPU and migration-disabled tasks.
=> scx_bpfland: Skip migration attempts for migration-disabled tasks

tools/scxtop/Cargo.toml, tools/scxtop/src/app.rs, tools/scxtop/src/config.rs, tools/scxtop/src/main.rs, tools/scxtop/src/perf_event.rs, tools/scxtop/src/perfetto_trace.rs
scxtop has `unused_imports = allow`, I'm guessing because it was copy/pasted
from somewhere. Remove this and cleanup the unused imports. Will be checked in
the CI under the clippy step in future.
Test plan:
- CI
=> scxtop: clean up unused imports

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs
Add CLI parameters for tuning load balancing on the select_cpu/enqueue path. It's now disabled by default as doing load balancing in the select/enqueue path seems to regress wakeup latencies, but I figured it's worth making it configurable.
Tested on EPYC 9D64 with 11 LLCs and `schbench -t 100` to partially load the system.
`schbench` 30s run:
```
Wakeup Latencies percentiles (usec) runtime 30 (s) (403491 total samples)
50.0th: 10         (108393 samples)
90.0th: 15         (133389 samples)
* 99.0th: 23         (35247 samples)
99.9th: 146        (3236 samples)
min=1, max=4191
Request Latencies percentiles (usec) runtime 30 (s) (404316 total samples)
50.0th: 6584       (116445 samples)
90.0th: 10768      (157308 samples)
* 99.0th: 12368      (35623 samples)
99.9th: 17824      (3451 …
```
=> scx_p2dq: Add CLI args for tuning load balancing

Cargo.lock, rust/scx_utils/Cargo.toml, rust/scx_utils/src/bpf_builder.rs
test_bpf_builder_new ends up creating some files in the directory specified by
the environment variable OUT_DIR. This fails if, for example, you use a read only
VM that can see that directory but not write to it. Use `tempfile::tempdir` to
set this variable to a writeable temporary directory and clean it up automatically
at the end of the test.
Example files created:
```
$OUT_DIR/scx_utils-bpf_h
$OUT_DIR/scx_utils-bpf_h/vmlinux.h
$OUT_DIR/scx_utils-bpf_h/.gitignore
$OUT_DIR/scx_utils-bpf_h/lib
$OUT_DIR/scx_utils-bpf_h/lib/cpumask.h
$OUT_DIR/scx_utils-bpf_h/lib/percpu.h
$OUT_DIR/scx_utils-bpf_h/lib/sdt_task.h
$OUT_DIR/scx_utils-bpf_h/bpf-compat
$OUT_DIR/scx_utils-bpf_h/bpf-compat/gnu
$OUT_DIR/scx_utils-bpf_h/bpf-compat/gnu/stubs.h
```
Test plan:
- `cargo test`
- CI
=> scx_utils: use tempdir in test_bpf_builder_new

scheds/rust/scx_lavd/src/bpf/introspec.bpf.c, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c
1000 has been used for fixed point arithmetic since it is easier to understand for humans. Change to 1024 because 1) it is more efficient in the machine and 2) it is compatible with the kernel conventions.
LAVD_SCALE and LAVD_SHIFT are defined and used throughout the code. p2scale() and s2percent() are provided and used for conversion between scale (1024) and percent (100).
There is no functional change.
=> scx_lavd: Use 1024 instead 1000 for fixed point arithmetic.

tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs, tools/scxtop/src/perfetto_trace.rs
This change establishes relationships between a thread group leader (the main thread in a process) and its children. This therefore enables us to aggregate various attributes to the process which is very necessary for analysis of workloads.
At a perfetto UI level we now get what appear to be correct groupings of threads within their process groups (the attached image shows this). We still don't label all processes with their comm as we rely on having seen the main thread during capture for that. This is annoying and I'll see if there is a way to fix that.
=> scxtop: add process and thread descriptors

.github/include/ci.py, .github/include/flake.lock, .github/include/flake.nix, .github/workflows/build-kernel.yml, .github/workflows/caching-build.yml, scheds/rust/scx_chaos/Cargo.toml, tools/scxtop/Cargo.toml, tools/scxtop/src/config.rs
Nix'ify the build process for Rust tests and move them to the large machine when in org. Remove the test matrix, as the overhead here is mostly contained in starting the VM and it's inefficient to start many/repeat the build.
The new CI script, which only coveres Rust tests for now, doesn't require Nix to run. Nix enables it to run more reproducibly, and is required for the CI as that's how the self hosted runner handles dependencies, but is not required to run the script locally.
Specific changes:
- Move `rust-tests` to the big self-hosted machine when in the `sched-ext` org.
- Nix'ify the dependencies. This uses a fixed version of `cargo`, `rustc` and `clippy` rather than the moving target of `rust-toolchain.toml`, but it is still `stable`. We can pull more speciifc versions using a …
=> ci: add nixed script to cover rust part of ci

tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs
Kernel workqueue threads have a comm field that always begins with "kworker/" and this isn't helpful at all for identifying the actual function of the thread which is super useful when analysing workloads. This change identifies workqueue threads and replaces the comm field we stash with the description of the thread that was provided when it was created. This idea and the bpf code was shamelessly stolen from the [systing](https://github.com/josefbacik/systing) project.
Just a note on the lib.rs changes (which @JakeHillion knows all about as he basically came up with them :-) ): the current lib.rs implementation pulls 16 bytes from the passed in event struct and uses `std::str::from_utf8()`  to construct a string which asserts if any of the bytes are not utf8. Using …
=> scxtop: better naming for kernel workqueue threads

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/introspec.bpf.c, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
Previously, neither CPU capacity nor frequency were considered when calculating CPU utilization. CPU utilization merely means the compute time ratio to a certain time duration. So, it is not possible to compare the utilization value of one CPU directly with that of another CPU.
The new scaled utilization (sys_stat.avg_sc_util and sys_stat.cur_sc_util) is normalized value to the highest frequency of the fastest CPU, so the scaled utilization values are safely compared across CPU types with different frequencies.
After this PR, the scaled, invariant utilization will be used for core compaction.
=> scx_lavd: Calculate scaled and invariant CPU utilization.

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs
Make load balancing configurable on the dispatch path by setting the dispatch_lb_busy value. If the load proportion is under the busy value then allow the CPU to migrate tasks across LLCs.
=> scx_p2dq: Add configuration for dispatch load balancing

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs
Refactor wakup logic with configuration to control migrating across LLCs. Keep interactive tasks sticky to the local LLC when waking.
=> scx_p2dq: Refactor wakeup logic

tools/scxtop/src/perfetto_trace.rs
We now have process -> thread relationships setup so the grouping are good. However, for longer running processes it is quite common for the main thread to not run at all while we are tracing and this means we never get to capture its comm. This makes it hard to identify the process to which a bunch of threads belong as any `ProcessDescriptors` objects which have the `process_name` Option unset causes the process thread (the thread group leader) to be labelled as "Process" in the resulting perfetto trace.
The solution here is to simply go lookup the `comm` value in `/proc` if it exists when scxtop exits. I'm not worried about pid reuse as trace times are too short for it to be a problem.
An example of before the changes shows the current state with lots of processes being labelled with …
=> scxtop: fixing missing process names

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs
scaled_busy represents the performance state "final score", i.e. scaled frequency used by the CPU.
=> scxtop: trace (part of) pstate_sample

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs
Add an option to load balance interactive tasks. Depending on the workload this may greatly improve interactivity.
default:
```
Wakeup Latencies percentiles (usec) runtime 30 (s) (396749 total samples)
50.0th: 11         (138184 samples)
90.0th: 17         (140408 samples)
* 99.0th: 22         (31329 samples)
99.9th: 48         (2940 samples)
min=1, max=4220
Request Latencies percentiles (usec) runtime 30 (s) (397615 total samples)
50.0th: 6632       (115863 samples)
90.0th: 10768      (158902 samples)
* 99.0th: 12368      (35392 samples)
99.9th: 18080      (3375 samples)
min=5815, max=43930
20.0th: 13072      (7 samples)
* 50.0th: 13296      (9 samples)
90.0th: 13488      (12 samples)
min=12747, max=13638
average rps: 13253.83 …
```
=> scx_p2dq: Allow interactive task load balancing

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_layered/src/stats.rs
This prevents the layer's dispatch path from trying to dispatch from DSQs in remote NUMA nodes which should reduce cross-node traffic and hopefully help machines that are more constrained in terms of cross-node bandwidth.
=> scx_layered: Implement layer option skip_remote_node

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
Allow direct dispatch on sync wakeup only within the same LLC (to reduce LLC migrations that can be costly on certain architectures - e.g., AMD).
Based on tests and benchmarks from the CachyOS community, these changes don't appear to bring significant improvements, but the overall trend seems positive, with small performance gains.
=> scx_bpfland: improve wakeups

rust/scx_utils/src/compat.rs, rust/scx_utils/src/lib.rs
Currently the stall watchdog timer is either hardcoded into each scheduler's
struct_ops or left at the kernel default of 30s. This is inconvenient
particularly when performing testing as 30s is an incredibly long time.
Add an environment variable SCX_TIMEOUT_MS that dictates `timeout_ms` when set.
`scx_ops_open` is quite opinionated already, so we add it there and this variable
will propagate to all schedulers that use that. Will propose a similar change to
C-schedulers in the future.
Test plan:
- `cargo build --release && sudo SCX_TIMEOUT_MS=5000 target/release/scx_chaos --random-delay-frequency 0.1 --random-delay-min-us 5000000 --random-delay-max-us 5000000` - kicked for stalling with the environment variable, stays without.
=> rustscheds: add common SCX_TIMEOUT_MS env var to set stall watchdog limit

README.md
Include the complete list of dependencies needed to build the scx schedulers and tools on Ubuntu.
=> README: update list of build dependencies for Ubuntu

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c
The preemption at ops.tick() is cheap because it does not require expensive IPI. However, the quality of the preemption decision is suboptimal using only local information. It is insufficient to check that the current task is less latency-critical than the one in a DSQ. Even if it is true, there is no guarantee that the current task is the least latency-critical among currently running tasks. Moreover, the preemption at ops.tick() is rather redundant with the preemption at ops.qneueue(). The poor, redundant preemption decision pressures ops.enqueue() and ops.dispatch() operations. So, drop the preemption at ops.tick().
On the other hand, the preemption at the ops.enqueue() is more expensive. However, the quality of the decision is better because it tries to find the least latency-critical …
=> scx_lavd: Improve preemption at ops.tick() and ops.qneueue().

scheds/rust/scx_lavd/src/bpf/balance.bpf.c
When there is only one compute domain, there is only one DSQ so load balancing is unnecessary. So skip the load balancing when nr_cpdoms == 1.
=> scx_lavd: Skip load balancing when there is only one compute domain.

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
Certain workloads (especially games) seem to benefit from the synchronous wakeup optimization, which tries to dispatch a wakee on the waker’s CPU when both share the same LLC. This can improve cache locality and responsiveness in typical producer/consumer pipelines, where the same two tasks communicate frequently.
However, in other workloads, this behavior can lead to performance regressions and excessive CPU migrations. In particular, it can be detrimental in:
- Mixed workloads with latency-sensitive and background pipe-intensive tasks (e.g., telemetry or logging daemons), where the latter are chatty but not performance-critical. Prioritizing them via direct dispatch skews fairness and may hurt important foreground tasks.
- Many-to-one communication patterns, such as a centralized …
=> scx_bpfland: Introduce --no-wake-sync

scheds/rust/scx_p2dq/src/bpf/intf.h, scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Refactor big/little scheduling to prioritize putting non interactive tasks on big cores.
PR:
```
$ stress-ng -c 6 -t 15 -M
stress-ng: info:  [17737] setting to a 15 secs run per stressor
stress-ng: info:  [17737] dispatching hogs: 6 cpu
stress-ng: metrc: [17737] stressor       bogo ops real time  usr time  sys time   bogo ops/s     bogo ops/s CPU used per       RSS Max
stress-ng: metrc: [17737]                           (secs)    (secs)    (secs)   (real time) (usr+sys time) instance (%)          (KB)
stress-ng: metrc: [17737] cpu              141995     15.00     89.98      0.02      9465.23        1577.57       100.00          8204
stress-ng: info:  [17737] skipped: 0
stress-ng: info:  [17737] passed: 6: cpu (6)
stress-ng: info:  [17737] failed: 0
stress-ng: info:  [17737] metrics …
```
=> scx_p2dq: Refactor big/little scheduling

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
The implementation of --no-wake-sync mistakenly inverted its intended behavior.
Flip the condition to match the correct semantics.
Fixes: 342233da ("scx_bpfland: Introduce --no-wake-sync")
=> scx_bpfland: Fix inverted logic for --no-wake-sync

rust/scx_utils/Cargo.toml, rust/scx_utils/examples/mangolog.rs, rust/scx_utils/src/lib.rs, rust/scx_utils/src/mangoapp.rs
Add module for reading from mangoapp via gamescope. This module can be used to gather real time data for gaming.
Output from running the example:
```
~/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive $  ~/git/scx/target/release/examples/mangolog
Received MangoApp data:
Visible Frametime: 4753886
FSR Upscale: 0
FSR Sharpness: 2
App Frametime: 4753886
Latency: 18446744073709551615
PID: 27004
Output Width: 1920
Output Height: 1177
App Wants HDR: false
Steam Focused: false
Engine Name:
Received MangoApp data:
Visible Frametime: 5128282
FSR Upscale: 0
FSR Sharpness: 2
App Frametime: 5128282
Latency: 18446744073709551615
PID: 27004
Output Width: 1920
Output Height: 1177
App Wants HDR: false
Steam Focused: false
Engine Name:
```
I may integrate this library into `scxtop` for …
=> scx_utils: Add mangolog module

rust/scx_utils/src/misc.rs, rust/scx_utils/src/topology.rs, scheds/rust/scx_lavd/src/main.rs
There are processors where CPUs with the same capacity have different cache sizes. To address such processors in determining CPU preference order, made the following three changes in topology:
- Add per-CPU cache size to Topology::Cpu (cache_size)
- Add the SMT level of a CPU to Topology::Cpu (smt_level)
- Assign core_id in a natural order
With these changes, scx_lavd was changed to take the per-CPU cache size into account -- always prefer a CPU with a bigger cache.
=> scx_utils, scx_lavd: Use per-CPU cache size for CPU preference order.

.github/include/ci.py, .github/include/flake.nix
I like to keep this Python file linted. Enforce that in the CI so it doesn't break.
Test plan:
- `nix run ./.github/include#ci format`
- CI
=> ci.py: run black and isort on self

.github/include/ci.py, .github/include/flake.nix
The CI currently builds the tests then parses the Cargo output to find the test binaries. This does work but it's pretty grim. Switch to `cargo-nextest` with its explicit support for running tests from an archive. This runs the tests in parallel for a whole workspace, rather than the behaviour before (and with `cargo test`) of running a single test crate at a time, and overall provides a much nicer interface for CI output.
The archive extraction takes a dominant amount of time given how few tests we have at the minute. With 8 CPUs this goes from 25s to 35s for this step in the CI, which is a big percentage but a small amount of absolute time. Bump the cores in the VM to mitigate this, which is worth it anyway because tests will run in parallel now.
Test plan:
- `nix run …
=> ci.py: switch to cargo-nextest

scheds/rust/scx_chaos/Cargo.toml, scheds/rust/scx_chaos/build.rs, scheds/rust/scx_chaos/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs
scx_chaos can't be published to crates.io currently because it depends on being built in the monorepo. Expose the BPF sources as bytes in the p2dq crate, which also solves the issue of needing to rebuild when p2dq changes.
Adding the custom include dir is really hacky. The BpfBuilder defines the cflags really early, and it's not really possible to neatly change them after, for example with a `.add_include_path()` method. We would need to break this API pretty significantly to add this cleanly. For now, hack the environment variable in the build of chaos to add an extra flag "after" (with) the includes.
In the future we may need to do something more generic like the TAR_H feature in scx_utils, but for 2 files I think this is simpler to follow.
Test plan:
- `cargo build`
- CI
=> p2dq/chaos: expose bpf file contents from p2dq crate

rust/scx_utils/examples/mangolog.rs, rust/scx_utils/src/mangoapp.rs, tools/scxtop/src/app.rs, tools/scxtop/src/cli.rs, tools/scxtop/src/keymap.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs, tools/scxtop/src/mangoapp.rs
Add a view to the TUI to render data from mangoapp. Show scheduler metrics and perf events for the application running with mangoapp enabled.
This is a continuation of #1708. An example showing filtered perf events and scheduler stats for CS2:
=> scxtop: Add mangoapp TUI view

.github/include/ci.py, .github/include/flake.nix
I like to keep the Nix files linted. Enforce that in the CI so it doesn't break.
Test plan:
- `env -i nix run ./.github/include#ci format`
- CI
=> ci.py: format nix files

scheds/rust/scx_lavd/src/bpf/main.bpf.c
Recent changes in the kernel added new restrictions to rq locks, aiming to prevent deadlocks. lavd triggers this new case in running when calling `scx_bpf_cpuperf_set`. This is because running has already locked an rq before entry and cpuperf_set attempted to operate on and lock a different rq, potentially causing a deadlock.
Get the `cpuc` in lavd_running identified by `scx_bpf_task_cpu` instead of the current CPU. I look forward to being told why this works, but the failure was completely reliable before and goes away with this change.
Relevant kernel commits:
- https://git.kernel.org/pub/scm/linux/kernel/git/tj/sched_ext.git/commit/?h=for-next&id=18853ba782bef65fc81ef2b3370382e5b479c5eb
- https://git.kernel.org/pub/scm/linux/kernel/git/tj/sched_ext.git/commit/?h=for-next&id=a11d6784d731 …
=> scx_lavd: get cpu context of scx_bpf_task_cpu in running

rust/scx_utils/src/energy_model.rs, scheds/rust/scx_lavd/src/main.rs
When deciding the CPU preference order, group the CPUs in the same performance domain (i.e., CPU frequency domain) to minimize the number of active performance domains.
=> scx_utils, scx_lavd: Group CPUs in the same performance domain.

.github/actions/install-deps-action/action.yml
Update llvm to 19 in the Ubuntu runners. This is needed for proper arena support and was leading to verifier errors.
Test plan:
- CI
=> ci: update ubuntu installations to clang 19

scheds/rust/scx_lavd/src/bpf/main.bpf.c
Similarly to commit e81fa0d3 ("lavd: get cpu context of scx_bpf_task_cpu in running") apply the same change to ops.stopping() as well.
Both ops.running() and ops.stopping() can be called from a CPU other than the one the task is assigned to (i.e., a task changing a property of another task), therefore always rely on scx_bpf_task_cpu() to get the right CPU context.
=> scx_lavd: Get the right CPU context from ops.stopping()

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Remove the unneeded cpu_ctx lookup and get the llc_id directly from the task_ctx.
=> scx_p2dq: Fix context lookup in stopping

tools/scxtop/src/main.rs
On kernsl < 6.13, scxtop isn't attaching bpf programs that capture dsq information and therefore isn't capturing any dsq related information. `ksym_attach` returns a Result which is always Ok() and therefore the `is_ok()` used in the current implementation meant that we always went down the 6.13 path, regardless of version.
On a 6.9 based system we previously capture no dsq information and this is demonstrated by the lack of counter tracks created. We should create a number of tracks including one for each dsq to store latency information but we only see one (for the invalid dsq - 0 ):
```
$ ./trace_processor ./scxtop.out.nodsq
> select count(*) from counter_track where name like '%latency ns%';
count(*)
--------------------
1
```
With the fix we se a lot of tracks created:
```
$ …
```
=> scxtop: attach dsq bpf programs on kernels < 6.13

scheds/rust/scx_layered/src/bpf/main.bpf.c
The protected flag currently prevents any tasks from executing in CPUs owned by layers that set it. This ensures QoS for the tasks in the protected layer,  but can lead to stalls if there are not enough unprotected CPUs in the system to drain the low fallback queues in time. Relax the guarantees the flag provides by letting protected CPUs run low fallback tasks. Also clean up some of the logic related to the protected flag.
=> scx_layered: allow protected CPUs to pull tasks from the low fallback queues

Cargo.lock, rust/scx_utils/build.rs, rust/scx_utils/perf_wrapper.h, rust/scx_utils/src/lib.rs, rust/scx_utils/src/perf.rs, tools/scxtop/Cargo.toml, tools/scxtop/src/perf_event.rs
This PR adds a perf module to scx_utils that uses the bindgen crate to generate the bindings for perf_event_open syscall.
This replaces the use of perf-event-open-sys2 crate in scxtop in order to be more portable.
=> scx_utils, scxtop: Bindgen perf event

rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/intf.h, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/src/main.rs
A set of fixes/improvements for scx_rustland_core:
- avoid refilling task's time slice in ops.running() that may cause starvation
- expose task's CPU time since last sleep to user-space
- allow to toggle bulilt-in idle CPU policy
And a redesign of scx_rustland:
- use scheduling policy similar to bpfland and flash
- enable the built-in idle CPU selection policy to get optimal performance when the system is not fully saturated
This should fix #1731.
=> Revamp scx_rustland

Cargo.toml
rust: set lto to thin.
This is what (afaik) most folks use for LTO AFAIK because it's mostly the same as LTO but scales better/is way faster.
This reduces local `--release` warm-cache build times for me for layered when editing main.bpf.c from 20 seconds to 4 seconds.
This also reduces local clean-build `--release` builds from 88 seconds to 50 seconds.
=> rust: set lto to thin

.github/include/flake.lock
Bumps Nix dependencies and unblocks #1746 by providing a newer Cargo version.
Test plan:
- CI
=> chore(deps): nix lock file maintenance

.github/workflows/6_12.yml, kernel-versions.json
6.12 is LTS and has several incompatibilities with 6.13+. Add it to the CI tests, 6-hourly for now.
Test plan:
- CI
- Ran separately with `push:` enabled, it worked.
=> ci: track 6.12 lts kernel and test it 6-hourly

rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/main.bpf.c
Queued wakeup (ttwu_queue) is a wakeup optimization that invokes ops.enqueue() via IPI to reduce cacheline transfers,
Enable this optimization and properly support queued wakeup tasks in ops.enqueue().
While at it also enable ops.enqueue() for migration-disabled tasks and move all the scheduler's flags in the Rust part of the code for consistency.
=> scx_rustland_core: Support queued wakeups

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
Remove extra call to `scx_bpf_now` as `now` is already initialized in stopping.
=> scx_bpfland: Remove extra call to scx_bpf_now

rust/scx_rustland_core/assets/bpf/main.bpf.c
A set of improvements to reduce unnecessary overhead in scx_rustland_core and maximize CPU utilization.
With these changes, scx_rustland achieves nearly the same performance as scx_bpfland (except under extreme system overload) and it seems to remain stable and stall-free across all the stress test scenarios I conducted.
=> scx_rustland_core: Reduce overhead and maximize CPU utilization

rust/scx_rustland_core/assets/bpf/main.bpf.c
Commit c688b10b ("scx_rustland_core: Maximize CPU utilization") can increase CPU utilization with some topologies, but in systems with many CPUs it can significantly degrade performance.
Revert this commit for now to prevent big performance regressions on large systems.
=> Revert "scx_rustland_core: Maximize CPU utilization"

scheds/c/scx_central.c, scheds/c/scx_flatcg.c, scheds/c/scx_nest.c, scheds/c/scx_pair.c, scheds/c/scx_prev.c, scheds/c/scx_simple.c
Ensure the return value of `libbpf_num_possible_cpus()` is positive before use. This avoids undefined behavior when the function fails and returns zero or a negative error code.
Ref : https://docs.ebpf.io/ebpf-library/libbpf/userspace/libbpf_num_possible_cpus/
I believe the Rust-based schedulers might also be affected by the same issue. If this patch is helpful, I’d be happy to send a follow-up patch to add a similar check in the Rust version as well.
=> scheds/c: Validate CPU count from libbpf

scheds/rust/scx_rlfifo/src/main.rs
When an idle CPU is selected via `select_cpu()`, assign it directly instead of falling back to `RL_CPU_ANY`. If no idle CPU is available, keep the task running on its previous CPU.
This change makes the CPU assignment logic consistent with the comment description and ensures more deterministic scheduling behavior.
=> scx_rlfifo: Fix CPU assignment logic

rust/scx_rustland_core/README.md
Update README example to match the CPU assignment fix in commit 5fa3703. Align documentation with code behavior.
=> rustland_core: Update README for CPU assignment

rust/scx_utils/src/perf.rs, tools/scxtop/src/app.rs, tools/scxtop/src/cli.rs, tools/scxtop/src/config.rs, tools/scxtop/src/perf_event.rs
Add configuration for setting the default perf event from either the CLI or config file.
```
$ ./target/release/scxtop --default-perf-event sw:task-clock
```
=> scxtop: Add default perf event configuration

scheds/rust/scx_rustland/README.md, scheds/rust/scx_rustland/src/main.rs
With rustland now aligned to a scheduling policy similar to bpfland, update the default time slice settings and the scheduler's documentation to reflect the new design.
=> scx_rustland: Update doc and default settings

scheds/rust/scx_rlfifo/README.md, scheds/rust/scx_rlfifo/src/main.rs
Update both README and source file to clarify that scx_rlfifo implements a simple Round-Robin scheduler rather than pure FIFO.
Tasks are dequeued in FIFO order but assigned dynamic time slices, enabling preemption and re-enqueueing to achieve Round-Robin execution.
=> scx_rlfifo: Clarify Round-Robin scheduling

rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/main.bpf.c
SCX_OPS_KEEP_BUILTIN_IDLE and SCX_OPS_ENQ_LAST are strictly required for scx_rustland_core to function correctly. Without them, the framework may behave incorrectly, potentially leading to runtime errors or stalls.
To ensure these options are always defined, move them to BPF, instead of relying on the compat APIs. In this way, any missing definitions will result in a build-time error rather than runtime failures.
=> scx_rustland_core: Move mandatory scheduler options to BPF

.githooks/pre-commit
Add a git hook to format files like how ci does before committing (i.e. to remove fmt from the list of things everyone needs to care about etc.).
This is enable-able for folks's clones/forks via the following command:
```
git config core.hooksPath .githooks
```
=> add cargo fmt git hook

.github/include/flake.nix, .github/workflows/integration-tests.yml
Deduplicate the code in integration-tests.yml more by removing layered-matrix. Add a code generator for the test matrix and use that to decide which tests to run. This allows having a layered matrix within the same list. Add `flags` as a parameter so we can feed extra flags to any scheduler that needs it in the future.
This also removes one needed runner, as one of the layered matrix runs before duplicated the integration test for layered.
Test plan:
- CI
=> ci: squash layered matrix

scheds/rust/scx_layered/examples/prefix_suffix.json, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/bpf/util.bpf.c, scheds/rust/scx_layered/src/bpf/util.bpf.h, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
add a cgroup matcher to match suffix of cgroup also.
I used suffix to partition layers docker containers tasks were ran on here:
=> layered: add suffix matcher

scheds/include/scx/common.bpf.h
The scx_bpf_select_cpu_and() helper is currently only available in sched_ext/for-6.16, but we can safely add its declaration to common.bpf.h to avoid losing it during future kernel header resyncs.
=> scx_utils: Add header for scx_bpf_select_cpu_and()

rust/scx_rustland_core/assets/bpf/main.bpf.c
When a user-space scheduler selects an idle CPU via rs_select_cpu(), there's no need to immediately wake it up. At this point, the task still needs to be dispatched through the BPF code, and its exact dispatch time is unknown.
The BPF side already handles CPU wakeups proactively when a task is enqueued in a DSQ, which is more accurate and efficient than waking the CPU prematurely during selection, therefore drop the proactive wakeup from rs_select_cpu().
=> scx_rustland_core: Remove unnecessary CPU wakeup from rs_select_cpu()

scheds/rust/scx_lavd/src/bpf/idle.bpf.c, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
Preemption is good, but it is not free. It costs to find a victim CPU and send a preemption signal (IPI) to the remote victim CPU.
This PR optimizes the preemption operations in various ways:
1) Set the bar higher to trigger preemption operations. Now, the top 1.5-3% latency-critical tasks will be considered for preemption.
2) Replace the IPI-based remote CPU kick, scx_bpf_kick_cpu(), to resetting a victim task's slice to zero. While this does not trigger preemption immediately, it can avoid expensive IPI, which is even more costly in some (old) architectures.
In addition to these main changes, the following related, minor changes were included:
1) Add two options: --no-preemption and --no-wake-sync.
2) Print the preemption statistics for tunning and debugging.
=> scx_lavd: Reduce the preemption overhead and more.

scheds/c/scx_nest.bpf.c, scheds/include/scx/bpf_arena_common.h, scheds/include/scx/common.bpf.h
Fix the following build error in scx_nest:
```
libbpf: elf: sec '.addr_space.1': to use global __arena variables the ARENA map should be explicitly declared in SEC(".maps")
Error: failed to open BPF object file: No such file or directory
```
=> scx_nest: Fix build error

tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs
char is signed by default on x86 but not on aarch64/riscv64, this produces a build-error when trying to use CStr to load a pointer to the generated skel.
Switching to u8 instead of char and modifying the rust code to use String::from_utf8_lossy compiles and runs on the specified platforms.
Fixes: #1803
=> scxtop: Switch from char to u8

rust/scx_rustland_core/assets/bpf.rs
The `dequeue_task()` function called `saturating_sub(1)` on `nr_queued` but did not assign the result back to the field, leaving the counter unchanged. Assign the decremented value back to ensure `nr_queued` is updated correctly.
=> scx_rustland_core: fix nr_queued not decremented after dequeue

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Always update the dsq id on the `task_ctx` when enqueuing tasks.
=> scx_p2dq: Always update dsq_id when enqueuing tasks

README.md, rust/scx_utils/src/bpf_builder.rs, scheds/c/scx_central.bpf.c
- Fix "the followings" to "the following".
- Fix "buliding" to "building".
=> Fix typos in doc and comments

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Make the `--interactive-sticky` no longer work as a noop and fast path the `pick_idle_cpu` path for interactive tasks.
=> scx_p2dq: Make interactive sticky work again

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Add support for creating and pinning a 'scx_layered_task_hint_map' in bpffs so that tasks on the system can open it and update their values to add task hints. Mark the map as 666 so that all tasks are allowed to open it and write to it by default.
As a follow up, we would want to enforce access control such that a bpf_map_update_elem on this map can only happen from a task when the pidfd for the key is the same as its thread ID. This needs to be done using BPF LSM or something similar. Currently anyone who can obtain a pidfd for a task can write its hint. However, this is not something we can fix now as LSM or equivalent support in kernel is missing.
TODO:
=> scx_layered: Support task hint map

README.md
- Fix "staic" to "static"
- Fix "buildng" to "building"
- Enclose `crates.io`
- Fix incorrect closing quotes
=> doc: fix typos and formatting in README

.github/include/flake.nix, Cargo.lock, rust/scx_rustland_core/Cargo.toml, rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/src/alloc.rs, scheds/rust/scx_rustland/src/main.rs
The user-space schedulers should never perform blocking memory allocations, otherwise the entire scheduling pipeline may get stuck.
To prevent this from happening, scx_rustland_core implements a GlobalAlloc with a custom memory allocator that operates on a pre-allocated locked memory arena and all the memory of the process is automatically locked.
However, external libraries/crates can still execute mmap() syscalls directly (i.e., libc), potentially stalling the scheduler, for example:
R scx_rustland[159] -5016ms
scx_state/flags=3/0x1 dsq_flags=0x0 ops_state/qseq=2/1
sticky/holding_cpu=-1/-1 dsq_id=(n/a)
dsq_vtime=0 slice=0 weight=100
cpus=ff
asm_sysvec_apic_timer_interrupt+0x1a/0x20
mmap_region+0x65/0x140
do_mmap+0x47d/0x620
vm_mmap_pgoff+0xbc/0x1c0
do_syscall_64+0xbb/0x1e0 …
=> scx_rustland_core: Forbid mmap() syscall

scheds/rust/scx_layered/src/bpf/main.bpf.c
Use the passed in task_hint to control how vruntime advancement is scaled for threads. Currently, a linear scaling mode is used, but we can do other approaches (logarithmic/exponential) etc.
TODO: A little more testing, with a different scaling function.
=> scx_layered: Consume task_hint::hint for controlling vruntime advancement

scheds/rust/scx_lavd/src/bpf/idle.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c, scheds/rust/scx_lavd/src/main.rs
As the number of options grows in LAVD, it becomes harder to provide the right set of options because some options are conflicting (e.g., --autopilot vs. --no-core-compaction), so they cannot be used together.
To address this problem, this PR updates comments on each option and adds sanity checks if conflicting options are used or not.
=> scx_lavd: Clean up command line options.

scheds/c/README.md
- Wrap scheduler names like `scx_simple` in backticks for better readability
- Replace informal phrase "drown out" with "starve"
- Reword for clarity
- Fix couple typos
=> docs: fix typos and format scheduler names

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/types.h
Add slice_ns to the task_ctx field so that slice times can be dynamically adjusted per task. Refactor various lookups to use the new slice_ns field on the task_ctx.
=> scx_p2dq: Refactor slice handling

scheds/rust/scx_rustland/src/main.rs
The use of `or_insert_with_key()` is unnecessary here since the inserted value does not depend on the key. 
`or_insert()` provides the same behavior more simply.
This minor change improves clarity and readability, and I believe it's a reasonable cleanup rather than churn.
=> scx_rustland: replace `or_insert_with_key` with `or_insert`

rust/scx_userspace_arena/Cargo.toml
Edition of scx_userspace_arena was accidentally committed as 2024. Reset to 2021 for the previously mentioned compatibility issues.
Test plan:
- CI
=> scx_userspace_arena: set edition to 2021

rust/scx_rustland_core/assets/bpf.rs
Remove duplicated sentence about `exited()` and `shutdown_and_report()`.
=> scx_rustland_core : remove duplicated sentence

scheds/rust/scx_layered/src/bpf/main.bpf.c
layered: use passed in p instead of bpf_task_from_pid.
This fixes the situation where a task disappears (i.e. ends or it's pid is changed) wrt/ `bpf_task_from_pid` inside matcher code, causing layered to report unmatched tasks.
This looks like it was compat code around verifier issues previously (i.e. pid lookups are a nice, but somewhat problematic, way to make the verifier trust pointers).
=> layered: use passed in p instead of bpf_task_from_pid

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
If the `--keep-running` option is used then tasks can run longer than the max slice. Therefore, usage should not be clamped by max slice length. This fixes the case where long running tasks get over prioritized.
=> scx_p2dq: Fix accounting for long running tasks

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Make non-interactive tasks sticky to their CPU when there are no idle CPUs and spray interactive tasks across CPUs. This is to give better cache locality for non interactive tasks.
=> scx_p2dq: Keep non-interactive tasks sticky

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Have layered only attempt to skip preemption's that it could not accomplish (i.e. due to tasks with RT sched class) when kallsyms addresses for idle sched class and ext sched class are present.
At the present, layered would exit if those addresses were unobtainable.
still works when kallsyms present for both the skip and not-skip cases:
=> layered: cleanup skip-preempt

scheds/rust/scx_rustland/src/main.rs
Remove redundant clone and map lookup in `TaskTree::push`. 
This reduces memory operations and simplifies the code, improving runtime efficiency.
=> scx_rustland: Simplify TaskTree push logic

scheds/rust/scx_rustland/src/main.rs
The else branch in `TaskTree::pop` was returning `None` explicitly, even though that is already the default behavior when using `Option::map`. This refactor simplifies the logic and improves readability by adopting a more idiomatic Rust approach.
No change in functionality; this is a cleanup for clarity.
=> scx_rustland: Refactor TaskTree pop to remove redundant else

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/types.h
In order to avoid an extra map lookup on select/enqueue cache the node CPU make on the llc_ctx. This yields a measurable improvement in wakeup latency and benchmark throughput.
`main` schbench results:
```
Wakeup Latencies percentiles (usec) runtime 30 (s) (127035 total samples)
50.0th: 13         (29827 samples)
90.0th: 19         (52666 samples)
* 99.0th: 200        (8148 samples)
99.9th: 1526       (1143 samples)
min=1, max=6667
Request Latencies percentiles (usec) runtime 30 (s) (127364 total samples)
50.0th: 3596       (39633 samples)
90.0th: 7096       (48713 samples)
* 99.0th: 8784       (11040 samples)
99.9th: 17760      (1143 samples)
min=3326, max=35616
20.0th: 4328       (10 samples)
* 50.0th: 4360       (11 samples) …
```
=> scx_p2dq: Cache node CPU masks on llc_ctx

scheds/rust/scx_rustland/src/main.rs
1. Replaces a match statement with an if-let binding in dispatch_tasks, as the None arm was unused.
2. Also replaces a match on Result with an is_err() check, since only the Err case was handled and the Ok arm was empty.
=> scx_rustland: Refactor dispatch_tasks to simplify control flow

scheds/rust/scx_rustland/src/main.rs
Replaces a match on Result with an is_ok() check, since only the Ok case was meaningful.
=> scx_rustland: simplify monitor request handling in run()

rust/scx_rustland_core/assets/bpf/main.bpf.c
Certain pipe-intensive workloads are not capable of maxing out all available CPUs.
Improve this by routing the wakee to the waker's CPU during sync wakeups. This helps maintain locality and balance load more effectively, improving overall CPU utilization.
Example (using
https://github.com/marioroy/mce-sandbox/blob/main/bin/algorithm3.pl):
$ ./algorithm3.pl 1e12 --threads=8
- before:
```
0[||||||||||||||||||      58.3%]   4[|||||||||||||||||||||||100.0%]
1[||||||||||||||||||||||||85.9%]   5[||||||||||||||||||||||||95.6%]
2[||||||||||||||||||||||||87.8%]   6[||||||||||||||||||||||||91.2%]
3[|||||||||||||||||||||||100.0%]   7[||||||||||||||||||||||||94.4%]
```
- after:
```
0[|||||||||||||||||||||||100.0%]   4[|||||||||||||||||||||||100.0%]
1[|||||||||||||||||||||||100.0%] …
```
=> scx_rustland_core: Improve sync wakeups

scheds/rust/scx_tickless/src/bpf/main.bpf.c
Fix the following build warning:
```
warning: scx_tickless@1.0.3: src/bpf/main.bpf.c:674:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
warning: scx_tickless@1.0.3:   674 | }
warning: scx_tickless@1.0.3:       | ^
```
No functional change.
=> scx_tickless: Fix build warning

scheds/c/scx_qmap.bpf.c
As SCX_EV_ENQ_SLICE_DFL was renamed to SCX_EV_REFILL_SLICE_DFL, update the relevant scheduler code to synch with the kernel changes [1].
[1] https://lore.kernel.org/lkml/20250418032603.61803-2-jameshongleiwang@126.com/
=> scx_qmap: Sync with the kernel changes to fix a build break.

rust/scx_stats/src/server.rs
Replaces a match on Result with an is_err() check in the proxy loop, since only the Err case was meaningful and the Ok arm was empty.
=> scx_stats: simplify channel send error handling with is_err()

scheds/rust/scx_lavd/src/bpf/balance.bpf.c, scheds/rust/scx_lavd/src/bpf/idle.bpf.c, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c
Previously, load balancing assumed that all CPUs were in active sets and had
the same capacity. Also, it aims to equalize the DSQ length of each domain.
However, it does not work well if a system has heterogeneous processors
(big/LITTLE) or is under-loaded (i.e., DSQ lengths are all zero).
Thus, let's make the load-balancing core compaction and CPU capacity aware.
The load balancing now considers the active CPUs and each CPU's capacity.
The load balancing aims for two goals:
1) The *non-scaled* CPU utilizations of all active CPUs should be the same or
similar. This helps to maintain low latency when the system is underloaded.
2) The *scaled* queue lengths of active compute domains should be the same or
similar. Using scaled queue length allows putting more tasks to the powerful
compute …
=> scx_lavd: Make the load balancing core compaction- and capacity-aware.

rust/scx_utils/src/perf.rs
On glibc, the ioctl() function takes an unsigned 32-bit integer. However, on other platforms such as musl, it instead takes a signed 32-bit integer. When perf_wrapper.h was being processed through bindgen, it was internally representing the enum variants as u32, which caused issues on musl where ioctl expects an i32. This commit does away with the perf_event_ioctls enum entirely, instead using constant uint16_t values to ensure they can be passed to ioctl on both glibc and musl systems.
=> scx_utils: cast ioctl opcodes to libc::Ioctl

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Do not lookup task cpu_ctx unless adjusting vtime when migrating. This lowers the latency of wakeups for p2dq.
=> scx_p2dq: Optimize enqueue path lookups

scheds/rust/scx_p2dq/src/lib.rs
Add select_idle_in_enqueue flag to optionally enable select idle CPU in the enqueue path. Enabling this option may lead to better CPU selection at the cost of wakeup latency.
(new) default disabled:
```
Wakeup Latencies percentiles (usec) runtime 30 (s) (411907 total samples)
50.0th: 6          (131894 samples)
90.0th: 9          (122217 samples)
* 99.0th: 13         (28193 samples)
99.9th: 106        (3104 samples)
min=1, max=17011
Request Latencies percentiles (usec) runtime 30 (s) (412632 total samples)
50.0th: 6568       (122113 samples)
90.0th: 10736      (162216 samples)
* 99.0th: 12368      (37024 samples)
99.9th: 16144      (3570 samples)
min=5831, max=105697
20.0th: 13744      (7 samples)
* 50.0th: 13808      (10 …
```
=> scx_p2dq: Add --select-idle-in-enqueue flag

scheds/rust/scx_bpfland/src/main.rs
Replaces a match on Result with an is_err() check, since only the Err case was meaningful and the Ok arm was empty.
=> scx_bpfland: simplify error handling for sibling CPU setup

scheds/rust/scx_lavd/src/bpf/balance.bpf.c, scheds/rust/scx_lavd/src/bpf/idle.bpf.c, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c
When the system is underloaded, task stealing does not work well since there is almost always no task in DSQ.
To address this problem, when the system is underloaded, perform task donation at ops.select_cpu() and ops.enqueue() paths.
More specifically, try task donation when the sticky domain is a stealee domain (i.e., relatively overloaded) and there is no fully idle CPU on the sticky domain while picking an idle CPU at ops.select_cpu() and ops.enqueue(). In this case, traverse neighbor domains in distance order, find a fully idle CPU, and migrate the domain having the fully idle CPU.
=> scx_lavd: Donate tasks at ops.select_cpu() and ops.enqueue().

scheds/rust/scx_lavd/src/main.rs
When starting the scheduler, CPU preference orders for performance and power-save modes were printed. Printing unnecessary information (e.g., the power-save order when the performance option is specified) would confuse the user. So let's print only relevant information.
=> scx_lavd: Don't print unnecessary CPU preference orders.

rust/scx_rustland_core/assets/bpf.rs, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/src/main.rs
Previously, errors during sibling CPU setup were silently ignored, making failures hard to debug. Now they are returned with context as `io::Error,` allowing the caller to handle them as needed.
Ref: #1866
=> scx_rustland_core: propagate errors from enable_sibling_cpu_fn

scheds/rust/scx_lavd/src/main.rs
Remove unnecessary parentheses in `if` conditions.
=> scx_lavd: make rustfmt happy

rust/scx_rustland_core/assets/bpf/main.bpf.c
Remove the unused variable `cpu` from dispatch_task() in main.bpf.c. The variable was never read or assigned, and its presence triggered a -Wunused-variable warning during BPF compilation.
Log:
```
warning: scx_rlfifo@1.0.12: main.bpf.c:548:6: warning: unused variable 'cpu' [-Wunused-variable]
warning: scx_rlfifo@1.0.12:   548 |         s32 cpu;
warning: scx_rlfifo@1.0.12:       |             ^~~
warning: scx_rlfifo@1.0.12: 1 warning generated.
warning: scx_rustland@1.0.12: main.bpf.c:548:6: warning: unused variable 'cpu' [-Wunused-variable]
warning: scx_rustland@1.0.12:   548 |         s32 cpu;
warning: scx_rustland@1.0.12:       |             ^~~
warning: scx_rustland@1.0.12: 1 warning generated.
```
=> scx_rustland_core: drop unused variable

rust/scx_loader/configuration.md, rust/scx_loader/src/config.rs, rust/scx_loader/src/lib.rs, rust/scx_loader/src/main.rs
With the recent changes, scx_rustland has become quite a stable scheduler. Although there are more stable and sensible choices for the user, rustland also performs well.
Moreover, integrating scx_rustland into scx_loader will make it much easier to test new changes and pull requests.
```
lucjan at cachyos ~ 11:23:28    
❯ scxctl list          
supported schedulers: ["bpfland", "flash", "lavd", "p2dq", "tickless", "rustland", "rusty"]
lucjan at cachyos ~ 11:23:37    
❯ scxctl start -s rustland
started Rustland in Auto mode
lucjan at cachyos ~ 11:23:46    
❯ systemctl status scx_loader.service
● scx_loader.service - DBUS on-demand loader of sched-ext schedulers
Loaded: loaded (/usr/lib/systemd/system/scx_loader.service; disabled; preset: disabled)
Active: active (running) since Fri …
```
=> scx_loader: Add rustland scheduler

scheds/rust/scx_rlfifo/src/main.rs
Enable built-in idle selection policy from BPF and allow tasks to be migrated to other CPUs when the system is saturated.
These changes improve the scheduler's viability and robustness, making it potentially suitable even for certain production environments.
=> scx_rlfifo: Make the scheduler more viable

scheds/rust/scx_rustland/src/main.rs
If too many tasks are piling up in the user-space scheduler we may risk to hit stall conditions.
To prevent this, introduce a congestion threshold: when the number of waiting tasks exceeds this threshold, the scheduler will proactively flush the queue to bring the task count back below the critical level.
This helps handle heavy stress tests that might flood the system with a high volume of tasks.
=> scx_rustland: Introduce a congestion threshold

scheds/rust/scx_chaos/src/main.rs
Replace match statement with an if-let binding, as the Ok arm is empty.
=> scx_chaos: Refactor thread join error handling

scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/main.rs
Increase the minimum time slice from 300 usec to 500 usec since 500 usec seems generally works better.
=> scx_lavd: Change the min slice to 500us.

rust/scx_utils/src/cpumask.rs, rust/scx_utils/src/misc.rs, rust/scx_utils/src/topology.rs
A case was reported that /sys/devices/system/cpu/cpuX/acpi_cppc/highest_perf
have the same value for all CPUs on an Intel hybrid processor (i7-13650hx).
This should be a bug on the driver's side.
To circumvent such a problem, make more efforts to find a source that can tell
the capacity differences among the cores. If there is no such source, resort
to the max frequency of CPUs to estimate CPU capacity.
This should solve the following issue:
https://github.com/sched-ext/scx/issues/1893
=> scx_utils: Choose a CPU capacity source more judiciously.

rust/scx_rustland_core/src/alloc.rs
Replaces match statements with if-let bindings, as the OK arms were empty.
=> scx_rustland_core: Refactor memory lock/unlock error handling

rust/scx_rustland_core/assets/bpf/main.bpf.c
Letting the kernel directly dispatch migration-disabled tasks can lead to inefficiencies and unfairness, as these tasks bypass the user-space scheduler and override others. They also receive the default time slice, which can further amplify the imbalance.
To address this, enable SCX_OPS_ENQ_MIGRATION_DISABLED so that migration-disabled tasks are enqueued and managed by the user-space scheduler like all other tasks.
=> scx_rustland_core: Ensure migration-disabled tasks are always enqueued

rust/scx_utils/src/topology.rs
Initialize `raw_capacity` only when needed to avoid warning.
Ref: #1893
Log:
```shell
warning: value assigned to `raw_capacity` is never read
--> rust/scx_utils/src/topology.rs:606:13
|
606 |     let mut raw_capacity = 0;
|             ^^^^^^^^^^^^
|
= help: maybe it is overwritten before being read?
= note: `#[warn(unused_assignments)]` on by default
warning: `scx_utils` (lib) generated 1 warning
```
=> scx_utils: Remove unused assignment warning

rust/scx_utils/src/gpu.rs
So to gives a hint about the memory bandwith to do a better workload placement. Can be useful later if NVML leverages Multi Instances GPU data.
=> scx_utils: gpu topologyu add GPU's VRAM (max) clock frequency data.

DEVELOPER_GUIDE.md
Add `systing` to the developer guide. `systing` can be used to generate detailed perfetto traces for debugging performance and scheduling issues.
=> docs: Add systing to developer guide

rust/scx_rustland_core/README.md, scheds/rust/scx_rlfifo/src/main.rs
This patch updates the comments for `exec_runtime` and `sum_exec_runtime` in the `QueuedTask` struct to better reflect their distinct meanings.
=> docs: clarify QueuedTask time field comments

Cargo.lock, rust/scx_rustland_core/Cargo.toml, rust/scx_rustland_core/README.md, rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/intf.h, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/include/scx/common.bpf.h, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/Cargo.toml, scheds/rust/scx_rustland/src/main.rs
This PR provides multiple improvements for scx_rustland_core and scx_rustland both in terms of performance and robustness.
Summary of the changes:
- scx_rustland_core:
- The `struct QueuedTask` now provides `ops.running()` and `ops.stopping()` timestamps for a more accurate time slice evaluation. The struct has been also made more compact, dropping some attributes that can be inferred, reducing its size to 64 bytes (small enough to typically fit in a single cacheline).
- Reduced some unnecessary overhead in the idle CPU selection policy (the checks for online CPUs have been removed, since on hotplug events the scheduler is restarted anyway).
- kswapd is now always directly dispatched from BPF to prevent potential stall conditions 
- scx_rustland:
- Improved accuracy of the time slice …
=> scx_rustland_core / scx_rustland: Multiple improvements

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs
Add fifo scheduling option for interactive tasks. Performance tests on benchmarks was pretty similar to vtime scheduling.
=> scx_p2dq: Add fifo scheduling for interactive tasks

scheds/rust/scx_rusty/src/load_balance.rs, scheds/rust/scx_wd40/src/load_balance.rs
Replace redundant `match` expression with a direct call to `next()`, which already returns an `Option`.
Edit: Change title prefix to `load_balance`
=> load_balance: Refactor `find_first_candidate`

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Exclusive flag was really leaky - e.g. it wasn't excluding idle CPU picking so it was really easy for other tasks to occupy the preempted sibling. This PR improves exclusive handling so that it's a lot less leaky (the sibling is a lot more likely to stay idle) and exclusive tasks can share siblings when there are no CPUs left.
=> scx_layered: Make exclusive work better

scheds/rust/scx_chaos/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs
Saw a few hotpaths in profiling that don't need to be enabled by default. The first is that the runnable callback doesn't really do anything critical and causes redundant map lookups.
CPU frequency control can be disabled by default and enabled if a relevant CPU frequency governor is used. This saves some extra lookups in the running path, which is rather hot.
Running `schbench` to partially saturate a machine with `p2dq`:
```
Wakeup Latencies percentiles (usec) runtime 30 (s) (409578 total samples)
50.0th: 6          (126999 samples)
90.0th: 9          (133771 samples)
* 99.0th: 13         (29130 samples)
99.9th: 95         (3589 samples)
min=1, max=7852
Request Latencies percentiles (usec) runtime 30 (s) (410428 total samples)
50.0th: 6616       (127589 samples)
90.0th: 10768 …
```
=> scx_p2dq: Optimize default hot paths

lib/sdt_alloc.bpf.c
Update aarch64 compat ifdef -- the current ifdef doesn't work on all aarch64 machines. This change makes it work on more.
=> arenas: update aarch64 compat ifdef

rust/scx_rustland_core/assets/bpf.rs, scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_flash/src/main.rs, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_mitosis/src/main.rs, scheds/rust/scx_p2dq/src/main.rs, scheds/rust/scx_rusty/src/main.rs, scheds/rust/scx_tickless/src/main.rs, scheds/rust/scx_wd40/src/main.rs
Use `let _ = self.struct_ops.take();` to explicitly discard the return value and suppress potential warnings. This makes the intent clearer, indicating that the call is made purely for its side effect.
Ref : https://doc.rust-lang.org/core/option/enum.Option.html#method.take
=> rust: Handle return value from `Option::take`

scheds/rust/scx_layered/src/bpf/main.bpf.c
It turns out the verification failure was from the verifier not being able to know whether the loop will execute at all and thus leading to verifier thinking that the function could return an uninitialized variable.
Fix it by always initializing $cpu expicitly.
=> scx_layered: Remove loop workaround in pick_idle_cpu_from()

Cargo.lock, scheds/rust/scx_mitosis/Cargo.toml, scheds/rust/scx_mitosis/src/bpf/intf.h, scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c, scheds/rust/scx_mitosis/src/main.rs
This more or less completely reworks mitosis to allocate cells based on static CPU pinning. If it sees a cgroup with a cpuset configured, it will dynamically allocate a new cell and otherwise schedule as before. Eventually I expect to add back in the dynamic cell creation from userspace, but for now it's not needed.
=> scx_mitosis: Strip down for static cpu pinning

meson-scripts/stress_tests.ini, scheds/rust/scx_chaos/src/bpf/main.bpf.c
select_cpu currently returns -EINVAL if the chaos mode should skip p2dq's select_cpu. This isn't valid and leads to an error in the kernel. Update this to return `prev_cpu` instead. Also rename the helper as the current name seems incorrect.
Symptom:
```
DEBUG DUMP
================================================================================
swapper/28[0] triggered exit kind 1024:
runtime error (invalid CPU -22 from ops.select_cpu())
Backtrace:
ops_cpu_valid+0x58/0x80
select_task_rq_scx+0xe9/0x1b0
try_to_wake_up+0x165/0x790
call_timer_fn+0x2a/0x130
__run_timers+0x206/0x2a0
timer_expire_remote+0x4a/0x70
tmigr_handle_remote_up+0x2e5/0x350
__walk_groups.isra.0+0x22/0x80
tmigr_handle_remote+0xa0/0xf0
handle_softirqs+0xe4/0x2f0
__irq_exit_rcu+0xd6/0x100
sysvec_apic_timer_interrupt+0x73/0x80 …
```
=> chaos: return prev_cpu instaed of -EINVAL in select_cpu

.github/workflows/integration-tests.yml
Rustland got disabled on these stable kernels a while ago because it kept failing. This has hopefully been addressed now, so enable these tests again.
Tracking in #1794. If this is stable for a while we can close that issue.
Test plan:
- Added push to 6.12/rolling-stable. They passed. Will track over time after it lands.
=> ci: re-enable rustland on stable kernels

.github/include/flake.lock, .github/include/flake.nix, .github/include/veristat.nix, .github/workflows/integration-tests.yml, meson-scripts/veristat
We currently grab a pre-built binary for veristat. This is reproducible, but not ideal. Build it from source with Nix.
Test plan:
- CI
- Verified the veristat output is there in the uploaded pack. It is.
=> nix: build veristat from source

scheds/rust/scx_layered/src/bpf/main.bpf.c
improve compat of excl fixes on older kernels
older verifiers need the extra check on prev_layer and pulling out sib_keep_idle to reduce complexity (instruction count).
=> layered: improve compat of excl fixes on older kernels

Cargo.lock, scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c, scheds/rust/scx_lavd/src/main.rs
Limit the ratio of preemption to the roughly top P% of latency-critical tasks. When N is given as an argument, P is 0.5^N * 100. The default value is 6, which limits the preemption for the top 1.56% of latency-critical tasks.
=> scx_lavd: Add --preempt-shift option.

scheds/rust/scx_rustland/src/main.rs
Similarly to other Rust schedulers, always print the version info to stdout when the scheduler is loaded.
This can help for debugging and testing.
=> scx_rustland: Show version info

scheds/rust/scx_p2dq/src/main.rs
Call the topology print test after attaching to verify arena setup and suppress dead_code warning.
<details>
<summary> Edit : Warning log</summary>
```shell
warning: method `print_topology` is never used
--> scheds/rust/scx_p2dq/src/main.rs:266:8
|
95  | impl<'a> Scheduler<'a> {
| ---------------------- method in this implementation
...
266 |     fn print_topology(&mut self) -> Result<()> {
|        ^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: `scx_p2dq` (bin "scx_p2dq") generated 1 warning
```
=> scx_p2dq: Call print_topology after attaching scheduler

.github/actions/install-nix/action.yml, .github/workflows/6_12.yml, .github/workflows/bpf-next-test.yml, .github/workflows/caching-build.yml, .github/workflows/stable.yml
Reusable workflows can't read secrets by default. This meant that jobs under `integration-test.yml` couldn't upload artifacts to the Nix cache, causing some cache misses. As we own and trust this workflow, inherit all secrets.
Do a little cleanup in `install-nix` to make the use of "self-hosted" uniform.
Test plan:
- CI
- Previously "Post Install Nix" reported that it couldn't upload artifacts due to a missing key. Now it works and veristat isn't always a cache miss.
=> ci: fix CACHIX_AUTH_TOKEN access in integration-tests

.github/actions/install-nix/action.yml, .github/include/flake.nix, .github/workflows/integration-tests.yml, .github/workflows/update-kernels.yml
Currently any builds completed with Nix dependencies use the default nix clang, which is "empty" and wrapped to make it functional. Although this appears to work completely fine, it spews a load of warnings about unused arguments and this specific wrapper being only meant for x86_64 (or other native system).
Write a custom wrapper for the unwrapped Nix clang that only provides the necessary arguments. This also exposes a dependency on kernel headers. For now, use the sched_ext/for-next headers, but leave this open to a matrix in the future.
This change:
- Adds bpf-clang to get rid of the warnings and explicitly depend on kernel headers.
- Creates a default development shell for users who want to grab a working set of dependencies with `nix develop ./.github/include` or something like …
=> nix: add bpf-clang derivation

rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/main.bpf.c
Some small optimizations, cleanups and refactoring aimed at making the code more understandable, especially the BPF -> user-space scheduler activation workflow.
In particular, the user-space scheduler is now dispatched using a separate DSQ (reducing the overhead a bit on the shared DSQ),  SCX_LOCAL_DSQ / SCX_LOCAL_DSQ_ON are used when possible to reduce the overhead on the per-CPU shared DSQs and per-CPU kthreads are not allowed to preempt other tasks (which is overkill and it only introduced unnecessary context switches).
=> scx_rustland_core: Minor optimizations

scheds/rust/scx_layered/src/bpf/main.bpf.c
It was returning false when the CPU should go idle. Flip it.
=> scx_layered: Flip the return polarity of sib_keep_idle()

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
When updating the vtime of a task moving across LLCs give tasks with a lower weight a boost in vtime. Refactor vtime updating into a helper method and update the enqueue method to properly update vtime after selecting a CPU.
=> scx_p2dq: Refactor vtime handling of migrating tasks

scheds/rust/scx_layered/src/bpf/main.bpf.c
select_cpu/enqueue() looks for an idle CPU and if there is none, the task is queued to the layer's DSQ. However, a CPU can go idle between select_cpu/enqueue() checking idle cpumaks and the task being queued on DSQ:
```
CPU A                      CPU B
-------------------------------------------------
Waking task P
Look for idle CPU
No CPU idle
Going idle
Set idle bit
Enqueue P on layer DSQ
Enters idle
```
This leads to task P waiting in a DSQ while CPU B is sitting idle. This patch updates enqueue() and update_idle() so that:
- After enqueue() puts a task in a DSQ, it looks for idle CPUs one more time and if any is idle, kick it.
- update_idle() scans eligible DSQs. If any is occupied, kicks itself.
Combined with kernel update to update built-in idle mask before calling …
=> scx_layered: Fix race condition between picking an idle CPU and the CPU going idle

scheds/rust/scx_chaos/src/lib.rs, scheds/rust/scx_p2dq/src/lib.rs, scheds/rust/scx_p2dq/src/main.rs
c5cb9b4 recently started using the arena to store data for the topology in scx_p2dq. This wasn't fully implemented for chaos so chaos lost visibility of the topology abstraction, causing certain failures. Implement a trait on the p2dq/chaos skeletons to expose this functionality, and call it in the shared `init_skel` macro rather than in each scheduler. The trait approach was chosen as a compromise between code duplication and being stuck in macros for this sort of work.
Test plan:
- CI
=> p2dq/chaos: add trait for skeletons that can have their arenas setup

.github/actions/build-kernel/action.yml
Discussion in #1881 exposed a gap in the kernel caching process.
Current behaviour:
- Forked PR that changes the kernel fails to upload to the cache and future steps miss, wasting runner time. This is basically intended. Most kernel updates do not come from forked PRs - it does finish eventually.
- GitHub merge queue created branch has the perms, but GHA runners still miss the cache and one of those eventually uploads it after a build (they all build it).
- Entry is already cached by the time the PR is merged, meaning no one else has a cache miss.
This PR addresses the middle case. It was missing before because the self-hosted runner had already hit its local Nix store, and hence didn't upload the "new" result because the result isn't "new" (it was already built by the forked PR). Now we …
=> ci: push kernel and headers to cachix explicitly

rust/scx_rustland_core/README.md, rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/intf.h, rust/scx_rustland_core/assets/bpf/main.bpf.c, scheds/rust/scx_rlfifo/src/main.rs
Drop the internal cpumask generation counter from the task context shared with user-space (it's just easier to check the validity of the target CPU using `p->cpus_ptr`) and expose `p->nr_cpus_allowed` to the user-space scheduler, which can use this information to implement better scheduling policies.
After these changes the size of `QueuedTask / queued_task_ctx` is still 64 bytes, that still fits in a cacheline (typically) and it corresponds to the minimal allocation size in the custom user-space memory allocator, and the size of `DispatchedTask / dispatched_task_ctx` is reduced from 40 bytes to 32 bytes.
=> scx_rustland_core:  Expose nr_cpus_allowed to user-space

scheds/rust/scx_rustland/src/main.rs
Introduce the new option --percpu-local that allows to dispatch per-CPU tasks directly to their only usable CPU when the system is saturated.
This allows to reduce the pressure on the shared global queue and provide a better level of performance isolation through affinity.
=> scx_rustland: Introduce --percpu-local

tools/scxtop/src/app.rs
scxtop displays the data for each local DSQ, which can become unusable given the large amount of local DSQs. Ex.:
In order, to make it more useful, we'll now group GLOBAL, LOCAL, and LOCAL_ON DSQs by using their respective [bitmasks](https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/sched/ext.h#n47). Ex.:
=> scxtop: aggregate GLOBAL and LOCAL DSQs

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
Add a matcher to layered to enable using the command `bpftool map dump layer_match_dbg` to determine which layers tids have been matched to.,
This shows a pid being there while it was alive and gone after it was killed:
```
scx on  layered-debug-map [!] is 📦 v1.0.12 via 🐍 v3.13.3 via 🦀 v1.87.0 
❯ sudo bpftool map dump name layer_match_dbg | jq '.[] | select (.key == '945031')'
{
"key": 945031,
"value": 3
}
scx on  layered-debug-map [!] is 📦 v1.0.12 via 🐍 v3.13.3 via 🦀 v1.87.0 
❯ sudo bpftool map dump name layer_match_dbg | jq '.[] | select (.key == '945031')'
```
=> layered: add match debug capability

rust/scx_rustland_core/src/alloc.rs
Unmapping/remapping pages in the user-space scheduler's address space can lead to stall conditions: completing the operation may requires a kthread to run, but the kthread cannot run because the user-space scheduler is blocked => deadlock.
To prevent this stall condition, disable transparent huge pages for the user-space scheduler task. This ensures that khugepaged won't touch those pages, thereby avoiding the stall.
=> scx_rustland_core: Disable THP for user-space scheduler

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/types.h
When tasks stop in p2dq only update the DSQ if the task is no longer runnable. This improves accounting of task utilization by not penalizing tasks that run for different intervals.
Suggested-by: Emil Tsalapatis <aimilios.tsalapatis@gmail.com>
=> scx_p2dq: Improve accuracy of runtime accounting

Cargo.lock, rust/scx_rustland_core/assets/bpf.rs, rust/scx_rustland_core/assets/bpf/main.bpf.c, rust/scx_rustland_core/src/alloc.rs, scheds/rust/scx_rlfifo/Cargo.toml
khugepaged can arbitrarily unmap and remap memory pages in any user-space task at any time.
If this happens for the user-space scheduler task, we may trigger the following stall scenario:
- kugepaged umaps a page in the user-space scheduler's address space
- khugepaged is de-scheduled and re-enqueued
- user-space scheduler is blocked waiting for its page to be remapped
- khugepaged can't be scheduled again
- stall
Prevent this by always dispatching khugepaged directly, allowing it to bypass the user-space scheduler.
With that in place, we can even hint khugepaged to use huge pages for the preallocated memory arena used by the scx_rustland_core allocator and avoid disabling huge pages entirely.
=> scx_rustland_core: Always dispatch khugepaged directly

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
Associate each layer in the scheduler with the cpuset of the tasks running in the layer. This will be used in the future to improve support for containers that have associated cpusets.
=> scx_layered: associate each layer with a cpumask

lib/bitmap.bpf.c
scx_bitmap_empty() was incorrectly returning true when any bit was set.
=> bitmap: Fix scx_bitmap_empty() to return correct result

lib/bitmap.bpf.c
- Fix a logic bug in scx_bitmap_clear_cpu() where the bitmask was incorrectly computed as `1 << ~(...)`, leading to UB.
- Replace all int-based shifts with `1ULL` to ensure safe and portable 64-bit bit-op when manipulating CPU bitmaps.
=> bitmap: Fix clear_cpu logic and replace int-based shifts

tools/scxtop/src/app.rs
Adds the default instruction "d" to the help menu.
=> scxtop: add default instruction to help page

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/types.h
Refactor pick_idle_cpu to split out affinitized task handling to pick_idle_affinitized_cpu. This makes the code for handling affinitized tasks easier to follow. Remove the `cpu` field from the `taskc_ctx` as this can easily be queried with `scx_bpf_task_cpu`.
=> scx_p2dq: Refactor pick_idle_cpu for affinitized tasks

lib/sdt_task.bpf.c
Add a check for failed allocation when calling scx_alloc().
=> lib/sdt_task: Handle allocation failure

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
When selecting an idle CPU mask for affinitized tasks reset the temporary CPU mask used for finding an idle CPU. This fixes stalls in affinitized task handling under heavy load.
Tested with:
```
$ stress-ng --affinity-rand  --affinity 170 -t 35 -c 100 --affinity-delay 10 --affinity-sleep 10
stress-ng: info:  [334880] setting to a 35 secs run per stressor
stress-ng: info:  [334880] dispatching hogs: 170 affinity, 100 cpu
stress-ng: info:  [334880] skipped: 0
stress-ng: info:  [334880] passed: 270: affinity (170) cpu (100)
stress-ng: info:  [334880] failed: 0
stress-ng: info:  [334880] metrics untrustworthy: 0
stress-ng: info:  [334880] successful run completed in 35.08 secs
```
=> scx_p2dq: Fix stalls in affinitized tasks

tools/scxtop/src/app.rs, tools/scxtop/src/keymap.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs, tools/scxtop/src/tui.rs
See #1221 for initial issue. This update enables filtering perf events in TUI with fuzzy matching (#1989). 
The main challenge was determining how to differentiate standard keybindings from input. To do this, the code checks if the current state is AppState::Event, and if so, places characters into an input buffer as opposed to using the standard character keybindings. The escape button can be used to exit the event selection page (and can now also be used throughout the entire tool as an alternative to 'q'). Here's a quick visual view for how this works:
Additionally, the scrollbar for the event selection menu has been fixed and now functions as expected.
Example usage:
https://github.com/user-attachments/assets/84038890-43e6-4b3d-86b4-394822843a2c
=> scxtop: enabling filtering perf events via input

lib/cpumask.bpf.c, lib/topology.bpf.c, scheds/include/lib/topology.h, scheds/rust/scx_wd40/build.rs, scheds/rust/scx_wd40/src/bpf/main.bpf.c, scheds/rust/scx_wd40/src/domain.rs, scheds/rust/scx_wd40/src/main.rs
Bring scx_wd40 up to speed with the other schedulers:
1) Use the most recent arena syscall API to set up allocator state
2) Initialize the arena BPF topology tree for the scheduler
3) Introduce a new topology call in lib/topology that will be used in subsequent diffs to simplify the code
=> scx_wd40: integrate with topology add level calculation topology call

scheds/rust/scx_rusty/src/bpf/sdt_alloc.bpf.c, scheds/rust/scx_rusty/src/bpf/sdt_task.bpf.c
Here are the changes I made:
- Handle allocation failure.
- Fix incorrect NULL check.
- Unlock std_lock after allocation.
- Switch to new mem block. 
- ~[RFC] Recompute padding on allocation $\to$ should this align with `*scx_static_alloc(size_t bytes, size_t alignment)` ?~
Edit:
- Fix tab usage.
=> scx_rusty: arena library backports

lib/sdt_alloc.bpf.c, lib/topology.bpf.c, scheds/include/lib/topology.h, scheds/rust/scx_wd40/src/bpf/main.bpf.c
Many schedulers like scx_rusty often keep arrays of IDs for all LLCs and NUMA nodes in the systems that they use travesre linearly during operations like load balancing. We can offer a unified interface for such traversals through iterators on the base topology struct. Introduce an in-order iteration algorithm for topology nodes with the aim of replacing per-scheduler bookkeeping in the future.
=> lib/topo: rework topology traversal

scheds/include/scx/ravg_impl.bpf.h
Mark the array as `const` to reflect its read-only nature.
=> ravg_impl: Declare ravg_full_sum as const

tools/scxtop/src/bpf/main.bpf.c
The `state` field was incorrectly overwritten by `idx` and `ret`.
=> scxtop: Fix incorrect overwrite

scheds/rust/scx_layered/src/main.rs
Add a flag to layered for printing the layer config, including any autogenerated template layers, and exiting.
=> scx_layered: add option for printing layer config and exiting

scheds/rust/scx_layered/src/main.rs
Templates are supposed to specialize layers to a cgroup by adding a new term to the per-layer matcher. However, this new term is currently being added as an or-term to the matcher, while we should instead be adding it as an and-term for each or-term. Fix this by adding the new condition to each or-term in the layer.
=> scx_layered: add template suffix as and term to each or block

tools/scxtop/src/app.rs
Adding some helpful instructions in the event and help page:
Event page - explaining how to exit
Help page - adding a link to this github for issues or to get involved
=> scxtop: adding guiding instructions

rust/scx_stats/README.md, rust/scx_stats/examples/client.rs, rust/scx_stats/examples/server.rs, rust/scx_stats/src/server.rs, rust/scx_stats/src/stats.rs, rust/scx_utils/src/bpf_builder.rs, rust/scx_utils/src/misc.rs, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs, scheds/rust/scx_layered/src/stats.rs
Avoid unnecessary use of `&` in formatting macros like `info!` and `warn!` for cleaner ~and more idiomatic~ Rust code.
Edit: Since what is considered idiomatic can be subjective.
=> rust: Remove redundant references in log statements

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/types.h, scheds/rust/scx_p2dq/src/lib.rs
Fix LLC id handling by distinguishing the LLC id from the system perspective from the LLC index for iteration order. This fixes potential issues where LLCs may have LLC ids that are non incremental.
Cleanup dispatch_pick_two and remove the pick_two_llc_ctx helper method. Add new helper methods for consuming from LLCs consume_llc and consume_llc_compat. Update the load balancing so that when pick two load balancing is done both LLCs can be attempted if one LLC has no tasks. This provides better work conservation.
I had a few of these ideas after a long debugging session with @yaakov-stein.
Perf tests on partially loaded on large LLC system (AMD Bergamo):
`main`:
```
Wakeup Latencies percentiles (usec) runtime 30 (s) (405962 total samples)
50.0th: 10         (151118 samples)
90.0th: 13 …
```
=> scx_p2dq: Fix LLC id handling and refactor load balancing

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs
Doing a full pick two load balance on the wakeup path is rather expensive and hurts performance. Deprecate the existing wakeup pick two load balancing in favor of the precomputed load timer based wakeup balancing.
=> scx_p2dq: Deprecate wakeup pick two load balancing

lib/sdt_task.bpf.c, scheds/rust/scx_rusty/src/bpf/sdt_task.bpf.c
~In scx_task_free(), after releasing the allocator index, invoke bpf_task_storage_delete() to remove the task's entry from the BPF map.~
~Also zero-initialize `mval->tid` so that no stale identifier remains in local storage.~
Edit: Remove redundant mval field updates after deletion.
=> sdt_task: Avoid use-after-free after deleting task_storage

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
There are two competing mechanisms that try to prioritize percpu kthreads. One goes off of is_preempt_kthread() test and allows preemption on all percpu kthreads; then, a recent commit added explicit logic to specify SCX_ENQ_PREEMPT in the kthread handling block in enqueue() and try_preempt_cpu(). Unify them so that:
- Don't let is_preempt_kthread() route percpu kthreads into the preemption path. The later kthread handling block does the same thing without all the preemption path hassles.
- Split is_preempt_kthread() test into is_percpu_kthread() and is_percpu_kthread_preempting(). The latter now only says yes if percpu_kthread_preempt is set and either percpu_kthread_preempt_all is set or the task is high priority.
- In the kthread handling block in enqueue(), SCX_ENQ_PREEMPT is added if …
=> scx_layered: Unify percpu kthread handling

lib/arena.bpf.c, lib/topology.bpf.c, scheds/include/lib/arena.h, scheds/include/lib/topology.h, scheds/rust/scx_chaos/src/lib.rs, scheds/rust/scx_p2dq/src/main.rs, scheds/rust/scx_wd40/src/main.rs
Refactor and expand the function signatures of the BPF test programs used to initialize scheduler state on startup. First, refactor the code to not require bouncing allocated mask pointers through a temporary global variable. Also add a currently unused argument for allocating per-topology node state at node creation time.
=> lib/arena: expand argument passing from userspace

lib/arena.bpf.c, lib/topology.bpf.c, scheds/include/lib/arena.h, scheds/include/lib/topology.h, scheds/include/scx/common.bpf.h, scheds/rust/scx_chaos/src/lib.rs, scheds/rust/scx_p2dq/src/main.rs
Topology nodes do not currently have identifiers, but existing code assumes they do. We do not fundamentally need identifiers because nodes are arena-based, so we can just hold a pointer to them. However, all existing schedulers add ids to LLCs/nodes/CPUs because they retrieve them from BPF arrays and maps. This mismatch makes integrating topologies with existing schedulers more complicated.
As a temporary measure, introduce a global indexing structure for accessing topology nodes. These are functionally identical to the arrays of structs used by existing schedulers, and should make it easier to adapt existing code to use topology nodes.
=> lib/topology: add user-provided ids to topology nodes

lib/topology.bpf.c, scheds/include/lib/topology.h, scheds/rust/scx_wd40/src/bpf/lb_domain.bpf.c, scheds/rust/scx_wd40/src/bpf/lb_domain.h, scheds/rust/scx_wd40/src/bpf/main.bpf.c, scheds/rust/scx_wd40/src/load_balance.rs, scheds/rust/scx_wd40/src/main.rs
Adjust scx_wd40 to use the node indices we added for the topology library, replacing scx_wd40's own arrays used for indexing. This also serves as a case study on how to use the topology indices on other schedulers.
=> scx_wd40: use topology IDs

.github/actions/build-kernel/action.yml, .github/include/flake.nix, DEVELOPER_GUIDE.md
The Nix flake currently presents our tracked kernels and they're accessible with commands like `nix build ./.github/include#kernels.sched_ext/for-next`. This is non-standard and breaks tools like `nix flake show` which can't understand that an attrset is present where it expects a string value.
Flatten this hierarchy and make kernels available at `#kernel_sched_ext/for-next`.
Test plan:
- Built a kernel. It works.
- `nix flake show` now passes.
- CI
```
jake@rooster:/data/users/jake/repos/scx/ > nix flake show ./.github/include
git+file:///data/users/jake/repos/scx?dir=.github/include&ref=refs/heads/jakehillion/better-nix-kernels&rev=9a182f0ba95596f352ea3c89f0b8abeafda9dc79
├───apps
│   ├───aarch64-darwin
│   │   └───update-kernels: app
│   ├───aarch64-linux
│   │   └───update-kernels: …
```
=> nix: remove nested attrset in kernels

.github/workflows/integration-tests.yml
p2dq has been failing on 6.12 for a while reducing the signal on our Slack messages about failure. Disable it on that kernel for now after adding an issue to track the fix.
Test plan:
- CI
=> ci: disable p2dq on 6.12

scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_chaos/src/main.rs, scheds/rust/scx_flash/src/main.rs, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_p2dq/src/main.rs, scheds/rust/scx_rustland/src/main.rs, scheds/rust/scx_rusty/src/main.rs, scheds/rust/scx_tickless/src/main.rs, scheds/rust/scx_wd40/src/main.rs
Rust-based schedulers previously logged UTC timestamps, which could be confusing. 
This change uses local time instead to improve clarity and match the user’s timezone.
Before (showing UTC):
With this PR (showing local time; e.g., I'm at UTC+8):
=> sched/rust: Use local time for log timestamps

scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
52e3ace ("scx_layered: Use only owned execution time when sizing
grouped layers") made grouped layers exclude open execution time when
determining the target number of CPUs. This was primarily to avoid
osciallting the sizes of grouped layers when confined layers' owned
protection statuses fluctuate; however, bb600e6 ("scx_layered: Simplify
owned execution protection") removed the source of most of such fluctuations
and the exclusion of open cputime made configuring grouped layers more
difficult as how much a layer open executes isn't something the user has
much control over.
Add a layer option to include open cputime in grouped layer sizing. We
should transition to make this the default behavior and eventually drop the
option.
Note that the upper bound of 1.0 for util_range is removed as …
=> scx_layered: Implement LayerKind::Grouped::util_includes_open_cputime

scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c
With recent kernels I'm getting a verifier error when trying to load scx_mitosis.
91: (b7) r1 = 1024                    ; R1_w=1024
; if (runtime_cpumask_size > CPUMASK_SIZE) { @ mitosis.bpf.c:853
92: (a6) if w1 < 0x401 goto pc+7      ; R1_w=1024
; scx_bpf_error("all_cpumask should not be NULL"); @ mitosis.bpf.c:885
100: (b7) r1 = 0                      ; R1_w=0
; if (bpf_core_type_matches(struct cpuset___cpumask_arr)) { @ mitosis.bpf.c:860
101: (16) if w1 == 0x0 goto pc+3      ; R1_w=0
; } else if (bpf_core_type_matches(struct cpuset___cpumask_ptr)) { @ mitosis.bpf.c:864
105: (b7) r1 = 1                      ; R1_w=1
106: (16) if w1 == 0x0 goto pc+29     ; R1_w=1
; err = bpf_core_read(&entry->cpumask, runtime_cpumask_size, @ mitosis.bpf.c:866
107: (79) r8 = *(u64 *)(r8 +216)
access …
=> scx_mitosis: fix bpf verifier error

rust/scx_loader/configuration.md, rust/scx_loader/src/config.rs, scheds/rust/scx_flash/Cargo.toml, scheds/rust/scx_flash/src/bpf/intf.h, scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs, scheds/rust/scx_flash/src/stats.rs
As making changes to scx_bpfland without regressing someone’s workload has become increasingly difficult, I've decided to revamp scx_flash (which has been inactive for a while), port all the recent changes/features from scx_bpfland and re-align the two schedulers, so that we can use scx_flash as a playground to test new experimental changes.
This gives us a solid and stable baseline (scx_bpfland) to easily evaluate whether experimental changes in scx_flash are beneficial or not, comparing the two schedulers.
The core logic of tracking the rate of voluntary context switches to prioritize latency-sensitive tasks remains intact and is layered on top of scx_bpfland’s scheduling policy, see commit `8f7bd412 ("scx_flash: Reintroduce voluntary context switch-based prioritization"). Therefore the …
=> Rework scx_flash

lib/cpumask.bpf.c
cmpxchg returns the previous value, not the new one. To check for failure, the return value should not equal the expected old value.
Ref: PR #2102
=> lib/cpumask: Fix cmpxchg failure detection

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
When accounting for vtime only account for the scaled vtime at the task level rather than the LLC vtime. This prevents vtime from jumping for tasks that use niceness.
=> scx_p2dq: Fix vtime handling for nice tasks

lib/cpumask.bpf.c, scheds/include/lib/cpumask.h, scheds/include/scx/compat.bpf.h
Guard the bpf_cpumask_populate kfunc behind a __COMPAT define for backwards compatibility (see #2105).
=> compat: guard bpf_cpumask_populate behind __COMPAT macro

scheds/rust/scx_layered/src/bpf/main.bpf.c
We noticed regressions for production workloads due to recent changes. This pull request reverts one (which we will revisit by reintroducing a modified version of the patch after testing internally), and a fix for protected layers that causes idle selections to drop to 0 under layer saturation / load.
=> Fixes for layered regressions

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Add extra optional printk tracing on the select_cpu path. This is useful for debugging scheduler CPU selection.
The output format is as follows:
```
bpftool-23099   [002] d..41 216538.437586: bpf_trace_printk: SELECT [23100][grep] 8->8 idle 1
grep-23100   [008] d..41 216538.437596: bpf_trace_printk: SELECT [28086][kworker/u130:2] 12->12 idle 1
kworker/u130:2-28086   [012] d..41 216538.437603: bpf_trace_printk: SELECT [3758][tmux: server] 3->3 idle 1
grep-23100   [008] d..41 216538.437603: bpf_trace_printk: SELECT [26734][kworker/u130:3] 10->10 idle 1
bpftool-23099   [002] d.h31 216538.437607: bpf_trace_printk: SELECT [24396][scx_p2dq] 2->16 idle 1
grep-23100   [008] d..41 216538.437630: bpf_trace_printk: SELECT [28086][kworker/u130:2] 12->12 idle 1
```
=> scx_p2dq: Add tracing on select_cpu

scheds/rust/scx_flash/src/bpf/main.bpf.c
After a task is enqueued to the per-node DSQ we proactively wakeup an idle CPU usable by the task, potentially giving a quicker opportunity for the task to be consumed.
Like any idle CPU selection, we take into account the CPU previously used by the task as a preference. However, in this case, the task's domain might be not updated if the task has bounced across different CPUs without going through ops.select_cpu(), that is the only place where we refresh the preferred domains.
Therefore, make sure to refresh the task's preferred domains before applying the proactive wakeup logic.
=> scx_flash: Always update task domain before proactive wakeup

scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
Currently, the --slice-lag parameter serves a dual purpose: it limits both the maximum vruntime credit a task can accumulate while sleeping and the maximum execution time debit it can accumulate while running (i.e., the runtime since the last sleep).
To improve flexibility, use --slice-lag to control only the vruntime credit during sleep and introduce a new parameter, --run-lag, to separately cap the execution time debit.
This change allows users to experiment more effectively with different limits for sleep and run durations.
Example use case:
- Get a higher score with hackbench / perf bench, without compromising too much system responsiveness. :)
```
$ perf bench -f simple sched messaging -t -g 24 -l 10000
Time   | Responsiveness …
```
=> scx_flash: Introduce --run-lag

scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
Small refactoring to reduce the size of the task context and update the --help to explain more in details how the scheduler works.
=> scx_flash: Update help and small refactoring

.github/include/list-integration-tests.py, .github/include/update-kernels.py, .github/workflows/integration-tests.yml
The integration test matrix generation was not correctly finding CI-Test-Kernel trailers in PR commits due to incorrect base branch handling. This caused integration tests to always use the default kernel set rather than respecting trailer overrides.
Drive-by: fix naming of kernel update commits to include their kernel name.
Test plan:
- Pushed in JakeHillion/scx-ci-staging. Worked as intended.
- Created PRs in JakeHillion/scx-ci-staging. Works as intended, including with the new integration-tests/all-success job as the gate.
- Unsure if this works on merge queues until it goes through one. Will do my best to pull it out of the merge queue if the wrong thing happens.
CI-Test-Kernel: bpf/bpf-next
=> ci: fix kernel trailer detection in integration tests

rust/scx_utils/src/topology.rs
Some big/LITTLE architectures have less capacity gap [1], so tune thedifference threshold from 1.5x to 1.3x to cover such case.
[1] https://www.intel.com/content/www/us/en/products/sku/226257/intel-core-i31220p-processor-12m-cache-up-to-4-40-ghz/specifications.html
=> scx_utils: Tune the capacity gap threshold for correct detection of big/LITTLE.

scheds/rust/scx_bpfland/src/main.rs, scheds/rust/scx_chaos/src/main.rs, scheds/rust/scx_flash/src/main.rs, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_layered/src/main.rs, scheds/rust/scx_mitosis/src/main.rs, scheds/rust/scx_p2dq/src/main.rs, scheds/rust/scx_rustland/src/main.rs, scheds/rust/scx_rusty/src/main.rs, scheds/rust/scx_tickless/src/main.rs, scheds/rust/scx_wd40/src/main.rs
Log timestamps in local time rather than UTC.
Ref: #2081 (I forgot to update `scx_mitosis` :sweat_smile:)
=> scx_mitosis: Use local time for log timestamps

scheds/rust/scx_layered/src/main.rs
This PR makes cgroup template layers behave like regular layers when matching cgroups are not present.
For example, main does this when ran with template.json:
```
tot=      5 local_sel/enq=100.0/ 0.00 open_idle= 0.00 affn_viol= 0.00 hi/lo= 0.00/ 0.00
busy=  0.0 util/hi/lo=    0.2/ 0.00/ 0.00 fallback_cpu/util=  0/ 0.0 proc=0ms
excl_coll=0.00 excl_preempt=0.00 excl_idle=0.00 excl_wakeup=0.00
skip_preempt=0 antistall=0 fixup_vtime=0
the rest: util/open/frac=   0.2/100.0/  100.0 prot/prot_preempt= 0.00/ 0.00 tasks=   290
tot=      5 local_sel/enq=100.0/ 0.00 enq_dsq= 0.00 wake/exp/reenq= 0.00/ 0.00/ 0.00
keep/max/busy= 0.00/ 0.00/ 0.00 yield/ign= 0.00/    0 
open_idle= 0.00 mig= 0.00 xnuma_mig= 0.00 xllc_mig/skip= 0.00/ 0.00 affn_viol= 0.00
preempt/first/xllc/xnuma/idle/fail= 0.00/ 0.00/ …
```
=> layered: have template layers act as regular layers when no cgroup

scheds/rust/scx_layered/src/bpf/main.bpf.c
When there's excessive yields from a task that is not sharing its CPU with others, and yield_ignore is not 1, we enter the dispatch path and fail the keep_running() check, but the expectation is that, after checking our DSQs, we'll end up replenishing the slice, because we're the only task running on this CPU. However, we short circuit layer DSQ draining for protected layers, as we don't want to pull tasks from other layers onto our CPUs, and only check and consume our own DSQs.
Returning early causes the process to be enqueued again instead of being reenqueued into the local DSQ by default, since it's time slice has been exhausted. We must replenish it before return to restore the correct behavior.
Given we would have checked lo_fb again if this worked properly, place the jump label …
=> scx_layered: Replenish slice for protected layers

scheds/rust/scx_chaos/src/lib.rs
Replaced the if-let-else construct with Option::map() to simplify the creation of the stats_thread.
=> scx_chaos: Refactor stats_thread initialization using map()

scheds/rust/scx_mitosis/src/bpf/intf.h, scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c, scheds/rust/scx_mitosis/src/main.rs
Adds functionality to print:
• total queue placement decisions and share of global work
• per-queue percentages (Local, Default, Hi, Lo)
• affinity-violation percentage
Output is width-aligned and skips empty cells.
Output example:
Total Decisions:     6872 100.0% | L:92.7% D: 5.9% hi: 1.4% lo: 0.0% | V: 0.0%
Cell  0 Decisions:   6872 100.0% | L:92.7% D: 5.9% hi: 1.4% lo: 0.0% | V: 0.0%
Modifies BPF code to add three counters.
Modifies intf.h to extend cell_stat_idx enum.
Modifies main.rs to read maps, compute cell stat diffs, compute percentages, and log output.
=> scx_mitosis: log global + per-cell queue counts.

rust/scx_utils/src/user_exit_info.rs
Refactor exit_code() to use `.then_some()` instead of an explicit if-else branch.
=> scx_utils: Use .then_some() to simplify exit_code()

scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/stats.rs
Multiple preemptors can race and pick the same victim CPU and end up queueing multiple tasks on the same local DSQ severely impacting scheduling latencies.
While preemption, as implemented in scx_layered, has always been racy, c66e2c374904 ("scx_layered: Reimplement preemption using direct dispatch to foreign local DSQs") made it significantly worse. Before, the race would just fail to kick enough CPUs but the preempting task would still be picked up relatively quickly as CPUs enter dispatch path after finishing their current tasks. After, the preempting tasks end up queued on a specific local DSQ.
Fix it by using cpu_ctx->preempting_task to synchronize preemptors. The field is claimed in try_preempt_cpu() and cleared from running() when the task goes on the CPU. There are cases that the …
=> scx_layered: Synchronize among competing preemptors

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Only do direct dispatch of affinitized kthreads if the kthread is bound to a single CPU and ensure to kick the cpu if the cpu is idle.
=> scx_p2dq: Update handling of affinitized kthreads

scheds/rust/scx_lavd/src/main.rs
Replace verbose match-based logic for compute domain creation with `BTreeMap::entry().or_insert_with()`.
=> scx_lavd/main: Simplify cpdom_map construction

scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
Add an option to enable round-robin scheduling, where tasks are assigned a fixed time slice (specified by --slice-us-max) and run in a simple, cyclic order.
This policy ensures fair time sharing and can be effective for maximizing throughput in compute-heavy workloads where latency is not a concern.
=> scx_flash: Introduce --rr-sched

scheds/rust/scx_lavd/src/main.rs
Previously, chip binning was not considered for CPU preference ordering. Chip binning makes preference ordering tricky because, with chip binning, CPU capacity can vary even in a homogeneous (non-big/LITTLE) architecture.
Revise the CPU preference ordering logic considering chip binning. Two changes/fixes are as follows:
1) In non-big/LITTLE systems, even if some cores have a higher capacity due to chip binning or turbo boost, avoid using hyper twins for performance mode. The preference order will be big CPUs, LITTLE CPUs, and hypertwins of big CPUs.
2) In multi-NUMA/LLC machines, for performance mode, fill the entire machine first, then start using hypertwins. The preference order will be something like: CPUs in NUMA 0, CPUs in NUMA 1, hypertwins in NUMA 0,  and hypertwins in NUMA 1.
=> scx_lavd: Rework CPU preference ordering considering chip binning.

scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
Introduce the new option --cpu-runqueue to use distinct per-CPU DSQs. This makes the scheduler less aggressive with migrations and it can help improve certain cache-sensitive workloads.
=> scx_flash: Introduce --cpu-runqueue

scheds/rust/scx_p2dq/src/lib.rs, scheds/rust/scx_p2dq/src/main.rs
Currently p2dq declares the `bpf_intf` and `bpf_skel` modules in both main.rs and lib.rs. This means they get built twice in two different contexts, which is wasteful and incorrect. As they're both needed in lib.rs, move them both to lib.rs and clean up the second version in main.rs.
Drive-by: remove the `pub use bpf_skel::*;` in p2dq(lib) because that makes the public interface really wide.
Test plan:
- It builds.
- CI
=> p2dq: only declare each module once

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/types.h
Use a DSQ iterator to find the min vtime across DSQs. This makes DSQ selection more fair during dispatch and removes extra DSQ tracking code. This uses a similar idea as #2180
=> scx_p2dq: Update dispatch DSQ selection to use DSQ iterators

Cargo.lock, Cargo.toml, lib/arena.bpf.c, lib/selftests/selftest.bpf.c, lib/selftests/selftest.h, lib/selftests/st_bitmap.bpf.c, rust/scx_lib_selftests/Cargo.toml, rust/scx_lib_selftests/README.md, rust/scx_lib_selftests/build.rs, rust/scx_lib_selftests/src/bpf/main.bpf.c, rust/scx_lib_selftests/src/bpf_skel.rs, rust/scx_lib_selftests/src/main.rs
Add a helper crate for running selftests on the code in. the lib/ crate. Also add selftest stubs for the bitmap crate that we will flesh out later, so that the crate is immediately usable.
=> lib: add selftests

scheds/rust/scx_lavd/src/cpu_order.rs, scheds/rust/scx_lavd/src/main.rs
As a first step toward energy model-aware CPU ordering, let's refactor FlatTopology by separating it into a new module, cpu_order.rs. As the name 'FlatTopology' no longer makes sense, let's rename it to 'CpuOrder'. Additionally, clean up struct names for consistency (e.g., CpuFlatId -> CpuId, etc.).
Then, let's separate the implementation details from CpuOrder, so that struct CpuOrderCtx can guiltlessly carry implementation-dependent fields.
There are no functional changes.
=> scx_lavd: Refactor FlatTopology.

tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs
This is the first part of a multi-stage process that will eventually enable a scxtop user to select an arbitrary kprobe and view usage statistics/data on it in the terminal UI or in a perfetto trace.
This code adds the BPF generic handler that stores some basic data (more can be added as we see what is helpful) and also adds the Action in lib.rs so we can easily use the data in a trace or in the UI.
=> scxtop: add generic bpf kprobe handler

tools/scxtop/src/bpf/main.bpf.c
Previously, scxtop's dsq_slice_consumed overflowed and the logic needed to be slightly updated to accurately get the data for both the beginning of a slice and the end of a slice. One of the bugs was that we randomly sampled events, often missing the tail-end of a slice. Another bug included incorrect operand ordering for a subtraction.
To ensure we don't miss the tail-end of a slice, we always check if the previous task is the tail end of a slice and perform all necessary calculations if so, regardless of whether we are currently sampling. After that, we determine if we should sample the incoming task based on the sample rate.
Before:
After:
(Note: There is still a bug with dsq 0 for dsq_lat_us.)
=> scxtop: fix number overflow errors

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Use SCX_DSQ_LOCAL when dispatching to local CPU in select_cpu.
=> scx_p2dq: Use SCX_DSQ_LOCAL for select_cpu

scheds/rust/scx_p2dq/src/bpf/intf.h, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs
Add initial support for deadline scheduling based on the max DSQ timeslice. Deadline scheduling can potentially improve throughput during saturation. When doing pick two load balancing properly check the slack factor to ensure that load balancing is not overly aggressive.
`main` full saturation:
```
Wakeup Latencies percentiles (usec) runtime 30 (s) (410496 total samples)
50.0th: 17         (112341 samples)
90.0th: 124        (158688 samples)
* 99.0th: 933        (36907 samples)
99.9th: 1674       (3685 samples)
min=1, max=5013
Request Latencies percentiles (usec) runtime 30 (s) (410930 total samples)
50.0th: 12304      (125048 samples)
90.0th: 14192      (162320 samples)
* 99.0th: 23584      (36780 samples)
99.9th: 34496      (3626 samples)
min=6201, max=61446
RPS percentiles (requests) …
```
=> scx_p2dq: Add deadline scheduling

rust/scx_utils/src/compat.rs, rust/scx_utils/src/energy_model.rs, rust/scx_utils/src/lib.rs, rust/scx_utils/src/topology.rs
Currently, Topology and  EnergyModel are created by reading information
under sysfs. The sysfs path names, like "/sys/devices/system/cpu/online"
or "sys/kernel/debug/energy_model" are hard-coded in the code. While there
is nothing wrong with this, it is inconvenient to debug and test the related
code, especially when access to the environment is not possible [1].
To mitigate such a problem for ease of debugging, an environment variable,
SCX_SYSFS_PREFIX, is added, denoting the prefix of the root path, which is
an empty string, "", when SCX_SYSFS_PREFIX is not defined. topology.rs and
energy_model.rs are updated to read relevant data from
$SCX_SYSFS_PREFIX + "/sys/...".
For example, if the SCX_SYSFS_PREFIX is modified as follows and the relevant
sysfs files are placed under "/pixel6", …
=> scx_utils: Add an environment variable, SCX_SYSFS_PREFIX, for ease of debugging.

tools/scxtop/src/bpf/main.bpf.c
Previously, new task contexts where initialized without properly zero-ing out the data. This led to weird and incorrect results for dsq0, for example see dsq0 for dsq_lat_us here:
Now that the data is properly zero-ed out:
=> scxtop: fix dsq0 overflow

rust/scx_lib_selftests/Cargo.toml, rust/scx_lib_selftests/src/main.rs
Switch to Rust 2021 edition to fix build failure.
See #2186.
=> scx_lib_selftests/Cargo: Bump edition to 2021

scheds/rust/scx_rusty/src/bpf/main.bpf.c
Warning:
```bash
warning: scx_rusty@1.0.13: src/bpf/main.bpf.c:1267:12: warning: unused function 'node_dom_mask' [-Wunused-function]
warning: scx_rusty@1.0.13:  1267 | static u64 node_dom_mask(u32 node_id)
warning: scx_rusty@1.0.13:       |            ^~~~~~~~~~~~~
warning: scx_rusty@1.0.13: 1 warning generated.
```
Test on:
```bash
OS: Ubuntu 25.04 aarch64
Kernel: Linux 6.14.0-15-generic
```
Edit: updated warning log
=> scx_rusty: Suppress warning on aarch64

scheds/rust/scx_flash/src/bpf/main.bpf.c
Attempting to move migration-disabled tasks on other CPUs during direct dispatch can triggere errors like the following:
runtime error (SCX_DSQ_LOCAL[_ON] cannot move migration disabled coordinator[41400] from CPU 63 to 9)
Fix by properly handling migration-disabled tasks during direct dispatch and avoid migrating them.
=> scx_flash: Handle migration-disabled tasks in direct dispatch

tools/scxtop/src/app.rs
Currently, pressing 'x' to clear events does not work as expected. It clears the data for the event, but leaves the event visible and present in the available_events array. This fix causes 'x' to fully clear whatever events have been added.
Also removed unused variable non_hw_event_active.
=> scxtop: fix event clearing bug

scheds/rust/scx_p2dq/src/bpf/intf.h, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/types.h
Add a migration DSQ for tasks that are eligible to be load balanced. Previously when iterating across all DSQs the time complexity is O(N) across all N tasks in the worst case. The migration eligible DSQ allows for O(logN) lookups when doing LLC migrations, where N is the number of eligible tasks for migration.
Refactor p2dq_dispatch_impl to only lookup the llc_ctx context when needed in order to reduce map lookups in the dispatch path.
=> scx_p2dq: Add migration DSQs

scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
This helps reduce task migrations for interactive workloads, improving performance for those that are cache-sensitive or otherwise benefit from fewer migrations (e.g., gaming, audio).
It also introduces options to enable/disable per-CPU and per-node DSQs independently, providing a way to restore the previous behavior if desired.
By default, interactive tasks are dispatched to per-CPU DSQs, while non-interactive tasks go to per-node DSQs, ensuring natural load balancing across the system.
Test result (schbench):
- before:
```
$ schbench -L -m 4 -M auto -t 64 -n 0
auto pinning message and worker threads
Pinning to message thread index 1 cpu 1
Pinning to message thread index 2 cpu 2
Pinning to message thread index 0 cpu 0
Pinning to message thread index 3 cpu 3
Wakeup Latencies percentiles …
```
=> scx_flash: Enable per-CPU DSQs and per-node DSQs

tools/scxtop/src/app.rs, tools/scxtop/src/lib.rs
It is unnecessary and inefficient to filter the events every time we render the event list. Filtering should occur when we enter the event list and whenever input is updated. [This performance boost is necessary for when we will be filtering kprobe events (there are ~60k on my current machine and even a simple substring search takes >6ms)]. This decoupling also leads to a cleaner and more correct design.
To do this, I've added a FilteredEventState struct to the App struct. Since an input update and rendering an event list can occur simultaneously, this is stored behind a mutex.
=> scxtop: decouple filtering and rendering event list

scheds/rust/scx_flash/src/main.rs
```shell
warning: unnecessary parentheses around `if` condition
--> scheds/rust/scx_flash/src/main.rs:388:19
|
388 |         } else if (opts.cpu_runqueue) {
|                   ^                 ^
|
= note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
|
388 -         } else if (opts.cpu_runqueue) {
388 +         } else if opts.cpu_runqueue {
|
warning: unnecessary parentheses around `if` condition
--> scheds/rust/scx_flash/src/main.rs:391:19
|
391 |         } else if (opts.node_runqueue) {
|                   ^                  ^
|
help: remove these parentheses
|
391 -         } else if (opts.node_runqueue) {
391 +         } else if opts.node_runqueue {
|
warning: `scx_flash` (bin "scx_flash") generated 2 warnings (run `cargo fix --bin "scx_flash"` to apply 2 …
```
=> scx_flash: Remove unnecessary parentheses

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/types.h
Refactor DSQs so that there are no longer DSQs per slice interval. This Reduces the total number of DSQs that a CPU will check during dispatch to three. The layout of the DSQs is as follows:
LLC
DSQ - DSQ for LLC runnable tasks
MIG_DSQ- DSQ for migration eligible tasks
CPU
AFFN_DSQ- DSQ for affinitized tasks
When a CPU is dispatching it first checks the affinitized DSQ, then LLC DSQ and finally the migration eligible DSQ. All DSQs on a LLC share the same vtime priotization.
=> scx_p2dq: Refactor DSQs

tools/scxtop/src/bpf/main.bpf.c
Now that we'll be using the bpf kprobe handler for the UI as well as tracing, it needs to sample data when we are using it for the UI.
=> scxtop: make generic kprobe handler sample

scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
Add a new `--tickless-us N` option to enable tickless mode: tasks receive an infinite time slice, and the scheduler performs periodic checks (every N microseconds) to detect CPU contention and trigger preemption only when necessary.
This mode can improve performance isolation and reduce task migrations when the system is not saturated.
=> scx_flash: Introduce tickless mode

tools/scxtop/src/bpf/main.bpf.c
[PT_REGS_IP](https://docs.ebpf.io/ebpf-library/libbpf/ebpf/PT_REGS_IP/) gives the instruction directly after the ctx (addr + 1) while [bpf_get_func_ip](https://docs.ebpf.io/linux/helper-function/bpf_get_func_ip/) gives the exact address. When using the instruction pointer for matching purposes, the exact address is needed.
=> scxtop: fix kprobe instuction pointer

tools/scxtop/src/app.rs, tools/scxtop/src/keymap.rs, tools/scxtop/src/kprobe_event.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs
With PR's #2225, #2229, #2230, and #2234, we can now add the ability to monitor an arbitrary number of kprobes from the TUI. The kprobe event list is separate from perf events list and can be rendered by pressing 'K'. Performance is more important with kprobe events than perf events as (on my machine) there are about 60k kfuncs, so even a basic substring search can take >6ms.
Test Plan: 
1) Attached a kprobe to `schedule` kfunc, ensured using `sudo bpftool link show` that a single kprobe was properly attached and then properly de-attached when pressing 'x'.
2) Tested multiple kprobes on different functions while perf events were also selected (once again, using `sudo bpftool link show` to ensure the kprobes were properly attached). Ensured data was only being counted for the proper kfunc …
=> scxtop: add kprobe events to TUI

scheds/rust/scx_lavd/src/cpu_order.rs
```rust
warning: value assigned to `best_pdsi` is never read
--> scheds/rust/scx_lavd/src/cpu_order.rs:658:21
|
658 |             let mut best_pdsi: Option<PDSetInfo<'a>> = None;
|                     ^^^^^^^^^
|
= help: maybe it is overwritten before being read?
= note: `#[warn(unused_assignments)]` on by default
warning: field `perf_util` is never read
--> scheds/rust/scx_lavd/src/cpu_order.rs:69:9
|
67 | pub struct PerfCpuOrder {
|            ------------ field in this struct
68 |     pub perf_cap: usize,                 // performance in capacity
69 |     pub perf_util: f32,                  // performance in utilization, [0, 1]
|         ^^^^^^^^^
|
= note: `PerfCpuOrder` has derived impls for the traits `Clone` and `Debug`, but these are intentionally ignored during dead code …
```
=> scx_lavd: Suppress warning

tools/scxtop/src/app.rs
Several users from the community noted that scxtop crashed right after starting it (see #2209). With a helpful backtrace from @mati865, it became clear the root of the problem was in combining num_format::SystemLocale's separator with the way ratatui splits strings. The num_format library uses the short 3 byte whitespace character `\u{202f}` as a separator for certain regions (France, several European countries, and wherever they write one million as 1 000 000). However, ratatui assumes the whitespace characters are in 4 byte increments and was therefore panicking when it attempted to split_at() the whitespaces.
For a temporary fix, I'm going to fixe the locale to use Locale::en, which uses a `,` as a separator.
Test Plan:
- I put myself in the French locale using num_format::Locale::fr …
=> scxtop: temporary fix for locale crash

tools/scxtop/src/app.rs
I'm not sure about the correctness but fixes this crash when using debug builds:
```
thread 'main' panicked at tools/scxtop/src/app.rs:2513:20:
attempt to subtract with overflow
stack backtrace:
0: __rustc::rust_begin_unwind
at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/panicking.rs:697:5
1: core::panicking::panic_fmt
at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/panicking.rs:75:14
2: core::panicking::panic_const::panic_const_sub_overflow
at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/panicking.rs:178:21
3: <u64 as core::ops::arith::Sub>::sub
at /home/mateusz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/arith.rs:215:45
4: <&u64 as core::ops::arith::Sub<u64>>::sub
at …
```
=> scxtop: avoid udnerflow when calculating DSQ vtime delta

scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/types.h
Make interactive a first class field on the task_ctx. This cleans up many parts of the code which use a helper function or do manual/inconsistent checks. This improves overall code quality.
=> scx_p2dq: Refactor interactive handling

lib/sdt_alloc.bpf.c, meson.build
The commit 1881d080 re-introduced the compiler error with the recent GCC (15) that was fixed by 9d3e0ab4. So let's revert the commit and fix the warning in a different way. Let's initialize the variable to make those GCC versions happy and compile the code without any warnings.
```
../lib/sdt_alloc.bpf.c: In function ‘scx_buddy_chunk_alloc’:
../lib/sdt_alloc.bpf.c:1227:37: warning: ‘order’ may be used uninitialized [-Wmaybe-uninitialized]
1227 |         chunk->order_indices[order] = header->next_index;
|         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../lib/sdt_alloc.bpf.c:1214:13: note: ‘order’ was declared here
1214 |         u64 order;
|             ^~~~~
```
=> lib: Suppress a possibly uninitialized variable warning.

.github/include/ci.py, rust/scx_lib_selftests/Cargo.toml
`scx_lib_selftests` is a crate provided to run selftests written in BPF for the lib code. Run this in the CI so it doesn't regress. We already build all of the Rust crates in the workspace and have a VM (selftests need root) so simply throw running the binary in the VM inner logic.
This only runs on our sched_ext/for-next kernel for now. It's pretty easy to extend, but we currently only spin up the for-next VM in this step. Easy to extend later on.
Drive-by: disable publishing on `scx_lib_selftests` crate. I don't think we need to publish this, it's effectively an internal crate for testing.
Test plan:
- CI
=> ci: run scx_lib_selftests and disable it publishing

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
The --dispatch-lb-interactive flag is used to configure the load balancing of interactive tasks on the dispatch path. However, this functionality was removed in recent refactoring. Add handling for the flag in the can_migrate helper.
=> scx_p2dq: Fix interactive load balancing

scheds/rust/scx_chaos/src/bpf/main.bpf.c
When entering runnable, next_trait should be updated to CHAOS_NONE_TRAIT if that is the result of choose_chaos. At the moment, it is only reset if it was previously set at CHAOS_TRAIT_RANDOM_DELAYS in enqueue_chaotic.
=> scx_chaos: update runnable logic

README.md
We've seen some success with deepwiki documenting code and control flow of sched_ext. Add the DeepWiki badge to the README, which according to previous documentation will enable auto-refresh, and provide a link to people interested.
=> README: add DeepWiki badge

tools/scxtop/src/app.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/util.rs
Following up from #2209 and #2248, this fix allows us to return to using SystemLocale to better suit each user's preferences. A more permanent fix will come with the next ratatui version (see [issue](https://github.com/ratatui/ratatui/issues/1928), [PR](https://github.com/ratatui/ratatui/pull/1934)), but it's unclear exactly when that might happen.
Testing:
Used Locale::fr to ensure that narrow no-break whitespaces (\u{202F}) were being properly replaced with standard whitespaces. Ex.:
=> scxtop: sanitize no break space

scheds/rust/scx_chaos/src/bpf/intf.h, scheds/rust/scx_chaos/src/bpf/main.bpf.c, scheds/rust/scx_chaos/src/lib.rs
This adds the ability to introduce delays whenever a provided kprobe is hit. kprobes and a desired delay frequency can be passed in via the command line.
Testing: 
1) Ensured that only using kprobe-frequency arg causes stops scheduler from starting.
2) Ensured multiple kprobes can be attached at different frequencies. Used `bpftool link show` to verify all kprobes were attaching properly. Used dbg to ensure BPF handler was properly executing.
3) Ensured that program correctly exits immediately if kprobes fail validation.
4) Works with only --kprobes set (uses default frequency of .1)
=> scx_chaos: add kprobe delays

.github/include/list-integration-tests.py
A recent change made it possible to specify different default kernels for the standard PR CI job for each scheduler. This broke the deduplication of the "default" jobs, meaning commits with trailers were triggering way more tests than necessary. Clean this up by removing the kernel argument from the matrix if it matches the scheduler's default choice.
Test plan:
- This CI job. It has a tonne of test kernels. With the old behaviour we'd see 3x the normal jobs, the new behaviour should be that chaos doesn't get a for-next job and that we only have 2x.
CI-Test-Kernel: sched_ext/for-next
CI-Test-Kernel: stable/linux-rolling-stable
=> ci: deduplicate kernel specific matrix entries properly

scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
Replace the periodic timer used to check for contended CPUs with a direct check in ops.enqueue(): when enqueuing a task, if its previously used CPU is running a tickless task (a task with an infinite time slice), assign it a regular time slice. This resumes the tick on that CPU, effectively re-enabling preemption for contended CPUs.
With this, the global tickless timer is no longer needed. Consequently, the --tickless_ns option can be simplified to a --tickless boolean flag.
Suggested-by: Changwoo Min <changwoo@igalia.com>
=> scx_flash: Remove the tickless timer

rust/scx_utils/src/energy_model.rs, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c, scheds/rust/scx_lavd/src/cpu_order.rs, scheds/rust/scx_lavd/src/main.rs
When the energy model is available, use the upper bounds of the lowest
performance state and the lower bounds of the highest performance state
as the thresholds for the power save and performance modes, respectively.
Use the PCO table so that we can also utilize the middle states in
the PCO table.
When switching to a different performance mode (e.g., power save -> balanced),
use the required compute capacity, which is compatible with the PCO table,
instead of relying on CPU utilization based on wall-clock time. Clean up the
calculation of avg_sc_util to use more time_delta() and remove redundant reads
of volatile variables, etc.
The old, unnecessary code is removed as now the code compiles successfully.
Now the scheduler uses the first PCO entry for powersave mode and the last
PCO entry …
=> scx_lavd: Use the PCO (Performance vs. CPU Order) table when calculating the number of active CPUs.

lib/atq.bpf.c, lib/minheap.bpf.c, lib/selftests/st_atq.bpf.c, lib/selftests/st_minheap.bpf.c, rust/scx_lib_selftests/src/main.rs, scheds/include/lib/atq.h, scheds/include/lib/minheap.h
Minheaps are currently statically allocated because the verifier does not accept data structures with a variable array at the end. Bite the bullet and make the minheap's element array into a separate allocation referred to with a pointer. This allows us to bump the maximum task capacity of an ATQ significantly. Also add a method for dumping the minheap's contents to help with debugging, and fix a minheap bug assigning elem to the weight field of an helem.
=> lib: dynamically allocate minheap and add minheap/ATQ fixups

UNIT_TESTING_GUIDE.md, lib/scxtest/meson.build, lib/scxtest/overrides.c, lib/scxtest/overrides.h, lib/scxtest/scx_test_cpumask.c, lib/scxtest/scx_test_cpumask.h, lib/scxtest/scx_test_map.c, lib/scxtest/scx_test_map.h, scheds/rust/scx_p2dq/src/bpf/main.test.bpf.c
This adds cpumask stuff and more complicated helpers. This also adds a basic unit test for p2dq's select idle function to take advantage of these new helpers.  I'm also getting ready to disappear for a month long vacation so I've added documentation on what I've been doing an how to go about expanding the work.
=> scx: add more unit testing

scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c
When a CPU is almost fully utilized (say 90%) during a period, we may underestimate the utilization. For example, when the measured CPU utilization is 100%, there is a possibility that the actual utilization is actually higher, such as 130%.
To handle such utilization spike cases, we give a 50% premium for the scaled CPU time where the CPU is almost fully utilized. This overestimates the scaled CPU utilization and the required compute capacity. Then, this finally allocates more active CPUs. The over-allocated CPUs become the breathing room.
=> scx_lavd: Handling the CPU utilization spikes in autopilot mode.

scheds/rust/scx_flash/src/bpf/main.bpf.c
Add a comment explaining the logic for reusing the same CPU during synchronous wakeups, covering both SMT-enabled and SMT-disabled cases.
Suggested-by: Changwoo Min <changwoo@igalia.com>
=> scx_flash: Clarify conditions for reusing prev_cpu on sync wakeup

rust/scx_utils/src/compat.rs, scheds/rust/scx_lavd/src/bpf/lock.bpf.c, scheds/rust/scx_lavd/src/main.rs
Since ftrace has a lower overhead than tracepoint, use ftrace for futex tracing whenever possible. If any functions for futex tracing are not available (e.g., due to function inlining), fall back to using tracepoints.
=> scx_utils, scx_lavd: Use ftrace for futex tracing whenever possible.

tools/scxtop/src/app.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/llc_data.rs, tools/scxtop/src/node_data.rs, tools/scxtop/src/profiling_events/cpu_util.rs, tools/scxtop/src/profiling_events/mod.rs, tools/scxtop/src/stats.rs
Following on #2290, #2293, (and somewhat #2282, more on that later), this adds `CpuUtilEvent`'s to allow checking cpu utilization at the CPU, LLC, and Node level within the event pane. The main challenge with this addition was ensuring that the LLC and Node cpu utilization statistics were correct and properly normalized (i.e., that the summed utilization was accurately divided by the relevant number of CPUs). Previously, `VecStats` was only used for aggregating raw totals across LLC/Node's (such as total cycles), and not for computing percentage-based metrics like CPU utilization.
To enable this, a `num_cpus` field was added to the `LlcData` and `NodeData` structs. This allows us to normalize utilization values by dividing them by the number of CPUs that belong to a given LLC or node, …
=> scxtop: add cpu util events

scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
A set of changes to make tasks more sticky to their CPU, improving cache locality, without regressing work conservation or responsiveness under high load.
The key idea is to favor per-CPU DSQs over per-node DSQs, as long as the CPU isn't saturated. This helps avoid unnecessary migrations. Example: when a short per-CPU kthread interrupts a task for a really short amount of time, the task is queued to a per-node DSQ and potentially picked up by another CPU, triggering a migration.
Instead, when the CPU becomes saturated, the scheduler switches to using per-node DSQs, increasing the chances of task migration. This boosts work conservation and maintains responsiveness under high load conditions.
To determine when a CPU becomes saturated the scheduler dynamically adjusts the saturation …
=> scx_flash: CPU stickiness

scheds/rust/scx_lavd/src/bpf/idle.bpf.c, scheds/rust/scx_lavd/src/bpf/lock.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c
Miscellaneous cleanup to cover minor edge cases and improve readability.
- scx_lavd: Do not recalculate the task's deadline when re-euqued.
- scx_lavd: Clean up checking sync wakeup.
- scx_lavd: Add the overhead number for tracepoint and ftrace.
=> scx_lavd: Misc clean up

rust/scx_loader/configuration.md, rust/scx_loader/src/config.rs, scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
Adjust the default parameters to prioritize system responsiveness and update scx_loader performance profiles to reflect all the recent changes in the scheduler.
=> scx_flash: Tune defaults

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
`cpu` is set to `prev_cpu` in the beginning of both `select_cpu` methods, so unless it is possible it has changed, we don't need to reset it to `prev_cpu`.
=> scx_p2dq: minor select_cpu path cleanup

scheds/rust/scx_flash/src/main.rs
This option has no effect if the primary scheduling domain includes all the CPUs. Clarify this in the help.
=> scx_flash: Clarify help about --sticky-cpu

scheds/rust/scx_chaos/src/bpf/main.bpf.c
I generally assume the one liner is more readable/clean, but if this was on purpose, then let me know and I'll close this up.
=> scx_chaos: cleanup skip_select_cpu check

rust/scx_loader/src/config.rs
Use predefined type conversion from SupportedSched into &str, instead of relying on hardcoded values
=> scx_loader: refactor hardcoded scheduler names

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs
When SCX_OPS_ALLOW_QUEUED_WAKEUP is set, wake-up operations are batch-processed in the kernel. Hence, @current is no longer a waker task, so we cannot correctly track the task's wake frequency. So we disable SCX_OPS_ALLOW_QUEUED_WAKEUP for now.
Also, we limit the wake frequency tracking within userspace tasks under the same parent. The kernel tasks are too broadly related.
=> scx_lavd: Correctly measure wake frequency. 

scheds/rust/scx_bpfland/src/bpf/main.bpf.c, scheds/rust/scx_bpfland/src/main.rs
NUMA optimizations are only introducing overhead if systems that don't have multiple nodes.
Therefore, automatically disable such optimizations on non-NUMA systems or when --disable-numa is specified.
=> scx_bpfland: Disable NUMA optimizations on non-NUMA systems

rust/scx_loader/src/config.rs, scheds/rust/scx_flash/src/bpf/main.bpf.c, scheds/rust/scx_flash/src/main.rs
A set of changes aimed to improve CPU locality without regressing work conservation and system responsiveness when the system becomes saturated or overcommitted.
These changes are still following the idea of keeping tasks running on the same CPU (as long as the CPU is sufficiently idle), using per-CPU DSQs, and move tasks to the per-node DSQs when their CPU becomes busy.
A set of new options have been added to better adapt the scheduler to different workloads:
- `--slice-lag-scaling`: Dynamically adjusts the maximum sleep-time budget based on CPU load. When CPUs are mostly idle, the budget shrinks, making the scheduler behave more like FIFO. When the system is busy, the budget increases to better differentiate between interactive and CPU-intensive tasks.
- `--direct-dispatch`: Enables …
=> scx_flash: Improve CPU locality

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Add a few more hueristics to can_migrate to make it harder for interactive tasks to be load balanced. This gives better throughput at peak saturation.
=> scx_p2dq: Refactor can_migrate

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
When using deadline scheduling use the max slice length when there are idle CPUs. This improves throughput by lowering the amount of context switches.
=> scx_p2dq: Use max slice for idle deadline scheduling

tools/scxtop/src/cli.rs
This makes it so you can enter perf events without comma-delimiting and aligns the way we accept these args with krpobe args.
=> scxtop: make entering perf events easier

scheds/rust/scx_p2dq/Cargo.toml
p2dq was disabled on 6.12 for affinitised task stalls. There have been a lot of changes to p2dq recently, let's re-enable it.
Closes #2075
Test plan:
- CI, repeatedly. Amended this commit several times and checked it always passed. It has the trailer that triggers 6.12 testing.
CI-Test-Kernel: stable/6_12
=> p2dq: re-enable ci on 6.12

scheds/rust/scx_chaos/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/intf.h, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/types.h
p2dq's enqueue has diverged from the implementation when chaos was initially implemented. Then, we had P2DQ_ENQUEUE_COMPLETE but only based on a fixed task condition. Now, _COMPLETE gets hit based on a variety of conditions, many of which include the idle state of the machine. As this state can change, we started hitting complete in dispatch (delayed enqueue) even though we didn't hit it in enqueue the first time around. This meant that tasks weren't being enqueued properly the second time, and tasks were stalling.
Implement `kick_if_idle` for the enqueue promise and cover many of the remaining p2dq cases. I left the per-CPU kthread for now in the hope it includes BPF timers, as delaying BPF timers would prevent forward progress in chaos and lead to stalls. This also required the …
=> p2dq/chaos: switch more enqueue cases to be async

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
When running the promise for enqueue ensure that the CPU is properly set when handling cases where the CPU needs to be selected such as affinitization. This improves wakeup latency as CPU kicks are properly routed to the correct CPU.
=> scx_p2dq: Set CPU on promise during enqueue

scheds/rust/scx_chaos/src/bpf/main.bpf.c, scheds/rust/scx_chaos/src/lib.rs, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs
Add configuration structs in the bpf side to make managing different types of scheduler configs scalable.
=> scx_p2dq: Refactor configuration

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/introspec.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
Let's collect the time duration from when a task becomes quiescent to when it becomes runnable again.
=> scx_lavd: Add 'rerunnable_interval' for '--monitor-sched-samples'

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/cpu_stats.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs, tools/scxtop/src/perfetto_trace.rs, tools/scxtop/src/profiling_events/cpu_util.rs, tools/scxtop/src/util.rs
Now that scxtop keeps all cpu stats in `CpuStatTracker`, we can add that data to the trace. 
Cpu Frequency:
Cpu Utilization (example is idle ns):
=> scxtop: add cpu stats to trace

Cargo.lock, tools/scxtop/Cargo.toml, tools/scxtop/src/app.rs, tools/scxtop/src/cli.rs, tools/scxtop/src/config.rs, tools/scxtop/src/cpu_stats.rs, tools/scxtop/src/keymap.rs, tools/scxtop/src/profiling_events/cpu_util.rs, tools/scxtop/src/profiling_events/kprobe.rs, tools/scxtop/src/profiling_events/mod.rs, tools/scxtop/src/profiling_events/perf.rs, tools/scxtop/src/util.rs
Majority of this is tests (for config and the event structs). The main functional change here is to generalize the default event so it can be any of the current event types (krpobe, perf, or cpu) or any other future event type. This also allows us to clean up the `app.rs` file a bit. To do this, the config will now require a <source> prefix and a `from_str` method was added to the `ProfilingEvent` enum. For example, this is what default events can now look like:
* `perf:hw:cycles`
* `cpu:cpu_total_util_percent`
* `kprobe:vfs_read`
Now that it is generalized, we will also switch to using `cpu:cpu_total_util_percent` to show cpu utilization, at least until this gets it's own dedicated pane.
=> scxtop: update default event

rust/scx_loader/configuration.md
With PR #2360, we changed the default scheduler from bpfland to flash in the /etc/default/scx file. To be consistent between settings, let's apply similar suggested settings in scx_loader.conf.
=> scx_loader: cleaning and adjusting settings

scheds/rust/scx_lavd/src/bpf/lat_cri.bpf.c, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h
The amount of the wakelet's latency criticality inherited needs to be limited, so the wakee's latency criticality portion should always be a dominant factor. In the current setting, 12.5% of the waker's latency criticality can be inherited up to 25% of the wakee's latency criticality.
=> scx_lavd: Limit the impact of latency criticality inheritance.

Cargo.toml
Update some of the cargo profiles and add a `release-tiny` profile that has stripped binaries. Some builds have gotten rather bloated and the release-tiny is for building binaries to run on machines with limited resources.
Tested with `scx_p2dq` as it is the largest scheduler binary.
before:
```
$ ls -la ./target/release/scx_p2dq
-rwxr-xr-x 2 hodgesd users 13081288 Jul 15 06:58 ./target/release/scx_p2dq
$ ls -la ./target/release-fast/scx_p2dq
-rwxr-xr-x 2 hodgesd users 19036784 Jul 15 07:01 ./target/release-fast/scx_p2dq
$ ls -la ./target/debug/scx_p2dq
-rwxr-xr-x 2 hodgesd users 138523616 Jul 15 07:06 ./target/debug/scx_p2dq
```
after:
```
$ ls -la ./target/release/scx_p2dq
-rwxr-xr-x 2 hodgesd users 13081280 Jul 15 07:43 ./target/release/scx_p2dq
$ ls -la ./target/debug/scx_p2dq …
```
=> cargo: Update build profiles

tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs, tools/scxtop/src/mem_stats.rs, tools/scxtop/src/perfetto_trace.rs
This adds a `MemStatSnapshot` struct to collect memory data that can be used for both the TUI and the trace. For now, it will just be added into the trace, with `free` and`swap_free`, as well as with the ratios for those, `mem_ratio` and `swap_ratio`:
=> scxtop: add mem stats

.github/include/list-integration-tests.py
As was mentioned here https://github.com/sched-ext/scx/pull/2401#issuecomment-3078053586, scx_flash was never added to integration-tests. Let's fix this.
=> scx_flash: add to integration-tests

tools/scxtop/src/perfetto_trace.rs
This adds the process command line arguments to `scxtop trace` by adding the command line args to a `Process` that is inserted in a `ProcessTree` and having perfetto link those `ProcessTree`'s to the proper `ProcessDescriptor`. Examples:
=> scxtop: add process cmdline

tools/scxtop/src/app.rs, tools/scxtop/src/bpf/intf.h, tools/scxtop/src/bpf/main.bpf.c, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs, tools/scxtop/src/perfetto_trace.rs
the process has been stopped to avoid cpu cycles waste unless the needed resource is available
=> scxtop: adding sched_process_wait trace point.

Cargo.lock, Cargo.toml, scheds/rust/scx_wd40/Cargo.toml, scheds/rust/scx_wd40/src/load_balance.rs, scheds/rust/scx_wd40/src/main.rs, scheds/rust/scx_wd40/src/tuner.rs
libbpf-cargo was updated in #2397. This was very invasive and I missed wd40 while doing this because `cargo build` & the CI don't build wd40.
Fix the build, and add wd40 to the Cargo workspace and therefore the CI builds. This doesn't test wd40 but does build it. This will prevent silly regressions like this in the future.
Test plan:
- CI
=> scx_wd40: fix build and build in CI

rust/scx_loader/configuration.md, rust/scx_loader/src/config.rs
that allows distributions to ship with default config at:
- /usr/share/scx_loader/config.toml
- /usr/share/scx_loader.toml
user can overwrite it with own configuration at existing paths:
- /etc/scx_loader/config.toml
- /etc/scx_loader.toml
=> scx_loader: add config search path for distributions

services/scx_loader.toml, services/systemd/meson.build
Adding bundled configuration for scx_loader also means that whenever a user or application(e.g. scxctl,scx-manager) asks scx_loader, it will already start the scheduler
=> scx_loader: add bundled configuration like for scx.service

.github/include/flake.nix, .github/workflows/caching-build.yml, .github/workflows/integration-tests.yml
GitHub branch protection rules aren't defined in the code and changes to them have to be made by administrators instead of the usual code review process. This is inconvenient for two reasons: external contributors can't help with many CI changes, and any changes to them require every PR to be rebased before it'll pass the CI.
Add a `required-checks` job to replace the `rust-tests` and `integration-test/all-success` requirements currently in the branch rule. `integration-test/all-success` already partially covers this for adding/removing integration tests, but we don't have an equivalent for caching-build. Adding this job and making it the requirement makes splitting `rust-tests` for better parallelism less annoying, for example. Will enable this check in the CI after this has bedded in …
=> ci: add required-checks job

scheds/rust/scx_lavd/src/bpf/lat_cri.bpf.c, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/lock.bpf.c, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/bpf/power.bpf.c, scheds/rust/scx_lavd/src/bpf/preempt.bpf.c, scheds/rust/scx_lavd/src/bpf/util.bpf.c, scheds/rust/scx_lavd/src/main.rs
This PR includes the refactoring and clean-up patches, which do not cause any functional & behavioral changes, as follows:
- scx_lavd: Add const to no_wake_sync. 
- scx_lavd: Extend test_task_flag() for multi-bit testing. 
- scx_lavd: Keep running task's flag on cpu_ctx.
- scx_lavd: Rename cpuc->stopping_tm_est_ns to cpuc->est_stopping_clk. 
- scx_lavd: Keep track of running_clk at cpu_ctx. 
- scx_lavd: Refactoring greedy penalty calculation.
- scx_lavd: Refactoring preemption-related code.
- scx_lavd: Remove redundant time slice calculation. 
Additionally, it includes one optimization for preemption: when a particular CPU is chosen for an enqueuing task, consider that CPU as a preemption candidate. This way, we can increase the chance that the enqueued task runs on the chosen CPU.
- …
=> scx_lavd: Mostly refactoring and clean up, and one preemption optimization.

scheds/rust/scx_cosmos/src/bpf/main.bpf.c
On systems with a many CPUs sharing a single LLC, enabling flat idle scanning (-i) can be really beneficial. However, as system load increases, scanning all CPUs to find an idle one becomes more costly than using the built-in cpumask-based method.
To find the optimal balance, use the global CPU load to decide whether to use the flat idle scanning or the built-in idle CPU selection policy: when the system is mostly idle (load below the busy threshold), use flat scanning for faster placement; otherwise, fall back to the default idle CPU selection policy.
This adaptive approach provides the advantages of both methods, especially on large systems with a flat topology.
=> scx_cosmos: Use flat idle scan only when the system is sufficiently idle

scheds/rust/scx_lavd/src/bpf/balance.bpf.c, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/introspec.bpf.c, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
Sample time for scx_bpf_dsq_move_to_local() latencies to determine how much contention is happening at each DSQ.
=> scx_lavd: Sample dsq_consume latencies

scheds/rust/scx_tickless/src/bpf/intf.h, scheds/rust/scx_tickless/src/bpf/main.bpf.c, scheds/rust/scx_tickless/src/main.rs
Since the scheduler already dispatches tasks by iterating over all CPUs, implementing preferred core prioritization is straightforward.
This change introduces a simple mechanism to prefer higher-capacity CPUs (based on capacity information provided by the topology crate). More exactly, the scheduler prioritizes dispatching to the fastest full-idle SMT cores first, followed by the fastest idle CPUs.
CPU capacity is currently evaluated only at scheduler startup, so runtime capacity changes are not handled unless the scheduler is restarted.
=> scx_tickless: Add support for preferred cores

rust/scx_utils/src/topology.rs
```rust
$ cargo check
warning: /home/eric-wcnlab/linux2025/scx/Cargo.toml: unused manifest key: profile.release-fast.target-cpu
warning: /home/eric-wcnlab/linux2025/scx/rust/scx_rustland_core/Cargo.toml: unused manifest key: lib.include
Compiling scx_utils v1.0.17 (/home/eric-wcnlab/linux2025/scx/rust/scx_utils)
warning: unused import: `std::path::PathBuf`
--> rust/scx_utils/src/topology.rs:85:5
|
85 | use std::path::PathBuf;
|     ^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: `scx_utils` (lib) generated 1 warning (run `cargo fix --lib -p scx_utils` to apply 1 suggestion)
warning: `scx_utils` (lib) generated 1 warning (1 duplicate)
Compiling scx_rustland_core v2.3.3 (/home/eric-wcnlab/linu
```
=> scx_utils/topo: Remove unused import

Cargo.lock, rust/scx_bpf_compat/Cargo.toml, rust/scx_bpf_compat/build.rs, rust/scx_bpf_compat/src/bpf/main.bpf.c, rust/scx_bpf_compat/src/bpf_skel.rs, rust/scx_bpf_compat/src/lib.rs, scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
It is an unfortunate fact of the world that Frankenkernels exist. Often these are extremely hard to detect, particularly when it comes to the BPF verifier - the only reliable way is to load a BPF program and judge the behaviour.
In this initial example, layered fails to load on a kernel missing a8e03b6bbb2c: bpf: Allow invoking kfuncs from BPF_PROG_TYPE_SYSCALL progs. The workaround for this is pretty simple but regresses performance on kernels that don't need it.
Add a crate `scx_bpf_compat` with a generated skel that uses scx_utils BpfBuilder (the reason this utility isn't in scx_utils). It contains a function `kfuncs_supported_in_syscall` that can be used to test whether a kernel allows calling kfuncs inside a SYSCALL prog type.
Use this new utility in layered to upstream a patch …
=> scx_bpf_compat: add crate to detect difficult kernel features and use in layered

tools/scxtop/src/app.rs, tools/scxtop/src/proc_data.rs
This adds both an average slice duration (in ns) and maximum latency (in us) to the process view. Example:
On my machine, with ~1000 processes running, I timed `render_process_table` and found that the entire method takes ~3.5 ms without these and 3.5-4 ms with it. As we'll probably continue to add data, we should keep an eye on this.
=> scxtop: add fields to process view

tools/scxtop/src/app.rs, tools/scxtop/src/keymap.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs
This adds the ability to pause the TUI in case you see something you want to focus on by pressing the space key (' '). The plan is to use 'p' for a special process view with more optionality and a thread deep dive, so couldn't use that.
=> scxtop: add pause capability

tools/scxctl/README.md
The manual was somewhat outdated and incomplete.
- `scxctl` is no longer in AUR as a standalone package
- was missing an example of using a numeric value in a parameter
Now the instruction should be a bit more complete and up-to-date, as the user has an example of how to customize the numeric values in the parameter to suit their needs.
=> scxctl: update README.md

scheds/rust/scx_cosmos/src/bpf/main.bpf.c, scheds/rust/scx_cosmos/src/main.rs
Introduce a new --mm-affinity option to improve cache locality by keeping threads of the same process (e.g., tasks sharing the same mm_struct) on the same CPU across wakeups.
When enabled, if the waker and wakee share the same address space and were both running on the same CPU, the scheduler will prefer to keep the wakee on that CPU.
The optimization speculates on the fact that a wakee sharing the address space and CPU of the waker will likely find hot cache data on that CPU.
Since the impact is highly workload-dependent and may degrade performance in some cases, this optimization is provided as an option and is disabled by default.
Enabling this option resulted in a consistent 2.5%-5% throughput improvement (operations/sec) with Redis and MySQL benchmarks.
=> scx_cosmos: Introduce mm affinity

scheds/rust/scx_rusty/src/load_balance.rs, scheds/rust/scx_wd40/src/load_balance.rs
- Append `;` after `self.perform_balancing()?` for clarity
- Use `.map().collect()` to build `nodes` without a loop
- Swap `unwrap()` for `ok_or_else(anyhow!())?` to surface errors
- Replace `pop()/insert()` loop with `SortedVec::from_unsorted`
=> load_balance: Refactor create_domain_hierarchy

.github/include/ci.py, .github/workflows/caching-build.yml
Currently we build the kernels into an env variable in the CI workflow and use that where available. This is not ideal as it makes the CI flow harder to reproduce locally & constrains us to a single kernel. Add a helper function to build a named kernel and use in the script (still with a single hardcoded kernel for now). We can add a command line argument if this becomes useful but it isn't needed yet as this is only for the cargo tests that don't require a specific kernel.
Test plan:
- CI
=> ci: build kernel directly in ci script

scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_lavd/src/main.rs, scheds/rust/scx_lavd/src/stats.rs
In order to better monitor the effectiveness of slice_boost, measure how long the task ran for before it got scheduled out.
=> scx_lavd: Add 'slice_used' for '--monitor-sched-samples'

scheds/rust/scx_cosmos/src/bpf/main.bpf.c, scheds/rust/scx_cosmos/src/main.rs
The mechanism of doing deferred wakeups using a BPF timer can help making the hot path in ops.enqueue() faster, but it can also increase power consumption due to the timer that is contantly checking if there are tasks waiting on the local DSQs.
This might be problematic on battery-powered devices, so introduce the option --no-deferred-wakeups to disable this behavior and wake up CPUs synchronously in ops.enqueue().
This can reduce performance and throughput in certain workloads, but it helps reducing power consumption.
Example on an AMD Ryzen AI 9 HX 370 laptop:
- scx_cosmos:
```
$ sudo turbostat -S -s PkgWatt,CorWatt
CorWatt	PkgWatt
1.99		5.78
2.00		5.75
2.01		5.32
1.99		5.78
2.01		5.79
```
- scx_cosmos --no-deferred-wakeups:
```
$ sudo turbostat -S -s PkgWatt,CorWatt
CorWatt	PkgWatt …
```
=> scx_cosmos: Allow disabling deferred wakeups

scheds/include/scx/percpu.bpf.h
Add various helpers using bpf_per_cpu_ptr to read common percpu data structures for schedulers. This allows for better interoperability between schedulers and existing kernel data structures.
Tested with the following patch to `p2dq`:
```
diff --git a/scheds/rust/scx_p2dq/src/bpf/main.bpf.c b/scheds/rust/scx_p2dq/src/bpf/main.bpf.c
index c54f05fe..b1611e59 100644
--- a/scheds/rust/scx_p2dq/src/bpf/main.bpf.c
+++ b/scheds/rust/scx_p2dq/src/bpf/main.bpf.c
@@ -11,6 +11,7 @@
#define __bpf__
#include "../../../../include/scx/common.bpf.h"
#include "../../../../include/scx/bpf_arena_common.bpf.h"
+#include "../../../../include/scx/percpu.bpf.h"
#include "../../../../include/lib/atq.h"
#include "../../../../include/lib/cpumask.h"
#include "../../../../include/lib/minheap.h"
@@ -20,6 +21,7 @@ …
```
=> percpu: Add common helpers for reading percpu data

scheds/include/scx/percpu.bpf.h
Add helper to return the percpu cpufreq_policy used by the cpufreq governor. Refactor the formatting of helper macros.
Test with the following patch:
```
diff --git a/scheds/rust/scx_p2dq/src/bpf/main.bpf.c b/scheds/rust/scx_p2dq/src/bpf/main.bpf.c
index cfed627e..6ce362f1 100644
--- a/scheds/rust/scx_p2dq/src/bpf/main.bpf.c
+++ b/scheds/rust/scx_p2dq/src/bpf/main.bpf.c
@@ -2204,6 +2204,22 @@ static __always_inline s32 p2dq_init_impl()
int i, ret;
u64 dsq_id;
+       s32 cpu = bpf_get_smp_processor_id();
+       struct cpufreq_policy *freq_policy;
+       freq_policy = cpu_cpufreq_policy(cpu);
+       if (freq_policy) {
+               unsigned int min_freq = 0;
+               unsigned int max_freq = 0;
+               unsigned int cur_freq = 0;
+
+ …
```
=> percpu: Add helper to get cpufreq_policy

scheds/rust/scx_tickless/src/bpf/main.bpf.c
```c
Compiling scx_tickless v1.0.5 (/home/eric-wcnlab/linux2025/scx/scheds/rust/scx_tickless)
warning: scx_tickless@1.0.5: src/bpf/main.bpf.c:243:6: warning: unused variable 'cpu' [-Wunused-variable]
warning: scx_tickless@1.0.5:   243 |         s32 cpu = scx_bpf_task_cpu(p);
warning: scx_tickless@1.0.5:       |             ^~~
warning: scx_tickless@1.0.5: 1 warning generated.
```
=> scx_tickless: Remove unused variable

meson.build
There is currently a huge meson matrix, but one place that causes issues is the libbpf vendoring. libbpf is available to be vendored which is very important for c schedulers, but not important for Rust schedulers. This is because Rust already has a pinned and vendored libbpf in the form of libbpf-sys.
As part of the vendoring we have to work hard to select a correct set of compiler arguments. Although this appears to work just fine for C schedulers, it seems flaky for Rust schedulers, particularly with LTO.
Drop the vendored libbpf for Rust schedulers in the case where it wasn't specified. That is, no arguments now allows Rust to use the libbpf-sys version of libbpf, which sidesteps any compiler version issues.
Test plan:
- CI for usual checks
- Arch PKGBUILD with LTO. Failed without this …
=> meson: don't provide libbpf to cargo

rust/scx_bpf_compat/src/bpf/main.bpf.c
We provide kfunc definitions in common.bpf.h. I'm not sure where this file was getting them from before but it doesn't seem to work in all environments. Use the scx/common.bpf.h header like everywhere else.
Test plan:
- CI
=> scx_bpf_compat: use proper scx/common.bpf.h header

scheds/rust/scx_lavd/src/bpf/idle.bpf.c, scheds/rust/scx_lavd/src/bpf/intf.h, scheds/rust/scx_lavd/src/bpf/lavd.bpf.h, scheds/rust/scx_lavd/src/bpf/main.bpf.c
This PR improves the ops.enqueue() path in two ways:
1) Remove redundant pick_idle_cpu() selection when a CPU was already picked at ops.select_cpu().
2) Use the Power of 2 Random Choices technique when a proper CPU is not chosen to choose a less loaded CPU.
=> scx_lavd: Improve the ops.enqueue() path.

scheds/rust/scx_flash/src/bpf/main.bpf.c
scx_bpf_cpu_rq() may return NULL on invalid CPU.
Check for NULL accordingly.
Signed-off-by: Christian Loehle <christian.loehle@arm.com>
=> scx_flash: Handle NULL scx_bpf_cpu_rq() return

Cargo.lock, tools/scxtop/Cargo.toml, tools/scxtop/src/cpu_stats.rs, tools/scxtop/src/mem_stats.rs
This switches to using the more commonly used 0.15.1 version of procfs. Functionality remains the same.
=> scxtop: use procfs 0.15.1

scheds/rust/scx_lavd/src/main.rs
Turn on libbpf logging for scx_lavd. This enables both setup-related warnings and emitting the verifier log in case of verification failures by default and independently of any scheduler-related diagnostics.
=> scx_lavd: turn on libbpf error logging for verifier failures

tools/scxtop/src/cli.rs, tools/scxtop/src/config.rs, tools/scxtop/src/main.rs, tools/scxtop/src/tui.rs
This allows the user to configure the render rate in the range `[15, 5000]` ms - `scxtop -f 200` for example. The bounds exist to ensure one cannot leave scxtop in a state where it is unresponsive.
=> scxtop: make frame rate configurable

tools/scxtop/src/app.rs
Adds the new filter process feature key to the help page.
=> scxtop: update help with filtering

tools/scxtop/src/app.rs
Adds back bpf sample rate so the user can see what the current sample rate is.
Example (top right corner):
=> scxtop: re-add sample rate

tools/scxtop/src/app.rs
This adds a scrollbar on the left-hand side of the process view to help the user see the current state of the view. Example:
=> scxtop: add process scrollbar

tools/scxtop/src/columns.rs
Make the column consistent in formatting so that the column type is first.
=> scxtop: Refactor Lat us column

scheds/rust/scx_lavd/src/bpf/lavd.bpf.h
Reduce the competition window that allows later enqueued tasks to be scheduled earlier by 1/4. This prevents unexpected stalls in some cases and fixes the issue 2491 [1] without causing performance regression.
[1] https://github.com/sched-ext/scx/issues/2491
=> scx_lavd: Reduce the competition window to prevent stalls.

tools/scxtop/src/app.rs, tools/scxtop/src/cpu_data.rs, tools/scxtop/src/event_data.rs, tools/scxtop/src/llc_data.rs, tools/scxtop/src/node_data.rs, tools/scxtop/src/proc_data.rs, tools/scxtop/src/stats.rs, tools/scxtop/src/thread_data.rs
Previously, avg/max data was showing up as 50/100 whenever there wasn't any data. Ex. (see the threads that don't have NUMA/LLC):
This was due to the `EventData::event_data_immut` returning a vec of `[0, max_data_size]` whenever an entry didn't exist. Instead, we should just return an empty vec. Now, the data is correct:
To hopefully prevent these issues from coming up in the future, test suites were added to `EventData` and `VecStats`. These tests already caught an possible overflow bug in `VecStats` where we were adding u64's into a single u64.
=> scxtop: fix various bugs + add tests

scheds/rust/scx_chaos/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/bpf/main.bpf.c
Add handler to reenqueue tasks on the local DSQ when the CPU has been released to a higher level scheduling class.
=> scx_p2dq/scx_chaos: Add cpu_release handler

.github/include/ci.py, .github/include/flake.nix, .github/workflows/caching-build.yml, .github/workflows/integration-tests.yml, scheds/rust/scx_wd40/Cargo.toml, scripts/extract_bpf_objects.sh
Currently we run veristat when we run a full set of stress tests for a
scheduler. There are a few flaws with this approach:
- Any failures of veristat are completely ignored and still allow the PR
to merge.
- We spin up an entire virtme-ng VM to run a single veristat invocation,
even though veristat is very quick and the VMs are quite expensive.
- We only run veristat against the kernel(s) we have chosen for full
stress tests, which are few because the tests are expensive.
This moves the veristat jobs from the Ubuntu runners to the ci.py Python
script. In doing that, it adds the plumbing for a job internal matrix
and many efficiency improvements. This allows us to run veristat for all
relevant kernels for all schedulers on every PR with a single quick job.
Adds a new `ci.disable_veristat` …
=> ci: move veristat job from ubuntu runners to python script

tools/scxtop/src/app.rs, tools/scxtop/src/columns.rs, tools/scxtop/src/main.rs
This adds layer_id to the thread view as well, making it easier to understand which layers individual threads are located in. Example:
=> scxtop: add layered thread support

tools/scxtop/src/app.rs, tools/scxtop/src/keymap.rs, tools/scxtop/src/lib.rs, tools/scxtop/src/main.rs
This adds a detailed process view and sets the stage to enable additional columns on the wider screen and column toggling. Also removes unnecessary `AppState::Memory` checks.
Testing:
* Played around with it. Went Default -> Process -> Scheduler and Default -> Process -> Thread -> Process -> Default, behavior was as expected.
=> scxtop: add process appstate

tools/scxtop/src/proc_data.rs, tools/scxtop/src/thread_data.rs
Add some tests to thread data. They're not necessarily amazing tests, but they'll alert one if they change behavior unknowingly.
=> scxtop: add tests to thread data

tools/scxtop/src/layered_util.rs
Use a libbpf map iterator when searching for the layered map. This removes the dependency on bpftool.
=> scxtop: Remove dependency on bpftool

lib/btree.bpf.c, scheds/include/lib/btree.h
Add a linked list of freed btree nodes to each tree. This lets us implement free without switching off of the static allocator.
=> lib/btree: add free bnode cache

Cargo.lock, rust/scx_bpf_compat/Cargo.toml, rust/scx_bpf_unittests/Cargo.toml, rust/scx_lib_selftests/Cargo.toml, rust/scx_rustland_core/Cargo.toml, rust/scx_userspace_arena/Cargo.toml, rust/scx_utils/Cargo.toml, scheds/rust/scx_bpfland/Cargo.toml, scheds/rust/scx_chaos/Cargo.toml, scheds/rust/scx_cosmos/Cargo.toml, scheds/rust/scx_flash/Cargo.toml, scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_layered/Cargo.toml, scheds/rust/scx_mitosis/Cargo.toml, scheds/rust/scx_p2dq/Cargo.toml, scheds/rust/scx_rlfifo/Cargo.toml, scheds/rust/scx_rustland/Cargo.toml, scheds/rust/scx_rusty/Cargo.toml, scheds/rust/scx_tickless/Cargo.toml, scheds/rust/scx_wd40/Cargo.toml, tools/scxtop/Cargo.toml
Update libbpf-rs version for scx_utils and all uses of scx_utils to use the latest libbpf-rs version. This version contains this [patch]( https://lore.kernel.org/all/20250718001009.610955-1-andrii@kernel.org/) which seems to remediate random segfault issues when using arenas.
=> scx_utils: Update libbpf-rs version

scheds/rust/scx_lavd/src/bpf/power.bpf.c
Remove an unused variable to fix a compiler warning. There is no functional change.
=> scx_lavd: Fix a compiler warning.

tools/scxtop/src/bpf/main.bpf.c
Not all architectures have the pt_regs::ip field.
=> scxtop: use PT_REGS_IP() macro

Cargo.lock, rust/scx_utils/Cargo.toml, rust/scx_utils/src/misc.rs, scheds/rust/scx_lavd/Cargo.toml, scheds/rust/scx_lavd/src/main.rs
Setting rlimit for MEMLOCK to infinity would fail with -ENOPERM.
However, it does not necessarily mean catastrophic failure. Especially
when rlimits are already set to a large enough value, it is okay to
ignore the error.
So let's ignore the error and print the current rlimits. If the current
rlimits are insufficient, the program will fail anyway later in the
initialization, allocating BPF objects.
=> scx_utils, scx_lavd: Handle an error in set_rlimit_infinity() gracefully.

scheds/include/scx/bpf_atomic.h
Cherry-pick of upstream fix [0] to prevent the barrier from being optimized out.
[0]: https://lore.kernel.org/bpf/20250710175434.18829-2-puranjay@kernel.org
=> scx: Mark smp_mb variable as volatile

INSTALL.md
Two necessary packages are missing in the setup of the development environment step. So, let's add them: protobuf-compiler libseccomp-dev
=> INSTALL.md: Update ubuntu instructions.

scheds/rust/scx_lavd/src/bpf/intf.h
AMD processors could have many LLC domains (e.g., 12 LLCs per socket). So, let's increase LAVD_CPDOM_MAX_NR to 24.
=> scx_lavd: Increase the maximum number of domains to 24.

tools/scxtop/src/app.rs
Fix clippy warnings for lifetime elision by giving explict lifetime annotations to helper methods.
=> scxtop: Fix clippy warnings

scheds/rust/scx_wd40/src/bpf/placement.bpf.c
```c
Compiling scx_wd40 v1.0.15 (/home/underdog/eric/scx/scheds/rust/scx_wd40)
warning: scx_wd40@1.0.15: src/bpf/placement.bpf.c:32:12: warning: unused function 'node_dom_mask' [-Wunused-function]
warning: scx_wd40@1.0.15:    32 | static u64 node_dom_mask(u32 node_id)
warning: scx_wd40@1.0.15:       |            ^~~~~~~~~~~~~
warning: scx_wd40@1.0.15: 1 warning generated.
```
follow up: #2610
=> scx_wd40: Fix warning on ARM64

scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c, scheds/rust/scx_mitosis/src/main.rs
A couple more clean ups for things spotted while looking at the code, first it seems like we can enable the queued wakeup optimization on newer kernels, second, there's a potential use of uninitialized variables in dispatch in absence of any tasks in the cell or CPU DSQs.
=> scx_mitosis: Few more clean ups

Cargo.lock, rust/scx_lib_selftests/Cargo.toml, rust/scx_lib_selftests/src/main.rs
Add support for the BPF streams error reporting interfaces when testing the arena library.
=> rust/scx_lib_selftest: add BPF Streams support

scheds/rust/scx_lavd/src/bpf/main.bpf.c
When Per-CPU DSQ option is enabled, the check on the number of queued tasks on Per-LLC DSQ will always return 0. We should check the CPU specific DSQ instead.
=> scx_lavd: Check Per-CPU dsq on select cpu path

.github/include/ci.py, .github/include/flake.nix, .gitignore, INSTALL.md, Makefile, README.md, lib/Makefile, scheds/c/Makefile
Currently we have two build systems: Cargo and Meson. Meson builds the C schedulers and is the only way, but can also drive Cargo providing a bunch of extra parameters. Meson also provides the framework for our current CI stress testing.
Add a Makefile based system for building the C schedulers. We lose a lot of knobs in this migration, but that's deliberate - the very large matrix of Meson options was really confusing, and led to weird edge cases that we'd often miss in CI and with local testing.
Also add the builds for the C schedulers to the CI for the first time. No real testing other than "it builds" yet.
This change does not remove the Meson builds, but that is the direction. Letting them run in parallel for a while as the CI currently still relies on Meson and we should iron out …
=> build: switch c scheds to make

lib/rbtree.bpf.c, lib/selftests/selftest.bpf.c, lib/selftests/selftest.h, lib/selftests/st_rbtree.bpf.c, rust/scx_lib_selftests/build.rs, scheds/include/lib/rbtree.h
Add a red-black tree data structure with nodes that are embeddable into other structs. This tree type can be used to back ATQs and the fact it is embeddable allows us to add it to task_ctx structs directly.
=> lib: introduce red-black tree

scheds/rust/scx_p2dq/src/bpf/intf.h, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs, scheds/rust/scx_p2dq/src/main.rs, scheds/rust/scx_p2dq/src/stats.rs
Add different modes for gaming, efficiency and default scheduler performance. For the the implementation is rather simple and only effects the select path.
=> scx_p2dq: Add scheduler mode configuration

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
When the system is saturated attempt to pick an idle CPU from the local NUMA rather than anywhere a task can run. This reduces the number of cross NUMA migrations.
=> scx_p2dq: Update saturate CPU selection

Cargo.lock, tools/scxcash/Cargo.toml, tools/scxcash/build.rs, tools/scxcash/src/bpf/intf.h, tools/scxcash/src/bpf/perf_sample.bpf.c, tools/scxcash/src/bpf/soft_dirty.bpf.c, tools/scxcash/src/main.rs, tools/scxcash/src/monitors.rs
A perf sampling backend support that enables firing of the program and capture of events and addresses.
This can now be combined with --soft-dirty flag to combine various monitoring backends together.
Output:
```
$ scxcash --pid 3050 --perf-sample --perf-freq 1000 --soft-dirty --json
...
{"type":"soft_dirty_fault","timestamp":487340764605663,"pid":3050,"tid":3050,"cpu":174,"address":130279465189376}
{"type":"soft_dirty_fault","timestamp":487340825410580,"pid":3050,"tid":3050,"cpu":35,"address":130279465193472} 
{"type":"soft_dirty_fault","timestamp":487340879684148,"pid":3050,"tid":3050,"cpu":40,"address":130279465197568} 
{"type":"soft_dirty_fault","timestamp":487340938595960,"pid":3050,"tid":3050,"cpu":10,"address":130279465201664} …
```
=> scxcash: Add perf sampling backend

scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/main.rs
By default, affinitized tasks are put in lo_fb queue to guarantee a small slice of CPU time on the CPU core to avoid stalls. However, we have an important thread that has CPU affinity but we still want to give it more CPU time. Created an option to throw matching thread to hi_fb to allow it to run.
=> scx_layered: Added --hi-fb-thread-name to give more CPU time for affinitized task

scheds/rust/scx_mitosis/src/main.rs
Commit https://github.com/sched-ext/scx/commit/57065c0947ec59375b4f722a7544dece9957e73c introduced an incorrect description of the “layered” scheduler, when it should be mitosis. Let's fix it.
Before:
```
lucjan at cachyos ~ 10:37:34    
❯ scxctl start -s mitosis            
started Mitosis in Auto mode
lucjan at cachyos ~ 10:37:39    
❯ systemctl status scx_loader.service
● scx_loader.service - DBUS on-demand loader of sched-ext schedulers
Loaded: loaded (/usr/lib/systemd/system/scx_loader.service; disabled; preset: disabled)
Active: active (running) since Wed 2025-08-27 10:37:39 CEST; 4s ago
Invocation: 9132e01691c74d69874e74d12f58c4c4
Main PID: 113952 (scx_loader)
Tasks: 23 (limit: 37402)
Memory: 20M (peak: 20.3M)
CPU: 72ms
CGroup: /system.slice/scx_loader.service
├─113952 …
```
=> mitosis: replace layered with mitosis

scheds/rust/scx_chaos/src/lib.rs
Before:
```rust
~/l/scx/ta/release  main *1 !1  sudo ./scx_chaos                                    ok  1m 18s  base py  eric-wcnlab@eric-wcnlab  21:42:35 
21:42:49 [INFO] Running scx_chaos (build ID: 1.0.18-g71cd0960-dirty x86_64-unknown-linux-gnu)
21:42:49 [INFO] Builder { traits: [], verbose: 0, kprobe_random_delays: None, p2dq_opts: SchedulerOpts { disable_kthreads_local: false, autoslice: false, interactive_ratio: 10, deadline: false, eager_load_balance: false, freq_control: false, greedy_idle_disable: false, interactive_sticky: false, interactive_fifo: false, dispatch_pick2_disable: false, dispatch_lb_busy: 75, dispatch_lb_interactive: true, keep_running: false, atq_enabled: false, cpu_priority: false, interactive_dsq: true, wakeup_lb_busy: 0, wakeup_llc_migrations: false, …
```
=> scx_chaos: Log unregister on drop

tools/scxtop/src/keymap.rs
Since [btop](https://github.com/aristocratos/btop) allows the same, I think it makes sense to provide this consistency.
=> scxtop: Bind both 'q' and 'Q' to Quit action

Cargo.lock
Current slab 0.4.10 is affected by CVE-2025-55159/RUSTSEC-2025-0047/GHSA-qx2v-8332-m4fv, use 0.4.11 which has the corresponding fix instead.
=> Bump slab to 0.4.11

tools/scxtop/src/main.rs
Simplify the logic in handle_input_entry by merging identical branches for AppState::Memory and AppState::PerfTop into a single match arm with a guard condition.
=> scxtop: Reduce redundant if-else

lib/scxtest/overrides.c, lib/scxtest/overrides.h, rust/scx_bpf_unittests/build.rs, scheds/rust/scx_p2dq/src/bpf/main.test.bpf.c
These tests were disabled recently because of missing arena stubs. Add them as stubs (for now) and re-enable the tests.
I want to start using these tests in scx_chaos to test for correct behaviour without the verifier interfering, which will likely require not stubbing the arena code. But this is good enough for now.
Test plan:
- `cargo test -p scx_bpf_unittests`
- CI
=> scx_bpf_unittests: fix build and run tests again

tools/scxcash/Cargo.toml, tools/scxcash/src/monitors.rs
```rust
eric@eric-hp:~/dev/scx$ cargo build --release 
error: failed to load manifest for workspace member `/home/eric/dev/scx/tools/scxcash`
referenced by workspace at `/home/eric/dev/scx/Cargo.toml`
Caused by:
failed to parse manifest at `/home/eric/dev/scx/tools/scxcash/Cargo.toml`
Caused by:
feature `edition2024` is required
The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.84.1 (66221abde 2024-11-19)).
Consider adding `cargo-features = ["edition2024"]` to the top of Cargo.toml (above the [package] table) to tell Cargo you are opting in to use this unstable feature.
See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature. …
```
=> scxcash: Bump edition to 2021

meson.build
Meson as a build system is being replaced by a split between Cargo/gnumake for Rust/C schedulers. Add a warning before the next release to ask packagers to switch over to the replacements.
In a future release we'll add an error that can be overridden with a configuration option, and in the release after that we'll remove the Meson build entirely.
Test plan:
- CI - the new warning shows up.
=> meson: add deprecation warning

rust/scx_rustland_core/assets/bpf.rs, scheds/rust/scx_rlfifo/src/main.rs, scheds/rust/scx_rustland/src/main.rs
Expose a `name: &str` parameter in `BpfScheduler::init` and write it into `struct_ops.rustland.name` before `scx_ops_load!()`.
Still wondering if we should also append the build version to the name, or just keep the exact string?
=> scx_rustland_core: Add API to set scheduler name

scheds/rust/scx_chaos/src/lib.rs, scheds/rust/scx_p2dq/src/bpf/main.bpf.c, scheds/rust/scx_p2dq/src/lib.rs
Update enqueue so CPU selection is always run in enqueue if a task has not been selected. This is needed because p2dq always reenqueues on cpu_release.
=> scx_p2dq: Refactor enqueue for unselected tasks

meson.build
Add a link to the Meson deprecation warning so distro packagers know where to report issues.
Test plan:
```
jake@rooster:/data/users/jake/repos/scx/ > meson setup build
The Meson build system
Version: 1.7.2
Source dir: /data/users/jake/repos/scx
Build dir: /data/users/jake/repos/scx/build
Build type: native build
Project name: sched_ext schedulers
Project version: 1.0.15
C compiler for the host machine: gcc (gcc 14.3.0 "gcc (GCC) 14.3.0")
C linker for the host machine: gcc ld.bfd 2.44
Host machine cpu family: x86_64
Host machine cpu: x86_64
meson.build:7: WARNING: Meson builds are deprecated. Please switch to `cargo build` for Rust schedulers and `make` for C schedulers. Meson will be removed in an upcoming release. Please report any issues packaing for distributions at …
```
=> meson: extend deprecation warning with link to gh discussion

INSTALL.md
Recent Ubuntu releases are now shipping a stable kernel with sched_ext, so there is no need to install the kernel from the unstable ppa.
Update installation steps accordingly.
=> docs: Update installation steps for Ubuntu

rust/arenalib/arenalib/src/arenalib.rs
Use the libbpf_sys from libbpf_rs instead to make importing code easier when using alternative build systems.
=> arenalib: make imports a bit easier

README.md
PR #2769 removed support for scx.service.
Let README.md indicate the current solutions.
=> README.md: update systemd howto

scheds/rust/scx_lavd/src/bpf/main.bpf.c, scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c
Replace manual struct_ops definition with SCX_OPS_DEFINE for consistency.
=> scx_mitosis: Use SCX_OPS_DEFINE for struct_ops

tools/scxcash/build.rs, tools/scxcash/src/bpf/hints_tls.bpf.c, tools/scxcash/src/bpf/intf.h, tools/scxcash/src/main.rs, tools/scxcash/src/monitors.rs
Add a backend for emitting events for updates to scx_layered's task hint map, so that we can track precisely the updates to the hint values happening across the system with the monotonic clock timestamps since system boot and correlate with other events in user space.
=> scxcash: Add task hint backend

scheds/rust/scx_rusty/src/load_balance.rs, scheds/rust/scx_wd40/src/load_balance.rs
In `perform_balancing`, we already check `self.dom_group.nr_nodes() > 1`
before calling `balance_between_nodes`. Inside `balance_between_nodes`,
there is another check on `self.nodes.len() < 2`.
However, as seen in `create_domain_hierarchy`, the length of
`self.nodes` is directly determined by `self.dom_group.nr_nodes()`.
This makes the second check redundant.
This commit removes the check in `balance_between_nodes`, while keeping
the one in `perform_balancing` to avoid unnecessary function calls.
=> load_balance: Remove duplicate node count check

scheds/rust/scx_rusty/src/bpf/main.bpf.c
Building scx_rusty with cargo emits the following warning:
```
warning: scx_rusty@1.0.16: src/bpf/main.bpf.c:1680:50: warning: variable 'wrapper' is uninitialized when passed as a const pointer argument here [-Wuninitialized-const-pointer]
warning: scx_rusty@1.0.16:  1680 |         ret = bpf_map_update_elem(&task_masks, &p_map, &wrapper, 0 /*BPF NOEXIST*/);
warning: scx_rusty@1.0.16:       |                                                         ^~~~~~~
warning: scx_rusty@1.0.16: 1 warning generated.
```
This commit initializes 'wrapper' to an empty struct to remove the warning.
=> scx_rusty: Initialize bpf wrapper var

rust/scx_raw_pmu/src/json.rs, scheds/rust/scx_layered/src/main.rs
Intel PMUs have several edge cases we are currently not covering, e.g., multiple event codes for offcore events. Adjust the parsing accordingly. Also adjust scx_layered to properly handle the Intel perf counters.
=> rust/scx_raw_pmu: adjust parsing for Intel PMUs

.cargo/config.toml, Cargo.lock, Cargo.toml, rust/arenalib/arenalib/Cargo.toml, rust/scx_raw_pmu/Cargo.toml, tools/xtask/Cargo.toml, tools/xtask/src/bump_versions.rs, tools/xtask/src/main.rs, tools/xtask/src/versions.rs
`cargo xtask` [0] is a pattern for running arbitrary commands in your Cargo workspace. You create a crate for `xtask` and add an alias for `cargo run -p xtask --` as `cargo xtask`. This means we can run "scripts" like `cargo xtask bump-versions --all` with only Cargo installed.
Add this pattern and a first couple of useful scripts to demonstrate the pattern. First we have `versions`, which emulates pretty closely the existing `version-tool.py` (with no arguments). Then we have `bump-versions`, which allows you to pass one or more crates and bumps their patch versions like we do for a full sched_ext release. Intermediate bumps are handled by the crate authors directly.
This will let us add more useful features but are a good base. After this lands I want to add more formats for `versions`, …
=> cargo: add xtask crate for repo scripts

scheds/rust/scx_rustland/src/main.rs
The variable previously named min_vruntime has been renamed to vruntime_now to better reflect its role in tracking the current vruntime rather than the absolute minimum. Updated inline comments accordingly to match the new naming and improve clarity.
Supersedes #2818
=> scx_rustland: rename min_vruntime to vruntime_now for clarity

scheds/rust/scx_rustland/src/main.rs
Updated the comment to correctly describe vruntime_now.
No functional change.
Related-to: #2822
=> scx_rustland: refine comment to clarify vruntime_now

rust/scx_rustland_core/assets/bpf/main.bpf.c
Commit 04033ecf ("scx_rustland_core: Re-enqueue tasks in cpu_release") seems to introduce pretty bad regressions with certain gaming workloads (i.e., Elden Ring becomes very stuttery).
Using scx_bpf_reenqueue_local() in ops.cpu_release() is quite pointless, since rustland-core never uses SCX_DSQ_LOCAL[_ON] directly, so this only adds unnecessary overhead and increases locking contention on the local DSQs.
Without this commit performance in Elden Ring and other games are restored to normal.
=> Revert "scx_rustland_core: Re-enqueue tasks in cpu_release"

scheds/rust/scx_layered/examples/ttl.json, scheds/rust/scx_layered/src/bpf/intf.h, scheds/rust/scx_layered/src/bpf/main.bpf.c, scheds/rust/scx_layered/src/config.rs, scheds/rust/scx_layered/src/main.rs
Layer membership for scx_layered is based on rules that are checked during tCertain layer membership conditions may change over the course of the scheduler's runtime. For example, the GPU matcher marks tasks that use NVIDIA API calls as "GPU tasks", but there are workloads that use GPUs once and never again. We want to mark some layers as having a Time-To-Live for its members, where layer membership is re-evaluated after a user-defined number of schedules. Add this per-layer TTL and check it during the .stopping() call to periodically trigger match_layer() for those tasks.
=> scx_layered: add TTL for layer membership

rust/scx_rustland_core/README.md, rust/scx_rustland_core/assets/bpf.rs, scheds/rust/scx_rlfifo/src/main.rs
Commit beab2f38 ("scx_rustland_core: Introduce QueuedTask:comm_str()") introduced the following build error on arm64:
```
error[E0308]: mismatched types
--> scheds/rust/scx_rustland/src/bpf.rs:167:19
|
167 |             comm: self.inner.comm,
|                   ^^^^^^^^^^^^^^^ expected `[i8; 16]`, found `[u8; 16]`
|
= note: expected array `[i8; 16]`
found array `[u8; 16]`
```
Fix by declaring comm as an array of c_char elements, instead of i8, ensuring portability across different architectures.
Fixes: beab2f38 ("scx_rustland_core: Introduce QueuedTask:comm_str()")
=> scx_rustland_core: Fix char type on arm64

.nix/flake.lock, .nix/flake.nix
Update all dependencies. Required a little bit of modification for veristat/libbpf/virtme-ng.
Test plan:
- CI
```
jake@merlin:/data/users/jake/repos/scx/ > cargo clean
Removed 21197 files, 29.9GiB total
jake@merlin:/data/users/jake/repos/scx/ > cargo build
...
Finished `dev` profile [unoptimized + debuginfo] target(s) in 2m 07s
jake@merlin:/data/users/jake/repos/scx/ > cargo build --release
...
Finished `release` profile [optimized] target(s) in 2m 32s
```
=> nix: update flake lock
