sched-ext/scx

meson.build

- scx_nest included.
- scx_rusty bug fix.
- Ubuntu build fixes.

Bump overall version to 0.1.1

---

README.md

I added a list of useful articles and blog posts at the end of README.

Update README for additional resources (blog posts and articles)

---

meson.build

@htejun most likely forgot to update the file

Bump to 0.1.3

---

scheds/rust/scx_rustland/README.md

Embed the video and drop "live" from section title as it's not really live.

scx_rustland: Update README.md

---

OVERVIEW.md

Pierre Jacquet pointed out that our docs in the scx repo are out of date for the latest APIs. Let's update it so readers don't get confused.
This will address https://github.com/sched-ext/scx/issues/117.

docs: Update OVERVIEW to match latest APIs

---

scheds/include/scx/common.bpf.h

And relocate scx_bpf_dispatch_nr_slots() while at it.

common.bpf.h: Add kfunc prototype for scx_bpf_dispatch_cancel()

---

services/scx

Just add scx_rlfifo to /etc/default/scx (adapting changes from #161)

scx: update /etc/default/scx

---

INSTALL.md
README.md

Also create a separate INSTALL.md as the primary REAME.md is getting a big long.

Add install instructions for Fedora

---

README.md

Add "Getting started with sched-ext development" blog post to the "Additional Resources" section.

README: update additional resources

---

scheds/rust/scx_lavd/src/bpf/main.bpf.c

Noticed a few typos. Let's fix em up

lavd: Fix a few typos

---

scheds/rust/scx_lavd/src/bpf/intf.h
scheds/rust/scx_lavd/src/bpf/main.bpf.c
scheds/rust/scx_lavd/src/bpf_intf.rs
scheds/rust/scx_lavd/src/bpf_skel.rs
scheds/rust/scx_lavd/src/main.rs

Correct the copyright and author information

scx_lavd: fix copyright information

---

rust/scx_utils/src/compat.rs

If another scheduler is already running, the Rust schedulers based on scx_utils are reporting an error like the following, that can be a bit difficult to understand:
Error: Failed to attach struct ops
Caused by:
bpf call "libbpf_rs::map::Map::attach_struct_ops::{{closure}}" returned NULL
Change the scx_ops_attach macro to check if another sched_ext scheduler is running and in that case report a more explicit error.
With this applied:
$ sudo scx_rustland
Error: another sched_ext scheduler is already running

scx_utils: report an explicit error when another scheduler is running

---

rust/scx_utils/src/topology.rs

Some users are running with NUMA disabled, which makes sense given that it's useless in a lot of contexts. Let's make the Topology crate assume a default node with ID 0 in such cases.

topology: Support CONFIG_NUMA=n in Topology crate

---

libalpm/openrc/90-scx-scheds-upgrade.hook
libalpm/openrc/meson.build
libalpm/openrc/scx-openrc-restart
meson.build

In PR #211, support for systemd services was added. So let's introduce a pacman hook similar to that of systemd

Add pacman hooks for openrc

---

INSTALL.md

Also add links to the fedora rpms.

Update INSTALL.md with fedora c scheds info

---

INSTALL.md

Adds a section how to install scx and sched-ext patched kernel on openSUSE Tumbleweed.

Add openSUSE installation notes

---

scheds/rust/scx_rustland/src/main.rs

Overview
========
Currently, a task's time slice is determined based on the total number of tasks waiting to be scheduled: the more overloaded the system, the shorter the time slice.
This approach can help to reduce the average wait time of all tasks, allowing them to progress more slowly, but uniformly, thus providing a smoother overall system performance.
However, under heavy system load, this approach can lead to very short time slices distributed among all tasks, causing excessive context switches that can badly affect soft real-time workloads.
Moreover, the scheduler tends to operate in a bursty manner (tasks are queued and dispatched in bursts). This can also result in fluctuations of longer and shorter time slices, depending on the number of tasks still waiting in the scheduler's …

scx_rustland: introduce virtual time slice

---

scheds/rust/scx_rusty/src/bpf/main.bpf.c

READ_ONCE()/WRITE_ONCE() macros are added in commit 0932fde, we should be able to utilize the macros to get around the possibility of data races for domc->min_vruntime.
_Personally I think `dom_min_vruntime` function is redundant, it simply does the load operation of `domc->min_vruntime`, nothing special. It doesn't provide better readability either, the variable `domc->min_vruntime` is easy and trivial enough to understand itself._

scx_rusty: Elimate data races possibility for domain min_vruntime

---

scheds/rust/scx_lavd/src/bpf/main.bpf.c

The core compaction seems to work great in various hardware. Now it is time to document its design.

scx_lavd: add the design of core compaction

---

services/README.md

It is worth adding information on how to restore the default values.

README: Add information about restoring default values

---

scheds/rust/scx_rlfifo/src/main.rs

Minor code readability improvements + force all tasks to be scheduled in user-space by default.
This makes the scheduler more accessible for experimentation, allowing to apply changes just to user-space code and observe the effects, without addressing any in-kernel optimization.

scx_rlfifo: improve code usability for experiments

---

rust/scx_rustland_core/assets/bpf/main.bpf.c

Fix a potential race condition that might lead to a task being dispatched without kicking the target CPU, which could result in a potential stall.
With this applied, scx_rustland has been running without any stall for about 18 hours on a system where the issue was previously quite easy to reproduce.
Moreover, clarify a couple of comments in the dispatch path.
This fixes issue #353.
Tested-by: SoulHarsh007 <harsh.peshwani@outlook.com>

scx_rustland_core: fix potential race in dispatch_task()

---

rust/scx_utils/README.md
rust/scx_utils/src/lib.rs

scx_utils: Fix typos

---

scheds/rust/scx_rusty/src/bpf/intf.h
scheds/rust/scx_rusty/src/bpf/main.bpf.c
scheds/rust/scx_rusty/src/main.rs

Refactor the WAKE_SYNC path, and improve how we do dispatching.

rusty: Clean up some logic in rusty

---

scheds/rust/scx_rusty/src/bpf/main.bpf.c

Modify the execution sequence before lookup operation for `new_domc`. If `new_dom_id == NO_DOM_FOUND`, lookup operation for `new_domc` is definitely going to fail so we don't have to wait until we found that `new_domc` is `NULL`, clearing of cpumask and return operation should be done directly in that case.
Plus we should avoid using `try_lookup_dom_ctx` outside the context of `lookup_dom_ctx`, as it can keep the interface's consistency.

scx_rusty: Refactor lookup operation for new_domc in task_set_domain

---

scheds/rust/scx_lavd/src/bpf/main.bpf.c

It seems that we are not updating `is_idle` when we find an idle CPU with pick_cpu(), causing unnecessary rescheduling events when select_cpu() is called.
To resolve this, ensure that the is_idle state is correctly set. Additionally, always ensure that the task is dispatched to the local DSQ immediately upon finding (and reserving) an idle CPU.

scx_lavd: properly check for idle CPUs in pick_cpu()

---

services/systemd/scx.service

Sadly, the idea that @arighi and I have been thinking about is not working as it should. I'll check right away how the timer works. 
This reverts commit f7e575808b4b11f163b71d14723d1fe5f2fe879e.

Revert "Add After=graphical.target into service"

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
scheds/rust/scx_bpfland/src/main.rs

Implement CPU hotplugging in scx_bpfland without restarting the scheduler.
The idle selection logic has been updated to consider online CPUs. Additionally, a cpumask for offline CPUs has been introduced. Tasks that have been dispatched to the DSQs associated with offline CPUs are consumed by the other CPUs that are still online.
Moreover, the dependency on the Topology crate is temporarily dropped and instead, /sys/devices/system/cpu/smt/active is used to determine if SMT should be taken into account during idle selection. The Topology crate will be re-introduced later when scx_bpfland will gain more topology-aware capabilities.
This fixes #406.

scx_bpfland: support CPU hotplugging

---

scheds/c/scx_flatcg.bpf.c

Fix "oppotunistic" to "opportunistic".

scx_flatcg: Fix_typo

---

rust/scx_utils/src/log_recorder.rs

This change adds the ability to customize the log recorder format for each metric type. There is a default format that is used if no custom `MetricFormatter` is provided. This is the same format that was used before this change.
The `MetricFormatter` should be implemented by the user to customize the format of the log recorder. The `LogRecorderBuilder` now takes a `MetricFormatter` as an optional parameter.
Following changes will allow additional customization of the log recorder format, such as how many metrics are logged per line.

sched_utils: Add log recorder format customization

---

scheds/rust/scx_rusty/src/load_balance.rs

Instead of performing domain mask checking inside `find_first_candidate()` every time, check whether the tasks within push domain are abled to run on pull domain by performing the mask check at vector generation stage.
This way can also avoid repeated computation generated by the same (task, pull_dom) pair as they'll try to check whether the pull domain is in the task domain mask.

scx_rusty: Pre-check task domain mask with pull domain mask

---

scheds/rust/scx_rusty/src/load_balance.rs

Simplify LoadBalancer::populate_tasks_by_load() by cutting out the heap allocation bits, by moving mutable accesses in front of immutable ones. Because multiple immutable accesses (between bss and rodata) do not conflict, we don't need the intermediate PID storage.

scx_rusty: Simplify LoadBalancer::populate_tasks_by_load()

---

scheds/rust/scx_rusty/src/bpf/intf.h
scheds/rust/scx_rusty/src/bpf/main.bpf.c

Revert "rusty: Rework deadline as a signed sum"

---

scheds/rust/scx_layered/src/bpf/main.bpf.c
scheds/rust/scx_layered/src/main.rs

Add a parameter to disable topology awareness. This is useful when trying to compare the scheduling performance of topology aware scheduling compared to the previous scheduling strategy.
Run layered with the config:
```
[{
"name":"random",
"comment":"random user",
"matches":[
[{"UIDEquals":1234}]
],
"kind": {
"Confined":{
"nodes":[1],
"util_range": [0.05, 0.7],
"exclusive": true
}
}
},
{
"name":"hodgesd",
"comment":"hodgesd user",
"matches":[
[{"UIDEquals":224791}]
],
"kind": {
"Confined":{
"nodes":[1],
"util_range": [0.05, 0.7],
"exclusive": false
}
}
},{
"name":"stress-ng",
"comment":"stress-ng slice",
"matches":[
[
{"CommPrefix":"stress-ng"}
],[
{"PcommPrefix":"stress-ng"}
]],
"kind": {
"Confined":{
"util_range": [0.05, 0.70],
"nodes":[1],
"exclusive": false
}
}
},
{ …
```

scx_layered: Add support for disabling topology awareness

---

scheds/rust/scx_lavd/src/main.rs

- Use .enumerate() consistently while building the cpu_fids vector.
- Use .then_with() to chain .cmp() when sorting cpu_fids.
Both reduce visual clutter.

scx_lavd: Make FlatTopology::new() a bit prettier

---

rust/scx_rustland_core/assets/bpf.rs

It seems that musl glibc is not POSIX.1-2001, POSIX.1-2008 compliant and using sched_setscheduler() just returns -ENOSYS:
https://git.musl-libc.org/cgit/musl/commit/src/sched/sched_setscheduler.c?id=1e21e78bf7a5c24c217446d8760be7b7188711c2
Switch to pthread_setschedparam() to properly support building scx_rustland_core with musl.
This fixes #469.

scx_rustland_core: add support for musl

---

rust/scx_rustland_core/Cargo.toml
rust/scx_utils/Cargo.toml
scheds/rust/scx_bpfland/Cargo.toml
scheds/rust/scx_lavd/Cargo.toml
scheds/rust/scx_layered/Cargo.toml
scheds/rust/scx_mitosis/Cargo.toml
scheds/rust/scx_rustland/Cargo.toml
scheds/rust/scx_rusty/Cargo.toml
version-tool.py

It's error-prone to manage version updates with all the sub-projects. Add a tool to check and update them together and synchronize crate dependency versions using it.

Add a tool to manage versions and synchronize crate dependency versions

---

DEVELOPER_GUIDE.md

Add an intial version of a developer guide, where common tools and documentation can be shared.

docs: Add developer guide

---

scheds/rust/scx_layered/src/bpf/main.bpf.c
scheds/rust/scx_layered/src/bpf/util.bpf.c

Layer matching currently takes a large number of bpf instructions. Moving layer matching to a global function will reduce the overall instruction count and allow for other layer matching methods such as glob.
main:
```
$ sudo veristat ./target/release/build/scx_layered-ed7ff1cb72366b2f/out/bpf.bpf.o 
Processing 'bpf.bpf.o'...
File       Program                Verdict  Duration (us)   Insns  States  Peak states
---------  ---------------------  -------  -------------  ------  ------  -----------
bpf.bpf.o  layered_cpu_release    success             24       2       0            0
bpf.bpf.o  layered_dispatch       success           4888    6472     651          274
bpf.bpf.o  layered_dump           success           9651   17363     465          192
bpf.bpf.o  layered_enqueue        success …
```

scx_rusty: Make layer matching a global function

---

DEVELOPER_GUIDE.md
README.md

Add some info on `perf` to the developer guide and link from the main readme.

docs: Update developer guide

---

rust/scx_stats/scripts/scxstats_to_openmetrics.py

It now retries until told to exit. This is a bit easier to use and matches `scx_layered --monitor`.

scx_stats/scripts/scxstats_to_openmetrics: Retry connection

---

.github/workflows/merge.yml
.github/workflows/pr_veristat.yml
meson-scripts/veristat
meson-scripts/veristat_diff

Make sure veristat is available for CI for PRs.

ci: fix veristat for PRs

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

Tasks enqueued with SCX_ENQ_WAKEUP are immediately classified as interactive. However, if interactive tasks classification is disabled (via `-c 0`), we should avoid promoting them as interactive.
This is particularly important because, with the nvcsw logic disabled, tasks can remain classified as interactive indefinitely and they will never be demoted to regular tasks.

scx_bpfland: allow to completely disable interactive classification

---

rust/scx_utils/build.rs
scheds/rust/scx_rusty/Cargo.lock
scheds/rust/scx_rusty/src/domain.rs
scheds/rust/scx_rusty/src/load_balance.rs
scheds/rust/scx_rusty/src/main.rs
scheds/rust/scx_rusty/src/tuner.rs

- Formatting.
- Dep updates.
- scx_utils version string generation update.

scx_rusty: Misc updates

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

Enable SCX_OPS_ENQ_LAST, so that sched_ext core won't automatically re-schedule the task on the same CPU, implicitly assigning a time slice of SCX_SLICE_DFL, if no other task wants to run on that CPU.
Instead, explicitly replenish the task's time slice from ops.dispatch() if the task still wants to run and no other task is selected.
Moreover, instead of determining the task time slice in ops.enqueue(), refresh the time slice immediately before the task is started on its assigned CPU in ops.running().
This allows to use a more precise time slice, adjusted based on the actual amount of tasks that are currently waiting to be scheduled.

scx_bpfland: better time slice control

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

Keep evaluating the average number of voluntary context switches for each task when lowlatency mode is enabled, even when interactive tasks classification is disabled (via `-c 0`).
The average nvcsw is also used in lowlatency mode to evaluate the proportional bonus to the tasks' deadline and it shouldn't be ignored when interactive tasks classification is disabled. Moreover, make sure that such bonus never exceeds the starvation threshold.
Keep in mind that it is still possible to disable the periodic average nvcsw evaluation with `-c 0`, without specifying `--lowlatency`.
Fixes: 6a22853 ("scx_bpfland: introduce --lowlatency option")

scx_bpfland: always honor average nvcsw in lowlatency mode

---

scheds/rust/scx_layered/src/main.rs

Forgot to add doc for tgid matching

scx_layered: Update help for tgid matching

---

scheds/rust/scx_lavd/src/bpf/main.bpf.c

With an ill combination of old kernel and old LLVM, the BPF verifier incorrectly detects an infinite loop. After changing the loop with a constant end, the old verifier can pass the code.

scx_lavd: make a loop easier to correctly verify

---

rust/scx_utils/src/topology.rs

This borrows some of the logic in scx_lavd for figuring out if a core is a P/E core. If this makes sense we can add helper methods directly on the topology to return P/E cores so that each scheduler doesn't have to reinvent the same logic.

scx_utils: Add Big/Little core logic to Topology

---

scheds/rust/scx_layered/README.md

Add some more documentation for `scx_layered` for tuning.

Layered docs

---

scheds/rust/scx_layered/src/main.rs

Add docs for layer slice setting.

scx_layered: Update docs for layer slice setting

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

Aggressively try to keep tasks running on the same CPU / cache / domain, to achieve higher performance when the system is not over commissioned.
This is done by giving a second chance in ops.enqueue(), in addition to ops.select_cpu(), to find an idle CPU close to the previously used CPU.
Moreover, even if the task is dispatched to the global DSQs, always try to check if there is an idle CPU in the primary domain that can immediately consume the task.
= Results =
This change seems to provide a minor, but consistent, boost of performance with the CPU-intensive benchmarks from the CachyOS benchmarks selection [1].
Similar results can also be noticed with some WebGL benchmarks [2], when system usage is close to its maximum capacity.
Test:
- cachyos-benchmarker
System:
- AMD Ryzen 7 5800X …

scx_bpfland: enhanced task affinity

---

scheds/rust/scx_layered/src/main.rs

Add a per layer config for different implementations of layer growth algorithms. Convert the existing default logic into a default layer growth algorithm and add a linear implementation.

scx_layered: Add layer growth config

---

scheds/rust/scx_rustland/src/main.rs

scx_rustland was originally designed as a PoC to showcase the benefits of implementing specialized schedulers via sched_ext, focusing on a very specific use case: prioritize game responsiveness regardless of what runs in the background.
Its original design was subsequently modified to better serve as a general-purpose scheduler, balancing the prioritization of interactive tasks with CPU-intensive ones to prevent over-prioritization.
With scx_bpfland serving as a more "general-purpose" scheduler, it makes sense to revisit scx_rustland's original goal and make it  much more aggressive at prioritizing interactive tasks, determined in function of their average amount of context switches.
This change makes scx_rustland again a really good PoC to showcase the benefits of having specialized …

scx_rustland: aggressively prioritize interactive tasks

---

services/scx

As soon as https://github.com/sched-ext/scx/pull/615 @arighi is merged, let's update /etc/default/scx with new flags for bpfland.

scx-scheds: update bpflands suggested flags

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

When selecting an idle CPU for a task that has been woken up, prioritize reusing the same CPU if the waker and wakee share the same L3 cache.
Otherwise, attempt to migrate the wakee to the waker's CPU, provided it is allowed by the wakee's scheduling domain.
This seems to consistently improve FPS performance when the system is not operating over its full capacity.
Example:
$ __GL_SYNC_TO_VBLANK=0 vblank_mode=0 glxgears -geometry 800x600
- before: ~18305.77 FPS
- after:  ~19060.62 FPS

scx_bpfland: optimize producer/consumer workloads

---

scheds/rust/scx_layered/src/stats.rs

scx_layered: Fix stats typo

---

scheds/rust/scx_layered/src/main.rs

Small change to get rid of a warning when building that the initial value of `layer_growth_algo` is unused. Also gets rid of the `mut` and makes this code a bit easier to read.

scx_layered: clean up Layer::new layer_growth_algo

---

cargo-publish.py
rust/scx_loader/LICENSE
version-tool.py

Let's make cargo publishing a bit less painful.

release: Add cargo-publish.py

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

Using p->scx.slice to evaluate the consumed time slice can be a bit imprecise, because the sched_ext core implements yielding by setting p->scx.slice to 0.
When the task's vruntime is evaluated this is considered as the task has exhausted its entire allocated time slice, even though it voluntarily released the CPU before the slice fully expired.
To avoid this inaccuracy and prevent penalizing tasks that voluntarily release the CPU, always evaluate the used time slice based on the difference in the task's total execution time (p->se.sum_exec_runtime).
This method provides a more precise calculation of vruntime and results in a fairer task's deadline evaluation.

scx_bpfland: use sum_exec_runtime to evaluate task's used time slice

---

scheds/rust/scx_layered/src/main.rs

Add a new `LayerGrowthAlgo` which performs a round robin between NUMA nodes/LLCs. Introduce shuffling at all three layers (Nodes/LLCs/Cores) before the round robin to reduce conflicts between multiple layers.
Closes #588
2xNUMA nodes, 1 LLC per node
```
22:14:00 [DEBUG] layer: batch algo: RoundRobin core order: [16, 29, 5, 35, 7, 21, 19, 22, 17, 20, 3, 39, 8, 28, 9, 27, 12, 26, 11, 23, 0, 31, 1, 37, 2, 25, 10, 24, 15, 38, 14, 36, 4, 30, 6, 33, 18, 34, 13, 32]
22:14:00 [DEBUG] layer: immediate algo: RoundRobin core order: [12, 35, 14, 28, 0, 33, 3, 25, 5, 38, 8, 31, 15, 36, 2, 34, 6, 21, 17, 39, 18, 20, 9, 32, 13, 23, 19, 26, 11, 30, 7, 29, 1, 22, 16, 24, 4, 37, 10, 27]
22:14:00 [DEBUG] layer: normal algo: RoundRobin core order: [33, 5, 36, 14, 31, 18, 24, 12, 35, 9, 39, 16, 30, 2, 32, 8, …
```

scx_layered: add round robin growth strategy

---

scheds/rust/scx_lavd/src/bpf/main.bpf.c

In case of sync wake-up, consider waker's CPU also to improve cache locality.

scx_lavd: consider waker's CPU when ops.select_cpu()

---

rust/scx_rustland_core/assets/bpf/main.bpf.c

Prevent stall bypassing user-space scheduling for tasks that are handling page faults.

scx_rustland_core: fix mm stall

---

rust/scx_loader/src/main.rs
rust/scx_utils/src/gpu.rs
rust/scx_utils/src/topology.rs

run cargo fmt to make ci green

run cargo fmt to make ci green

---

.github/workflows/caching-build.yml

fix artifact names to work with merge queue naming

fix artifact names to work with merge queue naming

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Cleanup various compiler warnings.

scx_layered: Fix compiler warnings

---

scheds/rust/scx_lavd/src/bpf/main.bpf.c

scx_lavd: Fix typo

---

DEVELOPER_GUIDE.md

add link to generated docs in developer guide

add link to generated docs in developer guide

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

In lowlatency mode (option --lowlatency) tasks are ordered using a deadline that is evaluated as the vruntime minus a certain "bonus", determined in function of the max time slice and the average amount of voluntary context switches, to amplify the priority boost of the tasks that are voluntarily releasing the CPU (which are typically interactive).
However, this method can be extremely unfair in some cases: tasks with short bursts of voluntary context switches may receive a huge priority boost, making the rest of the system almost unresponsive (see massive hackbench stress tests for example).
To prevent this rework the task's deadline logic to use the vruntime and a "deadline component" that is a function of the average used time slice, scaled using a dynamic task priority (evaluated as …

scx_bpfland: rework lowlatency mode

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Improve the performance on non topology aware paths by skipping some map lookups and uneccessary initializations. Move idle cpu selection for non topology aware scheduling to separate function.

scx_layered: Improve perf on non topo aware paths

---

scheds/rust/scx_layered/src/main.rs

Add doc comment to `CpuPool` as a quick reference for each member. Most importantly, differentiate "cpu" and "core", as logical core and physical core, respectively.

scx_layered: Add doc comment to CpuPool

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

clang is correctly warning that we use various uninitialised variables. clean
these up so real errors are easier to read.
The largest change here is to non-topological layered_dispatch. The
matching_dsq logic seems to be incorrect. It checks whether an uninitialised
variable is 0, if it is sets it, then only uses the variable if the value is 0.
I have changed this to default to -1, then use the value if it is no longer -1.

layered: cleanup warnings in bpf compilation

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Enable specifying a layer growth algo when topology is disabled and have that be respected in dispatch.
Also, replace some member_vptr's with regular accesses in those iterations.
I saw a substantial change in stress-ng output for fork in local stress tests when setting all layers to random.
The usual result is ~3500-5500 bogo mips. This configuration yielded 6k minimum and 8-20k for most (7 tries). 
I kind of discount the 20k's altogether because I occasionally see those while testing w/o this change and a fully random config (maybe 1/10 tries), but I see it more often with this  change and a random config.
Wrt/ replacing member_vptr's with regular accesses, in addition to making the code a bit simpler, I think that could lighten those loops a bit (i.e. that adds assembly to those loops …

scx_layered: enable configuring layer iteration when no topo

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Refactor layered_dispatch into two functions: layered_dispatch_no_topo and
layered_dispatch. layered_dispatch will delegate to layered_dispatch_no_topo in
the disable_topology case.
Although this code doesn't run when loaded by BPF due to the global constant
bool blocking it, it makes the functions really hard to parse as a human. As
they diverge more and more it makes sense to split them into separate
manageable functions.
This is basically a mechanical change. I duplicated the existing function,
replaced all `disable_topology` with true in `no_topo` and false in the
existing function, then removed all branches which can't be hit.
Test plan:
- Runs on my dev box (6.9.0 fbkernel) with `scx_layered --run-example -n`.
- As above with `-t`.
- CI.

layered: split dispatch into no_topo version

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Fix verifier errors when using different DSQ iteration algorithms and cleanup some code.
`weight`:
```
$ sudo ./target/release/scx_layered  f:/home/hodgesd/user.json --dsq-iter-algo  weight 
21:38:05 [INFO] CPUs: online/possible=176/176 nr_cores=88
21:38:05 [INFO] libbpf: struct_ops layered: member cgroup_init not found in kernel, skipping it as it's set to zero
21:38:05 [INFO] libbpf: struct_ops layered: member cgroup_exit not found in kernel, skipping it as it's set to zero
21:38:05 [INFO] libbpf: struct_ops layered: member cgroup_prep_move not found in kernel, skipping it as it's set to zero
21:38:05 [INFO] libbpf: struct_ops layered: member cgroup_move not found in kernel, skipping it as it's set to zero
21:38:05 [INFO] libbpf: struct_ops layered: member cgroup_cancel_move not found …
```

scx_layered: Fix verifier errors

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Refactor topology preemption logic so the non topology aware code is contianed to a separate function. This should make maintaining the non topology aware code path far easier.
Topo aware:
```
$ sudo ./target/release/scx_layered --stats 1 f:/home/daniel/user2.json
01:26:01 [INFO] CPUs: online/possible=16/16 nr_cores=8
01:26:01 [INFO] libbpf: struct_ops layered: member cgroup_init not found in kernel, skipping it as it's set to zero
01:26:01 [INFO] libbpf: struct_ops layered: member cgroup_exit not found in kernel, skipping it as it's set to zero
01:26:01 [INFO] libbpf: struct_ops layered: member cgroup_prep_move not found in kernel, skipping it as it's set to zero
01:26:01 [INFO] libbpf: struct_ops layered: member cgroup_move not found in kernel, skipping it as it's set to zero
01:26:01 …
```

scx_layered: Refactor topo preemption

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

In the WAKE_SYNC path lf L3 cache awareness is disabled (--disable-l3) we may hit the following error:
Error: EXIT: scx_bpf_error (CPU L3 cpumask not initialized)
Fix this by setting the L3 cpumask to the whole primary domain if L3 cache awareness is disabled.

scx_bpfland: fix cpumask initialization error

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Cleanup some some ugly code in the idle/preempt path to remove unneeded checks.

scx_layered: Cleanup topology preempt path

---

scripts/vtime_dist.bt

For my own better understanding of vtime distribution across dsqs I made this bpftrace script. It might be useful for others as well.
Example output:
```
@dsq_vtime[1]:
[256K, 512K)           1 |                                                    |
[512K, 1M)             0 |                                                    |
[1M, 2M)               0 |                                                    |
[2M, 4M)               7 |                                                    |
[4M, 8M)             118 |                                                    |
[8M, 16M)            194 |                                                    |
[16M, 32M)           335 |                                                    |
[32M, 64M)           474 | …
```

Add bpftrace script to print vtime distributions across DSQs

---

scheds/rust/scx_lavd/src/bpf/lavd.bpf.h
scheds/rust/scx_lavd/src/bpf/main.bpf.c

- Fix the unnecessary downscaling in calculating the virtual deadline
- Fix an integer overflow in the introspection code (--monitor-sample-scheds)

scx_lavd: misc updates

---

DEVELOPER_GUIDE.md

Update the developer guide with info on how to run the helper script to generate Perfetto compatible traces.

Update developer guide with Perfetto info

---

scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c

If we're not on the wakeup path, we may see enqueue() invoked without select_cpu() which will require an idle cpu lookup. In order to fix this, we refactor the idle_cpu lookup in select_cpu so it can be invoked from enqueue().

scx_mitosis: handle enqueue() on !wakeup

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Refactor the logic for refresh cpumasks to be easy to read and verify.

scx_layered: Refactor refresh cpumasks

---

.github/actions/install-deps-action/action.yml
.github/workflows/caching-build.yml

remove apt fast from ci setup to reduce non-core dependencies and fix ci

remove apt fast from ci setup

---

scheds/rust/scx_rusty/src/bpf/main.bpf.c

Use the `cask_mask` helper function to cleanup scx_rusty.

scx_rusty: Cleanup cpumask casting

---

rust/scx_utils/src/topology.rs
scheds/rust/scx_layered/src/lib.rs

This PR addresses #733
* scx_layered: Read CPU topology for building CpuPool
* Building CpuPool from cache-cpu topology did not apply on arm, because `/sys/devices/system/cpu/cpu{}/cache/index{}/id` file is unavailable.
* Read CPU topology from topology.rs instead.

scx_layered: Fix crash on aarch64 due to unavailable cache id file

---

scheds/rust/scx_rustland/src/main.rs

Adjust the amount of vruntime budget an idle task can accumulate in function of its latency weight, which is derived from the average number of voluntary context switches.
This ensures that latency-sensitive tasks naturally receive an additional priority boost and we can get avoid scaling down the vruntime to determine the task's deadline, making the scheduler more fair.
It also makes the scheduler more robust, now rustland can survive intensive stress tests, such as `stress-ng --cpu-sched 64` or hackbench.

scx_rustland: Adjust task's vruntime budget based on latency weight

---

scheds/rust/scx_layered/src/bpf/intf.h
scheds/rust/scx_layered/src/bpf/main.bpf.c
scheds/rust/scx_layered/src/bpf/timer.bpf.c
scheds/rust/scx_layered/src/bpf/timer.bpf.h

Add a registry of timers and a timer manager for running bpf timers.

scx_layered: Add timer helpers

---

scripts/gen_vmlinux_h.sh

This script iterates over a list archs and generates vmlinux.h for each. Generated files are put under the corresponding arch directory.

Add script for generating per-arch vmlinux.h files

---

scheds/rust/scx_lavd/src/bpf/preempt.bpf.c

The previous code accesses uninitialized memory in comp_preemption_info() when called from can_task1_kick_task2() <-try_yield_current_cpu() to test if a task 2 is a lock holder or not. However, task2 is guaranteed not a lock holder in all its callers. So move the lock holder testing to can_cpu1_kick_cpu2().
This addresses https://github.com/sched-ext/scx/issues/845

scx_lavd: fix uninitialized memory access at comp_preemption_info()

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Refactor dispatch to use a separate set of global helpers for topo aware dispatch. This change only refactors dispatch to make it more maintainable, without any functional changes.

scx_layered: Refactor dispatch

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Add the layer CPU cost when dumping. This is useful for understanding the per layer cost accounting when layered is stalled.

scx_layered: Add layer CPU cost to dump

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

scx_layered Fix trace format

---

scheds/include/arch/x86/vmlinux-v6.12-rc2-g5b7c893ed5ed.h

* increasing the number of bits for cpumask

[bug-fix] fixes #810

---

scheds/rust/scx_lavd/src/bpf/main.bpf.c

Previously, the cur_logical_clk is updated with WIRTE_ONCE(), which does not guarantee the atomicity when concurrent writes happen -- which is possible. So change it using CAS (compare-and-swap).
This addresses https://github.com/sched-ext/scx/issues/897

scx_lavd: update cur_logical_clk atomically

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

When selecting the idle CPU use the idle_smt option on the layer. This may improve cache locality in some cases by placing tasks on CPUs that are on closer cache lines.

scx_layered: Use layer idle_smt option

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

The loops in topology aware mode were recently refactored to place the -per-LLC
loops inside the per-layer loops. However, the layer specific checks were left
in the inner loops, slowing this down unnecessarily.
Pull the layer specific checks from the inner loop into the outer loop.
Also changes these functions to `__weak` to ensure they don't get inlined -
they're expected to be verified as global functions.
Note to reviewers: this looks good to me, but I'd appreciate if you reviewed
the De Morgan applications in detail.
Test plan:
- `cargo build --release && sudo target/release/scx_layered --run-example` on a
machine with multiple LLCs. It's possible to stall it quite easily with
stress-ng but I believe this is the case on main.

layered/topo: lift layer specific checks out of per-LLC loop

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Output:
```
HI_FALLBACK[1024] nr_queued=16 -28532ms
HI_FALLBACK[1025] nr_queued=17 -29620ms
LO_FALLBACK nr_queued=0 -0ms
COST GLOBAL[0][build] budget=37647933128584578 capacity=37647933128584578
COST GLOBAL[1][stress-ng] budget=37647933128584578 capacity=37647933128584578
COST GLOBAL[2][normal] budget=24054910496864847 capacity=24054910496864847
COST FALLBACK[1024][0] budget=37647933128584578 capacity=37647933128584578
COST FALLBACK[1025][1] budget=37647933128584578 capacity=37647933128584578
COST CPU[0][0][build] budget=5555555555555555 capacity=5555555555555555
COST CPU[0][1][build] budget=2777748217976380 capacity=2777777777777777
COST CPU[0][2][build] budget=5555555544755555 capacity=5555555555555555
COST CPU[0]FALLBACK[0][1024] budget=0 capacity=5555555555555555
COST …
```

scx_layered: Add fallback costs to dump

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

scx_layered: Fix formatting

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

A task may end up in a layer which doesn't have any CPUs that are allowed for the task. They are accounted as affinity violations and put onto a fallback DSQ. When antistall_set() is trying to find the CPU to run a stalled DSQ, it ignores CPUs that are not in the first task's layered_cpumask. This makes antistall skip stalling DSQs with affnity violating tasks at the front.
Consider all allowed CPUs for affinity violating tasks. While at it, combine the two if blocks to set antistall to improve readability.

scx_layered: Don't limit antistall execution to layered_cpumask

---

scheds/rust/scx_lavd/src/bpf/main.bpf.c

Instead of using a constant runtime value in the deadline calculation, use the adjusted runtime value of a task. Since tasks' runtime value follows a highly skewed distribution, we convert the highly skewed distribution to a mildly skewed distribution to avoid stalls. This resolves the audio breaking issue in osu! under heavy background workloads.

scx_lavd: Factor the task's runtime more aggressively in  a deadline calculation

---

.github/workflows/caching-build.yml
DEVELOPER_GUIDE.md
rust-toolchain.toml

Test plan:
- CI
- On a machine with rustup this works.

rust-toolchain: init file

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
scheds/rust/scx_bpfland/src/main.rs

With commit efc41dd ("scx_bpfland: strict domain affinity") the scheduling domain of a task is determined when the task is created or when it changes its affinity via ops.set_cpumask().
When the energy profile changes, the global primary scheduling domain is automatically adjusted (for example switching from P-cores to E-cores or vice-versa), but the scheduling domain of each running task is not updated to reflect this change, so the existent tasks will keep running on the same cores.
To fix this without introducing too much overhead in the hot paths, simply trigger a scheduler restart on energy profile changes.
Moreover, allow tasks to keep running on the same CPU only if the CPU is in the primary scheduling domain.
This allows to automatically migrate tasks to the new scheduling domain …

scx_bpfland: restart on energy profile change

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Refactor layer initialization into a separate helper function.

scx_layered: Refactor layered initialization

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Refactor CPU initialization into a separate helper function and clean up the use of zero values with a common const.

scx_layered: Refactor CPU initialization

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

While refactoring layer init path, 0edbc05e6da1 ("scx_layered: Refactor layered initialization") dropped layer->id init which breaks a lot of stuff. Fix it. While at it, replace j, k iterators with i, j in init_layer().

scx_layered: Fix missing layered->id init

---

rust/scx_loader/src/main.rs

fixes https://github.com/sched-ext/scx/issues/937

scx_loader: restart scheduler upon fail

---

scheds/include/scx/common.bpf.h

Introduce for_each_possible_cpu() for_each_online_cpu() iterators

---

.github/workflows/caching-build.yml

fix document generation by disabling document generation for all features.
looks like a bug in the tooling around optional features and the all-features flag.

fix document generation

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Fix idle selection to take into account the layer growth algorithm to properly select big/little cores when selecting idle CPUs.

scx_layered: Fix idle selection on big/little

---

scheds/rust/scx_layered/src/bpf/intf.h
scheds/rust/scx_layered/src/bpf/main.bpf.c
scheds/rust/scx_layered/src/bpf/util.bpf.c
scheds/rust/scx_layered/src/main.rs
scheds/rust/scx_layered/src/stats.rs

- Drop now unused load metric.
- Implement per-task avg runtime tracking.
- Layer sizing related bug fixes.

scx_layered: State tracking updates and layer sizing related fixes

---

.github/workflows/caching-build.yml

this fixes the pages build here: 
https://github.com/likewhatevs/scx/actions/runs/12124307848/job/33801740919

scx: fix pages build

---

scripts/scxtop.bt

Fix a few bugs with calculations and add dsq vtime.

scripts: Refactor scxtop

---

rust/scx_loader/configuration.md
rust/scx_loader/org.scx.Loader.xml
rust/scx_loader/src/config.rs
rust/scx_loader/src/lib.rs

ref: https://github.com/sched-ext/scx/pull/1094

scx_loader: add mode for server-oriented workloads

---

rust/scx_utils/src/bpf_builder.rs

The Rust multiple compilation unit code paths do not currently generate rerun-if-changed cargo statements for the BPF files. Add cargo rerun-if-changed statement generation in scx_utils during the compile-and-link process.

fix missing rerun-if-changed statements

---

scheds/rust/scx_lavd/src/bpf/main.bpf.c
scheds/rust/scx_lavd/src/bpf/preempt.bpf.c

Refactor the code to get the current time only once in an operation.

scx_lavd: Reuse bpf_ktime_get_ns() as many as possible

---

rust/scx_rustland_core/assets/bpf/main.bpf.c
rust/scx_rustland_core/src/alloc.rs

Minor build fixes and a small improvement in the CPU idle selection logic.

scx_rustland_core: minor fixes

---

scheds/rust/scx_lavd/src/bpf/main.bpf.c

When the system is overloaded, there is no idle CPU, so stay on the previous CPU without performing a (hopefully) optimal idle CPU selection process.

scx_lavd: Add a fast path to pick_idle_cpu() when overloaded

---

scheds/rust/scx_layered/src/lib.rs

scx_layered: Fix lifetime variable related compile warnings

---

scheds/rust/scx_flash/src/bpf/main.bpf.c

Similar to commit 809ce6c ("scx_rusty: prevent scheduling bubbles on kernels >= 6.12"), avoid allocating idle CPUs unless it is certain that a task will be dispatched to them.
This ensures the CPU idle state reflects its actual state and is not allocated without running any tasks.

scx_flash: prevent scheduling bubbles on kernels >= 6.12

---

tools/scxtop/src/app.rs

Misc fixes for `scxtop` to make the LLC/Node views more usable:
- Fix titles for LLC/Node to display perf event sample rate
- Add scheduler view to LLC/Node view
- Make formatting consistent for borders on LLC/Node views

scxtop: Add scheduler view to llc/node views

---

tools/scxtop/src/app.rs

Add support for both barchart and sparkline view states for the NUMA node view in scxtop.
Example output:

scxtop: Add barchart to node view

---

rust/scx_utils/src/bpf_builder.rs
tools/scxtop/src/app.rs
tools/scxtop/src/perf_event.rs
tools/scxtop/src/theme.rs

scxtop: code simplifications and reduction of heap allocations for perf

---

tools/scxtop/src/app.rs
tools/scxtop/src/cpu_data.rs
tools/scxtop/src/llc_data.rs
tools/scxtop/src/node_data.rs

Cleanup initialization of cpu, node and llc data when intializing events.

scxtop: Cleanup event intialization

---

INSTALL.md

The scx package was accepted into Factory and is able to be installed
without adding any repositories.

docs: Update tumbleweed installation steps

---

scheds/rust/scx_layered/examples/cmdjoin.c
scheds/rust/scx_layered/examples/cmdjoin.json
scheds/rust/scx_layered/src/main.rs

Document the CmdJoin layer type and add a usage example.

scx_layered: Document the CmdJoin layer

---

rust/scx_utils/src/topology.rs
scheds/rust/scx_layered/src/layer_core_growth.rs
scheds/rust/scx_layered/src/main.rs
tools/scxtop/src/app.rs

struct init, loops and iterators simplifications for scx_layered.

scx_utils/scx_layered: code modernisation/simplifications.

---

scheds/rust/scx_lavd/src/main.rs

When determining the preference ordering of CPUs for performance and power-save mode, consider a CPU's hardware resource sharing levels -- such as whether a CPU shares an L2/L3 cache or a physical core. For the performance mode, in which using an SMT core is not preferred, CPUs that share fewer hardware resources are preferred. On the other hand, for the power-save mode, in which using an SMT core is preferred, CPUs that share more hardware resources are preferred.

scx_lavd: Conder the hardware resource sharing level in CPU ordering

---

tools/scxtop/src/app.rs

Fix layout when rendering DSQ sparklines so that there is no overflow in the node, llc, and scheduler views.
`main`:
PR:

scxtop: Fix layout for sparklines

---

scheds/rust/scx_layered/src/main.rs

scx_layered: fix typo in docs

---

tools/scxtop/src/perfetto_trace.rs

Clean up uses of `.entry` by creating the `Vec` empty first then always pushing
in the same way.
Test plan:
- It builds.
- It generated a valid trace.

scxtop: clean up duplicated entry insertion code

---

rust/scx_utils/src/bpf_builder.rs

The schedulers that use multiple compilation units only generate Clang rerun-if-changed directives for the *.bpf.c files explicitly added to build.rs. Expand the code to also rebuild the scheduler if any of its local *.h files are modified.

rust/scx_utils: rebuild scheduler when headers are modified

---

tools/scxtop/src/main.rs

This showed up because we're holding an RwLock across an await point. Rather
than changing this to a tokio aware lock, let's remove the Arc and lock
altogether as this variable is only used from a single thread.
Thank you Rust for confirming this is safe :)

scxtop: drop unnecessary Arc and RwLock on tui

---

tools/scxtop/src/app.rs
tools/scxtop/src/bpf/intf.h
tools/scxtop/src/bpf/main.bpf.c
tools/scxtop/src/lib.rs
tools/scxtop/src/main.rs
tools/scxtop/src/perfetto_trace.rs

Add softirq event collection for perfetto traces.
Screenshot of trace:

scxtop: Add softirq events

---

scheds/rust/scx_lavd/src/bpf/preempt.bpf.c

When trying to preempt the currently running task on the current CPU, instead of the expensive scx_bpf_kick_cpu(SCX_KICK_PREEMPT) call, reset task's time slice to 0 (ops.tick) or 1 (ops.enqueue). We do not reset the time slice to 0 in the ops.enqueue path because it can cause the zero slice warning -- letting the sched_ext core reset the time slice to SCX_SLICE_DFL (20 msec).

scx_lavd: Avoid scx_bpf_kick_cpu(SCX_KICK_PREEMPT) for self-preemption

---

rust/scx_loader/configuration.md
rust/scx_loader/src/config.rs
rust/scx_loader/src/lib.rs
rust/scx_loader/src/main.rs

scx_loader: Add p2dq scheduler

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Be less aggressive with load balancing on dispatch and always try to consume from LLC local DSQ first. On enqueue path kick idle CPUs for more responsiveness. Update stats to be more accurate for DSQ usage.

scx_p2dq: Refactor dispatch for better interactivity

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Simplify idle CPU selection to be more idle SMT affinitized and fix verifier issue for big/little topologies.

scx_p2dq: Fix verifier issue on big/little topology

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
scheds/rust/scx_p2dq/src/main.rs

Add autoslice tuning mode and fix a bug when a tasks stops to check the DSQ index rather than the DSQ id when changing DSQs.
Running with `scx_p2dq --stats 1  -s 1 -x 1 -v -r 1 -a -q 3` trace pipe logs of slice tuning with `stress-ng`:
```
stress-ng-cpu-20532   [010] ..s1. 19103.780198: bpf_trace_printk: load 4147435569 interactive 11271777
stress-ng-cpu-20532   [010] ..s1. 19103.780210: bpf_trace_printk: ideal/sum 41474355/11271777
stress-ng-cpu-20532   [010] ..s1. 19103.780211: bpf_trace_printk: interactive slice 5550
stress-ng-cpu-20532   [010] ..s1. 19103.780211: bpf_trace_printk: interactive slice 22200
stress-ng-cpu-20532   [010] ..s1. 19103.780212: bpf_trace_printk: interactive slice 44400
stress-ng-cpu-20542   [010] ..s1. 19104.030221: bpf_trace_printk: load 3992651369 interactive …
```

scx_p2dq: Add autoslice tuning

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Update pick2 migration logic so that only non interactive tasks are considered for XLLC/XNUMA migrations during pick2 balancing in dispatch.

scx_p2dq: Update pick2 migration logic

---

tools/scxtop/src/app.rs
tools/scxtop/src/bpf/intf.h
tools/scxtop/src/bpf/main.bpf.c
tools/scxtop/src/lib.rs
tools/scxtop/src/main.rs
tools/scxtop/src/perfetto_trace.rs

Add IPI event collection and perfetto trace collection.

scxtop: Add IPI events

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Add support in select CPU path to handle wake sync events. This is only partial support for wake sync but should be an improvement over nothing.

scx_p2dq: Add initial wake sync support

---

tools/scxtop/README.md

Update scxtop README with some useful information and screenshots

scxtop: Update README

---

scheds/rust/scx_bpfland/src/main.rs

Skip creating cache domains when they don't provide any benefit:
- when a cache domain contains only a single CPU,
- when a cache domain contains all available CPUs,
- when all CPUs in the cache domain belong to the same SMT core.

scx_bpfland: avoid creating redundant cache domains

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
scheds/rust/scx_bpfland/src/main.rs

In ops.dispatch() we normally extend the time slice for tasks running on primary domain CPUs that have no contention, allowing them to continue their execution without the overhead of going through ops.enqueue().
However, the CPU might be part of an SMT core with another task running on the sibling CPU. In this case, migrating the task to another CPU, preferably a fully idle SMT core, can lead to better performance.
Therefore, in such cases, rather than keeping the task running on its current CPU, direct it through the standard ops.enqueue() path to enable potential migration.

scx_bpfland: Always re-enqueue tasks that are running on a busy SMT core

---

rust/scx_utils/src/gpu.rs

allows to retrieve the closest devices (connectivity wise) to a given
GPU. NVML_TOPOLOGY_HOSTBRIDGE is a compromise in term of check
efficiency as we limit to the same PCI board.
We can possibly refine the mode if we deal with a multi board system
(e.g. some Tesla) if it makes sense, so we can choose a faster mode
in those cases.

scx_utils: gpu topology adding nearest available devices.

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

When the system is fully busy, immediately give up searching for an idle CPU and just dispatch tasks on the first CPU available.
Moreover, do not attempt to migrate a task to a full-idle SMT core if all the SMT cores are busy.

scx_bpfland: Skip idle CPU selection when system is fully busy

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

Rename is_full_smt() to is_fully_idle() and return true when SMT is disabled, to represent the fact that the CPU doesn't have any busy shared resources.
This solves an issue in non-SMT cases where CPUs were incorrectly considered always busy.
Fixes: a480d880 ("scx_bpfland: reduce task migrations")

scx_bpfland: fix non-SMT CPU busy state detection

---

.github/workflows/bpf-next-test.yml
.github/workflows/caching-build.yml
.github/workflows/stable.yml
meson-scripts/stress_tests.ini
meson-scripts/test_sched
scheds/rust/scx_p2dq/Cargo.toml
services/scx

Add p2dq to meson scripts/CI for builds and stress tests.

meson: Add p2dq to meson scripts and CI

---

Cargo.lock
tools/scxtop/Cargo.toml
tools/scxtop/src/cli.rs
tools/scxtop/src/config.rs
tools/scxtop/src/main.rs

Add a separate subcommand for running the scxtop TUI. Add a subcommand to generate shell completions for scxtop.

scxtop: Add separate subcommand for TUI and shell completion

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

scx_layered: fix gpu matcher

---

scheds/rust/scx_wd40/src/domain.rs
scheds/rust/scx_wd40/src/load_balance.rs
scheds/rust/scx_wd40/src/main.rs

- mostly remove unneeded clone() calls.
- remove unneeded references.
- apply lifetime simplification like other schedulers.

scx_wd40: optimisations/simplifications

---

scheds/rust/scx_bpfland/src/main.rs

Properly differentiate between CPUs that share the same cache and those that belong to the same SMT core.
This fixes a bug where L2/L3 caches were incorrectly identified as belonging to the same SMT core, causing them to be skipped.
Fixes: def6d305 ("scx_bpfland: avoid creating redundant cache domains")

scx_bpfland: fix cache domain detection

---

tools/scxtop/src/bpf/main.bpf.c
tools/scxtop/src/main.rs

scx_bpf_dsq_insert_vtime, scx_bpf_dsq_insert, scx_bpf_dsq_move scx_bpf_dsq_move_set_vtime and scx_bpf_dsq_move_set_slice returns ENOENT.

scxtop: making few kernel probes conditional.

---

scheds/rust/scx_flash/src/bpf/main.bpf.c
scheds/rust/scx_flash/src/main.rs

With the recent kernel improvements (such as the topology awareness in the built-in idle CPU selection policy and the NUMA functionalities) we can now get rid of the custom `ops.select_cpu()` implementation and rely on the in-kernel one.
Moreover, we can simplify the overall scheduling policy, aligning more to the scx_bpfland algorithm, also applying some fixes as well.
Overall, with these new changes in place, the scheduler seems to provide a better level of responsiveness, it's also really hard to trigger audio cracking issues, even when the system is massively overloaded and we can reduce the code significantly:
```
scheds/rust/scx_flash/src/bpf/main.bpf.c | 700 +++--------------------
scheds/rust/scx_flash/src/main.rs        |  85 ---
2 files changed, 91 insertions(+), 694 …
```

scx_flash: simplify scheduling policy

---

tools/scxtop/src/app.rs
tools/scxtop/src/bpf/main.bpf.c

Fix initialization issues in DSQ 0 when dispatching events that don't have previous values. Filter these DSQ events until an initial DSQ dispatch time is recorded.
With fix:
`main` branch:

scxtop: Fix DSQ initialization

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

When a CPU is stolen by a higher scheduling class we re-schedule all the tasks in the local DSQ from ops.cpu_release() to give them a chance to be dispatched on a different CPU.
However, this is pointless for per-CPU tasks, since they can only run on that specific CPU, so re-scheduling them is only increasing the risk of triggering stalls.
Therefore, dispatch them directly on reschedule, to maximize their chances of reclaiming the CPU quickly and avoiding stalls.
This approach will be more effective once dl_server support is added to the sched_ext core.

scx_bpfland: handle per-CPU tasks preempted by a higher scheduling class

---

scheds/rust/scx_flash/src/bpf/main.bpf.c

Trigger scx_bpf_reenqueue_local() from ops.cpu_release(), similarly to scx_bpfland, to mitigate potential stalls that might be caused by higher scheduling classes stealing CPUs from scx.
This can help mitigate issues like #1504.

scx_flash: mitigate stalls from higher priority scheduling classes

---

scheds/rust/scx_p2dq/src/main.rs

Add option to set idle QoS resume latency. This can be useful in configuring the latency at which a CPU enters deeper sleep states. This is more for experimentation, but so far being able to control the idle resume latency seems to have some interesting results.
Tested with a smallish value (100us):
```
./target/release/scx_p2dq --idle-resume-us 100
01:54:30 [INFO] Setting idle QoS to 100us
01:54:30 [INFO] Running scx_p2dq (build ID: 1.0.10-gb5976f80-dirty x86_64-unknown-linux-gnu)
01:54:30 [INFO] DSQ[0] slice_ns 100000
01:54:30 [INFO] DSQ[1] slice_ns 3200000
01:54:30 [INFO] DSQ[2] slice_ns 6400000
01:54:30 [INFO] P2DQ scheduler started! Run `scx_p2dq --monitor` for metrics.
```
`turbostat` reading of c-states:
```
Core    CPU     Avg_MHz Busy%   Bzy_MHz TSC_MHz IPC     IRQ     POLL    C1 …
```

scx_p2dq: Add idle resume QoS config

---

scheds/rust/README.md
scheds/rust/scx_p2dq/README.md

Update links of rust schedulers and add additional details for p2dq docs.

docs: Update rust scheduler docs

---

scheds/rust/scx_layered/src/layer_core_growth.rs

node spread wasn't accounting for smt order/topo beyond "spread across numa nodes". fix this to improve locality and make `exclusive` flag work better (err, if not better, make how `NodeSpread + exclusive` work make sense w/ how folks would reason about them).

scx_layered: make nodespread account for smt

---

scheds/rust/scx_layered/src/layer_core_growth.rs

make node spread determine cpu order in a less-fragile manner (i.e. use topo instead of shifting by number of cpus)

scx_layered: cleanup node spread

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Refactor p2dq idle CPU selection to use scx_bpf_pick_idle_cpu for idle CPU selection. Simplify some of the cpumask null checks to make the code easier to follow.

scx_p2dq: Refactor idle CPU selection

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Refactor pick_two_cpu when load balancing to first attempt to find an idle SMT and then an idle cpu. This should make slightly better load balancing decisions.

scx_p2dq: Refactor pick_two_cpu idle selection

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Update the enqueue path so that idle CPU selection attempts to select idle cores first.

scx_p2dq: Update enqueue CPU selection

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
scheds/rust/scx_p2dq/src/main.rs

Update default p2dq scheduler configs to be more dynamic based on the underlying hardware. Refactor idle selection for load balancing.

scx_p2dq: Update default scheduler config

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Refactor the enqueue path when an idle CPU is found to directly dispatch to the local CPU.
I think this makes sense on the enqueue path to first check for an idle CPU before inserting in the the LLC DSQ.

scx_p2dq: Refactor enqueue path

---

scheds/rust/scx_p2dq/src/main.rs

Add support if enabled in the kernel for SCX_OPS_ALLOW_QUEUED_WAKEUP.
I believe this should be supported now handles when `select_cpu` isn't called ([code](https://github.com/sched-ext/scx/blob/main/scheds/rust/scx_p2dq/src/bpf/main.bpf.c#L663)).

scx_p2dq: Add support for SCX_OPS_ALLOW_QUEUED_WAKEUP

---

tools/scxtop/src/app.rs
tools/scxtop/src/bpf/intf.h
tools/scxtop/src/bpf/main.bpf.c
tools/scxtop/src/lib.rs
tools/scxtop/src/main.rs
tools/scxtop/src/perfetto_trace.rs

refactoring existing cpu hotplug enter naming as well.

scxtop: adding cpu hotplug event on exit trace event.

---

tools/scxtop/README.md

Update docs to include information on shell completions and collecting perfetto traces.

scxtop: Update docs

---

scheds/rust/scx_bpfland/src/main.rs

Introduce --disable-smt to explicitly disable SMT support. With this option, the scheduler will select idle CPUs without distinguishing between fully-idle and partially-idle SMT cores.

scx_bpfland: Introduce an option to disable SMT awareness

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

During direct dispatch from ops.enqueue(), move the task to the right picked CPU, if a new idle CPU is found for migration.
Moreover, make sure to ignore migration attempts with per-CPU tasks and always keep them running on the same CPU if it's idle.
Fixes: b7af9db3 ("scx_bpfland: Handle ttwu_queue case in ops.enqueue()")

scx_bpfland: Fix direct dispatch migration

---

scheds/c/scx_pair.bpf.c

suggestion fron @DanielKristofKiss
close GH-1498

Fix GH-1498 never inline try_dispatch.

---

rust/scx_utils/src/energy_model.rs
rust/scx_utils/src/topology.rs

and make it the new energy model code more consistent,
rust idiomatic wise.

scx_utils: fix too_many_arguments warning on create_insert_cpu().

---

tools/scxtop/src/main.rs

Some progs require a libbpf with extra BTF info to attach properly. Conditionally attach these probes to prevent warnings from autoattachment.

scxtop: Conditionally attach progs

---

scheds/include/scx/common.bpf.h

Testing p->migration_disabled in a BPF code is tricky because the migration is _always_ disabled while running the BPF code. The prolog (__bpf_prog_enter) and epilog (__bpf_prog_exit) for BPF code execution disable and re-enable the migration of the current task, respectively. So, the _current_ task of the sched_ext ops is always migration-disabled. Moreover, p->migration_disabled could be two or greater when a sched_ext ops BPF code (e.g., ops.tick) is executed in the middle of the other BPF code execution.
Therefore, we should decide that the _current_ task is migration-disabled only when its migration_disabled count is greater than one. In other words, when  p->migration_disabled == 1, there is an ambiguity, so we should check if @p is the current task or not.

scx_utils: Correctly test is_migration_disabled().

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

The task weight range is quite large: [1 .. 10000] (default 100) and it can occasionally lead to stalls when tasks with low nice values run alongside those with high nice values. This issue arises from the way vruntime, and consequently task's deadline, is scaled.
For example, in Fedora with dnf-automatic enabled, the dnf process may run with a niceness of 19. If there are tasks running with nice values of -10 or -20, their relative vruntime scaling factor would be 1000 or even 10000, which can easily increase the risk of triggering stalls.
To mitigate the influence of task weight on deadline computation, normalize the weight into a smaller range: [1 .. 128] (default 64).
This normalization ensures that the relative vruntime scaling factor in the previous example would be around 20 or 100 …

scx_bpfland: Normalize task weight

---

scheds/rust/scx_layered/src/main.rs

Gate nvidia_poll kprobe behind flag `--enable-nvidia-poll`.
This probably is creating performance overhead. It is unclear how to deal with this, because there is a trade off between knowing the correct GPU PIDs ASAP (to place them correctly) and the overhead obtaining this information incurs.

scx_layered: gate nvidia_poll kprobe behind flag

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

Prevent updating task's local cpumasks when it's not needed. Moreover, fix a bug where the L2 cpumask was incorrectly ignored when L3 cpumask is defined.

scx_bpfland: Avoid unnecessary cpumask updates

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c
scheds/rust/scx_p2dq/src/lib.rs

Add a slack factor that prevents load balancing if load is within a certain percentage.

scx_p2dq: Refactor dispatch load balancing

---

Cargo.lock
scheds/rust/scx_p2dq/Cargo.toml

scx_p2dq: Bump version

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Small optimizations on the pick_idle_cpu path to improve performance.
PR:
```
Wakeup Latencies percentiles (usec) runtime 30 (s) (408405 total samples)
50.0th: 8          (173876 samples)
90.0th: 12         (105937 samples)
* 99.0th: 17         (30165 samples)
99.9th: 24         (2525 samples)
min=1, max=4010
Request Latencies percentiles (usec) runtime 30 (s) (409159 total samples)
50.0th: 6600       (116368 samples)
90.0th: 10544      (160256 samples)
* 99.0th: 12304      (36233 samples)
99.9th: 17760      (3671 samples)
min=5833, max=54415
20.0th: 13648      (8 samples)
* 50.0th: 13808      (15 samples)
90.0th: 13840      (6 samples)
min=11603, max=13865
average rps: 13638.63
```
`eevdf`:
```
Wakeup Latencies percentiles …
```

scx_p2dq: Optimize paths on pick_idle_cpu

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Currently affinitized tasks can cause stalls. For now select a random CPU in the affinitized mask and direct dispatch. On `main` p2dq can stall when handling affinitized  tasks:
```
[sudo] password for :
22:03:56 [INFO] Running scx_p2dq (build ID: 1.0.13-g6483f5bf-dirty x86_64-unknown-linux-gnu)
22:03:56 [INFO] DSQ[0] slice_ns 100000
22:03:56 [INFO] DSQ[1] slice_ns 3200000
22:03:56 [INFO] DSQ[2] slice_ns 6400000
22:03:56 [INFO] Kernel does not support queued wakeup optimization.
22:03:56 [INFO] P2DQ scheduler started! Run `scx_p2dq --monitor` for metrics.
DEBUG DUMP
================================================================================
kworker/u97:3[16913] triggered exit kind 1026:
runnable task stall (plasmashel:cs0[25797] failed to run for 24.000s)
Backtrace: …
```

scx_p2dq: Fix handling of affinitized tasks

---

.github/actions/install-deps-action/action.yml
Cargo.lock
tools/scxtop/Cargo.toml
tools/scxtop/build.rs
tools/scxtop/src/app.rs
tools/scxtop/src/perfetto_trace.rs
tools/scxtop/src/protos/mod.rs

Clean release builds on my machine:
```console
$ cargo check # prefetch dependencies
$ cargo clean && cargo build --release
...
$ git switch main
$ cargo clean && cargo build --release
...
```
|   protobuf crate   | release | check  |
|--------------------|--------:|-------:|
| `protobuf-codegen` |  65.00s | 37.12s |
| `prost-build`      |  50.02s | 21.33s |
Closes #1462

fix(#1462): switch scxtop from protobuf to prost

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

- Fix underflow in reported queue delays.
- Fix cpumask printing format.

scx_layered: Debug dump improvements

---

rust/scx_utils/src/bpf_builder.rs
rust/scx_utils/src/build_id.rs
rust/scx_utils/src/cpumask.rs

and addressing few clippy warnings.

scx_utils: using more modern rust idiomatics.

---

scheds/rust/scx_flash/src/bpf/main.bpf.c

When a higher scheduling class steals a CPU, we trigger a re-enqueue of all the tasks waiting on that CPU, to give them a chance to be dispatched elsewhere, preventing potential stalls.
Per-CPU tasks are excluded by this logic and they are just re-enqueued directly to the same CPU's local DSQ, as they can't be migrated somewhere else.
However, this behavior can unintentionally favor per-CPU tasks if a higher class task periodically steals the CPU, since these tasks get continuously re-enqueued locally and may run ahead of other tasks without affinity constraints, potentially causing stalls.
To address this, treat per-CPU tasks like any other: enqueue them to the shared per-node DSQ during SCX_ENQ_REENQ to ensure a fairer scheduling and prevent starvation.

scx_flash: Avoid direct local dispatch of per-CPU tasks on SCX_ENQ_REENQ

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

The --slice-lag option was introduced to give users control over the maximum vruntime budget that an idle task can accumulate, effectively capping the advantage sleeping tasks receive in scheduling decisions.
A larger slice_lag favors tasks that sleep longer by allowing them to accumulate more credit, leading to shorter deadlines and earlier execution. A smaller slice_lag reduces the advantage of long sleeps, treating short and long sleeps equally once they exceed the threshold.
If slice_lag is negative, it can be used to de-emphasize the deadline-based scheduling altogether by charging all tasks a fixed vruntime penalty (equal to the absolute value of slice_lag), effectively approximating FIFO behavior as the penalty increases.
Commit f61405e4 ("scx_bpfland: Do not scale slice lag with …

scx_bpfland: Restore slice_lag tunable

---

rust/scx_utils/src/topology.rs

The previous handling of CPU IDs for natural ordering ignored the NUMA boundaries, causing an error on multi-NUMA machines. So, pursue the numerical ordering of CPU IDs within a NUMA domain.
Fixes: 98f24eaa ("scx_utils: Create Cpus in a numerical order.")
Reported-by: Andrea Righi <arighi@nvidia.com>

scx_utils: Fix incorrect handling of CPU IDs on multi-NUMA machines.

---

scheds/rust/scx_lavd/src/bpf/idle.bpf.c

Previously, the synchronous wake-up is used to mitigate cross-domain migrations. However, waker's CPU is good for cache locality too.
If the waker CPU is idle, stay on the waker CPU when there is no other idle CPU in the sticky domain. It is good for cache locality because the waker task hands over the CPU to the wakee task for the further processing after finishing its job.

scx_lavd: Improve handling of synchronous wake-up.

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

make verifier happy. should do the same thing, but with a happy verifier.

layered: verifier fix

---

rust/scx_rustland_core/assets/bpf/main.bpf.c

When a task expires its time slice, if there are no other competing tasks on the same CPU, automatically replenish its time slice and let it continue running without going through the full scheduling pipeline.
This helps maximize CPU utilization and significantly reduces overhead when the system is not overcommitted.
This also doesn't introduce regression on large systems, unlike the previous attempt: commit c688b10b ("scx_rustland_core: Maximize CPU utilization").
Tests
=====
Performance was evaluated using two scenarios: a parallel kernel build to measure throughput and a combination of stress-ng's socket and CPU stressors to assess responsiveness under background load:
- kernel build time: $ make -j $(nproc)
- socket messages with background load: $ stress-ng -c $(nproc) --sock …

scx_rustland_core: Improve CPU utilization

---

rust/scx_rustland_core/assets/bpf/main.bpf.c

Keep track if the user-space scheduler is not running for too long (USERSCHED_TIMER_NS) and in that case explicitly wakeup an idle CPU and force the user-space scheduler to run.
This allows to automatically recover from potential stall conditions when the BPF <-> user-space scheduling pipeline gets stuck.

scx_rustland_core: Periodically wakeup user-space scheduler

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Fix nice handling to use the existing p->scx.weight value for scaling vtime and time slices.
Ran eevdf vs p2dq with background `nice`d work:
```
$ nice -n 19 stress-ng -c `nproc` -t 15
stress-ng: info:  [24758] setting to a 15 secs run per stressor
stress-ng: info:  [24758] dispatching hogs: 16 cpu
stress-ng: info:  [24758] skipped: 0
stress-ng: info:  [24758] passed: 16: cpu (16)
stress-ng: info:  [24758] failed: 0
stress-ng: info:  [24758] metrics untrustworthy: 0
stress-ng: info:  [24758] successful run completed in 15.01 secs
```
`p2dq`:
```
$ nice -n -19 stress-ng -c `nproc` -t 10 -M
stress-ng: info:  [24729] setting to a 10 secs run per stressor
stress-ng: info:  [24729] dispatching hogs: 16 cpu
stress-ng: metrc: [24729] stressor       bogo ops real time  usr time  sys time   bogo …
```

scx_p2dq: Fix nice handling

---

scheds/rust/scx_lavd/src/bpf/balance.bpf.c
scheds/rust/scx_lavd/src/bpf/idle.bpf.c
scheds/rust/scx_lavd/src/bpf/intf.h
scheds/rust/scx_lavd/src/bpf/lavd.bpf.h
scheds/rust/scx_lavd/src/bpf/main.bpf.c
scheds/rust/scx_lavd/src/bpf/util.bpf.c
scheds/rust/scx_lavd/src/main.rs
scheds/rust/scx_lavd/src/stats.rs

This PR includes optimizations for common cases: notably ops.dispatch(), math in calculating deadlines and time slides, and dealing with CPU utilization. No behavioral changes are intended.

scx_lavd: Common case optimizations for ops.dispatch() and more.

---

scheds/rust/scx_rustland/src/main.rs

Evaluate the task's used time slice based on the total execution time since its last sleep (exec_runtime).
This provides a smoother measure of how long a task has kept a CPU busy and eliminates the need to store the previous sum_exec_runtime for each task, which also reduces the memory footprint of the user-space scheduler.

scx_rustland: Evaluate used time slice based on partial exec runtime

---

tools/scxtop/src/app.rs

`scxtop` currently panics if `StatsClient` fails to connect, which happens with schedulers that do not expose `scx_stats` over the default socket.
This patch wraps `stats_client` in `Option<>` and conditionally performs stats fetching. This avoids crashing when stats are unavailable.
Closes: #1588

scxtop: Make stats client optional to avoid panic

---

README.md

README: fix inconsistent formatting

---

scheds/rust/scx_tickless/src/bpf/main.bpf.c

Avoid pinning the scheduling timer to a single primary CPU, instead, allow it to run on any available CPU. While this may introduce some minor system noise, it improves the overall throughput, especially when the system is fully saturated.
Moreover, rather than cycling through all CPUs to identify the idle ones, directly iterate over the idle CPUs using the idle cpumasks. This reduces the overhead of finding which CPUs are idle, especially on large systems.

scx_tickless: Improve scheduling timer

---

scheds/rust/scx_tickless/src/bpf/main.bpf.c

When assigning tasks to the available CPUs, treat the scheduling CPUs as a last resort to ensure they're kept free whenever possible. In this way they can be used primarily for scheduling purposes, giving tasks a better chance to run uninterrupted.
Moreover, make sure to mark CPUs that are used or skipped as busy to prevent repeated attempts to dispatch tasks to the same CPU
Fixes: aed4f584 ("scx_tickless: Improve scheduling timer")

scx_tickless: Avoid distributing tasks on scheduling CPUs

---

scheds/rust/scx_tickless/src/bpf/main.bpf.c
scheds/rust/scx_tickless/src/main.rs

A sync wakeup change that improves performance for pipe-intensive workloads, along with some refactoring of timer initialization and task dispatch to eliminate unnecessary overhead.

scx_tickless: Misc improvements

---

rust/scx_rustland_core/assets/bpf/main.bpf.c

When specifying RL_CPU_ANY as the target CPU for task dispatch, attempt to wake the task's previously used CPU, instead of trying to wakeup a CPU close to RL_CPU_ANY, which is an invalid CPU ID.
Moreover, always use SCX_KICK_IDLE to prevent unnecessary wakeup events when the target CPU is not idle (which can occur due to concurrent wakeup attempts).

scx_rustland_core: Fix CPU wakeup with RL_CPU_ANY

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Remove the unneeded `dsq_id` variable as that is already stored on the `task_ctx`. This should save a few bytes on the stack.

scx_p2dq: Remove unneeded variable

---

scheds/rust/scx_chaos/src/bpf/main.bpf.c

Chaos enqueues delayed enqueues in chaos_dispatch. This loop is currently limited
to enqueuing 8 tasks for verifier reasons. Add a wrapped version of `async_p2dq_enqueue`
that is a global function to allow this loop to converge and run for all tasks
in the queue.
This approach is taken to avoid adding the call overhead to p2dq and chaos_enqueue.
This will still require p2dq's implementation to be globally verifiable, and that's
enforced by CI in the monorepo.
`check_dsq_times` was suspicious before so I cleaned it up. It now checks all
tasks until it finds one that would preempt in the timer. The most aggressive
kicking is done first, so ensure we only kick once. Set the timer for the first
task that would require preemption.
Test plan:
- CI
Performance:
Before: - dispatch instructions …

chaos: remove limit on delayed enqueue loop

---

scheds/rust/scx_lavd/src/main.rs

Each compute domain has two IDs: its unique ID and the alternative compute domain's ID (e.g., LITTLE compute domain's ID for a big compute domain). The alternative compute domain is used to quickly find a compute domain matching with task's performance criticality type.
Previously, an alternative domain was considered only within the same node/LLC domain. However, it does not work in such an architecture where big and LITTLE cores do not share the same LLC.
Hence, choose the closest alternative domain if big and LITTLE cores do not share the same LLC.

scx_lavd:  Find an alternative domain beyond the current node/LLC.

---

rust/scx_rustland_core/assets/bpf/main.bpf.c

Handle the return value of bpf_cpumask_and() when computing L2 and L3 domain masks to avoid propagation of invalid masks and potential verifier rejection or runtime errors.

scx_rustland_core: skip L2/L3 search when domain is empty

---

scheds/rust/scx_wd40/README.md

Fix README title and link formatting in scx_wd40.

doc: Fix README title and link formatting

---

scheds/rust/scx_lavd/src/main.rs

Refactor the logic for initializing `cpu_pf/ps_order` by replacing manual iteration and `push()` with iterator-based `.map().collect()`. This imporves readability and removes repetitive code.

scx_lavd: Simplify CPU preference order setup

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Avoid unneeded lookups of llc_ctx in the keep running path.

scx_p2dq: Optimize the keep running path

---

scheds/rust/scx_chaos/src/bpf/main.bpf.c
scheds/rust/scx_chaos/src/lib.rs

Chaos trait selection is currently handwritten for each trait. Refactor this to have a uniform selection process based on the `chaos_trait` value. This makes adding types easier in the future.
This also implies that CHAOS_TRAIT_NONE is the most unlikely, and this is now explicitly selected as the first random value. Also uses an unrolled loop in the hope that the `const volatile` can be JIT'ted nicely, but this isn't overly important.
Test plan:
- CI
- Manually, tested a few and read the debug output which looks good.

chaos: refactor trait selection

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

For affinitized tasks aggressively try to keep tasks sticky. This saves an extra task storage map lookup when affinitized tasks are sticky.

scx_p2dq: Optimize affinitized selection

---

tools/scxtop/src/app.rs

Originally, the default CPU, LLC, and NUMA views showed `dsq_vtime_delta` pane (bottom left). Ex.:
However, the `dsq_slice_consumed` is more useful, so the default has been updated to show that instead (bottom left). Ex.:
Once the default `dsq_vtime_delta` was no longer the default, we can just use the generic `render_scheduler` method to display the `dsq_vtime_delta` when needed. `dsq_vtime_delta` can still be found by using the `s` keybinding.

scxtop: Update TUI defaults to slice-consumed

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

When using interactive fifo queueing ensure that all dispatches to interactive DSQs are interactive. Fixes a runtime bug when using interactive fifo queueing.

scx_p2dq: Fix interactive fifo handling

---

scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c

- Add explicit casts to match `const struct cpumask *` in BPF helpers
- Mark unused inline functions as `__maybe_unused`.
- Initialize `err` to silence uninitialized variable warning.
These changes eliminate all cpumask-related type warnings.
<details>
<summary>Warning log</summary>
```shell
warning: scx_mitosis@0.0.9: src/bpf/mitosis.bpf.c:510:41: warning: incompatible pointer types passing 'struct bpf_cpumask  __attribute__((btf_type_tag("kptr")))*' (aka 'struct bpf_cpumask *') to parameter of type 'const struct cpumask *' [-Wincompatible-pointer-types]
warning: scx_mitosis@0.0.9:   510 |         if (tctx->cpumask && bpf_cpumask_empty(tctx->cpumask)) {
warning: scx_mitosis@0.0.9:       |                                                ^~~~~~~~~~~~~
warning: scx_mitosis@0.0.9: …
```

scx_mitosis: Fix cpumask casts and suppress BPF warnings

---

scheds/rust/scx_chaos/src/main.rs

Implement PID targeting for scx_chaos. Turns out this was easier than expected, I simply poll `kill(pid, 0)` to check when it drops.
Test plan:
- Pointed it at a shell instance. That one fell apart, everything else worked (testing the combo with ppid targeting).
- Exiting the shell/program under test successfully tells the scheduler to exit.

chaos: implement pid targeting

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Rename cur_llcx to waker_llcx which is a more accurate description of what the variable represents. Move the fast path for checking the previous cpu to the start of pick_idle_cpu. This should improve throughput during mostly idle situations.

scx_p2dq: Cleanup pick_idle_cpu

---

rust/scx_rustland_core/assets/bpf/main.bpf.c

Refactor the idle CPU selection policy with the following changes:
- rely on scx_bpf_pick_idle_cpu(), which is less racy at selecting idle CPUs,
- optimize CPU selection for tasks that don't have affinity restrictions (in this case there's no need to update the local task's cpumasks and we can simply use the cache cpumasks directly),
- always use the custom pick_idle_cpu() both from ops.select_cpu() and ops.enqueue() to apply a consistent idle CPU selection policy both in the local wakeup and remote wakeup (ttwu_queue) cases,
- handle gracefully the cases where pick_idle_cpu() returns an invalid CPU (this may happen due to races with CPU affinity changes).
These changes seem to fix some stall conditions and inefficiencis reported by the CachyOS community.

scx_rustland_core: Idle CPU selection refactoring and optimizations

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c
scheds/rust/scx_bpfland/src/main.rs

Revert three commits incorrectly pushed directly to main without a proper pull request.

bpfland: Revert commits incorrectly applied

---

lib/sdt_alloc.bpf.c

#1996 properly adjusts the static allocator base pointer after reallocation. This operation changes the address to be returned to the user, and with it the padding necessary to align the address. Recompute the padding when allocating a new block of memory.

lib/sdt_alloc: recompute padding on allocation

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

scx_p2dq: Remove dead code

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

improve compatibility with older kernels

layered: compat tweaks

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Make the code easier to follow and fix and edge case in old kernels where interactive tasks would not be dispatched in pick two load balancing.

scx_p2dq: Cleanup dispatch_pick_two

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

For scheduling latency, scx_layered usually depends on the fact that a task
can be pulled by multiple CPUs and an eligible CPU is likely to open up
soon. However, if a task is a high-priority per-cpu kthread, it has to run
soon and can only run on one particular CPU. Preempt whatever is running on
that CPU.
Preempt whatever is running on the CPU for them and don't let them be
preempted by others.

scx_layered: Better prioritize highpri per-cpu kthreads

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Since the fixed commit, prev_taskc and prev_layer are always NULL in layered_dispatch and all checks conditional on them (keep_running() heuristics and slice assignment to the previous task) do not occur.
Move the hunk initializing them back to layered_dispatch. Before this, all keep/max/busy counters for layers are 0, after this they are populated again.
Restore the comment before slice refresh again for clarity.
Fixes: e2b6cbe7bee7 ("layered: improve compat of excl fixes on older kernels")

scx_layered: Unbreak layered_dispatch

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

When updating the vtime in the running method ensure that the updated vtime is in a reasonable range. In certain scenarios, such as affinitized kthreads, tasks are directly dispatched and not vtime ordered. Add tracing logging for tracking of vtime in the dispatch method.
Tested with `bpftool prog trace`:
```
kworker/u64:4-12161   [000] d..31  2621.460721: bpf_trace_printk: DISPATCH cpu[0] vtime 83668913523 min_vtime 83652259620 dsq_id 3
schbench-14633   [000] dN.31  2621.461716: bpf_trace_printk: DISPATCH cpu[0] vtime 83680490530 min_vtime 83671217468 dsq_id 1
schbench-14635   [000] dN.31  2621.462715: bpf_trace_printk: DISPATCH cpu[0] vtime 83696214092 min_vtime 83682763000 dsq_id 3
bpftool-14366   [000] d..31  2621.462888: bpf_trace_printk: DISPATCH cpu[0] vtime 83702445958 min_vtime …
```

scx_p2dq: Fix vtime jumps

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

Currently, if a CPU doesn't go through `ops.select_cpu()` before being migrated, its task domain may be stale in `ops.enqueue().` The proposed change tries to ensure that in this case, proactive wakeup will target a CPU near the one the task was most recently running on.

Refresh task domain if migrated to different CPU without going through ops.select_cpu()

---

README.md

Add Discord server to README.md

README: add Discord server

---

scheds/rust/scx_flash/src/main.rs

Allow to specify "turbo" with the option --primary-domain to prioritize the CPUs with the highest max frequency.
This differs from the "performance" mode, which prioritizes the fast cores in systems with hybrid cores.
The "turbo" option can be beneficial with certain workloads in systems with turbo-boosted cores.

scx_flash: Introduce "turbo" mode

---

scheds/include/scx/common.bpf.h
scheds/rust/scx_rusty/src/load_balance.rs
scheds/rust/scx_wd40/src/load_balance.rs

- Replace the manual loop with an idiomatic iterator-based approach.
- Fix indentation

load_balance: Refactor get_stats

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Cleanup various code bits and optimize the dispatch path by first checking if there are any queued tasks in the DSQ before checking the iterator for the minimum vtime. This saves a small overhead in creating the DSQ iterator context.

scx_p2dq: Optimize dispatch

---

rust/scx_utils/src/infeasible.rs

- Refactor apply_infeasible_threshold.
- Fix assignment and remove duplicate constructor.

scx_utils/infeasible: Refactor apply_infeasible_threshold 

---

scheds/rust/scx_flash/src/bpf/main.bpf.c

If a task is re-enqueued because a higher scheduling class stole the CPU, allow it to migrate to a different CPU via direct dispatch in ops.enqueue() and skip updating its deadline, since it didn't actually ran.
In all other cases, migration should only be attempted on task wakeup.

scx_flash: Improve task re-enqueue

---

scheds/rust/scx_rusty/src/bpf/main.bpf.c
scheds/rust/scx_rusty/src/bpf/sdt_alloc.bpf.c

scx_rusty: Update aarch64 compat macro

---

lib/minheap.bpf.c

lib/minheap: Simplify parent index calculation

---

scheds/rust/scx_mitosis/src/bpf/intf.h
scheds/rust/scx_mitosis/src/bpf/mitosis.bpf.c
scheds/rust/scx_mitosis/src/main.rs

Nothing major here, just formatting, unused code, and fixing a minor all_cpus bug.

scx_mitosis: Small fixups

---

Cargo.lock
tools/scxtop/Cargo.toml

Clean up Cargo.toml and Cargo.lock.
Testing:
Ran `cargo clean && cargo check --all-targets --all-features` and `cargo build --release` successfully.

scxtop: clean up Cargo.toml

---

scheds/rust/scx_flash/src/bpf/main.bpf.c

In round-robin mode we are always re-enqueueing tasks to the local DSQ. However, if a CPU is stolen by a higher scheduling class (i.e., real-time), we want to give the task a chance to move to a different CPU, to reduce the risk of stalls.

scx_flash: Prevent potential stall with --rr-sched

---

tools/scxtop/src/app.rs

`dsq_nr_queued` was already used in scxtop tracing, this just adds it to the scheduler view as well.
Ex. (bottom right):

scxtop: add dsq_nr_queued to tui

---

scheds/rust/scx_flash/src/bpf/main.bpf.c

Always allow re-enqueued tasks to migrate, while restricting migration attempts for regular enqueues to wakeup events only.
This change improves CPU locality by favoring task retention on the same CPU when round-robin mode is active.

scx_flash: Refine round-robin mode

---

cargo-publish.py

cargo-publish has to publish the crates in a certain order based on their dependencies. Currently we deal with this with a manually managed "priority" list that gets prepended to the crate publishing.
As we're already parsing the crate metadata, grab the internal dependencies and do a topological sort on the crates. No need to manually specify things anymore.
Drive-by: fix the `--start` flag that I broke last time I refactored this file.
Test plan:
```
jake@rooster:/data/users/jake/repos/scx/ > nix run nixpkgs#python3 -- ./cargo-publish.py --dry
Publishing crate scx_loader
Publishing crate scx_stats
Publishing crate scx_stats_derive
Publishing crate scx_utils
Publishing crate scx_bpfland
Publishing crate scx_flash
Publishing crate scx_lavd
Publishing crate scx_layered
Publishing crate …
```

cargo-publish: add a topological sort

---

tools/scxtop/src/app.rs

https://github.com/user-attachments/assets/fe6a50ad-03e7-48cb-9385-c6fc907f775d
Close: #2310

scxtop: Add "missing scheduler" message

---

tools/scxtop/src/cpu_stats.rs

This keeps track of system-wide cpu utilization statistics, which sets the stage to easily add per-process cpu utilization (as mentioned in #2434).

scxtop: add cpu system-wide stats

---

tools/scxtop/src/app.rs

Calculating the vtime delta per DSQ can be pretty tricky, and at the moment, the calculation isn't correct (it calculates the delta over scxtop's sample size) and isn't super useful. To hopefully make it a bit more useful, this switches the stat to just keep track of the vtime per-DSQ, which gives insight into how the vtime is increasing as time goes on. Example:

scxtop: temporary fix for dsq vtime stat

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

When a CPU goes idle under the cpu_priority flag take the timestamp from when it went idle as part of the score in the min heap. This will prefer the most recently idle CPUs, which improves performance on partially loaded systems.
on 32 CPU system partially loaded with `--cpu-priority true`:
```
$ schbench -t 8
Wakeup Latencies percentiles (usec) runtime 30 (s) (72981 total samples)
50.0th: 6          (30637 samples)
90.0th: 8          (23387 samples)
* 99.0th: 12         (3446 samples)
99.9th: 23         (551 samples)
min=1, max=36
Request Latencies percentiles (usec) runtime 30 (s) (73091 total samples)
50.0th: 3260       (21074 samples)
90.0th: 3324       (29089 samples)
* 99.0th: 4376       (6192 samples)
99.9th: 4408       (459 samples)
min=3035, max=6045
RPS percentiles (requests) …
```

scx_p2dq: Refactor cpu priority handling

---

scheds/rust/scx_layered/src/bpf/main.bpf.c

Update dump so that some helpers return ints for global verification. Add extra bounds checks to make verification easier.

scx_layered: Make dump easier to verify

---

tools/scxtop/src/app.rs

Initially, the event view was rendering each NUMA as two blocks, one for the title and one for the body. Since the percentage was set at 2 for the title, it was getting cut out when the screen was even somewhat small. This uses a single block, adding a title and then uses .inner() to get the inner area to be used for the CPU data. 
Before:
After:

scxtop: fix event rendering bug

---

.github/include/ci.py

Some extra abstractions for `run_command` and `run_command_in_vm` were added a while ago. They're always swallowing output but some commands, such as the `format` one, are explicitly expecting to show their output.
Add a `no_capture` argument to `run_command` and `run_command_in_vm` so we can see the output sooner in the CI and get any useful output at all for the format job.
Test plan:
- CI

ci: add no_capture flag for run_command

---

scheds/sync-to-kernel.sh

Previously, missing target files were skipped with a warning. This patch ensures those files are created by making parent directories and copying them. Also fixes inconsistent indentation in the sync logic.
Additionally, skips syncing `include/arch/` and `.gitignore` files, as they are not intended to be copied into the kernel tree.
See: https://lore.kernel.org/all/aINzTW6Hi40EPSt8@gpd4/
[Screencast from 2025-07-27 21-09-53.webm](https://github.com/user-attachments/assets/459cdc46-c15a-42e1-9bd7-9164dd637a28)
But even after syncing all files, still fails ... :cry: 
```shell
$ # kernel
$ cd tools/testing/selftests/sched_ext
$ make -j$(nproc)
```
Edit: 
Full log : https://gist.github.com/EricccTaiwan/9d3f47762486e5453db627ed5b0d74ae

sync-to-kernel.sh: Create missing files and skip unwanted headers

---

scheds/rust/scx_p2dq/src/bpf/main.bpf.c

Add init_cpumask helper function to simplify the initialization of topology context structs.

scx_p2dq: Reactor initialization

---

scheds/rust/scx_lavd/src/bpf/main.bpf.c

When enqueuing a task without a pre-selected CPU,
cpuc was not initialized before later usage, potentially triggering -Wsometimes-uninitialized warnings from Clang.
This patch ensures cpuc is always retrieved after picking a CPU via pick_proper_dsq(). It also removes the incorrect pointer comparison (cpuc < 0) and avoids redundant get_cpu_ctx_id() calls for pinned task accounting.
---
log
```c
warning: scx_lavd@1.0.14: src/bpf/main.bpf.c:620:6: warning: variable 'cpuc' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
warning: scx_lavd@1.0.14:   620 |         if (!__COMPAT_is_enq_cpu_selected(enq_flags)) {
warning: scx_lavd@1.0.14:       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: scx_lavd@1.0.14: src/bpf/main.bpf.c:635:6: note: …
```

scx_lavd: Ensure cpuc is initialized in all enqueue paths

---

tools/scxtop/src/cpu_stats.rs
tools/scxtop/src/mem_stats.rs

As a follow-up to #2551, this uses the more idiomatic `From` trait.

scxtop: use more idiomatic style

---

tools/scxtop/src/app.rs

This adds filtering, scrolling, and a scrollbar to the thread view:
https://github.com/user-attachments/assets/48f2c697-c12c-46aa-8517-f0b19c74f57d

scxtop: add features to thread view

---

.github/include/ci.py

virtme-ng has a relatively short command length limit. To avoid ever hitting that (it's confusing when you do), write the command to a short shell script and use the shell to execute it.
Test plan:
- CI
- Stacked PR

ci: adjust run_command_in_vm to support long commands

---

tools/scxtop/src/cpu_data.rs
tools/scxtop/src/edm.rs
tools/scxtop/src/llc_data.rs
tools/scxtop/src/node_data.rs
tools/scxtop/src/proc_data.rs

Add test coverage for common and rather stable code.

scxtop: Add additional test coverage

---

tools/scxtop/Cargo.toml

Adding myself as a secondary author to the scxtop repo.

scxtop: add secondary author

---

tools/scxtop/src/app.rs

This cleans up how the usage of `ComponentViewState` and makes it easier to add more of these in the future (simply pull off another piece from left in `render_default`). This also moves the logic in `handle_action` to `set_state`, which makes it easier to see the whole picture in one method.
This also changes the behavior to be that once you enter into tri-state cycling, you stay in the cycle while pressing 'M'. This is in contrast to the behavior where pressing 'M' a second time would take you back to the previous state.

scxtop: clean component view state

---

Cargo.lock
tools/scxtop/Cargo.toml
tools/scxtop/src/perfetto_trace.rs

This version adds support for the s390x architecture.

scxtop: update perfetto_protos dependency to v0.51.1

---

lib/btree.bpf.c
lib/selftests/st_btree.bpf.c
scheds/include/lib/btree.h

Add merging and removal operations to the btree data structures.

lib/btree: add remove and merge operations

---

tools/scxtop/src/app.rs

Add colors to charts based on values using the gradient helpers. This makes it easier to visually spot changes in values.

scxtop: Add colors to charts

---

scheds/rust/scx_lavd/src/bpf/sys_stat.bpf.c

On ARM, the verifier hits the "BPF program is too large" error. Let's split a large loop body into two to lower the verification burden and work around the problem before the verifier becomes smarter.

scx_lavd: Fix a verification error on ARM.

---

tools/scxtop/src/app.rs
tools/scxtop/src/keymap.rs
tools/scxtop/src/proc_data.rs
tools/scxtop/src/thread_data.rs

Refactor on_tick method to only update relevant collectors based on the current TUI view.

scxtop: Refactor on_tick method

---

Cargo.lock
Cargo.toml
tools/scxcash/Cargo.toml
tools/scxcash/build.rs
tools/scxcash/src/bpf/intf.h
tools/scxcash/src/bpf/soft_dirty.bpf.c
tools/scxcash/src/bpf_intf.rs
tools/scxcash/src/bpf_skel.rs
tools/scxcash/src/main.rs
tools/scxcash/src/monitors.rs

Initial support for a cache usage analysis tool to figure out cache access patterns of processes on the machine. It will be augmented with different backends (perf-based, similarity heuristic-based) in the future, for now begin with soft-dirty based logic.
Output:
```
20:13:09 [TRACE] soft-dirty fault tid=3050 addr=0x767d0c5f8000
20:13:09 [TRACE] soft-dirty fault tid=3050 addr=0x767d0c5f9000
20:13:09 [TRACE] soft-dirty fault tid=3050 addr=0x767d0db49000
20:13:09 [TRACE] soft-dirty fault tid=3050 addr=0x767d0c5fa000
20:13:09 [TRACE] soft-dirty fault tid=3050 addr=0x767d0e749000
20:13:09 [TRACE] soft-dirty fault tid=3050 addr=0x767d0c5fb000
20:13:09 [TRACE] soft-dirty fault tid=3050 addr=0x767d0c5fc000
20:13:09 [TRACE] soft-dirty fault tid=3050 addr=0x767d0c5fd000
20:13:09 [TRACE] …
```

Cache Usage Analyzer

---

rust/scx_rustland_core/assets/bpf.rs

Use consume_raw_n() to fetch the first task from the BPF ring buffer and get rid of the LIBBPF_STOP workaround.
This is a cleanup enabled by the new consume_raw_n() API introduced in libbpf-rs v0.25. No functional changes.

scx_rustland_core: Use RingBuffer:consume_raw_n()

---

scheds/rust/scx_p2dq/README.md

Add section for Big/Little core support and some common options for tuning for gaming workloads.

scx_p2dq: Update docs

---

tools/scxtop/src/app.rs
tools/scxtop/src/lib.rs

Add support for rendering LineGauge for a more compact layout.
Event view:
LLC view:
Node view:

scxtop: Add LineGauge support

---

scheds/rust/scx_cosmos/src/bpf/main.bpf.c

To prioritize tasks that wake up frequently over those with long sleep periods, adjust the amount of time-slice credit a task can accumulate based on its wakeup frequency.
This allows frequently sleeping tasks to accumulate a bigger time slice credit than tasks that sleep infrequently for long intervals.
This concept is similar to the approach used in scx_flash, which limits the accumulated time slice credit based on the rate of voluntary context switches.
This mechanism helps to further prioritize latency-sensitive tasks that typically exhibit frequent sleep and wake-up patterns.
Example
=======
Recompile the kernel while running a WebGL app and measure fps:
- before this change: ~25 fps
-  after this change: ~45 fps

scx_cosmos: Consider wakeup frequency when determining task deadlines

---

rust/scx_rustland_core/assets/bpf/main.bpf.c

Add scx_bpf_reenqueue_local() to rustland_cpu_release() so that when a higher scheduler class steals the CPU, all tasks waiting on the local DSQ are re-enqueued and given a chance to run on other CPUs.
This patch significantly reduces max wakeup latency, while request latency and RPS remain within statistical variance.
Test plan:
- terminal#1: $ sudo cyclictest -a 0 -p 80 -t1	# RT task
- terminal#2: $ ./schbench -m 4 -t 4 -r 10
Before:
```
Wakeup Latencies percentiles (usec) runtime 10 (s) (59403 total samples)
50.0th: 3          (31803 samples)
90.0th: 3          (0 samples)
* 99.0th: 10         (2984 samples)
99.9th: 17         (472 samples)
min=1, max=3445
Request Latencies percentiles (usec) runtime 10 (s) (59407 total samples)
50.0th: 2148       (16596 samples)
90.0th: 3588 …
```

scx_rustland_core: Re-enqueue tasks in cpu_release

---

scheds/rust/scx_bpfland/src/bpf/main.bpf.c

Tasks pinned outside the primary domain repeatedly attempt to migrate into it, but since this is impossible, they end up causing excessive re-enqueue and migration attempts. This wastes cycles and results in CPU underutilization.
To address this, when selecting an idle CPU or checking whether a task should remain on its current CPU, ensure the task's domain intersects with the primary domain. If it does not, ignore the primary domain entirely and let the task run freely across all CPUs.
Example:
- Use cpu0-cpu3 as primary domain and run a CPU stressor on cpu8-cpu11:
```
$ scx_bpfland -m 0x000f
$ schedtool -a 8,9,10,11 -e stress-ng -c 4
```
- before this change:
```
0[|||||                    12.4%]  12[                          0.0%]
1[|||||                    14.3%]  13[ …
```

scx_bpfland: Fix CPU utilization for tasks pinned outside primary domain
